### ISSUE TITLE
Alexa Display Cards

### ISSUE THREAD

**Issue by dylono96** [MichMich/MagicMirror#1001]
is it possible to get the output of the alexa app displayed on the mirror? 
I saw that some other guy made something, but that was not build for the magic mirror 2.

**Comment by D3rpi** [comment]
That's something I have been wanting to do with my set up for a while now but sadly don't know how to do that.
Do you have a link for the thing the guy made?

**Comment by dylono96** [comment]
this is the link I first saw it on: https://www.hackster.io/mexitek/magic-mirror-amazon-echo-and-aws-iot-29bba5

**Comment by dylono96** [comment]
so i found another thing: https://github.com/joanaz/MirrorMirrorOnTheWallSkill maybe you should give that a try.

**Comment by nhubbard** [comment]
@dylono96 You're welcome to build a module with AWS Lambda with an Amazon Echo, but we can't show cards from the Alexa app (it's a private API restricted by a usage agreement).

**Comment by nhubbard** [comment]
@MichMich close

**Comment by dylono96** [comment]
So even with acces to that api it isnt possible because it has anotger license?

**Comment by dylono96** [comment]
ok I understand, but could you explain how the MirrorMirrorOnTheWall skill works then?

**Comment by nhubbard** [comment]
@dylono96 That skill works as I said (you can only access apps you create) because as part of the setup, you create a skill on AWS Lambda and attach it to your MM.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support, troubleshooting and module specific discussions.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
