### ISSUE TITLE
use language for "zh-cn" , has error.

### ISSUE THREAD

**Issue by ruicky** [MichMich/MagicMirror#1008]
Hi, coder:
 when i use *language:"zh_cn"* in `config.js` , has a error. clock not translate.
because  `moment.locale()`, use key `zh-cn`, not 'zh_cn'.

hope you can change it.

thank you .

**Comment by MichMich** [comment]
Feel free to send a PR.

**Comment by MichMich** [comment]
Closed due to inactivity.
