### ISSUE TITLE
Many RSS on the page

### ISSUE THREAD

**Issue by monsieurpouet** [MichMich/MagicMirror#101]
Hi all !

How to put a lot of RSS feed on the page ? 
I have to copy/paste many news.js. But one news.js per feed, it is so many heavy no ?

Do u have an idea ?

**Comment by Vaggan** [comment]
Hi @monsieurpouet !

How do you mean? 

Do you want to have many RSS sources but only display one news at a time.
Or do you want do display one news from each source at a time?

**Comment by monsieurpouet** [comment]
Hi ! Thx for your answer.

One news from each sources.

- Lalala : CNN
- Blabla : LeMonde
Etc..

:)

**Comment by MichMich** [comment]
This will be supported in V2 by duplicating the modules in the config.
