### ISSUE TITLE
Black Screen Issue

### ISSUE THREAD

**Issue by Nograe** [MichMich/MagicMirror#1018]
Hello,
After the setup of config.js and installation of npm and node, I succeed to launch the app but the screen is all black, and same for the index.html

**Comment by Nograe** [comment]
Just type npm start in vendor file and voilà !

**Comment by Nograe** [comment]
Just type npm start in vendor file and voilà !

**Comment by axellejamous** [comment]
hello @Nograe I'm having the same issue. Tried all of the other suggestions mentioned in other issues that are similar. including the "en" change but nothing seems to be working so my problem must be elsewhere.

What do you mean by vendor file?

**Comment by MichMich** [comment]
@axellejamous Please check http://forum.magicmirror.builders for support.

**Comment by hyd00** [comment]
for anyone else, i solved my blank screen issue by

```
cd ~/MagicMirror/vendor
npm install
```
it will download fonts and icons needed by modules.

then
```
cd ~/MagicMirror
npm start
```
and now it shows modules perfectly 💃  ..

**Comment by bucbowie** [comment]
+1 and kudos to hyd00

**Comment by bucbowie** [comment]
Magic Mirror would not properly install for me after doing apt-get update && apt-get upgrade. However, after doing: apt-get -y dist-upgrade, the Magic Mirror package installed. From there, I went inside MagicMirror and ran: git pull && npm install. That brought me current with an installed version of Magic Mirror. Again, thanks to hyd00 for the vendor folder recommendation.

**Comment by reillychase** [comment]
I was stuck for hours on this, thanks @hyd00! Should be added to the instructions for manual install.
