### ISSUE TITLE
MagicMirror is not formatted

### ISSUE THREAD

**Issue by DominicDecocco** [MichMich/MagicMirror#102]
Hey guys, 
It seems that the Interface´s formatting is not active.
https://gyazo.com/c983b006ad854eb498de238a58bcb3fc

I guess it´s the same issue which is solved https://github.com/MichMich/MagicMirror/issues/89 but I don´t know what to do / What is the right directory of the CSS files?

**Comment by MichMich** [comment]
Check your web inspector.

**Comment by DominicDecocco** [comment]
In time.js line 26
`this.intervalId = setInterval(function () {`
it displays "anonymous function"

**Comment by DominicDecocco** [comment]
In **time.js** in line 26 there is an _anonymous funktion_
`this.intervalId = setInterval(function () {`
but i dont think this causes my problem?!
Sorry I don´t have so much knwoledge about this.

**Comment by MichMich** [comment]
Could You post a screenshot of your web inspector?

**Comment by DominicDecocco** [comment]
![1](https://cloud.githubusercontent.com/assets/18035029/14043230/34898290-f282-11e5-8222-cfb6a406b529.jpg)

**Comment by MichMich** [comment]
Could you show what's in the console part?

**Comment by DominicDecocco** [comment]
![2](https://cloud.githubusercontent.com/assets/18035029/14044018/7ef62456-f28b-11e5-90fa-383ebebb7a90.jpg)

**Comment by DominicDecocco** [comment]
![2](https://cloud.githubusercontent.com/assets/18035029/14044078/4c20fac8-f28c-11e5-94b0-43cc59a45d6d.jpg)

**Comment by bitte-ein-bit** [comment]
Are you using a web server? Looks like you are using a file:// link?

Am Fr, 25. Mär 2016, um 13:20, schrieb DominicDecocco:

**Comment by ski7777** [comment]
looks like php is not installed

**Comment by DominicDecocco** [comment]
Sorry guys, I was on holiday..

I reinstalled everything again..copied the files to _/var/www/html/_
![3-1](https://cloud.githubusercontent.com/assets/18035029/14228720/fd2b0880-f91d-11e5-8104-13a00511a54f.png)

...after boot, chromium starts and it displays the same issue:(
![3](https://cloud.githubusercontent.com/assets/18035029/14228708/a4584510-f91d-11e5-94de-579220cfa3f1.png)
[Webserver is running cause the console displays _localhost_;right?]

May I forgot something or made a mistake again?

**Comment by MichMich** [comment]
What's the url Chromium uses?

**Comment by DominicDecocco** [comment]
How can I check that?

**Comment by MichMich** [comment]
What URL did you use in your autostart?

**Comment by DominicDecocco** [comment]
http://localhost

**Comment by MichMich** [comment]
If you click on the CSS folder in your debuggers left column. Doest it show a css file with contents? (In other words, does it load the CSS file?)

**Comment by DominicDecocco** [comment]
It shows
font-awesome.css
weather-icons.css

**Comment by MichMich** [comment]
It appears the main css file isn't loading. Is it in the css folder?

**Comment by DominicDecocco** [comment]
Ok. Yes it is in the folder.

**Comment by MichMich** [comment]
Sorry, I just remember the main CSS isn't included the usual way. It uses some PHP including: `<?php include('css/main.css') ?>`

That fact that this doesn't work probably is because your PHP isn't working. Like @ski7777 said before.

**Comment by DominicDecocco** [comment]
Well ok. Apache & PHP-Support are installed (according to your instructions _Webserver_) and the _index.php_ is in the folder, too.
What else can I do?

**Comment by MichMich** [comment]
You could go adventurous, and try the new V2 version I'm currently building. Build it's in an early stage so I can't give any support yet. Checkout the V2-beta branch.

**Comment by DominicDecocco** [comment]
Yes that would be an interesting option..
Could it also be issued by the raspberry I use..it´s pi 3?

**Comment by MichMich** [comment]
Yes, the installation is much more simple. I didn't yet test it on a Raspberry Pi though. But user @paviro did, so it should be working.

Keep in mind it's on heavy development at the moment, so you might need to update it every so often.

**Comment by paviro** [comment]
Haven't run it on a Pi for quite some time now but it works you just have to install nodejs. Going to setup the new version on my Pi, as well today.

**Comment by DominicDecocco** [comment]
Yeah I´m gonna try it when v2 is finished.
Do you have any idea why the php is not working?
