### ISSUE TITLE
Cannot create complex Json structure in module and Logging not working

### ISSUE THREAD

**Issue by sharmmoh1983** [MichMich/MagicMirror#1021]
Hey

I am trying to create complex json object in module and  pass it one of the script included in get script

const commands = {
  'hello': function () {
    console.log('You will obey');
  },
  '(give me) :flavor ice cream': function (flavor) {
    console.log('Fetching some ' + flavor + ' ice ceam for you sr')
  },
  'turn (the)(lights) :state (the)(lights)': function (state) {
    console.log('Turning the lights', (state == 'on') ? state : 'off')
  }
}

annyang.addCommands(commands);

Commands are always turning out to be blank

Also I am trying to use Log statements but nothing comes in console:

Log.log(payload);

**Comment by sharmmoh1983** [comment]
Callbacks in json are getting blank  or not get created

**Comment by MichMich** [comment]
Hi @sharmmoh1983, as explained in your previous issue, github issues are here for core bug reports. If you need support building your module, please use the forum. We cannot give support via GitHub issues. 

What I can say is what you're trying to do is not possible. Json objects can't contain methods. Please checkout some info on JSON. Google is your friend. 

I urge you to not open any other topics regarding development support. Thanks.

**Comment by sharmmoh1983** [comment]
Ok .. Thank buddy

**Comment by sharmmoh1983** [comment]
Just to update you, above thing is working in node_helper so there is no issue in JSON structure as JSON is just map of keys and values.

But some how in module class, it is getting converted it into some other  object other than JSON which is getting failed in method call

That is why I am updating it as it seems to be bug in your module class

**Comment by MichMich** [comment]
In the node module it's a JavaScript object. Not a JSON object. JSON objects can only contain strings, numbers, arrays and objects. Not functions.

**Comment by sharmmoh1983** [comment]
It can take functions also as happening in node_helper, anyways as per your suggestion I have posted detailed requirement on forum

**Comment by MichMich** [comment]
In the node helper it's a JavaScript object. Not a JSON object ...

**Comment by fewieden** [comment]
Could you give a reasonable usecase, why someone would need the module instance in the node helper?

**Comment by sharmmoh1983** [comment]
Hi

I am trying to communicate with other modules through node helper rather
than sending notification back to the curent module and then sending
notifications to other modules
