### ISSUE TITLE
Application shuts down in RPI3

### ISSUE THREAD

**Issue by sharmmoh1983** [MichMich/MagicMirror#1026]
Hi 

I hope this one qualifies to be reported in this forum

I am running Magic Mirror on Raspberry Pi and many times it stops itself and reboots the complete Raspberry Pi3 and  also sometimes at calling updateDOM method

There are 5-6 modules in my Magic Mirror

Is anyone facing the same issue  or some hardware/memory constraint?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
