### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by Snake16547** [MichMich/MagicMirror#1040]
Hi,
i got follwing error after update and restart with "pm2 restart mm"

 /home/pi/MagicMirror/node_modules/electron/index.js:9
0|mm       |   throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
0|mm       |   ^
0|mm       | Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/node_modules/electron/index.js:9:9)
0|mm       |     at Module._compile (module.js:570:32)
0|mm       |     at Object.Module._extensions..js (module.js:579:10)
0|mm       |     at Module.load (module.js:487:32)
0|mm       |     at tryModuleLoad (module.js:446:12)
0|mm       |     at Function.Module._load (module.js:438:3)
0|mm       |     at Module.require (module.js:497:17)
0|mm       |     at require (internal/module.js:20:19)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/node_modules/electron/cli.js:3:16)
0|mm       |     at Module._compile (module.js:570:32)
0|mm       | npm
0|mm       |  ERR! Linux 4.9.41-v7+
0|mm       | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
0|mm       | npm ERR!
0|mm       | node v6.11.3
0|mm       | npm ERR! npm  v3.10.10
0|mm       | npm ERR! code ELIFECYCLE
0|mm       | npm ERR! magicmirror@2.1.3 start: `sh run-start.sh`
0|mm       | npm ERR! Exit status 1
0|mm       | npm ERR!
0|mm       | npm ERR! Failed at the magicmirror@2.1.3 start script 'sh run-start.sh'.
0|mm       | npm ERR! Make sure you have the latest version of node.js and npm installed.
0|mm       | npm ERR! If you do, this is most likely a problem with the magicmirror package,
0|mm       | npm ERR! not with npm itself.
0|mm       | npm ERR! Tell the author that this fails on your system:
0|mm       | npm
0|mm       | ERR!     sh run-start.sh
0|mm       | npm ERR! You can get information on how to open an issue for this project with:
0|mm       | npm ERR!     npm bugs magicmirror
0|mm       | npm ERR! Or if that isn't available, you can get their info via:
0|mm       | npm
0|mm       |  ERR!     npm owner ls magicmirror
0|mm       | npm ERR! There is likely additional logging output above.
0|mm       | npm ERR! Please include the following file with any support request:
0|mm       | npm ERR!     /home/pi/MagicMirror/npm-debug.log
PM2        | App [mm] with id [0] and pid [2854], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:mm id:0
PM2        | App name:mm id:0 online

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
