### ISSUE TITLE
Too many calendar events

### ISSUE THREAD

**Issue by cederstrom** [MichMich/MagicMirror#1043]
**Platform**: Raspberry Pi 3.

**Node Version**: v6.10.2

**MagicMirror Version**: v2 (commit b7996097492baa57801c30b3d8fe2c2a7b5e3d03)

**Description**: Regarding the default calendar module.
When specifying more than one calendar, the maximum number of events will exceed that specified in `config.maximumEntries`.

**Steps to Reproduce**:
Example:
This config will yield a total of `calendars.length * maximunEntries = 4 * 5 = 20` events instead of 5.

**Expected Results**: I expect `config.maximumEntries` to limit the total number of events shown in by the module.

**Actual Results**: `config.maximumEntries` applies to each calendar in `config.calendars` and then the sum of all events will shown.

**Configuration**:
```javascript
{
    module: "calendar",
    position: "top_left",
    config: {
        maximumEntries: 5,
        calendars: [
            { url: "https://calendar.google.com/calendar/ical/family-member-one/basic.ics" },
            { url: "https://calendar.google.com/calendar/ical/family-member-two/basic.ics" },
            { url: "https://calendar.google.com/calendar/ical/family-member-three/basic.ics" },
            { url: "https://calendar.google.com/calendar/ical/family-member-four/basic.ics" }
        ]
    }
}
```

**Comment by MichMich** [comment]
Fixed in develop.
