### ISSUE TITLE
Configure Calendar

### ISSUE THREAD

**Issue by AngSupremo** [MichMich/MagicMirror#1063]
I'm getting my calendar from my Google ical and US-Holidays.  How can I configure the calendar to show something like the sample below?

![image](https://user-images.githubusercontent.com/32427364/31688396-172747a6-b341-11e7-9a03-b0643c238618.png)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
