### ISSUE TITLE
Sort modules by Date 

### ISSUE THREAD

**Issue by sainiaj** [MichMich/MagicMirror#1065]
Hi MichMich/MagicMirror Team
love your mirror have been running for more than an year love It
Thank you

I was wondering if their is anywhere to sort 3rd party modules added by date
reason being every week or so in order to check any new submissions i have to go through all of them because at the moment they are sorted by Name

Thank you once again for the amazing Magic Mirror

**Comment by MichMich** [comment]
Sorry, That's currently not possible since it's a simple wiki page. But maybe this is helpfull:
https://github.com/MichMich/MagicMirror/wiki/Home/_history
