### ISSUE TITLE
Events from Google Calendar showing at incorrect dates, or not showing at all

### ISSUE THREAD

**Issue by Txukie** [MichMich/MagicMirror#1070]
Edited:
I have been using a Google Calendar of birthdays to test this module out. Sometimes events show up but incorrectly, like several months in advance although they seem to show up on the same day, as in an event created for the 25th of March will actually show up as occurring on the 25th of October for example.

```
{
        module: "calendar",
        header: "Calendario",
        position: "top_left",
        classes: 'default everyone',
        config: {
            maximumEntries: 5,
            maximumNumberOfDays: 100,
            calendars: [
                  {
                           symbol: "exclamation-circle",
                           url: "webcal://calendar.google.com/calendar/ical/cf9euqob2a0tqe2409jffnpk2o%40group.calendar.google.com/private-a8870caf6c3ca46a785e7fd1fec0dcb5/basic.ics"
                   }
                  ]
              }
}
```

Just FYI, my locales are set as follows:

```
LANG=es_ES@euro
LANGUAGE=
LC_CTYPE="es_ES@euro"
LC_NUMERIC="es_ES@euro"
LC_TIME="es_ES@euro"
LC_COLLATE="es_ES@euro"
LC_MONETARY="es_ES@euro"
LC_MESSAGES="es_ES@euro"
LC_PAPER="es_ES@euro"
LC_NAME="es_ES@euro"
LC_ADDRESS="es_ES@euro"
LC_TELEPHONE="es_ES@euro"
LC_MEASUREMENT="es_ES@euro"
LC_IDENTIFICATION="es_ES@euro"
LC_ALL=
```

**Comment by morozgrafix** [comment]
@Txukie it may not be a good idea to post link to your private calendar in a public forum.

**Comment by Txukie** [comment]
You're totally right, let me make another account and copy this calendar accross and I will update my report accordingly.

**Comment by javilandoando** [comment]
I have same issue.
I don't know why although on google calendar any birthday remind is displayed properly, using this module I get a reminder related to a birthday on a different month although day, 21st for example, is correct.

Does any body find how to correct this?

**Comment by kleinmantara** [comment]
The same problem with me. I also use Google Calendar and all-day entries are displayed at the wrong time.

**Comment by mattmurf** [comment]
I'm getting garbled times..  The date is showing correctly.  

This was working and broke at some point in the past couple months.

Example:
Quiz blah, Blah, Blah
Today at AMb0oo12/4/2017ut1

**Comment by matthewpmangus** [comment]
I don't know if it'd work OR IF anything else MIGHT break, but it may be worth trying...

`npm update ical`?

**Comment by nhubbard** [comment]
@matthewpmangus If you don't have testing hardware, it works just fine on an Intel/AMD based system. We don't use any special modules.

**Comment by Txukie** [comment]
Tried the npm update ical to no avail

**Comment by E3V3A** [comment]
Make sure your locale is set correctly. There is little reason to not use UTF8.
```bash
# echo $LANG
en_US.UTF-8
```

Also check you time/date settings with:
```bash
# timedatectl status
...
```

**Comment by javilandoando** [comment]
time/date settings in my case are correct due to if they would be wrong, date will be displayed wrong on magic mirror.

I cannot check currently my locale setting but how does it impact on a time issue?
Does any body solve this problem?

**Comment by SpoturDeal** [comment]
I have noticed that events that are in the iCal records are without an DTEND will disappear on the actual date it should be visible. Without DTEND they will work in iPhone, Android and Windows.

```
BEGIN:VEVENT
UID:7c1caf04b1671cd607c204778c1ca9d1@www.uden.nl
DTSTAMP:20180118T102124
DTSTART;VALUE=DATE:20180317
SUMMARY:Papierinzameling
DESCRIPTION:Ophaaldag: zaterdag
TRANSP:TRANSPARENT
END:VEVENT
```
But this one works just add an DTEND to the event. (it is a mistake in building the iCal file by the provider.) In this case the city of Uden Netherlands

```
BEGIN:VEVENT
UID:7c1caf04b1671cd607c204778c1ca9d1@www.uden.nl
DTSTAMP:20180118T102124
DTSTART;VALUE=DATE:20180317
DTEND;VALUE=DATE:20180318 
SUMMARY:Papierinzameling
DESCRIPTION:Ophaaldag: zaterdag
TRANSP:TRANSPARENT
END:VEVENT
```

**Comment by MichMich** [comment]
Since this all has to do with the ical parser, I suggest we continue this issue discussion in: https://github.com/MichMich/MagicMirror/issues/1105
