### ISSUE TITLE
Filter news entries

### ISSUE THREAD

**Issue by TopperDEL** [MichMich/MagicMirror#1071]
This is not a bug, but a Feature request. I hope this place is still ok.

I would like to see a filter-Attribute for the newsfeed-module. There I would add a list of words and if any of these are found within the tilte of a news entry, the news entry gets ignored.

I want to hide any sport-related news on my mirror as this is of no interest for me. But there is no "normal" newsfeed in Germany without "news" about Soccer and such...

Thank you!

**Comment by ToddKlindt** [comment]
I would love this too. From one of my local newspaper's RSS feed I get headlines about pictures that I can't see, or editorial stuff. It would be great to be able to filter out articles by words in the title.

**Comment by morozgrafix** [comment]
Code for this feature has been merged into `develop` branch. Please test it out and let me know if this is something you had in mind. Also please let me know if you think it can be improved in any way.

Thanks.

**Comment by TopperDEL** [comment]
I checked it out and tried it. Seems to work exactly as expected - thank you! I have three newsfeed-modules with filter and one without - all work seemlessly.

**Comment by morozgrafix** [comment]
@MichMich I think we can close this one.
