### ISSUE TITLE
Empty black screen in IE 11/Edge

### ISSUE THREAD

**Issue by mrpetermatyas** [MichMich/MagicMirror#1073]
Dear Developers!

I tried to use on my laptop to check how it goes, but I realized, it works well in Chrome and does not work in IE 11/Edge. It only shows a black blank screen with the page named MagicMirror2.
I'm up to date with MM on a Rasbian with serveronly mode.

Thanks,

Peter

**Comment by MichMich** [comment]
Hi Peter,

IE & Edge are not officially supported. So I won't be working on a bug fix myself. Of course, anyone is welcome to send a PR which fixes this. I suggest you check out the forum to see if someone has a solution.

Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
