### ISSUE TITLE
how to stop mm from restarting

### ISSUE THREAD

**Issue by onkararj** [MichMich/MagicMirror#1077]
my MM keep restarting agin and again. can any one know how to stop it. right now for dev purpose i need it stop.

**Comment by ToddKlindt** [comment]
I believe you need to type, 'pm2 stop mm' at a prompt.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
