### ISSUE TITLE
Doesn’t work on Raspberry Pi Zero

### ISSUE THREAD

**Issue by kypse** [MichMich/MagicMirror#1085]
Dear Mich,
I got the same error message that MagicMirror doesn’t work at RPI zero.. same error closed on year ago...

**Comment by MichMich** [comment]
The Pi Zero is not officially supported. There are workaround which you can find on the forum.

Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
