### ISSUE TITLE
run magicmirror in subfolder - absolute include

### ISSUE THREAD

**Issue by balrok** [MichMich/MagicMirror#1086]
Using the latest version from github socket.io is included by an absolute path:
https://github.com/MichMich/MagicMirror/blob/master/index.html#L40

I run magicmirror with "node serveronly" and put it behind nginx, which maps it to a subfolder.. e.g.:
```
        location /dashboard/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://localhost:8080/;
        }
```
Having an absolute path there, it breaks my setup.. all other files seem to include just fine.

Edit: OK this is just the first in multiple bugs. I need to tell socket.io my subfolder too https://stackoverflow.com/questions/9729308/socket-io-connection-url

**Comment by MichMich** [comment]
Hi Balok, this is not a use case we support. Of course you can send a PR so we can include your fix for this, but I don't expect that any of the devs will . Cheers!
