### ISSUE TITLE
getting this error with ¨sh run-start.sh"on a fresh install. Before installing MM2,on a fresh Rasbian flashed SD card, I did a sudo apt-get update, then a sudo apt-get upgrade. I had this working great before and sent a copy of my config.js to myself in a gmail email. I got that file from the email and put it in the MagicMirror/Config folder. When I do npm start, it says there was a problem with electron and to report the issues saying there was a problem with sh run-start.sh¨.

### ISSUE THREAD

**Issue by AB-Normal1960** [MichMich/MagicMirror#1096]
Please only submit reproducible issues. 

If you're not sure if it's a real bug or if it's just you, please open a topic on the forum: [https://forum.magicmirror.builders/category/15/bug-hunt](https://forum.magicmirror.builders/category/15/bug-hunt)
Problems installing or configuring your MagicMirror? Check out: [https://forum.magicmirror.builders/category/10/troubleshooting](https://forum.magicmirror.builders/category/10/troubleshooting)

When submitting a new issue, please supply the following information:

**Platform**: Place your platform here... give us your web browser/Electron version *and* your hardware (Raspberry Pi 2/3, Windows, Mac, Linux, System V UNIX).

**Node Version**: Make sure it's version 0.12.13 or later.

**MagicMirror Version**: Now that the versions have split, tell us if you are using the PHP version (v1) or the newer JavaScript version (v2).

**Description**: Provide a detailed description about the issue and include specific details to help us understand the problem. Adding screenshots will help describing the problem.

**Steps to Reproduce**: List the step by step process to reproduce the issue.

**Expected Results**: Describe what you expected to see.

**Actual Results**: Describe what you actually saw.

**Configuration**: What does the used config.js file look like? Don't forget to remove any sensitive information!

**Additional Notes**: Provide any other relevant notes not previously mentioned. This is optional.

**Comment by AB-Normal1960** [comment]
BTW, I installed MM using this command from a fresh Raspian Stretch SD card after I did the Update and upgrade commands:  bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
