### ISSUE TITLE
After doing MMM-Assistant, voice recognition is not working

### ISSUE THREAD

**Issue by disheet** [MichMich/MagicMirror#1099]
I've install MMM-Assistant successful but while running the script, It is not working even microphone symbol is not coming to screen.

**Comment by MichMich** [comment]
This is an issue with a third party module, please open an issue in that repository.

Or refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
