### ISSUE TITLE
Using Roboto Condensed & subset latin-ext

### ISSUE THREAD

**Issue by ColonelMoutarde** [MichMich/MagicMirror#1100]
Hi,
By default using "Using Roboto Condensed" & "subset latin-ext" for improvment specials chars:
é, à, ù ... Using in french

**Comment by MichMich** [comment]
Those chars should work with the current font. Are you experiencing issues?

**Comment by ColonelMoutarde** [comment]
Without using Roboto Condensed" & "subset latin-ext
look météo...
![screenshot-2017-12-4 magicmirror](https://user-images.githubusercontent.com/4697568/33565404-4b2abae0-d91d-11e7-911e-f9fdc6992b09.png)

if i add in custom.css
@import url('https://fonts.googleapis.com/css?family=Roboto+Condensed&subset=latin-ext') ; 

![screenshot-2017-12-4 magicmirror 1](https://user-images.githubusercontent.com/4697568/33565541-acab71e2-d91d-11e7-805e-916f77fa483a.png)

**Comment by MichMich** [comment]
Ah, that's weird indeed. 

I think we need to mention this in the nam package of the font:
https://github.com/choffmeister/roboto-fontface-bower/issues/44

**Comment by ColonelMoutarde** [comment]
the diffrence is subset=latin-ext

**Comment by MichMich** [comment]
@ColonelMoutarde is it possible to set that with the NPM import?

**Comment by ColonelMoutarde** [comment]
How to do this with NPM, i'm newbe.

**Comment by nhubbard** [comment]
@MichMich This is difficult. The package we use doesn't have latin-ext in it. It looks like Google patches the font and hosts it instead. The solution may be using the Google Fonts version for now.

**Comment by nhubbard** [comment]
Either that, or we could download the fonts and make our own package.

**Comment by MichMich** [comment]
@nhubbard Looking forward to your PR! ;)

**Comment by MichMich** [comment]
@ColonelMoutarde: So, a bit of a slow response, but non the less ...

I wanted to add the correct front, but before I did I wanted to see the issue with my own eyes. So I configured a module with your exact French text, and it appears to show without any issues:

![screen shot 2017-12-30 at 21 26 50](https://user-images.githubusercontent.com/210954/34457142-665d0076-eda8-11e7-8825-39a15f6b27ef.png)

Is there anything I'm missing here?

**Comment by ColonelMoutarde** [comment]
For you, i add my config file
[config-Copie.js.txt](https://github.com/MichMich/MagicMirror/files/1597618/config-Copie.js.txt)

For write an accent you have 2 possibility. 
e+` and è 
first cas it's 2 chars and second cas is 1 char

**Comment by ColonelMoutarde** [comment]
[config-Copie.js.txt](https://github.com/MichMich/MagicMirror/files/1597622/config-Copie.js.txt)

**Comment by MichMich** [comment]
If I look at your config file the characters are scrambled too. It might be that your config file is encoded wrong. It the file stored as an utf-8 file?

**Comment by ColonelMoutarde** [comment]
the file is in utf-8 without BOM. That's what notepad++ says.

**Comment by MichMich** [comment]
Maybe it's the windows environment that causes the issue. Is it possible for you to test your setup in an Raspbian environment?

**Comment by MichMich** [comment]
Closed due to inactivity. Feel free to reopen.

**Comment by Knurlnheim** [comment]
Hello !

I have the same issue than @ColonelMoutarde, but I am on lastest Raspbian.
What can I do help investigate the issue ?

**Comment by MichMich** [comment]
@Knurlnheim Did you check the encoding of your config file? What system are you on?

**Comment by Knurlnheim** [comment]
System is a Raspian Strech Lite on a Raspberry Pi 2.
config.js is in UTF8.

**Comment by ColonelMoutarde** [comment]
I have reinstall MagicMirror in fresh install of Raspbian Stretch on my RPI2. 
All is OK, no problems

**Comment by MichMich** [comment]
@Knurlnheim Switch to the full version of Raspbian. Not the Lite version.
