### ISSUE TITLE
Electron failed to install correctly, please delete node_modules/electron and try installing again

### ISSUE THREAD

**Issue by nevets2k17** [MichMich/MagicMirror#1101]
**Anyone can help me to fix this problem ?**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.12.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.1.3~prestart: magicmirror@2.1.3
6 silly lifecycle magicmirror@2.1.3~prestart: no script for prestart, continuing
7 info lifecycle magicmirror@2.1.3~start: magicmirror@2.1.3
8 verbose lifecycle magicmirror@2.1.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle magicmirror@2.1.3~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle magicmirror@2.1.3~start: CWD: /home/pi/MagicMirror
11 silly lifecycle magicmirror@2.1.3~start: Args: [ '-c', 'sh run-start.sh' ]
12 silly lifecycle magicmirror@2.1.3~start: Returned: code: 1  signal: null
13 info lifecycle magicmirror@2.1.3~start: Failed to exec start script
14 verbose stack Error: magicmirror@2.1.3 start: `sh run-start.sh`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid magicmirror@2.1.3
16 verbose cwd /home/pi/MagicMirror
17 error Linux 4.9.67-v7+
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.12.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error magicmirror@2.1.3 start: `sh run-start.sh`
22 error Exit status 1
23 error Failed at the magicmirror@2.1.3 start script 'sh run-start.sh'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the magicmirror package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     sh run-start.sh
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs magicmirror
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls magicmirror
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
