### ISSUE TITLE
Uncaught exception in Calendar module

### ISSUE THREAD

**Issue by devinhedge** [MichMich/MagicMirror#1104]
**Platform**: Place your platform here... give us your web browser/Electron version *and* your hardware (Raspberry Pi 2/3, Windows, Mac, Linux, System V UNIX).

**Platform**:  Raspberry Pi 3

**Node Version**: v6.12.2

**MagicMirror Version**: [2.1.3]

**Description**:

MagicMirror default calendar module throws an exception when loading a calendar with an annual recurring event who's start date is before the UNIX Epoch date. Negative dates are not handled properly.

**Steps to Reproduce**:

1. Add calendar module to configuration.
2. Create Google calendar with recurring date starting prior to the UNIX Epoch date. ( aka Birthday)
3. Change calendar configuration URL to new calendar ics file from Google
4. pm2 restart mm
5. pm2 logs mm
.... find error in log.

**Expected Results**: Expected to see a list of future calendar events from Private gCal Calendar.

**Actual Results**: Describe what you actually saw.

`pm2 logs mm` produces...

`0|mm       | Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/somebody%40gmail.com/private-k9CpFEtHMFFvW3XtwGHzmk/basic.ics - Interval: 300000
0|mm       | Whoops! There was an uncaught exception...
0|mm       | Error: dates lower than Thu Jan 01 1970 00:00:00 GMT-0500 (EST) are not supported
0|mm       |     at Object.toOrdinal (/home/pi/MagicMirror/node_modules/rrule-alt/lib/rrule.js:105:15)
0|mm       |     at Iterinfo.rebuild (/home/pi/MagicMirror/node_modules/rrule-alt/lib/rrule.js:1415:35)
0|mm       |     at RRule._iter (/home/pi/MagicMirror/node_modules/rrule-alt/lib/rrule.js:984:10)
0|mm       |     at RRule.between (/home/pi/MagicMirror/node_modules/rrule-alt/lib/rrule.js:800:21)
0|mm       |     at /home/pi/MagicMirror/modules/default/calendar/calendarfetcher.js:135:24
0|mm       |     at Request._callback (/home/pi/MagicMirror/modules/default/calendar/vendor/ical.js/node-ical.js:11:5)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:186:22)
0|mm       |     at emitTwo (events.js:106:13)
0|mm       |     at Request.emit (events.js:194:7)
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1163:10)
0|mm       | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues`

**Visible behavior:** MagicMirror shows calendar placeholder, with the status of "Loading..." and never loads calendar events.

**Configuration**: 

`/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
    address: "localhost",   // Address to listen on, can be:
                            // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
                            // - another specific IPv4/6 to listen on a specific interface
                            // - "", "0.0.0.0", "::" to listen on any interface
                            // Default, when address config is left out, is "localhost"
    port: 8080,
    ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                   // or add a specific IPv4 of 192.168.1.5 :
	                                                   // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                   // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                   // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

    language: "en",
    timeFormat: 24,
    units: "imperial",

    modules: [
        {
            module: "MMM-OnScreenMenu",
            position: "bottom_right",
            /* Valid positions: 'top_right', 'top_left', 'bottom_right', 'bottom_left' */
            config: {
                touchMode: true,
                enableKeyboard: true
                // ... see more options below
            }
        },
        {
            module: "alert"
        },
        {
            module: "updatenotification",
            position: "top_bar"
        },
        {
            module: "clock",
            position: "top_left"
        },
        {
            module: 'calendar_monthly',
            position: 'top_left',
            config: {
                // The config property is optional
                // Without a config, a default month view is shown
                // Please see the 'Configuration Options' section for more information
                showHeader: true
            }
        },
        {
            module: "calendar",
            header: "US Holidays",
            position: "top_left",
            config: {
                calendars: [
                    {
                        symbol: "calendar-check-o",
                        url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics",
                        maximumEntries: 4
                    }
                ],
                maximumEntries: 4
            }
        },
        {
            module: "calendar",
            header: "Upcoming...",
            position: "top_left",
            config: {
                calendars: [
                    {
                        symbol: "calendar",
                        url: "https://calendar.google.com/calendar/ical/somebody%40gmail.com/private-k9CpFEtHMFFvW3XtwGHzmk/basic.ics"
                    }
                ],
                maximumNumberOfDays:1
            }
        },
        {
            module: "MMM-cryptocurrency",
            position: "top_center",
            config: {
                currency: ['bitcoin', 'dash', 'ethereum', 'litecoin', 'magi', 'monero', 'pivx', 'stratis', 'tether'],  //currently only pulls currencies in the top 25 by volume
                conversion: 'USD',
                headers: ['change24h', 'change1h', 'change7d'],
                displayType: 'details',
                showGraphs: true
            }
        },
        {
            module: "MMM-Stock",
            position: "top_center",
            config: {
                companies: ["MSFT", "GOOG", "ORCL", "FB", "AAPL"]
            }
        },
        {
            module: "MMM-Stocktable",
            position: "top_center"
        },
        {
            module: "currentweather",
            position: "top_right",
            config: {
                location: "Raleigh NC",
                locationID: "4487042",  //ID from http://www.openweathermap.org/help/city_list.txt
                appid: "c1ba9a29d87b10ab203d7f4b91067cd8"
            }
        },
        {
            module: "weatherforecast",
            position: "top_right",
            header: "Weather Forecast",
            config: {
                location: "Raleigh NC",
                locationID: "4487042",  //ID from http://www.openweathermap.org/help/city_list.txt
                appid: "c1ba9a29d87b10ab203d7f4b91067cd8"
            }
        },
        {
            module: "newsfeed",
            position: "bottom_bar",
            config: {
                feeds: [
                    {
                        title: "New York Times",
                        url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
                    }
                ],
                showSourceTitle: true,
                showPublishDate: true
            }
        }
    ]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}`

**Comment by MichMich** [comment]
Duplicate: https://github.com/MichMich/MagicMirror/issues/1066
