### ISSUE TITLE
weather forecast max days error

### ISSUE THREAD

**Issue by lilyangsta** [MichMich/MagicMirror#1118]
hi there for some reason the max numOf days shown on my screen is only 5 days but on your default code is 7. I've tried fixing it but didnt really work. maybe i'm doing something wrong?

**Comment by MichMich** [comment]
For some regions openWeatherMap doesn't supply enough days. This is not a config error.

Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
