### ISSUE TITLE
Chinese abnormality

### ISSUE THREAD

**Issue by Caibiy** [MichMich/MagicMirror#1119]
![rqp0yydr 9w l0ru07 xk](https://user-images.githubusercontent.com/16449809/34611494-b554652c-f260-11e7-851b-3031762145a6.png)
config: {
	compliments: {
		anytime: [
			"Hey,fuck the world pls!"
		],
		morning: [
			"Good morning, handsome!",
			"Enjoy your day!",
			"How was your sleep?"
		],
		afternoon: [
			"Hello, beauty!",
			"You look sexy!",
			"Looking good today!"
		],
		evening: [
			"晚上好"
		]
	}
}

**Comment by MichMich** [comment]
My guess is the font doesn't include the required characters. You could try changing the fonts bij adjusting your css file.

**Comment by Caibiy** [comment]
No effect
![image](https://user-images.githubusercontent.com/16449809/34641229-cf14c552-f33b-11e7-9532-d53f84bf7cb6.png)

**Comment by MichMich** [comment]
Than it might have something todo with the config.js encoding or the encoding used on the page. It could use some experimenting. A pull-request is more than welcome.

**Comment by Caibiy** [comment]
thank you..it is worked..

**Comment by MichMich** [comment]
Good to hear! What did you change? For future users having the same issue ...

**Comment by Caibiy** [comment]
Modified config.js encoding
