### ISSUE TITLE
Please reccomend MMM developers to add screenshots

### ISSUE THREAD

**Issue by E3V3A** [MichMich/MagicMirror#1122]
As **MM is a fantastic project that is highly connected with aesthetics**, it is quite annoying and surprising to see how few MMM module developers actually bother to put a screenshot on their README pages. Instead one has to go search or even make a temp install to find out how it really look. Most of the time a waste of effort as it doesn't suite what I was looking for. 

@MichMich 
Would you consider to or recommend module developers to add a screenshot to their pages?
(Actually, why not demand it!?)

**Comment by MichMich** [comment]
It’s an open framework so demanding is not an option (and not the route we want to take). Giving a recommendation is a good idea though. The best place to put this is in the developer documentation and at the top of the 3rd party module listing. Feel free to send a PR for this.

**Comment by E3V3A** [comment]
@MichMich 
Just updated README as well.
Thanks for your kind support! :) 🥇
