### ISSUE TITLE
Inform RPi users that npm install take a long time

### ISSUE THREAD

**Issue by E3V3A** [MichMich/MagicMirror#1124]
When I installed MM on my Rpi3 last night, I was quite surprised to see how long it took, without any info at all given to the user while waiting. We live in times of impatience, so when the npm native progress indicator disappeared for almost 8 minutes, after 2 minutes of completing many progress bars, I was getting concerned. Especially given that installing the entire OS only took about half the time. 

 ```bash
cd $HOME
git clone https://github.com/MichMich/MagicMirror.git
cd MagicMirror

# Install node dependencies (on Vanilla Stretch)
npm install
...
<eat your nails>
<scratch your balls (or what have you)>
<rip your hair out>
...
added 811 packages in 568.737s
```

**That is almost 8 minutes without any progress bar!**
Also, a basic MM install, take up: **348 MB** (not including any additional OS related installations.)

`cd $HOME/MagicMirror/ && du -sh ./`

We should put this in the README. 
I'm sure many (and even technical) users may freak out long before those 10 minutes are up.

**Comment by MichMich** [comment]
Or we can run NPM in verbose mode.

**Comment by E3V3A** [comment]
Ha ha! Yeah, there's always a simpler solution around the corner. :) 
I haven't looked at it, but if it's too verbose, that can be annoying too. 
Then people start freaking out for seeing too much of what they can't understand anyway. :D

**Comment by MichMich** [comment]
An alternative solution is a post install script which echos a warning.

**Comment by henrikra** [comment]
Yeah I was surprised on first time it took a long time :D

**Comment by amcolash** [comment]
Ironic that I was just browsing the issue tracker, I just updated my rpi2 and it took 25+ min! I know npm can be slow (so I was patient), but wow that was a shock.

**Comment by E3V3A** [comment]
Hmm.. Any ideas?
```
Running "markdownlint:all" (markdownlint) task
Warning: 
README.md: 53: MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
README.md: 55: MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
 Use --force to continue.
Aborted due to warnings.
```
