### ISSUE TITLE
A better source for example/template iCal *.ics files

### ISSUE THREAD

**Issue by E3V3A** [MichMich/MagicMirror#1129]
@MichMich 

I found a website that allow you download *iCal* formatted `*.ics` files of public/national holidays. They seem better than the one supplied by default. Please have a look and let us know you think.

Browse [countries here](https://www.officeholidays.com/ics/index.php) and select the new URL with the appropriate ISO country code in the link (here Ireland):

```
https://www.officeholidays.com/ics/ics_country_code.php?iso=IE
```

**Comment by E3V3A** [comment]
It's certainly not important, but it help people locate a working ics for their own country as the original site only seem to have ones available for US and UK (and possibly very few others).

**Comment by SpoturDeal** [comment]
I have made a Calender.ics with all Dutch holidays (feestdagen)
free to use through the url: http://acentra.nl/feestdagen

**Comment by hesseny2000** [comment]
thanks E3V3A

**Comment by SpoturDeal** [comment]
@hesseny 

(Als Ramadam, Eid Al Fitr (Suikerfeest) and Eid al Adha (Offerfeest) are in the list.
I am currently working on a system that you can also add a birthday list.

**Comment by MichMich** [comment]
Hi Guys, What do you want me to do with the issue? Can I close it, or does it need to stay open? Feel free to send a PR with a new default ical feed.

**Comment by nhubbard** [comment]
@MichMich We can close this, b/c I don't think a PR ever materialized for this issue.
