### ISSUE TITLE
currentweather disable windspeed and sunset/sunrise

### ISSUE THREAD

**Issue by bonaime** [MichMich/MagicMirror#1148]
Hi,
Is it possible to add the option to disable wind informations and sunset/sunrise ? 
Thank you

**Comment by MichMich** [comment]
Maybe this works for you:

`onlyTemp: true`

**Comment by bonaime** [comment]
I just found it ! Maybe it could be useful to explain that in the documentation : 
Show only current Temperature and weather icon without windspeed, sunset and sunrise

**Comment by MichMich** [comment]
Feel free to send a PR! :)

https://github.com/MichMich/MagicMirror/edit/develop/modules/default/currentweather/README.md

**Comment by bonaime** [comment]
#1149
