### ISSUE TITLE
Calendars and recurring events

### ISSUE THREAD

**Issue by SVendittelli** [MichMich/MagicMirror#115]
The calendar module only displays the first event for recurring events. So it only displays these for which the first event is in the future.

![image](https://cloud.githubusercontent.com/assets/17616742/14189107/91f2c0c6-f783-11e5-9aa0-5d5c4724bb82.png)
![screenshot 2016-03-31 20 59 52](https://cloud.githubusercontent.com/assets/17616742/14189113/9a091d50-f783-11e5-84af-77d5ad3bf8fd.png)

The relevant [.iCal](http://sharing.calendar.live.com/calendar/private/627e39d3-45d4-4763-b343-0b919de89dfa/a47b1221-7993-40bc-a844-5b42098bd9dc/cid-12ee71079603e521/calendar.ics).

**Comment by MichMich** [comment]
This issue should be solved now. Could you give it a try?

**Comment by SVendittelli** [comment]
Yep, works great!
