### ISSUE TITLE
Error in updating MagicMirror

### ISSUE THREAD

**Issue by caldecy** [MichMich/MagicMirror#1165]
**Description**: I can't seem to update my MagicMirror module due to the error below. 

**Steps to Reproduce**: upon running the `git pull && npm install` command

**Actual Results**:
error: Your local changes to the following files would be overwritten by merge:
	css/main.css
	modules/default/calendar/calendar.js
	modules/default/clock/clock.js
	modules/default/currentweather/currentweather.js
	modules/default/weatherforecast/weatherforecast.js
Please commit your changes or stash them before you merge.
Aborting

Could someone kindly guide me along or how to stash or commit my changes? 

Thanks!

**Comment by MichMich** [comment]
You've probably modified some core files. 
https://forum.magicmirror.builders/topic/2215/update-says-to-commit-your-changes-or-stash-them-before-you-can-merge/25

Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
