### ISSUE TITLE
Can I add Chinese translation to this project？

### ISSUE THREAD

**Issue by Caibiy** [MichMich/MagicMirror#1167]

**Comment by MichMich** [comment]
It looks like it’s already available:


	"zh_cn" : "translations/zh_cn.json", // Simplified Chinese
	"zh_tw" : "translations/zh_tw.json", // Traditional Chinese

**Comment by Caibiy** [comment]
I mean this is the document README.md

**Comment by MichMich** [comment]
Ah, ok. Since we have regular changes in the README and documentation, I'm not sure if that is a good idea. But of course, you're free to do so. It might be better to put the translation in the Wiki though.

**Comment by Caibiy** [comment]
It's free, of course. It's my pleasure
