### ISSUE TITLE
What is a "lagacy" module and how to avoid or determine the difference

### ISSUE THREAD

**Issue by E3V3A** [MichMich/MagicMirror#1169]
The wiki page for [Legacy Modules](https://github.com/MichMich/MagicMirror/wiki/legacy-modules) contain a long list of pretty much most modules. But there is not a word on what makes a module `legacy` or not. So since nobody in the world of programming likes the word "legacy", I think we need a clear definition what it means here. 

* How to determine if a module is legacy?
* How to avoid writing new *legacy* modules?
* How to update and modify a *legacy* module, to non-legacy status. 

Please consider adding these answers to the very short list of FAQ's...

**Comment by MichMich** [comment]
Those are not Legacy modules. It's a Legacy list, since there is a new grouped list. 
The API did not yet have an API change that killed old modules. So there are no legacy modules.

Feel free to edit the Wiki to make this more clear. Thanks.
