### ISSUE TITLE
MagicMirror module show/hide animation

### ISSUE THREAD

**Issue by paviro** [MichMich/MagicMirror#117]
If you hide a module and the one underneath it should stays visible it jumps (see [YouTube](https://www.youtube.com/watch?v=TwXuK0CHWTg)) to its new position. Would it be possible to animate/slide it to the new position?

**Comment by MichMich** [comment]
I experimented a bit with this, but it's rather difficult. I will work on this in the future, but for now it hasn't got the highest priority. I've put it on the todo list in the README.

**Comment by nhubbard** [comment]
If I'm correct, you could use CSS3 Transitions, correct?

**Comment by MichMich** [comment]
@nhubbard: it already does

**Comment by nhubbard** [comment]
In this case, when a module is deactivated, is it possible to apply a data tag (such as `data-module-deactivated=true`) to a tag and apply a transition/animation to that tag?

**Comment by MichMich** [comment]
I don't think this is going anywhere soon. Fee free to reopen if necessary.
