### ISSUE TITLE
Development Guide: module optimization

### ISSUE THREAD

**Issue by E3V3A** [MichMich/MagicMirror#1170]
I've noticed that many MMM's are relying upon using large npm packages libraries to do rather trivial tasks. AFAIK, using and running these may take up excessive memory and computation resources that will slow down and hamper (at best) the performance of MM's that are using many MMM's. Possibly even crashing your RPi by overload. 

For example, having your module require and rely upon using [moment](https://github.com/moment/moment/) which is a **1.3 MB** package just to do some trivial date manipulations is totally overkill!  

So perhaps more experienced MMM writers could add some ideas and recommendations on how to optimize your new MMM?

**Comment by MichMich** [comment]
No need to over optimise things. That fact that Moment.js is 1.3mb doesn't mean it's running 1.3mb of code. It includes a lot of localisation. This is not something from which the RPi suffers. Let alone crashes.

Please only open GitHub issues for proven problems with the core. If you think things can improve, feel free to discuss on [slack](http://slack.magicmirror.builders).
