### ISSUE TITLE
Auto install fails to install dependencies

### ISSUE THREAD

**Issue by joncage** [MichMich/MagicMirror#1187]
**Platform**: Raspberry Pi 3

**Node Version**: Make sure it's version 0.12.13 or later.

**MagicMirror Version**: Latest from github as of 26/02/18

**Description**: Fresh install of noobs on a brand new Raspberry Pi 3. Ran the auto install script specified from `readme.md ` and it failed.

**Steps to Reproduce**: Run the auto install command:

```
bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"
```

...then wait for the install to fail with the following message:

```
Cloning MagicMirror Done!
Installing dependencies ...
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN prefer global coffeescript@1.10.0 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g

> uws@9.14.0 install /home/pi/MagicMirror/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0
```

**Expected Results**: A message indicating the install completed as expected.

**Actual Results**: The error message above.

**Configuration**: No idea; Didn't get that far.

**Comment by MichMich** [comment]
Did you just get those warnings? Or does it fail to start? Because those warnings kan be ignored.

**Comment by joncage** [comment]
I did get it to start but the page it displays is completely black with no text so I had assumed something didn't work?

**Comment by ibrahim5alil** [comment]
please guys every time i try to use the auto installation code its Dosn't take any action how i can solve this 

pi@raspberrypi:~ $ curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh | bash
pi@raspberrypi:~ $

**Comment by fewieden** [comment]
@ibrahim5alil using a non outdated cmd would be a good start ^^

```bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"```

**Comment by ibrahim5alil** [comment]
@fewieden  i'v tried both of the codes and it didn't work 
can u explain wt do u mean by using a non outdated cmd please

**Comment by MichMich** [comment]
What happens if you leave out the `| bash` in the first command?

**Comment by ibrahim5alil** [comment]
@MichMich nothing just no action at all
pi@raspberrypi:~ $bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"
pi@raspberrypi:~ $

**Comment by MichMich** [comment]
No, the first one:
`curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh`

**Comment by ibrahim5alil** [comment]
pi@raspberrypi:~ $ curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh | bash
pi@raspberrypi:~ $ curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh | bash
pi@raspberrypi:~ $ curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh
pi@raspberrypi:~ $ bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"
pi@raspberrypi:~ $ curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh
pi@raspberrypi:~ $ 

@MichMich  just no action

**Comment by MichMich** [comment]
are you sure your pi is connected to the internet?

**Comment by ibrahim5alil** [comment]
@MichMich  yes i can clone and update i can enter any code except this
![img_8907](https://user-images.githubusercontent.com/37037870/36999243-f4261baa-20d8-11e8-8cb9-2204f3680b1f.jpg)

**Comment by MichMich** [comment]
What happens if you run `curl google.com`?

**Comment by ibrahim5alil** [comment]
![img_8908](https://user-images.githubusercontent.com/37037870/36999437-842e75bc-20d9-11e8-908c-8818ed7f5d79.jpg)
@MichMich

**Comment by MichMich** [comment]
Try `curl https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh`

**Comment by ibrahim5alil** [comment]
![img_8909](https://user-images.githubusercontent.com/37037870/36999625-2622154a-20da-11e8-98b2-c319dbddae00.jpg)
@MichMich nothing

**Comment by MichMich** [comment]
It appears the your pi cant resolve the GitHub domain name. Which DNS are you using?

**Comment by ibrahim5alil** [comment]
![img_8910](https://user-images.githubusercontent.com/37037870/37000076-9b862a28-20db-11e8-8a48-2fe87a50ed64.jpg)
@MichMich

**Comment by MichMich** [comment]
That’s your router. You might want to try a direct DNS like googles. 8.8.8.8

Furthermore this isn’t a MagicMirror issue. It’s more a generic Pi issue. I suggest you try to get some help on the forum http://forum.magicmirror.builders

**Comment by ibrahim5alil** [comment]
thank you @MichMich for you helping me

**Comment by MichMich** [comment]
You’re welcome!

**Comment by braunprinz** [comment]
Hello guys,
I was trying to install MagicMirror, I got the error message
"Unable to Install dependencies"
How can I solve this
I tried to install it few times, even manually it didn't work
![20190226_204344](https://user-images.githubusercontent.com/10375458/53441637-8742e100-3a07-11e9-9a31-1b3ba513667e.jpg)

**Comment by braunprinz** [comment]
Got it, the npm package was not installed
Just run the following command
sudo apt-get install npm

**Comment by braunprinz** [comment]
I have tried to install npm package. After doing that i run the auto,atic installation again, and I got the same error message
![20190226_205728](https://user-images.githubusercontent.com/10375458/53442654-1bae4300-3a0a-11e9-971e-cfecb3e153bc.jpg)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
