### ISSUE TITLE
Only black screen

### ISSUE THREAD

**Issue by thk4711** [MichMich/MagicMirror#1188]
I am using a PI 3 with a fresh installation of Raspbian. I followed the instructions under Manual Installation. The I copied config/config.js.sample to config/config.js This worked but when I start the software with npm start I only get a black screen. Also when I start the software with node serveronly and use Chrome on a different computer I only get a black screen in the browser. In the console of Chrome I get the following errors:

Failed to load resource: the server responded with a status of 404 (Not Found)
Roboto-Condensed-Regular.woff2 Failed to load resource: the server responded with a status of 404 (Not Found)
Roboto-Condensed-Regular.woff Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:404 Initializing MagicMirror.
translator.js:197 Loading core translation file: translations/en.json
translator.js:219 Loading core translation fallback file: translations/en.json
loader.js:182 Load script: modules/default/alert//alert.js
Roboto-Condensed-Regular.ttf Failed to load resource: the server responded with a status of 404 (Not Found)
module.js:477 Module registered: alert
loader.js:152 Bootstrapping module: alert
loader.js:182 Load script: modules/default/alert/classie.js
loader.js:182 Load script: modules/default/alert/modernizr.custom.js
loader.js:182 Load script: modules/default/alert/notificationFx.js
loader.js:157 Scripts loaded for: alert
loader.js:197 Load stylesheet: modules/default/alert/ns-default.css
loader.js:159 Styles loaded for: alert
translator.js:170 alert - Load translation fallback: translations/en.json
loader.js:161 Translations loaded for: alert
loader.js:182 Load script: modules/default/updatenotification//updatenotification.js
module.js:477 Module registered: updatenotification
loader.js:152 Bootstrapping module: updatenotification
loader.js:157 Scripts loaded for: updatenotification
loader.js:159 Styles loaded for: updatenotification
loader.js:161 Translations loaded for: updatenotification
loader.js:182 Load script: modules/default/clock//clock.js
module.js:477 Module registered: clock
loader.js:152 Bootstrapping module: clock
loader.js:182 Load script: vendor/node_modules/moment/min/moment-with-locales.js
:8080/vendor/node_modules/moment/min/moment-with-locales.js Failed to load resource: the server responded with a status of 404 (Not Found)
loader.js:190 Error on loading script: vendor/node_modules/moment/min/moment-with-locales.js
script.onerror @ loader.js:190
loader.js:182 Load script: vendor/node_modules/moment-timezone/builds/moment-timezone-with-data.js
:8080/vendor/node_modules/moment-timezone/builds/moment-timezone-with-data.js Failed to load resource: the server responded with a status of 404 (Not Found)
loader.js:190 Error on loading script: vendor/node_modules/moment-timezone/builds/moment-timezone-with-data.js
script.onerror @ loader.js:190
loader.js:157 Scripts loaded for: clock
loader.js:197 Load stylesheet: modules/default/clock/clock_styles.css
loader.js:159 Styles loaded for: clock
loader.js:161 Translations loaded for: clock
loader.js:182 Load script: modules/default/calendar//calendar.js
module.js:477 Module registered: calendar
loader.js:152 Bootstrapping module: calendar
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: calendar
loader.js:197 Load stylesheet: modules/default/calendar/calendar.css
loader.js:197 Load stylesheet: vendor/node_modules/font-awesome/css/font-awesome.min.css
192.168.178.40/:1 Refused to apply style from 'http://192.168.178.40:8080/vendor/node_modules/font-awesome/css/font-awesome.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
loader.js:206 Error on loading stylesheet: vendor/node_modules/font-awesome/css/font-awesome.min.css
stylesheet.onerror @ loader.js:206
loader.js:159 Styles loaded for: calendar
loader.js:161 Translations loaded for: calendar
loader.js:182 Load script: modules/default/compliments//compliments.js
module.js:477 Module registered: compliments
loader.js:152 Bootstrapping module: compliments
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: compliments
loader.js:159 Styles loaded for: compliments
loader.js:161 Translations loaded for: compliments
loader.js:182 Load script: modules/default/currentweather//currentweather.js
module.js:477 Module registered: currentweather
loader.js:152 Bootstrapping module: currentweather
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: currentweather
loader.js:197 Load stylesheet: vendor/node_modules/weathericons/css/weather-icons.css
192.168.178.40/:1 Refused to apply style from 'http://192.168.178.40:8080/vendor/node_modules/weathericons/css/weather-icons.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
loader.js:206 Error on loading stylesheet: vendor/node_modules/weathericons/css/weather-icons.css
stylesheet.onerror @ loader.js:206
loader.js:197 Load stylesheet: modules/default/currentweather/currentweather.css
loader.js:159 Styles loaded for: currentweather
loader.js:161 Translations loaded for: currentweather
loader.js:182 Load script: modules/default/weatherforecast//weatherforecast.js
module.js:477 Module registered: weatherforecast
loader.js:152 Bootstrapping module: weatherforecast
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: weatherforecast
loader.js:237 File already loaded: weather-icons.css
loader.js:197 Load stylesheet: modules/default/weatherforecast/weatherforecast.css
loader.js:159 Styles loaded for: weatherforecast
loader.js:161 Translations loaded for: weatherforecast
loader.js:182 Load script: modules/default/newsfeed//newsfeed.js
module.js:477 Module registered: newsfeed
loader.js:152 Bootstrapping module: newsfeed
loader.js:237 File already loaded: moment.js
loader.js:157 Scripts loaded for: newsfeed
loader.js:159 Styles loaded for: newsfeed
loader.js:161 Translations loaded for: newsfeed
loader.js:197 Load stylesheet: css/custom.css
alert.js:151 Starting module: alert
updatenotification.js:10 Start updatenotification
clock.js:40 Starting module: clock
clock.js:49 Uncaught ReferenceError: moment is not defined
    at Class.start (clock.js:49)
    at startModules (loader.js:55)
    at loader.js:40
    at HTMLLinkElement.stylesheet.onload (loader.js:203)
7clock.js:77 Uncaught ReferenceError: moment is not defined
    at Class.getDom (clock.js:77)
    at updateDom (main.js:99)
    at Object.updateDom (main.js:468)
    at Class.updateDom (module.js:358)
    at clock.js:45
192.168.178.40/:1 Refused to apply style from 'http://192.168.178.40:8080/vendor/node_modules/font-awesome/css/font-awesome.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
192.168.178.40/:1 Refused to apply style from 'http://192.168.178.40:8080/vendor/node_modules/weathericons/css/weather-icons.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
32clock.js:77 Uncaught ReferenceError: moment is not defined
    at Class.getDom (clock.js:77)
    at updateDom (main.js:99)
    at Object.updateDom (main.js:468)
    at Class.updateDom (module.js:358)
    at clock.js:45
getDom @ clock.js:77
updateDom @ main.js:99
updateDom @ main.js:468
updateDom @ module.js:358
(anonymous) @ clock.js:45

**Comment by fewieden** [comment]
looks like your dependencies didnt got installed correctly, go to the vendor directory and execute npm install

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
