### ISSUE TITLE
Using Roboto Condensed & subset latin-ext (see Issue #1100)

### ISSUE THREAD

**Issue by Knurlnheim** [MichMich/MagicMirror#1195]
Hello, 

Sorry about the duplicate, you cannot reopen a closed issue.
As I said in issue #1100, I have the same problem with the font and french accented characters.
I'm on a raspberry Pi with latest Raspbian.
Workaround in custom.css doesn't work for me.
What can I do to help solve the issue ?

**Comment by MichMich** [comment]
I Reopened #1100
