### ISSUE TITLE
Calendar and news feed stuck loading under language:"zh_cn"

### ISSUE THREAD

**Issue by philipdeng** [MichMich/MagicMirror#1196]
MM works well under all English environment. But it does not work if calendar or newsfeed contain any Chinese characters
However, after changing to language:"zh_cn" in config file, calendar and newsfeed stuck loading even it could be displayed under language en setting.

![image](https://user-images.githubusercontent.com/22946991/37063719-5ad12888-2168-11e8-93af-796bbd4e5da1.png)
![image](https://user-images.githubusercontent.com/22946991/37063921-1b758aac-2169-11e8-80cd-c576cd2a3994.png)
![image](https://user-images.githubusercontent.com/22946991/37063964-3d912cb8-2169-11e8-8904-cd9cb2270601.png)

I found this in errors log.
0|mm       | [1887:0306/172303:FATAL:bus.cc(1204)] D-Bus connection was disconnected. Aborti
ng.
0|mm       | #0 0x0000012a3bb0 <unknown>
0|mm       | #1 0x0000012b4406 <unknown>
0|mm       | #2 0x00000120fd0a <unknown>

**Comment by MichMich** [comment]
Did you check the encoding property you can set for news feeds?

**Comment by philipdeng** [comment]
Yes, I tried all available encoding, but not work.

**Comment by philipdeng** [comment]
It will be stuck on loading if this calendar or newsfeed contain any Chinese characters。

**Comment by fewieden** [comment]
Could you provide the config for your newsfeed?

**Comment by WuWeiWW** [comment]
这个是因为 用了`moment` 组件，设置本地语言时候 `setLccation`或 `updateLocal` 时候需要 `zh-cn` 但是传入的是 `zh_cn`;
解决方案: 修改 `translations.js` 和 `config.js` `zh_cn`为 `zh-cn`

**Comment by MichMich** [comment]
Merged.
