### ISSUE TITLE
Email Error

### ISSUE THREAD

**Issue by preciousviral** [MichMich/MagicMirror#1198]
Connecting socket for: email
email helper started ...
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/preciousviral%40gmail.com/public/basic.ics - Interval: 300000
Create new news fetcher for url: http://indiatoday.intoday.in/rss/homepage-topstories.jsp - Interval: 300000
Create new news fetcher for url: http://www.news18.com/rss/india.xml - Interval: 300000
Create new news fetcher for url: http://www.news18.com/rss/politics.xml - Interval: 300000
Create new news fetcher for url: http://www.news18.com/rss/tv.xml - Interval: 300000
listening for emails...
Can't parse feed item:
{ title: 'Subscribe Now',
  link: 'http://indiatoday.intoday.in/subscription.html?utm_source=rss',
  description: 'Subscribe now for your favourite magazines' }
Title: Subscribe Now
Description: Subscribe now for your favourite magazines
Pubdate: undefined
Whoops! There was an uncaught exception...
TypeError: mime.extension is not a function
    at MailParser._generateFileName (/home/pi/MagicMirror/modules/email/node_modules/mailparser/lib/mailparser.js:1407:27)
    at MailParser._processStateHeader (/home/pi/MagicMirror/modules/email/node_modules/mailparser/lib/mailparser.js:309:61)
    at MailParser._process (/home/pi/MagicMirror/modules/email/node_modules/mailparser/lib/mailparser.js:227:22)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Can't parse feed item:
{ title: 'Subscribe Now',
  link: 'http://indiatoday.intoday.in/subscription.html?utm_source=rss',
  description: 'Subscribe now for your favourite magazines' }
Title: Subscribe Now
Description: Subscribe now for your favourite magazines
Pubdate: undefined

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
