### ISSUE TITLE
Small documentation issues, broken links, and a query on where to find UI screenshots

### ISSUE THREAD

**Issue by mtfurlan** [MichMich/MagicMirror#1207]
So [the documentation](https://github.com/MichMich/MagicMirror/wiki/3rd-party-modules#general-advice) has the line
>  it is surprising to see how few module developers actually bother to put a screenshot on their README pages. 

But then if we look at any of the pages for the [default modules](https://github.com/MichMich/MagicMirror/wiki#default-modules), none of them have pictures. 

Also in the [readme modules section](https://github.com/MichMich/MagicMirror#modules) the link to  MagicMirror² Modules goes to a redirect. The magicmirror.builders navbar modules link also goes to the same wrong place.

I'm not trying to call everything bad, just want to help point out a few documentation issues I'm finding as I try to find pictures of what the UI looks like.

The only picture I've found is on the bottom of magicmirror.builders and is https://magicmirror.builders/img/explode.jpg

Is there like a gallery of pictures of the UI anywhere, because I seriously can't find any and I think I'm just blind.

**Comment by E3V3A** [comment]
@mtfurlan 
Hi Mark, 
Most of the pictures for MM and are (as you noticed?) in the [forum](https://forum.magicmirror.builders/) pages. The text you quoted was something I've added just very recently, while MM has been around for at least 2 years. Michael made this, most likely in his spare time, so the default modules are now, mostly updated by other people and may not be as up to date, documentation wise, as newcomers would wish.  

However,  we all are open to PR's and fixes are often merged in short time, if they are simple and going to the development branch. By all means, please contribute if you can.

**Comment by mtfurlan** [comment]
Yeah, fair enough.
If I find the time to get started with this I'll try to get pictures to add.
I did not notice, and I still don't find pictures in the forum? Aside from the "Show your mirror" section.
Clearly I'm missing something, but I just wanted to see what the calendar looks like.

**Comment by E3V3A** [comment]
@mtfurlan There are now several different calendar modules available, with very different visual porn aspects. I suggest you just get started, as that should be very straight forward. And you can see for yourself. Since I'm not using that calendar right now, I can 't show you. But I'd be very surprise if you're not able to find some picture of it... TBH I don't think you even bothered to google that. 

This was my first hit.
https://forum.magicmirror.builders/topic/5/calendar-event-dates-enhancement

**Comment by mtfurlan** [comment]
It's true, I did not try to use google to index your site, I tried to use your site.
Closing, because this isn't making magic mirror better.
