### ISSUE TITLE
Increase the stable node version in installation script

### ISSUE THREAD

**Issue by E3V3A** [MichMich/MagicMirror#1208]
In the `dev` branch the current instalaltion script is using the `6.x` as the [stable Debian node](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) branch. This is very out dated and should be changed to `9.x`. 

[Here](https://github.com/MichMich/MagicMirror/blob/develop/installers/raspberry.sh#L85) is the line. 
```bash
	NODE_STABLE_BRANCH="6.x"
```

That is:
```bash
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
```

**Comment by MichMich** [comment]
Could you please send a PR?

**Comment by MichMich** [comment]
Ah, just noticed you did :)
