### ISSUE TITLE
Unable to display weather description

### ISSUE THREAD

**Issue by leone510es** [MichMich/MagicMirror#1215]
Hi all!

I just wanted to display the short weather description text (fog, cloudy, etc...) provided by the openweathermap API, but can't find the way how...

Im was trying to extend the getDom: function() with this:
`var description = document.createElement("div");`
`description.innerHTML = this.desc;`
`large.appendChild(description);`

`wrapper.appendChild(large);`
`return wrapper;'`

and the processWeather: function(data) with this:
`this.desc = data.weather[0].description;`

But nothing was changed. The goal is to show that short description below the weather informations.

What am I missing?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
