### ISSUE TITLE
Black Screen **Still tried all fixes**

### ISSUE THREAD

**Issue by jdownwardpock** [MichMich/MagicMirror#1221]
cloned and followed instruction properly. installing on kali linux 2018.1 on a dell not sure what model
it starts up with a black screen and when I close it this is in my console

Starting MagicMirror: v2.2.2
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...

Ready to go! Please point your browser to: http://localhost:8080

Tried all fixes including downgrading electron and when that did not work upgraded electron still no work

contents of my config are 

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en-us",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Australian Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						//url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
						url: "webcal://www.calendarlabs.com/templates/ical/Australia-Holidays.ics"
					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Perth",
				locationID: "2063523",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "******************************************"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "Perth",
				locationID: "2063523",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "****************************************"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "TheWest (WA)",
						url: "https://thewest.com.au/news/wa/rss"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

I have removed my api keys from this paste for security reasons

**Comment by E3V3A** [comment]
1. Please use the README + installation instructions in the development branch. 
2. Try to start with just one module at the time. Because if any module fails (e.g. because of lacking API keys), it is likely all MM fails to start. 
3. Check your log files.
4. Enclose your pasted screen results in triple back-ticks (```), so that we can read it.
5. Make sure to include and clearly show your commands prior to any errors.
6. Make sure your nodejs and npm are up to date.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
