### ISSUE TITLE
Trouble Adding News Feeds

### ISSUE THREAD

**Issue by Linsanity77** [MichMich/MagicMirror#1223]
Hello,
I am trying to add news feeds into config/config.js, but when I add the third, it says please create config file. I don't know what's wrong. Here's the module:
  {
                        module: "newsfeed",
                        position: "bottom_bar",
                        config: {
                                feeds: [
                                        {
                                                title: "New York Times World",
                                                url: 'https://www.nytimes.com/s$
                                        },
{
title: "CNN",
url: 'http://rss.cnn.com/rss/cnn_topstories.rss'
},
{
title: "New York Times Us"
url: 'https://www.nytimes.com/services/xml/rss/nyt/US.xml',
},

                                ],
                                showSourceTitle: true,
                                showPublishDate: true
                        }
                },
        ]

};

Thanks!

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
