### ISSUE TITLE
Pi zero mm2

### ISSUE THREAD

**Issue by Mikgabo** [MichMich/MagicMirror#1226]
Hey all, noob alert... 

Trying to manual install on pi zero w and can't download Mm2. Here is what happens:
                                                
pi@raspberrypi:~ $ git clone https://github.com/MichMich/MagicMirror                
-bash: git: command not found

Any suggestions? 
Cheers, 
Mike

**Comment by MichMich** [comment]
You're probably running the Raspbian Lite version. Please use the full version.

Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
