### ISSUE TITLE
MagicMirror fails to start - NPM issue

### ISSUE THREAD

**Issue by Sachin1968** [MichMich/MagicMirror#1229]
Hello,

MagicMirror2 has been working for quite some time and stopped working a few weeks ago. I checked my script and I'm getting the following error. Any thoughts on what could be wrong?

pi@pi:~/MagicMirror-v2 $ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart magicmirror@2.0.0
6 info start magicmirror@2.0.0
7 verbose unsafe-perm in lifecycle true
8 info magicmirror@2.0.0 Failed to exec start script
9 verbose stack Error: magicmirror@2.0.0 start: `electron js/electron.js`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid magicmirror@2.0.0
11 verbose cwd /home/pi/MagicMirror-v2
12 error Linux 4.1.19-v7+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.3
15 error npm  v2.15.1
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error magicmirror@2.0.0 start: `electron js/electron.js`
20 error spawn ENOENT
21 error Failed at the magicmirror@2.0.0 start script 'electron js/electron.js'.
21 error This is most likely a problem with the magicmirror package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     electron js/electron.js
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs magicmirror
21 error Or if that isn't available, you can get their info via:
21 error
21 error     npm owner ls magicmirror
21 error There is likely additional logging output above.

**Comment by justjim1220** [comment]
Try updating your node.js. looks like it may be outdated. Needs to be vs 9.9.0

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
