### ISSUE TITLE
Support: hiding the modules' Name and description so it does not show on the screen.

### ISSUE THREAD

**Issue by TwistedTransistor** [MichMich/MagicMirror#1231]
Hello,

As in the subject, is it possible to hide the module's name and description so it does not show on the screen?

Thanks.

-Mario

**Comment by MichMich** [comment]
Yes. Check the docs.

**Comment by MichMich** [comment]
Just leave out the `header` field in the config file.

https://github.com/MichMich/MagicMirror#configuration
