### ISSUE TITLE
Calendar Module

### ISSUE THREAD

**Issue by Linsanity77** [MichMich/MagicMirror#1234]
Hi, I need some help with configuring the calendar module. How do I add new urls correctly? I add new ones but then Could Not Validate Config File pops up and I don't know why. Thanks.

**Comment by justjim1220** [comment]
I was able to get my calendar to work using MMM-MyCalendar...

tweaking it now.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
