### ISSUE TITLE
Issue accessing remote server with ipWhitelist[]

### ISSUE THREAD

**Issue by dbramarov** [MichMich/MagicMirror#1235]
Trouble accessing the webpage http://192.168.xxx.xxx:8080/remote.html

**Platform**: Raspberry 3
**Node Version**: V6.13.1
**MagicMirror Version**: JavaScript version (v2). (I believe) 

**Description**: Ran these steps:

cd ~/MagicMirror/modules 
git clone https://github.com/Jopyth/MMM-Remote-Control.git
cd MMM-Remote-Control
npm install

and added to config.js as the last module:

{
    module: 'MMM-Remote-Control',
    position: 'bottom_left'
}

I also switched address from "localhost" to "0.0.0.0"
Trying to add my phones IP to end of ipWhitelist -> [....., "::ffff:192.168.xxx.9"]

When I boot MM I can see the display at bottom left as my IP except the last number is a 4 instead of a 9! 

http://192.168.xxx.4:8080/remote.html

When I attempt to go to the correct IP with the 9 -> could not connect to server,
when I go to the wrong IP with the 4 -> "This device is not allowed to access your mirror"

Really lost on this one, help!

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
