### ISSUE TITLE
empty Calendar never finishes loading

### ISSUE THREAD

**Issue by CFenner** [MichMich/MagicMirror#124]
An empty calendar stays in "loading events" state.  

<img width="222" alt="bildschirmfoto 2016-04-02 um 09 26 25" src="https://cloud.githubusercontent.com/assets/9592452/14225085/16c69c5e-f8b6-11e5-8d19-55f76443c023.png">

I just created a new iCloud calendar and shared it.

**Comment by MichMich** [comment]
This should be solved now. If the issue persists, please reopen this issue.
