### ISSUE TITLE
calendar with charset can't be rendered

### ISSUE THREAD

**Issue by CFenner** [MichMich/MagicMirror#125]
<img width="663" alt="bildschirmfoto 2016-04-02 um 10 07 24" src="https://cloud.githubusercontent.com/assets/9592452/14225214/be354c66-f8ba-11e5-9f84-2b944d8094cb.png">

Calendar: webcal://p04-calendars.icloud.com/published/2/r2kdweJk1DTaAtzboNwR4xfi8LAOwHjnOEbF36sqzAeH16XGlkn85GdQy6PtmpX1v4BgzhHGEefdm8BzMJl-eP3oS_WSCBHss_g-OsbH4As

**Comment by MichMich** [comment]
I've just pushed an update. Could you please test to see if it works? **Please note:** you need to run `npm install` before running since it has a new dependency.

**Comment by MichMich** [comment]
Closing this issue for now. Please reopen if the issue persists.
