### ISSUE TITLE
rss feed with ISO-8859-1 encoding is not displayed properly

### ISSUE THREAD

**Issue by estres** [MichMich/MagicMirror#126]
rss feed with ISO-8859-1 encoding is not displayed properly

![isovsutf](https://cloud.githubusercontent.com/assets/6655163/14228491/a1ee0474-f916-11e5-8558-0c9fe6317752.JPG)

test feed:
http://www.spiegel.de/schlagzeilen/index.rss
header:
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>

**Comment by MichMich** [comment]
I've just pushed an update. Could you please test to see if it works? **Please note:** you need to run `npm install` before running since it has a new dependency.

**Comment by MichMich** [comment]
Closing this issue for now. Please reopen if the issue persists.

**Comment by MichMich** [comment]
**Update:** The encoding is now a configurable option. Please refer to the module's README. The default value is `UTF-8`.

**Comment by CFenner** [comment]
I'll try this evening.

**Comment by estres** [comment]
found some time to test it. 
works great. thx
:+1:
