### ISSUE TITLE
Error auto installer broken 

### ISSUE THREAD

**Issue by Darkcast** [MichMich/MagicMirror#1261]
I am using Raspberry pi 3 using stretch latest version. After running the automatic installation I get an error when installing the dependencies. so i reformated and re-insatalled strearch and tried it manually and I got the following error 
root@raspberrypi:~/MagicMirror/installers# cd ../
root@raspberrypi:~/MagicMirror# npm install && npm start
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/patriksimek/vm2.git
npm ERR! 
npm ERR! fatal: Could not change back to '/root/MagicMirror': Permission denied
npm ERR! 
npm ERR! exited with error code: 128

see attachment for more details
[Error.txt](https://github.com/MichMich/MagicMirror/files/1911541/Error.txt)

**Comment by E3V3A** [comment]
Do not try to install as root!

**Comment by Darkcast** [comment]
Will try again

**Comment by MichMich** [comment]
@Adsouza98 Never. Use. Root. ;)
