### ISSUE TITLE
Heat index "feels like" reporting inaccurate numbers

### ISSUE THREAD

**Issue by parnic** [MichMich/MagicMirror#1263]
**Platform**: Windows 10 (run from WSL Bash) and viewed with Chrome 65. Also seen with RPi Zero W host with Midori 0.4.3 browser.

**Node Version**: Seen with LTS 8.10.0 and 8.11.1

**MagicMirror Version**: 2.3.1

**Description**: "Feels like" heat index on the currentweather module is reporting wildly inaccurate values in Fahrenheit.

![image](https://user-images.githubusercontent.com/888126/38905230-f458dc6c-4274-11e8-8413-78ac681c245d.png)

**Steps to Reproduce**: Use the following currentweather config and hope that it's still hot outside. :)
```
                                location: "McKinney",
                                locationID: "4710178",
                                appid: "your app id",
                                roundTemp: true,
                                appendLocationNameToHeader: false
```

**Expected Results**: A (more or less) accurate "feels like" temperature.

**Actual Results**: Fatal heat levels.

**Configuration**: See 'steps to reproduce'. Global config uses `units: "imperial",`

**Comment by nhubbard** [comment]
@parnic Good PR! I will approve momentarily. This causes some unbelievably funny issues without your fix, especially in Kelvin (`default`).

**Comment by nhubbard** [comment]
Specifically, temperatures of nearly 1500 degrees outside.

**Comment by parnic** [comment]
I didn't modify how it was treating Kelvin, so an additional change may be necessary.

**Comment by MichMich** [comment]
Merged.
