### ISSUE TITLE
Getting a init.js file not found 

### ISSUE THREAD

**Issue by steveboatface** [MichMich/MagicMirror#1266]
Myapologies on this, i'm not sure where to go with this, as i know it seems like an Electron error based on the file not found below path, but I wasn't sure if this is maybe from your package building the electron pre-requisites or not. So i thought I would give it a shot. This is actually in the node-helper when i make this call:

req.jsonBody = JSON.parse(data);

It traces into the event emitter and then suddenly it gives me this error. Any thoughts?

Unable to open 'init.js': File not found (file:///c:/Users/stephen.botha/AppData/Roaming/npm/node_modules/electron/dist/resources/electron.asar/browser/init.js).

By the way this is the full function in the node helper that has that request:

	    this.expressApp.post('/weather', function (req, res) {
	        var data = "";
   			req.on('data', function(chunk){ data += chunk})
   			req.on('end', function(){
       			req.rawBody = data;
       			req.jsonBody = JSON.parse(data);
	        	self.sendSocketNotification("WEATHER", req.jsonBody);
	        	res.sendStatus(200);
   			})
	    });

**Comment by nhubbard** [comment]
@steveboatface I would try backing up your configuration and reinstall Raspbian. This is an error with Electron.

**Comment by MichMich** [comment]
As nhubbart suggests ...
