### ISSUE TITLE
My Google iCal failed to sync

### ISSUE THREAD

**Issue by werdnllac** [MichMich/MagicMirror#1267]
Hi everyone, I need help in this one. In my config.js, the script is as follow:

```
		{
			module: "calendar",
			header: "Upcoming Appointments",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://calendar.google.com/calendar/ical/callndrew%40gmail.com/private-xxxxxxxx/basic.ics"
					}
				]
			}
		},
```
It use to work fine until lately, I decide to upgrade Raspbian Jessie Lite to Raspbian Full version. It somehow couldn't retrieve the Google iCal as shown in the screen shot. 

`I tried both url: "webcal://calendar.google.com/calendar/ical/MyGmail/private-xxxxxxxxxx/basic.ics" `

**OR**

`url: https://calendar.google.com/calendar/ical/MyGmail/private-xxxxxxxxxx/basic.ics"`

It use to work till I change the Raspbian version to stretch full with Desktop. Anyone knows what is the problem?

![capture](https://user-images.githubusercontent.com/36906837/38977726-c9fe95e6-43e7-11e8-9ced-80ca5b27e3c0.PNG)

**Comment by drftg** [comment]
You might want to edit this post as it contains private information. 
But that made it possible to see that your calendar generates the following error

Error: dates lower than Thu Jan 01 1970 00:00:00 GMT+0100 (CET) are not supported
 
You should remove those appointments if you want it to work with MM.

**Comment by werdnllac** [comment]
@drftg may I know where did you get the "Error: dates lower than Thu Jan 01 1970 00:00:00 GMT+0100(CET)"

I had changed the Raspi Preference local and date setting and also the raspi-config. They all looks fine.

I have also checked the google calendar, they are also also correct.

**Comment by drftg** [comment]
If you ssh into your pi 
```
cd ~/MagicMirror
npm start
```
you will see all logging of MagicMirror

**Comment by werdnllac** [comment]
I have execute the above command and have the following screenshot.

![capture](https://user-images.githubusercontent.com/36906837/39171210-a44f6838-47d0-11e8-803f-1d4159227e23.PNG)
![magicmirror-18042018](https://user-images.githubusercontent.com/36906837/39171212-a481984e-47d0-11e8-82f4-bf55edc6ac9a.PNG)

**Comment by werdnllac** [comment]
The strange thing is, when I add a brand new calendar in Google, and uses the public sharing url, it works fine. Don't understand why and have gone through all the setting but still no clue how to resolve.

**Comment by MichMich** [comment]
The simplest suggestion is to do a reinstall of Raspbian full edition. It might have something to do with a ssl connection which is out of scope of the MM project.

**Comment by anooproy** [comment]
@werdnllac  Hello sir can u get me calendar module of your version.

**Comment by MichMich** [comment]
Can I close this issue?

**Comment by bbrendon** [comment]
This happens for me too. Can't the module just ignore invalid calendar items?

**Comment by axe1OO4** [comment]
Hi, im having issues with the schedule in my google calendar connected to the mmm-calendarext. Can someone help me how to show the schedule in the monthly calendar chart? Thanks

**Comment by MichMich** [comment]
Please use the forum for support requests: http://forum.magicmirror.builders
