### ISSUE TITLE
Implement a logging framework like winston

### ISSUE THREAD

**Issue by KilianB** [MichMich/MagicMirror#1268]
The <a href="https://github.com/MichMich/MagicMirror/blob/master/modules/README.md#magicmirror-logger"> module development readme</a> states:

> # MagicMirror Logger
> The Magic Mirror contains a convenience wrapper for logging. Currently, this logger is a simple proxy to the original console.log methods. But it might get additional features in the future. The Loggers is currently only available in the core module file (not in the node_helper).

Do we have any updates on weather this idea is going to be worked on in the future?  I distributed my own modules via npm to import them in magic mirror and found <a href="https://github.com/winstonjs/winston">winston</a> to be of great help (take a look at named loggers). Sadly this currently only allows me to use my loggers in node_helper.js.

Using a logging framework would allow to turn off/on logging for specific modules while formatting the logger in a ways to exactly know which module send the message. 

-----------
e.g. The rss feed of nytimes currently has a broken xml entry 
```xml
<item>
  <title/>
  <link>https://www.nytimes.com//?partner=rss&emc=rss</link>
  <guid isPermaLink="true">https://www.nytimes.com//</guid>
  <atom:link rel="standout" href="https://www.nytimes.com//?partner=rss&emc=rss"/>
  <description/>
  <dc:creator/>
  <pubDate/>
</item>
```

resulting in https://github.com/MichMich/MagicMirror/blob/60b9a5b9dad36a7748a5d1bdb3b32c0c6384e4c0/modules/default/newsfeed/fetcher.js#L63-L68
being printed to console every time the newsfeed module tries to update it's feed. It would be really convenient to simply to turn of logging for this module.

**Comment by E3V3A** [comment]
@KilianB So what's the correct xml code for NY times? (I was wondering for a while why that was not working.)

**Comment by justjim1220** [comment]
http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml

**Comment by MichMich** [comment]
Feel free to send a PR. As long as it's not a breaking change and doesn't require a massive load of dependencies.

**Comment by KilianB** [comment]
@E3V3A the news module requires a title and a publish date. The corresponding lines of code are here

```` javascribt
var pubdate = item.pubdate || item.published || item.updated || item["dc:date"];
   if (title && pubdate) {
   }else { error; }
````

Therefore, a valid xml entry has to have content for the title and publish date which the supplied example does not provide. It points towards the default nytimes homepage.

1. Winston is more useful than no logging framework due to the reasons  that developers gain more access to the ways logging is handled. Currently all log messages are simply forwarded to the console which don't allow for monitoring or error tracking throughout restarts of nodejs.

For example 

- Logging severity can be easily controlled (which level of logging do we want? Warnings, errors, debug statements ..)
- How are the log statements formatted? Timestamps, class origin, module names?
- Log endpoints. Frameworks usually allow to define some kind of _appenders_ that specific how logs are send. Are they saved to disk, emailed to users on a certain interval, rolled over after reaching x entries displayed as html ...
- Mute logs from certain modules

Overall I think it's really important to allow developers to log messages in either modules and node_helper with the same syntax, which currently is not possible. I am not saying that winston is the go to framework but it's simply what I am currently using.

2.  @nhubbard currently my time is severely constrained by other projects and I fear this will have to wait quite a bit before I can devote a fair share of it towards mm. NodeJS also isn't really a technology I have much experience with therefore, my code might not live up to the standards required here.  
Without putting much thought into it one possible approach would be to create a named logger during the module loading in the <a href="Loader.js">https://github.com/MichMich/MagicMirror/blob/8a101f9e9ad885289c687d6ea627dfa7294a0da0/js/loader.js</a>. To preserve backward compatibility <a href="https://github.com/MichMich/MagicMirror/blob/8010e6220d4cc68e9f9e3c1029998cc47df0f193/js/logger.js">logger.js</a> has to be bound to use the logger for the corresponding module. I am not sure how you would go about this. maybe instead of exporting Log through <a href="https://github.com/MichMich/MagicMirror/blob/fb0cc61e09542533affa92b1e8bd6f9a2aca6363/module-types.ts">module-types.ts</a> the logger object itself can be passed to the module instead. But again ECMAScript isn't really my strong suit.

@nhubbard it's great to see a fellow first robotics enthusiast participating here. Due to me moving away from the US I sadly can not participate actively anymore but I have been present at last years kickoff together with the teams in grand rapids and if my memory serves correctly participated against your team a few times ;). 

Nevertheless if by any chance I get some spare time I  am more than happy to look into this issue.

**Comment by MichMich** [comment]
FYI: https://github.com/MichMich/MagicMirror/pull/1331

**Comment by shbatm** [comment]
Saw this issue and wanted to share: I created a module to implement `tracer` on the back-end server (Node.JS) side. While it doesn't help from the front-end web-console side, if set as one of the first modules in the config, it will overwrite all module's existing console printing functions and format them.

https://github.com/shbatm/MMM-Logging
