### ISSUE TITLE
Unable to clone MagicMirror.

### ISSUE THREAD

**Issue by boomza19193** [MichMich/MagicMirror#1270]
> `pi@raspberrypi:~`
 $ bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"

$$\      $$\                     $$\           $$\      $$\ $$\                                          $$$$$$\
$$$\    $$$ |                    \__|          $$$\    $$$ |\__|                                        $$  __$$\
$$$$\  $$$$ | $$$$$$\   $$$$$$\  $$\  $$$$$$$\ $$$$\  $$$$ |$$\  $$$$$$\   $$$$$$\   $$$$$$\   $$$$$$\  \__/  $$ |
$$\$$\$$ $$ | \____$$\ $$  __$$\ $$ |$$  _____|$$\$$\$$ $$ |$$ |$$  __$$\ $$  __$$\ $$  __$$\ $$  __$$\  $$$$$$  |
$$ \$$$  $$ | $$$$$$$ |$$ /  $$ |$$ |$$ /      $$ \$$$  $$ |$$ |$$ |  \__|$$ |  \__|$$ /  $$ |$$ |  \__|$$  ____/
$$ |\$  /$$ |$$  __$$ |$$ |  $$ |$$ |$$ |      $$ |\$  /$$ |$$ |$$ |      $$ |      $$ |  $$ |$$ |      $$ |
$$ | \_/ $$ |\$$$$$$$ |\$$$$$$$ |$$ |\$$$$$$$\ $$ | \_/ $$ |$$ |$$ |      $$ |      \$$$$$$  |$$ |      $$$$$$$$\
\__|     \__| \_______| \____$$ |\__| \_______|\__|     \__|\__|\__|      \__|       \______/ \__|      \________|
                       $$\   $$ |
                       \$$$$$$  |
                        \______/

Updating packages ...
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease               
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease                  
Hit:3 https://deb.nodesource.com/node_9.x stretch InRelease
Reading package lists... Done
Installing helper tools ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.3).
curl is already the newest version (7.52.1-5+deb9u5).
git is already the newest version (1:2.11.0-3+deb9u2).
unzip is already the newest version (6.0-21).
wget is already the newest version (1.18-5+deb9u1).
The following packages were automatically installed and are no longer required:
  erlang-base erlang-crypto erlang-syntax-tools fonts-lato
  libboost-thread1.62.0 libdouble-conversion1 libpcre16-3 libqt5concurrent5
  libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5 libqt5opengl5
  libqt5printsupport5 libqt5scintilla2-12v5 libqt5scintilla2-l10n libqt5svg5
  libqt5widgets5 libqt5x11extras5 libqt5xml5 libqwt-qt5-6 libruby2.3
  libscsynth1 libsctp1 libuv1 libxcb-icccm4 libxcb-keysyms1 libxcb-randr0
  libxcb-render-util0 libxcb-xinerama0 libxcb-xkb1 libxkbcommon-x11-0
  libxkbcommon0 libyaml-0-2 qt5-gtk-platformtheme qttranslations5-l10n rake
  ruby ruby-did-you-mean ruby-minitest ruby-net-telnet ruby-power-assert
  ruby-test-unit ruby2.3 rubygems-integration
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Check current Node installation ...
Node currently installed. Checking version number.
Minimum Node version: v5.1.0
Installed Node version: v9.11.1
No Node.js upgrade necessary.
Cloning MagicMirror ...
Cloning into 'MagicMirror'...
fatal: unable to access 'https://github.com/MichMich/MagicMirror.git/': GnuTLS recv error (-54): Error in the pull function.
Unable to clone MagicMirror.

How i solve this problem.  i use raspberry pi 3

**Comment by MichMich** [comment]
Please make sure your internet connection is working.
