### ISSUE TITLE
ClientOnly issue

### ISSUE THREAD

**Issue by ragincajunintx** [MichMich/MagicMirror#1271]
Please only submit reproducible issues. 

When submitting a new issue, please supply the following information:

**Platform**: Raspberry Pi 3 - Raspbian Jessie

**Node Version**: 6.13.1

**MagicMirror Version**: 2.3.1

**Description**: When running "DISPLAY:0 node clientonly --address 10.14.62.118 --port 8080" I get a black screen on the display, but when running via ssh get the following output: Client: Starting MagicMirror: v2.3.1
Client: Launching application.
Client: libGL error: Client: MESA-LOADER: failed to retrieve device information
Client: MESA-LOADER: failed to retrieve device information
Client: MESA-LOADER: failed to retrieve device information

**Steps to Reproduce**: Install Raspbian, clone MagicMirror from Github, run "npm install" enter MagicMirror folder and run the above command.

**Expected Results**: I expect to see the serveronly setup I have installed on another raspberry pi 3. I verified that I can see it through any other browser on my network.

**Actual Results**: Black screen on monitor.

**Configuration**: 
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
    address: "0.0.0.0", // Address to listen on, can be:
                          // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
                          // - another specific IPv4/6 to listen on a specific interface
                          // - "", "0.0.0.0", "::" to listen on any interface
                          // Default, when address config is left out, is "localhost"
    port: 8080,
    ipWhitelist: [], // Set [] to allow all IP addresses
                                                           // or add a specific IPv4 of 192.168.1.5 :
                                                           // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
                                                           // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
                                                           // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

    language: "en",
    timeFormat: 12,
    units: "imperial",

    modules: [
        {
            module: "alert",
        },
        {
            module: "updatenotification",
            position: "top_bar"
        },
	{
	    module: "MMM-EasyPix",
	    position: "bottom_left",
	        config: {
	                  picName: "wifi_config.png",
	                  maxWidth: "25%"
	    }
	},
	{
            module: "MMM-bitcoin",
            position: "bottom_left",
            config: {
                fiat: 'usd',
                showBefore: 'BTC',
                updateInterval: 60000
            }
        },
        {
            module: "clock",
            position: "bottom_left",
        },
        {
            module: 'MMM-WunderGround',
            position: 'bottom_right',
            config: {
                apikey: '********************', // private; don't share!
                pws: '
                hourly: '0',
                fctext: '1',
                fcdaycount: "4",
                fcdaystart: "0",
                scaletxt: "1",
                hourlyinterval: "3",
                hourlycount: "2",
                alerttime: 10000,
                alerttruncatestring: "english:",
                roundTmpDecs: 1,
                windunits: "mph",
                UseCardinals: 1,
                layout: "horizontal",
                coloricon: true,
                sysstat: 0
            }
        },
        {
            module: "newsfeed",
            position: "middle_center",
            config: {
                feeds: [
                    {
                        title: "Technology",
                        url: "https://news.google.com/news/rss/headlines/section/topic/TECHNOLOGY?ned=us&hl=en"
                    },
                    {
                        title: "Ars Technica",
                        url: "http://feeds.arstechnica.com/arstechnica/index"
                    },
                    {
                        title: "NPR",
                        url: "http://www.npr.org/rss/rss.php?id=1001"
                    }
                ],
                showSourceTitle: true,
                showPublishDate: true
            }
        },
        {
            module: "MMM-RandomPhoto",
            position: 'fullscreen_below',
            config: {
                opacity: 0.2,
                animationSpeed: 1000,
                updateInterval: 60,
                url: 'https://*************'
            }
	},
	{
            module: 'MMM-Remote-Control'
            // uncomment the following line to show the URL of the remote control on the mirror
            // , position: 'bottom_left'
            // you can hide this module afterwards from the remote control itself
	},
        {
            module: "MMM-CalendarExt",
            position: "bottom_center",
                config: {
                  system: {
                show: ['weeks'],
                    locale: 'en-US',
                  },
                  views: {
                    weeks: {
                      position:'top_bar',
                      showWeeks: 0,
                      weeksFormat: 'wo',
                           weekdatFormat: 'ddd',
                           titleFormat: 'MMM D',
                                counts: 1,
                      timeFormat: 'h:mm a',
                      oneLineEvent: 0,
                    },
              },
                calendars: [
                  {
                    name: "Joint Calendar",
                    url: "********************************************.ics",
                    styleName: "style_custom2"
                  },
                  {
                    name: "US Holidays",
                    url: "********************************************.ics",
                    styleName: "style_custom2"
                  },  
                ],
                }
        },
        {
			module: "compliments",
			position: "bottom_center",
            config: {
                updateInterval: "60000"
            }               
		},
    ]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Additional Notes**: Provide any other relevant notes not previously mentioned. This is optional.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
