### ISSUE TITLE
Need Correct and Running code 

### ISSUE THREAD

**Issue by liquid1** [MichMich/MagicMirror#1272]
anyone who have already created and is in running form, kindly send the code.
because am facing alot of issues in these modules( weather forecast, weather, facial recognition) & if changing other default modules.
i have placed issues here but no response.
i have been working on this project for 2 months, kindly help me out

**Comment by justjim1220** [comment]
can you post your config.js and/or your log files.?
Or, send them to me through private chat?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by liquid1** [comment]
hi jim, sorry for late emailing actually alot late.. i was away..
dude can you navigate me the config file??

**Comment by liquid1** [comment]
aahh thanks man, got it
