### ISSUE TITLE
not really an issue with the Mirror or the Modules...

### ISSUE THREAD

**Issue by justjim1220** [MichMich/MagicMirror#1274]
more of a question... Apologies in advance... Having a brain fart day...

Is there an easy way to update modules without having to recode it to retain the settings I was using???

I had another question, but for the life of me, I cannot remember what it was at the moment. So, I guess I'll ask it when I figure out what it was.

Not sure if this was the question I had in mind, but it is one I've been wanting to ask...

would someone be willing to help me incorporate Watson into the Mirror? 
I've tried the MMM=STT , biut it's only Speech to text. I found a code that incorporates that, and also a slew of other skills, like TTS, Voice recognition, Facial recognition, Personality Learning, and a lot more AI skills I am wanting to get working, that I can't seem to get with Alexa, Cortana, Siri, or Google Assistant.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
