### ISSUE TITLE
Show Description not working when leaving full article

### ISSUE THREAD

**Issue by McNose** [MichMich/MagicMirror#1282]
Hi,

I would like to see the description of the news in the newsfeed all the time.
So, like mentioned in the options, I changed the “showDescription = false” in the newsfeed.js to “true”.
It works fine. I can see the description of every article without doing anything, even when the articles update.

The problem is when I use the command “ARTICLE_MORE_DETAILS” to open the full article. It works like a charm, but when I close the full article I use the command “ARTICLE_LESS_DETAILS”. It goes back to the newsfeed but unfortunately without showing the descriptions anymore. I only see the headlines (like “showDescription = false” although “true” is still set of course).

When leaving the full article, the newsfeed should still show the description if "true" is set in the options.
Can somebody please fix that?
Or instead, how can I remove the freeze of the newsfeed, when I open the description manually by using "ARTICLE_MORE_DETAILS"?

Thanks a lot.
Greetings

McNose

**Comment by MichMich** [comment]
Merged.
