### ISSUE TITLE
Mirror Just loads up black and i cant access it from remote web browser

### ISSUE THREAD

**Issue by ADBYITS** [MichMich/MagicMirror#1286]
Hi all i am buggers here i have been trying to get this working for a week was going to be a gift for my wife for mothers days but no time now , i have done many many clean installs and each time no matter what i havedone it only start with a black screen and no data on the screen at all, i have made sure that the onfig file is the sample and still no data on the screen, i have tried to access it with the ipaddress from a remote pc using port 8080 and cant see anything, i am new to this any help would be great please

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
