### ISSUE TITLE
MMM-PublicTransportHafas doesn't show me anything

### ISSUE THREAD

**Issue by webs123** [MichMich/MagicMirror#1296]
Hey,
I just installed fresh raspbian and configured some basic modules. MM works fine. At least I installed MMM-PublicTransportHafas with basic-configuration (see att.). But this module doesn't show me anything.
How and where can I search for an error message?
Or what can be the problem? 

```
{
  module: "MMM-PublicTransportHafas",
  position: "top_right",
  
  config: {
    stationID: "008012202",
    stationName: "St.",
    direction: "",
    ignoredLines: [],
    excludedTransportationTypes: [],
    timeToStation: 0,
    showColoredLineSymbols: true,
    useColorForRealtimeInfo: true,
    showTableHeadersAsSymbols: true,
    maxUnreachableDepartures: 0,
    maxReachableDepartures: 7,
    customLineStyles: "",
    showOnlyLineNumbers: false
  }
},
```

thx
webs123

**Comment by MichMich** [comment]
Please open an issue in the repository of the Mmm-PublicTransportHafas module.
