### ISSUE TITLE
No helper found.

### ISSUE THREAD

**Issue by aaminhakim** [MichMich/MagicMirror#1299]
when i run the command "npm start" it gives me this

Starting MagicMirror: v2.3.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: http://www.calendarlabs.com/templates/ical/US-Holidays.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000

using chromium and Raspberry pi 3 on windows

the result
![problem](https://user-images.githubusercontent.com/39739448/40670914-06817c5c-639d-11e8-9805-82570b30400c.png)

my config
[config.txt](https://github.com/MichMich/MagicMirror/files/2049144/config.txt)

please help ASAP...

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
