### ISSUE TITLE
Problem with iCal calendars - Gmail

### ISSUE THREAD

**Issue by nico0709** [MichMich/MagicMirror#1306]
Hi,
I just had a problem with my iCal Gmail calendar. When I start MagicMirror, only some events, espaced in time, are showing... I check in Google Agenda, and all my events had the same access: private.
Could you help me?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
