### ISSUE TITLE
MultiCalendars only work with less than about 250KB 

### ISSUE THREAD

**Issue by Albyricus** [MichMich/MagicMirror#1315]
Hi,

i installed today the Magic Mirror (V. 2.3.1) with your Batch and so far everything is working fine, but i have a bug, that had driven me crazy. 
I wanted to add 2 different Calendars which i automatically export from my Owncloud to an ICS File on my NAS, from where the Raspi with MagicMirror imports it with "localhost:8080...". One Calendar worked from the beginning, the second one dont wanted to show ANY entries. After 3 hours of testing i used a third and forth Calender and these instandly worked (even exported from the same Owncloud). Then i checked the ics files and the Calender with about 284 KB was the bigggest one. Calender one has 213 KB and the other have about 36 KB. When i open up the Calender Nr. 2 and Delete some rows by hand to reduce the size the file even works! The "Magic Size" is about 250 KB so that this file will work or not.

Any idears how this could be fixed?

If you want further informations i will send you the screenshots and Code and so on, but now i am such as tiered that i just want to fall in my bed ;o). G8

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
