### ISSUE TITLE
Clock module : bold is only bolding the minute

### ISSUE THREAD

**Issue by prysme01** [MichMich/MagicMirror#1325]
Hello, 

After setting the parameter to bold at true, I only see the minute "bolded" not the hours.

thanks.

**Comment by prysme01** [comment]
As I can see in the code 
`		if (this.config.clockBold === true) {
			timeString = now.format(hourSymbol + "[<span class=\"bold\">]mm[</span>]");
		} else {
			timeString = now.format(hourSymbol + ":mm");
}`

Is this the expected behavior to only bold the minute ?

**Comment by nhubbard** [comment]
Yes. It is intended to only bold the minute and remove the colon to produce a more modern look. See this screenshot for the intended result:
![1463875363455-screenshot-from-2016-05-21-19-34-23](https://user-images.githubusercontent.com/3649523/41667870-01b1c2be-747c-11e8-9abf-26450daf1afa.png)

(Source: am author of bold option in clock module.

**Comment by prysme01** [comment]
Well on my installation with no special customization in the CSS, the expected result is not the same
[https://framapic.org/eAoARpyqQbu5/SOS8J17z4RnU.jpg](url)

**Comment by justjim1220** [comment]
this is where I changed it to get the full time to be bold... in the **_clock.js_** file
`// Style Wrappers
		dateWrapper.className = "date normal xlarge bolder";
		timeWrapper.className = "time bright xlarge bolder";
		secondsWrapper.className = "dimmed";
		weekWrapper.className = "week dimmed medium"
`

**Comment by justjim1220** [comment]
![screenshot 12](https://user-images.githubusercontent.com/27590633/41813870-3400ed64-7704-11e8-976b-86fc0acf5247.png)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
