### ISSUE TITLE
Weather will not populate at all

### ISSUE THREAD

**Issue by StriQen** [MichMich/MagicMirror#1326]
Okay, so i am back again and am having trouble with getting my weather to load. I have gone to both sides to get my location ID as well as created an account and got an APPID/Key. 

I input the information in the way i understood it should be. but i guess i messed up somewhere. i removed the first part of the current weather from the code, so i just have the second half of the module. 

hopefully someone can help me out! :) 

//              {
//                      module: "CurrentWeather",
//                      position: "top_right",
//                      config: {
//                              location: "Fox Lake, Illinois",
//                              locationID: "false",  //ID from http://www.openwea$
//                              appid: "5e83279a4b8a44561e7265xxxxxxxxx"
//                      }
//              },
                {
                        module: "WeatherForecast",
                        position: "top_right",
                        header: "Fox Lake",
                        config: {
                                location: "",
                                locationID: "4892950",  //ID from http://www.openw$
                                appid: "1ec6f84a04243e9b48b201xxxxxxxxxx"
                        }
                },

**Comment by fewieden** [comment]
the module names should be lowercase

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
