### ISSUE TITLE
no helper found for modules

### ISSUE THREAD

**Issue by onkararj** [MichMich/MagicMirror#1327]
> magicmirror@2.1.2 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.1.2
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
![dcdcd](https://user-images.githubusercontent.com/32007899/41719787-b3aeebec-757e-11e8-9dc2-45b7ff3aa615.jpg)
![dcdcd](https://user-images.githubusercontent.com/32007899/41719808-c778e614-757e-11e8-869c-3ffcd8e2d643.jpg)

**Comment by fewieden** [comment]
not all modules require a node helper and most of the default modules have one.

**Comment by onkararj** [comment]
so what i have to do? to turn on all the modules

**Comment by fewieden** [comment]
Just saying that this is not your issue, those are just informations that those modules do not have a node_helper. It's not the reason why your screen is black. Open the developer tools in electron and check the console for errors.

**Comment by justjim1220** [comment]
you need to update Magic Mirror, you're using version 2.1.2, and the current version is 2.3.1

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by wajidraza786** [comment]
try this command in module folder:
npm i

**Comment by chiliwax** [comment]
`npm run install` fix the problem for me (install fonts and usefull stuffs to display modules)
MM2 version : `2.14.0-dev`
Run on RPI 1.2 (raspberry 1 b+)
