### ISSUE TITLE
Disabled flag for modules does not seem to work

### ISSUE THREAD

**Issue by fiveseven808** [MichMich/MagicMirror#1328]
According to the Readme.md it appears we should be able to add a `disabled: "true",` to a module and it should hide/disable it, but I have not been able to get this to work. 

Am I doing something wrong?

**Comment by fewieden** [comment]
Remove the quotes otherwise you'Re not able to specify a falsy value, because a string (except empty string) always evaluates as true.

You need to specify it like:
```
{
  disabled: true,
  module: "MMM-Fuel",
  position: "top_right",
  config: {
    provider: "spritpreisrechner",
    lat: 48.569398,
    lng: 13.454522,
    types: ["e5"],
    sortBy: "e5",
    radius: 12,
    max: 5,
    rotate: false
  }
},
```
so it should not be in the config block
