### ISSUE TITLE
"Can't parse feed item:" flooding log, disable this or make a debug level

### ISSUE THREAD

**Issue by flyingchipmunk** [MichMich/MagicMirror#1329]
**Platform**:
Raspberry Pi 3B+, electron 1.7.13

**Node Version**:
v9.11.2

**MagicMirror Version**:
v2.3.1

**Description**:
The ~/.pm2/logs/MagicMirror-out-0.log is getting flooded with "Can't parse feed item:" messages from the default/newsfeed module. Regardless of source of the newsfeeds that can't be parsed this message needs to be removed or set to a debug level and a flag to enable it. On a production installation this should not be printing as console.log(). On an unchecked system this will flood the log file and speed the destruction of the sdcard with unneeded writes.

**Steps to Reproduce**:
Leave the default NYT RSS feed that fetcher.js can't parse, i.e. http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml and watch the log for the errors.

**Expected Results**:
No log messages written unless a fatal operation has occurred.

**Actual Results**:
Messages like this flood the out.log
```
Can't parse feed item:
{ title: '',
  link: 'https://www.nytimes.com//?partner=rss&emc=rss',
  guid: { ispermalink: 'true', text: 'https://www.nytimes.com//' },
  'atom:link':
   { rel: 'standout',
     href: 'https://www.nytimes.com//?partner=rss&emc=rss' },
  description: '',
  'dc:creator': '',
  pubdate: '' }
Title:
Description:
Pubdate: undefined
```

**Configuration**: 
```
        {
            module: "newsfeed",
            position: "bottom_bar",
            config: {
                feeds: [
                    {
                        title: "New York Times",
                        url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
                    }
                ],
                showSourceTitle: true,
                showPublishDate: true
            }
        },
```

**Additional Notes**:

**Comment by almazini** [comment]
I met the same issue today on Raspberry 3 today

**Comment by MichMich** [comment]
Feel free to send a PR to disable this using a configuration option.

**Comment by flyingchipmunk** [comment]
I briefly looked at how you implemented the logger class on the non-module side of the code. Didn't know if there were plans to expand that to modules. If not, and a config option for this module would be acceptable for this I can work up a PR for it.

**Comment by MichMich** [comment]
Yeah for now a config option would be the easiest solution. Thanks!

**Comment by MichMich** [comment]
Merged
