### ISSUE TITLE
MagicMirror-2.4.0 not starting?

### ISSUE THREAD

**Issue by meischdaddy30** [MichMich/MagicMirror#1340]
I finally got the updated version installed.  I extracted the .tar.gz file into my original MM directory so my MagicMirror-2.4.0 directory is in an already existing MM folder.  I navigated MagicMirror-2.4.0/config and copied the sample and renamed it config.js.  I then attempted to start my updated version in my MagicMirror-2.4.0 directory and unfortunately I cannot add everything loads in the terminal because it freezes at the end.

Some of the messages I remember it gave me was 

> No helper found for module: clock

etc.  There were a lot of them, and then at the end it said "Launching Application" and it freezes.  I let it sit for about 5 minutes but still nothing.  Any ideas on why this could be?  My original MM config.js and my new MM-2.4.0 config.js have all the same information for port and iPwhitelist.  I'm fairly positive the problem is here but because I am new to this stuff I'm not 100% how to fix it.

**Comment by MuhammadJamee** [comment]
did you find a fix?
