### ISSUE TITLE
CSS class and Alert module

### ISSUE THREAD

**Issue by Ybbet** [MichMich/MagicMirror#1353]
Please only submit reproducible issues. 

If you're not sure if it's a real bug or if it's just you, please open a topic on the forum: [https://forum.magicmirror.builders/category/15/bug-hunt](https://forum.magicmirror.builders/category/15/bug-hunt)
Problems installing or configuring your MagicMirror? Check out: [https://forum.magicmirror.builders/category/10/troubleshooting](https://forum.magicmirror.builders/category/10/troubleshooting)

When submitting a new issue, please supply the following information:

**Platform**: Place your platform here... give us your web browser/Electron version *and* your hardware (Raspberry Pi 2/3, Windows, Mac, Linux, System V UNIX).
- All

**Node Version**: Make sure it's version 0.12.13 or later.

v9.11.1

**MagicMirror Version**: Now that the versions have split, tell us if you are using the PHP version (v1) or the newer JavaScript version (v2).

v2 (2.5.0-dev)

**Description**: Provide a detailed description about the issue and include specific details to help us understand the problem. Adding screenshots will help describing the problem.

In the alert module, for messages, spans are used. The script adds inline styles instead of CSS classes.
Should not we evolve this part to replace these styles with the CSS class equivalent?
For titles, _.light.dimmed.medium_
And for messages: _.thin.bright.small_

**Steps to Reproduce**: List the step by step process to reproduce the issue.

- Replace https://github.com/MichMich/MagicMirror/blob/develop/modules/default/alert/alert.js#L41 with:
``
msg += "<span class='thin dimmed medium'>" + message.title + "</span>";
``
- Replace https://github.com/MichMich/MagicMirror/blob/develop/modules/default/alert/alert.js#L47 with:
``
msg += "<span class='light bright small'>" + message.message + "</span>";
``
- Replace https://github.com/MichMich/MagicMirror/blob/develop/modules/default/alert/alert.js#L84 with:
``
message += "<span class='light dimmed medium'>" + params.title + "</span>";
``
- Replace https://github.com/MichMich/MagicMirror/blob/develop/modules/default/alert/alert.js#L91 with:
``
message += "<span class='thin bright small'>" + params.message + "</span>";
``

**Expected Results**: Describe what you expected to see.

With those modifications, it will be easier to personnalize the alert with `custom.css`

**Comment by MichMich** [comment]
Merged.

**Comment by Ybbet** [comment]
Thanks
