### ISSUE TITLE
Black Screen After Update

### ISSUE THREAD

**Issue by andrew16x** [MichMich/MagicMirror#1357]
Hello,

I am running MagicMirror on a RP Model 3B+.

Today I did an `npm install` in the MagicMirror folder. It completed successfully and at the end said that there is a new MM update 6.0.1 I believe it was (previously was running version 5) and to update to latest to use the `npm i -g npm` - which I did. 

Following this update and starting MaggicMirror back up (either using `pm2 start MagicMirror` or `npm start`) all I get is the black screen - nothing else and I can't get out of it (previously able by using Ctrl + Q). 

I have found this issue already closed - [https://github.com/MichMich/MagicMirror/issues/1243](url)
#
Believe the issue was caused by the version the node was using. Mine was 8.11.1. The suggested fix was to revert to an older version by using `npm install electron@1.4.15` which I did but did not resolve the issue. 

I did an `npm run config:check` to make sure there were no errors:
![image](https://user-images.githubusercontent.com/35963444/42726816-90c9cdec-8792-11e8-8673-c7794e176007.png)

Can someone please help?

**Comment by MichMich** [comment]
You can always download old versions here: https://github.com/MichMich/MagicMirror/releases

But I suggest you contact the creator go the Awesome Alexa module to fix it.
