### ISSUE TITLE
Magic mirror forum

### ISSUE THREAD

**Issue by mikecy22** [MichMich/MagicMirror#1361]
I dont know if it the correct place to post this but i cannot post anything in the forum.
 I have a problem with my confirmation email. I haven't received it. I resend it a couple of times i even changed my email to another one but still havent received anything. My username is mikecy

**Comment by tuicemen** [comment]
At least you got a confirmation email.
I've not received one yet.

**Comment by paviro** [comment]
mikecy Has already confirmed his email address.

**Comment by paviro** [comment]
tuicemen does not exist as a user.

**Comment by tuicemen** [comment]
@paviro  I noticed I was approved Thanks.
However I never did get a email, maybe the forum email activation is not working.

**Comment by paviro** [comment]
It is. I tested it when I send yours. I received the mail without a problem. Check your spam folders.

**Comment by mikecy22** [comment]
Yes i received it 4-5 days later but i was away. Now i am a member!!!

**Comment by tuicemen** [comment]
There must be a delay, if mikecy22 email was 4-5 days late I won't see anything for a few more days.
Funny I get the update to this  issue fast though.
Different server?
I don't mind a delay in receiving emails however a post on the forum that registration email activation notifications could take a few days would ease some newbies worries.

**Comment by mikecy22** [comment]
I have just checked it. I opened the issue here in github 21 july. The registration email came at 24 of july. So there was some delay.
