### ISSUE TITLE
 Error: listen EADDRINUSE 127.0.0.1:8080

### ISSUE THREAD

**Issue by katherinemyersLPD** [MichMich/MagicMirror#1367]
**Platform**: Raspberry Pi 3 and Windows Putty

**Node Version**: 0.12.13

**MagicMirror Version**: Magic Mirror v2.4.1

**Description**: I have everything set up correctly, I think, and when I try to run npm start to launch MagicMirror with the MMM-GoogleAssistant module, I get this error:
 
{ Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080 }

**Steps to Reproduce**: I followed all the steps to add Google Assistant to my magic mirror from https://www.magicmirrorcentral.com/get-google-assistant-magic-mirror/
I am able to see a Google Assistant logo on my mirror and am able to communicate in the virtual trial. 

**Expected Results**: I expected to be able to communicate with Google Assistant via my Pi.

**Actual Results**: I was not able to communicate with Google Assistant, but there is a Google Assistant logo on my Pi.

**Configuration**: This is my ~/MagicMirror/config/config.js

var config = {
        address: "localhost", // Address to listen on, can be:
                              // - "localhost", "127.0.0.1", "::1" to listen on l$
                              // - another specific IPv4/6 to listen on a specifi$
                              // - "", "0.0.0.0", "::" to listen on any interface
                              // Default, when address config is left out, is "lo$
        port: 8080,
        ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow$
                                                               // or add a specif$
                                                               // ["127.0.0.1", "$
                                                               // or IPv4 range o$
                                                               // ["127.0.0.1", "$

        language: "en",
        timeFormat: 24,
        units: "metric",

        modules: [
                {
                        module: "MMM-GoogleAssistant",
                        position: "top_right",
                        config: {
                        maxWidth: "100%",
                        header: ""
                        }
                },
                {
                        module: "alert",
                },
                {
                        module: "updatenotification",
                        position: "top_bar"
                },
                {
                        module: "clock",
                        position: "top_left"
                },
                {
                        module: "calendar",
                        header: "US Holidays",
                        position: "top_left",
                        config: {
                                calendars: [
                                        {
                                                symbol: "calendar-check-o ",
                                                url: "webcal://www.calendarlabs.c$
                                        }
                                ]
                        }
                },
                {
                        module: "compliments",
                        position: "lower_third"
                },
                {
                        module: "currentweather",
                        position: "top_right",
                        config: {
                                location: "New York",
                                locationID: "",  //ID from http://www.openweather$
                                appid: "YOUR_OPENWEATHER_API_KEY"
                        }
                },
                {
                        module: "weatherforecast",
                        position: "top_right",
                        header: "Weather Forecast",
                        config: {
                                location: "New York",
                                locationID: "5128581",  //ID from http://www.open$
                                appid: "YOUR_OPENWEATHER_API_KEY"
                        }
                },
                {
                        module: "newsfeed",
                        position: "bottom_bar",
                        config: {
                                feeds: [
                                        {
                                                title: "New York Times",
                                                url: "http://www.nytimes.com/serv$
                                        }
                                ],
                                showSourceTitle: true,
                                showPublishDate: true
                        }
                },
        ]

                                locationID: "5128581",  //ID from http://www.open$
                                appid: "YOUR_OPENWEATHER_API_KEY"
                        }
                },
                {
                        module: "newsfeed",
                        position: "bottom_bar",
                        config: {
                                feeds: [
                                        {
                                                title: "New York Times",
                                                url: "http://www.nytimes.com/serv$
                                        }
                                ],
                                showSourceTitle: true,
                                showPublishDate: true
                        }
                },
        ]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by hundredrabh** [comment]
I am assuming you are running a python script through MM for GA.
If so can you check if you have no current process running that python script from any of your previous invocations?

I usually do : 
ps -aef | grep python
to list all processes invoked using python.

Then kill any old processes not cleaned properly. 
kill -9 pid

If this fixes your issue. Try to understand why you had a rogue child process and make sure it is cleaned up properly.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
