### ISSUE TITLE
Slide Alert from top.

### ISSUE THREAD

**Issue by MichMich** [MichMich/MagicMirror#137]
Currently, the alert messages slide in from the side. Since the default location of a messages is the top center, I would prefer the default animation to be: _slide in from top_. Since this is done using CSS, this can't easily be changed.

Could you take a look at this, @paviro?

**Comment by paviro** [comment]
Yes but probably not before Friday. Having my finals the next two days.

**Comment by MichMich** [comment]
No worries! Good luck with your finals! :)

**Comment by paviro** [comment]
Thanks! :)
