### ISSUE TITLE
MM keep restarting with electron and pm2 

### ISSUE THREAD

**Issue by alws34** [MichMich/MagicMirror#1378]
Please only submit reproducible issues. 

If you're not sure if it's a real bug or if it's just you, please open a topic on the forum: [https://forum.magicmirror.builders/category/15/bug-hunt](https://forum.magicmirror.builders/category/15/bug-hunt)
Problems installing or configuring your MagicMirror? Check out: [https://forum.magicmirror.builders/category/10/troubleshooting](https://forum.magicmirror.builders/category/10/troubleshooting)

When submitting a new issue, please supply the following information:

**Platform**: Place your platform here... give us your web browser/Electron version *and* your hardware RPI3b Noobs os (let it be, it worked until today perfectly)

Node Version: v10.5.0

**MagicMirror Version**: Now that the versions have split, tell us if you are using the PHP version (v1) or the newer JavaScript version (v2). i downloaded from here: 
https://github.com/MichMich/MagicMirror#manual-installation

**Description**: i have uninstalled MM because it was problematic and i wanted to start from scratch.
after i followed the steps  here: 
https://github.com/MichMich/MagicMirror#manual-installation
i launched MM. 
unfortunatly, MM started in two different threads wich one is controlled by PM2 that i can stop using
`pm2 stop mm`
and the other i just cant kill. it just keep restarting. 
now, iv'e looked into the task manager and saw "electron" proccesses running wich i tried to kill manually,  but they just keep re-apearing and re-starting MM... what do i need to configure? or what did i do wrong? :\
 
**Steps to Reproduce**: re installing MM using :
`bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"`

just like that

**Expected Results**: MM start and behave normally with 
`pm2 start mm`
and
`pm2 stop mm` 

**Actual Results**: two different threads of mm (start up twice) one controlled by pm2, and the oter just cant get rid of...

**Configuration**: MM conf.js file: 
tell me if you need anything else

`/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: ""
					}
          
				]
        
			}
		},
    
    
    {
			module: "calendar",
			header: "",
			position: "bottom_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: ""
					}
          
				]
        
			}
		},
    
    
		{
			module: "compliments",
			position: "" //lower_third
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "",
				locationID: "",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: ""
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "",
				locationID: "",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: ""
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "news",
						url: "my news source"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
    
    
    
    {
  module: 'MMM-Tools',
  position: 'bottom_right',
  config: {
    device : "RPI", // "ATB" is also available
    refresh_interval_ms : 1000,
    warning_interval_ms : 1000 * 60 * 5,
    enable_warning : true,
    warning : {
      CPU_TEMPERATURE : 65,
      GPU_TEMPERATURE : 65,
      CPU_USAGE : 95,
      STORAGE_USED_PERCENT : 80,
      MEMORY_USED_PERCENT : 90
    }
  }
}
// For more detailed information, see below;
    
    
    
    
	]
    

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}`

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
