### ISSUE TITLE
OpenGL ES Support

### ISSUE THREAD

**Issue by IteDas** [MichMich/MagicMirror#1387]
Running MagicMirror on TinkerBoard, scripts run fine. No issues except Node.js wants to use OpenGL but TinkerBoard supports only OpenGL ES. Is there any chance of recompiling electron Node for use with OpenGL ES?

Greetings

When submitting a new issue, please supply the following information:

**Platform**: TinkerBoard

**Node Version**: v9.11.2

**MagicMirror Version**: 2.4.

**Comment by MichMich** [comment]
This is an electron question. Please ask in the electron repository.
