### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by rlarnghks3** [MichMich/MagicMirror#1393]
WARNING! Could not find config file. Please create one. Starting with default configuration.
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: helloworld.
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Sockets connected & modules started ...
Launching application.
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.

^CShutting down server...
Stopping module helper: updatenotification

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
