### ISSUE TITLE
Umlauts not working

### ISSUE THREAD

**Issue by ohjasry** [MichMich/MagicMirror#1398]
Please only submit reproducible issues. 

If you're not sure if it's a real bug or if it's just you, please open a topic on the forum: [https://forum.magicmirror.builders/category/15/bug-hunt](https://forum.magicmirror.builders/category/15/bug-hunt)
Problems installing or configuring your MagicMirror? Check out: [https://forum.magicmirror.builders/category/10/troubleshooting](https://forum.magicmirror.builders/category/10/troubleshooting)

When submitting a new issue, please supply the following information:

**Platform**: Raspberry Pi 3B, Raspbian Stretch

**Node Version**: v6.14.4 (output of node -v)

**MagicMirror Version**:v2

**Description**: I'm using the default newsfeed module, and added some german feeds. Now those feeds use ä, ö and ü, and MagicMirror just shows strange question marks. Can I do something to fix this?

**Steps to Reproduce**: 
1. Install Magic Mirror.
2. Add some german newsfeeds to the config.js
3. P̶r̶o̶f̶i̶t̶ Watch

**Expected Results**: See the news, with umlauts.

**Actual Results**: I saw the news, without umlauts.

**Configuration**: (i just copied the important module)
               {
                        "module": "newsfeed",
                        "position": "bottom_bar",
                        "config": {
                                "feeds": [
                                        {
                                                "title": "New York Times",
                                                "url": "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
                                        },
                                        {
                                                "title": "taz.de",
                                                "url": "http://www.taz.de/!s=;rss/"
                                        },
                                        {
                                                "title": "queer.de",
                                                "url": "http://www.queer.de/rss/newsticker2.0.komplett.xml"
                                        }
                                ],
                                "showSourceTitle": true,
                                "showPublishDate": true
                        }
                }

**Comment by MichMich** [comment]
Please set the correct feed encoding in your config. See documentation: https://github.com/MichMich/MagicMirror/tree/master/modules/default/newsfeed (all the way at the bottom)
