### ISSUE TITLE
Gzip encoded calendar urls fail to load

### ISSUE THREAD

**Issue by ubertao** [MichMich/MagicMirror#1400]
**Platform**: Raspberry Pi 3B+, Electron 2.0.0

**Node Version**: v9.11.2

**MagicMirror Version**: v2.4.1

**Description**: 
Some calendar servers (e.g. icloud.com) responses are gzip encoded, calendar module won't load them.

**Steps to Reproduce**: 
Add "https://p33-calendars.icloud.com/holidays/cn_zh.ics" to calendar module.
(Or any url which response is gzip encoded.)

**Expected Results**:
Calendar module displays the calendar events.

**Actual Results**:
Calendar always displays "loading".

**Configuration**: 
```json
{
    module: "calendar",
    header: "China Holidays",
    position: "top_left",
    config: {
        calendars: [
            {
                symbol: "calendar-check-o ",
                url: "https://p33-calendars.icloud.com/holidays/cn_zh.ics"
            }
        ]
    }
}

```

**Comment by MichMich** [comment]
Fix merged.
