### ISSUE TITLE
npm install && npm start error on MacOS High Sierra 10.13.6 

### ISSUE THREAD

**Issue by Beyond-Chao** [MichMich/MagicMirror#1404]
When I run **npm install && npm start**
npm WARN grunt-stylelint@0.10.1 requires a peer of stylelint@^9.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 7.002s

> magicmirror@2.4.1 start /Users/chengchaochao/Downloads/MagicMirror
> sh run-start.sh

dyld: lazy symbol binding failed: Symbol not found: _SSL_library_init
  Referenced from: /Users/chengchaochao/Downloads/MagicMirror/node_modules/uws/uws_darwin_57.node
  Expected in: flat namespace

dyld: Symbol not found: _SSL_library_init
  Referenced from: /Users/chengchaochao/Downloads/MagicMirror/node_modules/uws/uws_darwin_57.node
  Expected in: flat namespace

----

when I run **sh run-start.sh**  

dyld: lazy symbol binding failed: Symbol not found: _SSL_library_init
  Referenced from: /Users/chengchaochao/Downloads/MagicMirror/node_modules/uws/uws_darwin_57.node
  Expected in: flat namespace

dyld: Symbol not found: _SSL_library_init
  Referenced from: /Users/chengchaochao/Downloads/MagicMirror/node_modules/uws/uws_darwin_57.node
  Expected in: flat namespace

**Comment by ubertao** [comment]
Same issue and found a workaround here:
https://github.com/wonderunit/storyboarder/issues/735

Just delete uws folder: `rm -rf node_modules/uws` and MagicMirror would start.

**Comment by henrikra** [comment]
@MichMich I came across to the same problem because I am developing my modules with OSX and then deploy them to Pi. Can you guys add this to README? @ubertao 's solution worked

**Comment by MichMich** [comment]
@henrikra Feel free to send a PR. I close this issue since the solution is found. Let me know if I need to keep it open.
