### ISSUE TITLE
MMM-Facial-Recognition Typeerror: Python shell is not a constructor

### ISSUE THREAD

**Issue by PimDietzenbacher** [MichMich/MagicMirror#1415]
Everything seems to be right implemented into my config.js file with training.xml in the right directory and assigned into the right path within config.js. I think the module is installed correctly as I see the difference in modules for changing classes, however this error occurs when I start the magicmirror with npm start. Therefore I don't get the 'Hello stranger... alert' yet (pls help!!):

TypeError: PythonShell is not a constructor
    at Class.python_start (/home/pi/MagicMirror/modules/MMM-Facial-Recognition/node_helper.js:11:21)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Facial-Recognition/node_helper.js:40:14)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by rbrueckner82** [comment]
The error appears to occur on several modules, it hits me
MMM fitbit and MMM FRITZ box call monitor

0|mm  | TypeError: PythonShell is not a constructor
0|mm  |     at Class.loadDataFromAPI (/home/pi/MagicMirror/modules/MMM-FRITZ-Box-Callmonitor/node_helper.js:216:17)
0|mm  |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-FRITZ-Box-Callmonitor/node_helper.js:62:10)
0|mm  |     at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
0|mm  |     at emitTwo (events.js:126:13)
0|mm  |     at Socket.emit (events.js:214:7)
0|mm  |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
0|mm  |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|mm  |     at process._tickCallback (internal/process/next_tick.js:180:9)
0|mm  | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm  | Set credential request recieved.
0|mm  | { client_id: '1234',
0|mm  |   client_secret: '1234567' }
0|mm  | Whoops! There was an uncaught exception...
0|mm  | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm  | TypeError: PythonShell.run is not a function
0|mm  |     at Class.setCreds (/home/pi/MagicMirror/modules/MMM-fitbit/node_helper.js:32:15)
0|mm  |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-fitbit/node_helper.js:18:9)
0|mm  |     at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
0|mm  |     at emitTwo (events.js:126:13)
0|mm  |     at Socket.emit (events.js:214:7)
0|mm  |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
0|mm  |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|mm  |     at process._tickCallback (internal/process/next_tick.js:180:9)
0|mm  | Initial run request recieved.
0|mm  | Running getData.py
0|mm  | Whoops! There was an uncaught exception...
0|mm  | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

**Comment by MichMich** [comment]
It seems there is an issue with the python scripts supplied by those modules. Please refer to the 3rd party's repository for issues, since this is not an issue with the MagicMirror core.

I close this issue for now, please let me know if I need to reopen it.
