### ISSUE TITLE
remove module

### ISSUE THREAD

**Issue by LeyDi1987** [MichMich/MagicMirror#1417]
im not a programmer, a noob:)
How can i delete a module from my raspberry pi? Now i just move it to the trash. 
Is that enough or must i delete it another way?

**Comment by fewieden** [comment]
Remove the config.js entry and delete the files as you did. Some modules also install additional dependencies on the os. If that's the case you can also remove them.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
