### ISSUE TITLE
Blank page with new version...

### ISSUE THREAD

**Issue by justjim1220** [MichMich/MagicMirror#1420]
here's my errors from Developer tools...

![screenshot 84](https://user-images.githubusercontent.com/27590633/46273740-6a6bb580-c51c-11e8-86a5-f71af728f123.png)

**Comment by justjim1220** [comment]
I did the npm start dev, but can't find the log file to post for you...

**Comment by MichMich** [comment]
Can you try restarting your pi?

**Comment by justjim1220** [comment]
I am not using a pi. I use Windows on PC's.

I replaced the defaults folder with the backup I made. Now it works fine.

I will try again with the new defaults directory and reboot my PC.

**Comment by justjim1220** [comment]
Thank You!

Restarting Worked!

I guess I need to do that more often... The third time recently that restarting my PC helped get a module to work!

Sorry to bother you!

**Comment by MichMich** [comment]
No worries! Glad it's solved.
