### ISSUE TITLE
Installation on RPi1B+

### ISSUE THREAD

**Issue by yanngeny** [MichMich/MagicMirror#1428]
Hey, i'm french and i want to use magic mirror on my raspberry pi 1 B+, is someone ca explain how can i install on it step by step ?

**Comment by Ybbet** [comment]
Hi,
I'm french too. You could find some articles on my website about the installation for raspberry Pi.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
