### ISSUE TITLE
add left & right container to middle location

### ISSUE THREAD

**Issue by CFenner** [MichMich/MagicMirror#143]
Hi,

I would like to have a module placed in the middle bar but on the side. What do you think about adding some more containers like in the top and bottom bar?

**Comment by MichMich** [comment]
I don't want it to get too bloated. But two extra containers probably won't hurt. Will you send a pull request?

**Comment by CFenner** [comment]
Yes, I can do.

**Comment by MichMich** [comment]
I close this issue for now. Feel free to reopen.
