### ISSUE TITLE
document / fix showEnd

### ISSUE THREAD

**Issue by tkoeberl** [MichMich/MagicMirror#1439]
Hi,

since the latest update the Dates are shown at the end of the calendar entry.
I tried to disable it via the config with showEnd: "false", or showEnd: false but didn't work out.

as a workaround I set the default to false in file: ./modules/default/calendar/calendar.js

regards,
-thomas

**Comment by Duske** [comment]
I guess this should be fixed with #1437

**Comment by BennyS91** [comment]
I had the same problem, I just added it direct in config.js as `showEnd: false,` as base configuration element in my calendar. This applies for all then, and now it looks fine again ;-).

Here for example:

```      {
            module: "calendar",
            header: "Kalender",
            position: "top_left",
            config: {
                colored: true,
                maximumEntries: 11,
                maxTitleLength: 40,
                showEnd: false,
                calendars: [{
                        symbol: "smile-o",
                       .........
```

**Comment by tkoeberl** [comment]
Cool. thats it.
