### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by boomza19193** [MichMich/MagicMirror#1453]
How i solve this problem.

`pi@raspberrypi:~/MagicMirror` $ git pull && npm install
Updating 6aa156d..6db61b4
error: Your local changes to the following files would be overwritten by merge:
	config/config.js.sample
	package-lock.json
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by Mattie38wit** [comment]
Delete the file and then update it. thats what I did and it updated for me.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
