### ISSUE TITLE
global encoding...

### ISSUE THREAD

**Issue by justjim1220** [MichMich/MagicMirror#1455]
would there be a way to add a global encoding to the config.js file?

For example:
`
        language: "en",
	timeFormat: 24,
	units: "imperial",
        encoding: "UTF-8", // "ISO-8859-9", "ISO-8859-15" support European Characters
            // http://scratchpad.wikia.com/wiki/Character_Encoding_Recommendation_for_Languages
`
I would think it would solve a lot of the issues with showing the correct characters within MM if this could be done globally somehow. There are quite a few modules that don't include encoding and it seems those are the ones that people have the most issues with and this seems like it would be the best way to solve the issues.

**Comment by MichMich** [comment]
Feel free to send a PR.
