### ISSUE TITLE
[Branch v-2] brackets appear after loading calendar.

### ISSUE THREAD

**Issue by delize** [MichMich/MagicMirror#146]
Something in my Google Calendar (and I narrowed it down to at least one, my private ical link) is causing this to happen after launching the MagicMirror v2 branch:

> All module helpers loaded.
> Starting server op port 8080 ... 
> Server started ...
> Connecting socket for: calendar
> Starting node helper for: calendar
> Connecting socket for: newsfeed
> Starting module: newsfeed
> Sockets connected & modules started ...
> Launching application.
> Create new calendar fetcher for url: http://www.calendarlabs.com/templates/ical/US-Holidays.ics - Interval: 300000
> Create new calendar fetcher for url: https://www.facebook.com/ical/u.php?uid=omit&key=omit - Interval: 300000
> Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/uid/public/basic.ics - Interval: 300000
> Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/user/private-uid/basic.ics - Interval: 300000
> Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
> []
> []
> []
> []
> []
> []
> []
> []
> []
> ^C

This only occurs when the last calendar option is loaded. Which means that something is causing these brackets to appear in the calendar, because something is not closed properly.

**Comment by MichMich** [comment]
Those were just debugging prints. I've removed them. 
If this problem still occurs, feel free to reopen this issue.
