### ISSUE TITLE
calendar module infinit loading

### ISSUE THREAD

**Issue by JooMiHyun** [MichMich/MagicMirror#1461]
![20181110_192000](https://user-images.githubusercontent.com/39157344/48300282-b3e8f080-e51d-11e8-8ffa-e7f1ac4226db.png)
like this.
How can i resolve that?
i already founded data about calendar problems in magicmirror forum.
i use google calendar private, public ical all have problem.

**Comment by Stefane56** [comment]
bonjour j ai le meme souci
