### ISSUE TITLE
Not install on arm64

### ISSUE THREAD

**Issue by vvzvlad** [MichMich/MagicMirror#1462]
**Platform**: 
```
orangepi@orangepizeroplus2:~$ grep . /etc/*-release
/etc/armbian-image-release:# PLEASE DO NOT EDIT THIS FILE
/etc/armbian-image-release:BOARD=orangepizeroplus2-h5
/etc/armbian-image-release:BOARD_NAME="Orange Pi Zero Plus 2"
/etc/armbian-image-release:BOARDFAMILY=sun50iw2
/etc/armbian-image-release:VERSION=5.65
/etc/armbian-image-release:LINUXFAMILY=sunxi64
/etc/armbian-image-release:BRANCH=next
/etc/armbian-image-release:ARCH=arm64
/etc/armbian-image-release:IMAGE_TYPE=stable
/etc/armbian-image-release:BOARD_TYPE=conf
/etc/armbian-image-release:INITRD_ARCH=arm64

orangepi@orangepizeroplus2:~$ uname -m
aarch64
orangepi@orangepizeroplus2:~$ getconf LONG_BIT
64
orangepi@orangepizeroplus2:~$ dpkg -s libc6 | grep Arch
Architecture: arm64
Multi-Arch: same
orangepi@orangepizeroplus2:~$ npm -v
6.4.1
orangepi@orangepizeroplus2:~$ node -v
v10.13.0
orangepi@orangepizeroplus2:~$ 

```

**Node Version**: 
v10.13.0

**MagicMirror Version**: 
2.5.0, master

**Description**: 
Unable to install MM on the arm64 platform, npm install fails with:
`Error: Failed to find Electron v1.7.0 for linux-arm64 at https://github.com/electron/electron/releases/download/v1.7.0/chromedriver-v1.7.0-linux-arm64.zip`

Same problems:
https://forum.magicmirror.builders/topic/6377/error-on-clean-installation-using-npm-install-electron-chromedriver-1-7-1
https://forum.magicmirror.builders/topic/8786/rpi3-npm-install-failed-to-find-electron-v1-7-0-for-linux-arm64
https://forum.magicmirror.builders/topic/6926/mm-installation-error-by-electron-arm64/2

**Steps to Reproduce**: npm install

```
orangepi@orangepizeroplus2:~/MagicMirror2$ npm install
npm WARN deprecated time-grunt@2.0.0: Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.

> electron-chromedriver@1.7.1 install /home/orangepi/MagicMirror2/node_modules/spectron/node_modules/electron-chromedriver
> node ./download-chromedriver.js

/home/orangepi/MagicMirror2/node_modules/spectron/node_modules/electron-chromedriver/download-chromedriver.js:16
  if (error != null) throw error
                     ^

Error: Failed to find Electron v1.7.0 for linux-arm64 at https://github.com/electron/electron/releases/download/v1.7.0/chromedriver-v1.7.0-linux-arm64.zip
    at Request.<anonymous> (/home/orangepi/MagicMirror2/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:182:13)
    at Request.onRequestResponse (/home/orangepi/MagicMirror2/node_modules/request/request.js:1068:10)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:441:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
npm WARN grunt-stylelint@0.10.1 requires a peer of stylelint@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
Full log: http://paste.ubuntu.com/p/wkVdMYXqNQ/

**Comment by burnbabyburn** [comment]
PLs see the following link: https://github.com/electron/electron/issues/8291

**Comment by vvzvlad** [comment]
I see link. As we can see, the electron for arm64 exists:
https://github.com/electron/electron/releases

The problem is that there is no version 1.7.0 for arm64.
https://github.com/electron/electron/releases/tag/v1.7.0

In any case, there is a problem in that on a certain platform the magic mirror cannot be installed and launched — my words confirm three topics on the forum. It is necessary to somehow solve the problem.

**Comment by vvzvlad** [comment]
P.S. Using solutions consisting of crutches, I solved this problem. But this is the wrong decision.

```
npm install --arch=armv7l
rm -rf ./node_modules/electron
npm install electron
npm start
```

**Comment by burnbabyburn** [comment]
> I see link. As we can see, the electron for arm64 exists:
> https://github.com/electron/electron/releases
you're right. i'll better go to bed.

**Comment by gkreitz** [comment]
A cleaner way to fix the build is to simply bump the dependency `spectron` to `^4.0.0` (which seems to be the version matching the current `electron` dependency anyway, according to [spectron's readme.md](https://github.com/electron/spectron/blob/master/README.md))

**Comment by MichMich** [comment]
Since we officially only support the Raspberry Pi, I close this issue. Feel free to send a non breaking PR which fixes this issue.

**Comment by vvzvlad** [comment]
I create PR #1537 according to the recommendation of distinguished @gkreitz
