### ISSUE TITLE
Calendar: date headers not fading

### ISSUE THREAD

**Issue by lavolp3** [MichMich/MagicMirror#1464]
When submitting a new issue, please supply the following information:

**Platform**: Raspberry Pi 3b, Raspbian Jessie, electron v3.0.9

**Node Version**: v11.0.0

**MagicMirror Version**: v2.5.0
**Description**: 
In the Calendar module, when timeFormat is set to dateheaders, the headers do not fade as the calendar entries do.

**Steps to Reproduce**: n/a
**Expected Results**: date headers also fading

**Actual Results**: date headers not fading

**Configuration**: 
`    {
        module: "calendar",
        classes: 'xsmall',
        header: "Kalender",
        position: "top_left",
        config: {
            colored: true,
	    maximumEntries: 15,
            timeFormat: 'dateheaders',
            dateFormat: 'dddd DoMo',
            dateEndFormat: 'HH:mm',
            fullDayEventDateFormat: 'dddd DoMo',
            displayRepeatingCountTitle: true,
            broadcastEvents: false,
            fadePoint: 0.65,
			maxTitleLength: 35,
            calendars: [
                {
                    symbol: 'calendar',
                    url: 'https://calendar.google.com/calendar/ical/xxx/basic.ics'		
                },
				{
                    symbol: 'birthday-cake',
                    color: '#f4a341',
                    url: xxx                },
            ],
         },
    },
`

**Comment by MichMich** [comment]
merged
