### ISSUE TITLE
Error while sync some events from Google Calendar

### ISSUE THREAD

**Issue by nico0709** [MichMich/MagicMirror#1465]
Hi! I reinstall my Magic Mirror setup, to correct lots of bugs. But one is stay: some events of one of my Google Calendar account are not shown in the calendar module. Could you help me? ;)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
