### ISSUE TITLE
Magic Mirror <--> Digital Picture Frames

### ISSUE THREAD

**Issue by jraff2** [MichMich/MagicMirror#1474]
This is more of an alternate usage of a Magic Mirror or not.
After a while of inaction (5 - 10 min.) switch to a Digital Picture Frames display.
Yeah I know it takes away the mirror usage but makes the display really display something.
One would have to pull images from some other source like an attached HD or maybe from the net.
Just a thought!

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
