### ISSUE TITLE
A functional question about face effects

### ISSUE THREAD

**Issue by ijustlearn** [MichMich/MagicMirror#1475]
Hello，
I want to implement a project.
like:
When I look in the mirror, the camera in the mirror automatically recognizes the position of the face and adds facial effects.

The key issue is that the location of the face recognized by the camera may not be the same as the position in the   mirror.

Do you have any good ideas?

thanks!

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by ijustlearn** [comment]
thanks
