### ISSUE TITLE
Calendar entries start in 12 hour time, end in 24 hour time

### ISSUE THREAD

**Issue by nickbeaulieu98** [MichMich/MagicMirror#1479]
My calendar shows appointment times starting using 12 hour time (my preference) but ending using 24 hour time: 

![image](https://user-images.githubusercontent.com/45611625/49716255-080fef00-fc08-11e8-835a-a4254eec115e.png)

**Comment by javaughnlanglois** [comment]
I am experiencing the same

**Comment by txajay** [comment]
I just installed this and I am having the same issue as well.

**Comment by sprestel** [comment]
no fix but a workaround.

insert 
`
showEnd: false
`
into the configuration will be fine for now

**Comment by xuv** [comment]
Seems to me this line: https://github.com/MichMich/MagicMirror/blob/de57daa3cd881ce1a14b88307bf61e8109879c81/modules/default/calendar/calendar.js#L355

```timeWrapper.innerHTML += this.capFirst(moment(event.endDate, "x").format(this.config.dateEndFormat));```

has to be changed to this:

```timeWrapper.innerHTML += this.capFirst(moment(event.endDate, "x").format(this.config.dateFormat));```

And that should solve it.

**Comment by lavolp3** [comment]
There is a config option dateEndFormat which can be adapted to your style. Take the proper moment.js format [as shown here](https://momentjs.com/docs/#/parsing/string-format/)

However, this could have been easily avoided by changing line the line 
`timeWrapper.innerHTML += this.capFirst(moment(event.endDate, "x").format(this.config.dateEndFormat));`
to
`timeWrapper.innerHTML += this.capFirst(moment(event.endDate, "x").format("LT"));`

However I think the whole showEnd function is kind of messed up and I'd like to redo it more generally. In the meantime this should help your issue.

**Comment by lavolp3** [comment]
Should be fixed in the develop branch using the PR above. @nickbeaulieu98 you can try out the fix by just setting dateEndFormat: "LT", or your preferred time setting, in your config for the module.

**Comment by lavolp3** [comment]
@MichMich I'd suggest to close this.
