### ISSUE TITLE
sendSocketNotification is not a function

### ISSUE THREAD

**Issue by dracepj** [MichMich/MagicMirror#1490]
I am new to node and am having issues sending data from server to client using the sendSocketNotification function. Below I have included an example of the output on the server side. I have looked over previous issues and have not been able to resolve this problem. Been stuck for a while now. Any help would be appreciated. 

Things tried: 

-I am sending a message to initialize the connection between the client and server. 
-creating a helper variable
`var self = this;`
All things in Issue #196

Platform: Mac OS 10.14.2
<img width="351" alt="screen shot 2018-12-28 at 5 01 04 pm" src="https://user-images.githubusercontent.com/32557068/50530350-3cb5ee80-0ac2-11e9-8623-d139f141caf4.png">

<img width="927" alt="screen shot 2018-12-28 at 4 04 28 pm" src="https://user-images.githubusercontent.com/32557068/50530296-b39eb780-0ac1-11e9-816b-1e7033449d96.png">

SNIPPET
`

     socketNotificationReceived: function(notification, payload) {
		if (notification === "AUTHENTICATE") {
			console.log("Notification recieved on server:", notification, "payload: ", payload);
			//Starts authentication process with this.authConfirmationCallback as callback method
			this.authenticate(this.authConfirmationCallback);
		}else if(notification === ("GET_EMAILS")){
			console.log("Notification recieved on server:", notification, "payload: ", payload);
			this.sendNotification(this.getEmailIds(oAuth2Client));
		}
	},

     authConfirmationCallback: function(){
		console.log("SENDING AUTH_CALLBACK TO CLIENT");
		//Fails here 
		this.sendSocketNotification("AUTH_CALLBACK", "TEST PAYLOAD");
	},

`

config.js

`

      var config = {
	   address: "localhost", // Address to listen on, can be:
	                        // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
        },
        {
            module: "MMMGmail",
            position: "top_right"
	},
		  
	]

     };

    /*************** DO NOT EDIT THE LINE BELOW ***************/
    if (typeof module !== "undefined") {module.exports = config;}
    
`

Module is located on my github page [https://github.com/dracepj/MMMGmail](url). You will need a credentials.json file in the same dir as node_helper.js  from google for authentication to work.

**Comment by MichMich** [comment]
The node helper only has the `this.sendNotification` method, not the `this.sendSocketNotification`.
