### ISSUE TITLE
Creating an image with a clean installation of MagicMirror

### ISSUE THREAD

**Issue by ishepard** [MichMich/MagicMirror#1492]
I see a lot of people having issues on installing dependencies, MagicMirror, etc. 
Maybe it could be useful to create an image that people can use to format their SD card (i.e., using `dd`) containing the basic installation of MagicMirror. 
We can create an image for Raspberry Pi 3, 3+, of 8 and 16GB. So 4 images in total.

What do you think?

**Comment by MichMich** [comment]
It will be a lot of work to maintain, and defeats the purpose of the Project. (https://github.com/MichMich/MagicMirror#manifesto)

But feel free to create and host a image yourself! :)

**Comment by ShrinivasPuranik** [comment]
There is a repo that does that maintained by skarbat [https://github.com/skarbat/raspimirror](https://github.com/skarbat/raspimirror). Though I dont think there is an automated build.

**Comment by MichMich** [comment]
This solves this issue. Closing it for now. Feel free to let me know if I need to reopen.
