### ISSUE TITLE
MagicMirror Forum

### ISSUE THREAD

**Issue by Batminer** [MichMich/MagicMirror#1493]
Total noob. Been working on a mirror for a few weeks. 
I am having an issue using the forum, https://forum.magicmirror.builders/
1) When I am trying to post in the troubleshooting section I get the following pop up;
Your email has not been confirmed yet, please click here to confirm your email.
I have been clicking the link in the pop up and the button on the edit profile page half a dozen times with three different emails (@outlook, @yahoo & @gmail)
I don't see anything anywhere in any of my email inboxes. 
What gives
Merry New Year!
Sincerely,
Andy Wa

**Comment by MichMich** [comment]
@paviro Can you help?

**Comment by MichMich** [comment]
@paviro @Batminer is this issue solved?

**Comment by Batminer** [comment]
Yes it looks like this has been corrected.
Thank you
