### ISSUE TITLE
new weather module

### ISSUE THREAD

**Issue by apm1007** [MichMich/MagicMirror#1499]
i found three problems with the new weather module
decimal signal isnt working. 
![grafik](https://user-images.githubusercontent.com/11927080/50591150-55415280-0e8e-11e9-9175-e3c93b7727cf.png)
![grafik](https://user-images.githubusercontent.com/11927080/50591178-6be7a980-0e8e-11e9-8b2d-c3928c4ff484.png)
layout of forecast ist far to big. dunno why there are empty lines compared to the old forecast
![grafik](https://user-images.githubusercontent.com/11927080/50591196-8cafff00-0e8e-11e9-91bb-d20843cc12f4.png)
hour forecast isnt possible.
Pretty Good idea for taking indoor temp and humidity to the weather module! but would be great to get the symbols vertical for better screen use.
![grafik](https://user-images.githubusercontent.com/11927080/50591273-0811b080-0e8f-11e9-9fed-0f4d2f81a27a.png)
Thank you!

**Comment by MichMich** [comment]
@apm1007  Thanks for your feedback! 

@fewieden do you want me to tag you in these issue reports?

**Comment by fewieden** [comment]
@MichMich sure you can tag me it will not hurt, but I'm back at work now, so I can't promise anything.

1. Decimal symbol was not implemented, but still documented in the readme. I added it and it will be in the next pr.

2. I'm not sure yet why the forecast table has this spacing. Will have a look when I find time to debug this.

3. The indoor values are horizontal like in the currentweather module. I made them now smaller and vertical. Also added a class to it so people can style it individually. Will be in next pr.

**Comment by fewieden** [comment]
All 3 points are handled in https://github.com/MichMich/MagicMirror/pull/1510

**Comment by MichMich** [comment]
Merged.
