### ISSUE TITLE
New weather module: support for missing config entries

### ISSUE THREAD

**Issue by vincep5** [MichMich/MagicMirror#1516]
In the existing weatherforecast.js, we have the ability to fade the forecast (config setting) fade and fadePoint.  Is it possible to carry this over to the weather module when we display a forecast ?  @fewieden

scale and maxNumberOfDays and retryDelay are other missing ones.

**Comment by MichMich** [comment]
There are a few other things to address. Maybe its a good idea to add a wiki page with a todo list so we can add stuff on a list. Or should we make separate issues with [Weather Module] at the start if the title?

**Comment by vincep5** [comment]
Wiki page would be good. Then we figure what is needed
