### ISSUE TITLE
can't auto start magimirror automatically

### ISSUE THREAD

**Issue by Appleudaya** [MichMich/MagicMirror#1523]
For Auto Starting Magic Mirror , the command are refer from the bellow link
https://github.com/MichMich/MagicMirror/wiki/Auto-Starting-MagicMirror

But there is error to run while the reboot the magicmirror , the MagicMirror does not auto start

while running the terminal issues found

pi@raspberrypi:~ $ sudo npm install -g pm2
/usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2
/usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev
/usr/bin/pm2-runtime -> /usr/lib/node_modules/pm2/bin/pm2-runtime
/usr/bin/pm2-docker -> /usr/lib/node_modules/pm2/bin/pm2-docker
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/pm2/node_modules/fsevents):
**npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})**

+ pm2@3.2.4
updated 1 package in 86.95s

   So please give the trobleshoot procudure to solve the probloem

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
