### ISSUE TITLE
FullDay Event One Day

### ISSUE THREAD

**Issue by knubbl1983** [MichMich/MagicMirror#1526]
Still have a problm with full day event on one day..
 "Bug showing FullDayEvents one day too long in calendar fixed" is correct

But i have still the indication for a full day event .e.g 15.Jan-15.Jan when i configure show end true.
around line 307: edit the i clause to chek if an event ist just one day 

``if(this.config.showEnd && this.capFirst(moment(event.endDate  , "x").format(this.config.fullDayEventDateFormat)) != this.capFirst(moment(event.startDate  , "x").format(this.config.fullDayEventDateFormat))){
						timeWrapper.innerHTML += "-" ;
						timeWrapper.innerHTML += this.capFirst(moment(event.endDate  , "x").format(this.config.fullDayEventDateFormat));
					}`

This might solve the problem`

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
