### ISSUE TITLE
There are some errors in the description

### ISSUE THREAD

**Issue by Robiv8** [MichMich/MagicMirror#153]
Hello World in your Module readme
    {
        module: 'helloworld',
        position: 'bottom_bar', // This can be any of the regions.
        config: {
            // See 'Configuration options' for more information.
            text: 'Hello world!', **<-- wrong**
        }
    }

Your example config.js on GitHub
   {
            module: "helloworld",
            position: "lower_third",
            classes: "small"
            config: {
                text: "Hello world!" **<-- wrong**
            }
        }

My functioning Module:
{
            module: "helloworld",
            position: "lower_third",
            classes: "small"
            config: {
                text: ’Hello world!’ **<-- correct**
            }
        }

**Comment by nhubbard** [comment]
I would recommend that you fork the project, make the change to fix this issue, and then make a pull request to correct it.

**Comment by MichMich** [comment]
Is it just me, or isn't there really any difference? All three versions should work, I think.

**Comment by nhubbard** [comment]
I would agree. JSCS *might* complain, but there isn't really a difference.

**Comment by MichMich** [comment]
I close this issue for now. Feel free to reopen.

**Comment by Robiv8** [comment]
I feel just a bit fooled. I have needed a little while to come to this tiny error. And no! I am not a programmer, coder or the like.
In the first 2 versions "Please create Config" comes.

And sorry, I dont know how everything works here with forks, pull etc ..
So do what you want with it

**Comment by MichMich** [comment]
Please, Don't feel fooled. Your contribution is more than welcome. Unfortunately I fail to find the issue in your description. All three versions seem correct. Since you are currently not experiencing any issues (as far as I can understand) I closed this issue.

**Comment by Robiv8** [comment]
It is probably too small to read.
I have made the points again in bold.
In 1st apostrophe closed comma.
At 2 quotes
At 3 the correct version. Apostrophe without comma.
As I said are No1. and No.2 from the tutorial and do not work because the message is you should create a config.
Greeting

## 1. text: **'**Hello world!**',** <-- wrong
2. text: **"**Hello world!**"** <-- wrong
3. text: **’**Hello world!**’** <-- correct

**Comment by MichMich** [comment]
Honestly, I think it's an issue with your text editor which converts te comma's into the wrong entities. What editor are you using?

The extra comma does not matter since it's a javascript object.

I'm using the code from the tutorial and it works.

**Comment by Robiv8** [comment]
Ha Ha, We are talking past each other, but no matter!
No, it is not on my text editor, but no matter.
I give up.
Keep it up. The project is great.

**Comment by MichMich** [comment]
Can You send a pullrequest?

**Comment by Robiv8** [comment]
OK let me try.
