### ISSUE TITLE
Google calendar stops syncing after 3+ hours

### ISSUE THREAD

**Issue by zakari13** [MichMich/MagicMirror#1536]
I just got and installed my magic mirror but the google calendar will stop syncing after a few hours. the calendar only updates for a few hours after I run a fresh npm start with my magic mirror. I am aware of the fetch interval command and I have mine set to update after 1 minute ( I know a bit excessive ). Everything else stays up to day ( weather, BBC news, time, etc ). I was wondering if there was any other information that I was missing that causes this issue with google calendar. Also just FYI I use the private ical address. 

here is my calendar code snip-it:
module: "calendar",
			header: "Calendar",
			position: "top_left",
			config: {
				fetchInterval: 1000x60x1,
				maximumEntries: 7,
				calendars: [
					{
						symbol: "calendar-check",
						url: 'Super sneaky url for google calendar',

					}
				]
					}

**Comment by zakari13** [comment]
Just forgot to mention that I am running off a Pi 3+ b

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
