### ISSUE TITLE
New weather module current.njk JS error on develop branch

### ISSUE THREAD

**Issue by vincep5** [MichMich/MagicMirror#1538]
Issue with current.njk on the develop branch.   When I add the "current" module, I get a JS error: TypeError: value.replace is not a function.  It's because of 

`		this.nunjucksEnvironment().addFilter("decimalSymbol", function(value) {
			return value.replace(/\./g, this.config.decimalSymbol);
		}.bind(this));`
value.replace throws the error.  If I put it as value.toString().replace, it works

Also the "Loading . . ." string is escaped improperly in the current.njk and forecast.njk
it shows up as "Loading &hellip"

**Comment by MichMich** [comment]
Could you please send a PR to fix this? Thanks! :)
