### ISSUE TITLE
Layout - News Feed

### ISSUE THREAD

**Issue by skyales** [MichMich/MagicMirror#1543]
Is it possible to wrap the news module description with shorter lines? 
It has one long line as description noe, despite having wrapDescription enabled.
It would be perfect if the description would have 70 characters each line.
I can't figure out how to do that. Can someone help please?

**Comment by mlcampbe** [comment]
Are you still having this problem? We can't change the line length without modifying the javascript code but we can use some custom css to use less space. In my case I have the newsfeed in the 'lower_third' section and added the following into my custom.css file:

```
.module.newsfeed {
	max-width: 50%; // adjust px to taste, or use %, em, etc
}

.region.lower.third {
  left: 25%;
}

```
