### ISSUE TITLE
Keep showing “ No upcoming events “

### ISSUE THREAD

**Issue by jasb1011** [MichMich/MagicMirror#1547]
I have just installed my magic mirror, but it just shows “ No upcoming events” instead of Holidays. Please tell me how I can fix this problem

**Comment by lavolp3** [comment]
Are you using pm2?
Then go into the console and type in 
`pm2 logs`
and look up if you find an error referring to the calendar module.

If not:
start the mirror in dev mode by typing in
`npm start dev`
and look up any error messages that come up referring to the calendar module

**Comment by jasb1011** [comment]
The only thing I see for calendar is “Initializing new module helper ...
Module helper loaded: calendar “
Is that a problem, if so how can I fix it please help

**Comment by justjim1220** [comment]
Have you tried rebooting the system?

**Comment by jasb1011** [comment]
Just rebooted it, it still shows the no upcoming events

**Comment by lavolp3** [comment]
> The only thing I see for calendar is “Initializing new module helper ...
> Module helper loaded: calendar “
> Is that a problem, if so how can I fix it please help

It's not an issue. Try looking up the error if you open the Mirror in an external browser and looking into the developer's tab (F12)
Also, It's better to move these things into the forum. forum.magicmirror.builders.
It doesn't seem to be an issue with the code after all.

**Comment by alexlobrano** [comment]
The problem isn't necessarily with the code, it's with the default URL for the holidays link the config file.

Using the default URL ("webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics") only gets you an ics for 2017-2018 holidays, so nothing shows now. You can verify this by downloading it and opening it in a calendar app.

@jasb1011 - Trying using the new URL "https://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics" in your config file and that should get your MagicMirror to show the holidays in 2019.

**Comment by jasb1011** [comment]
Thank you so much @alexobrano it worked

**Comment by cobra85ec** [comment]
> The problem isn't necessarily with the code, it's with the default URL for the holidays in the config file.
> 
> Using the default URL ("webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics") only gets you an ics for 2017-2018 holidays, so nothing shows now. You can verify this by downloading it and opening it in a calendar app.
> 
> @jasb1011 - Trying using the new URL "https://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics" in your config file and that should get your MagicMirror to show the holidays in 2019.

THIS WORKS THANK YOU VERY MUCH
