### ISSUE TITLE
showWindDirection: "false" doesn't work

### ISSUE THREAD

**Issue by nickbeaulieu98** [MichMich/MagicMirror#1548]
I don't want the wind direction to show in my weather module, so I've set showWindDirection: "false" but that doesn't do anything.

**Comment by mattgahs** [comment]
Try `showWindDirection: false,` without the quotes around false.

**Comment by nickbeaulieu98** [comment]
that did it. Thanks. I wouldn't have expected that, since all the other statements use quotes

**Comment by ToddKlindt** [comment]
> that did it. Thanks. I wouldn't have expected that, since all the other statements use quotes

I always struggle with this too. I've been using MM for a couple of years and I made this mistake just this last week. The trick I use is to look at the examples. The trues and falses are never in quotes, where the other config options are.

**Comment by mattgahs** [comment]
I assume it's because true/false is a binary state, whereas text/numbers are strings that can have an infinite number of options that have to be defined by quotes.

**Comment by fewieden** [comment]
@mattgahs numbers are normally also not in quotes, if there is a number in quotes it gets interpreted a text/string
