### ISSUE TITLE
List of notifications IDs and payload formats in wiki

### ISSUE THREAD

**Issue by mrdis** [MichMich/MagicMirror#1550]
I was looking for the currently defined notification IDs in order to decide how and if I should define a new notification type in a module I'm writing, and it seems that there is no such a list anywhere in the wiki.
I think it could be useful to have a "catalog" for the available notifications, similar to the one we have for the available modules.

**Comment by MichMich** [comment]
Absolutely a good idea! Feel free to contribute! :)

**Comment by mrdis** [comment]
Somebody recently added the page to the wiki, so I'm contributing there, great!
