### ISSUE TITLE
MM2 Server Deployment Black Screen non-RPi

### ISSUE THREAD

**Issue by nconder** [MichMich/MagicMirror#1551]
Using the manual deployment instructions for MM2 server I'm receiving a black screen. I've deployed MM2 on Ubuntu server 16.04.03 and 18.04 both receive the same results. The config includes no modifications outside of the basics instructions for MM2 server.

The manual installation is successful with no errors returned. 

MM2 git pull from 1/22/19

node -v v10.15.0

` node serveronly
Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ...
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...

Ready to go! Please point your browser to: http://0.0.0.0:8080
`

**Comment by khassel** [comment]
did you run `npm install` with user `root`? If yes you can try `npm install --unsafe-perm`

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
