### ISSUE TITLE
Improvement? - how to format "compliments" for quotes

### ISSUE THREAD

**Issue by feedbagg** [MichMich/MagicMirror#1559]
Hi!
I want to add some quotes im my compliments, therefore i'll add the name of the quoted person like this:

"Egal wie schwierig das Leben geworden ist.\nEs gibt immer etwas, worin du erfolgreich sein kannst.\NAMEStephen Hawking",

should look like:

![image](https://user-images.githubusercontent.com/2532420/52164920-700b1f00-26f9-11e9-914a-3bae14c27ba6.png)

may this be realizable?

Thank You in advance!
FeedBagg

**Comment by MichMich** [comment]
Not in the current form, but feel free to send a PR. I'm not sure I like the /NAME solution. I think a better idea would be using a (json) object.

**Comment by MichMich** [comment]
I think you are better of using one of the quotes modules. Please check: https://github.com/MichMich/MagicMirror/wiki/3rd-party-modules
