### ISSUE TITLE
Adding description to RSS feeds

### ISSUE THREAD

**Issue by hulkhaugen** [MichMich/MagicMirror#157]
I want the RSS feed to have the option to enable description in addition to the title. Nowdays, the titles are often click-bait and doesn't tell much, so adding the description would be nice. I imagine it should (by default) be shown in a smaller font beneath the title.

It's also wort to mention that some rss feeds has pictures and links in them, those should be (possible to) filter out.

I also tried adding several feeds without luck, but that could be my bad. If possible, it would be nice to have a source name/icon in front of the feed. My experience is from v1, so some of this might already have been fixed. Hope this doesn't come off as too demanding, I believe it would give the whole experience a nice touch.

**Comment by MichMich** [comment]
You can now display the item description for the news feed. Simply add the following to your newsfeed config: `showDescription: true`. (See [documentation](https://github.com/MichMich/MagicMirror/blob/v2-beta/modules/default/newsfeed/README.md).)
