### ISSUE TITLE
(MMM-weatherforecast)

### ISSUE THREAD

**Issue by mastory123** [MichMich/MagicMirror#1570]
Hi,
how i change the size of text in this module?(MMM-weatherforecast)
TY

https://ibb.co/DpzWj0w

**Comment by mastory123** [comment]
![mm](https://user-images.githubusercontent.com/47565566/52641960-511b4280-2eda-11e9-96a6-6da5123fad91.jpg)

**Comment by MichMich** [comment]
Please open a issue in the respective repository. Thanks.
