### ISSUE TITLE
default calendar incorrectly calculates offsets for full day events. in format=relative

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#1572]
Please only submit reproducible issues. 

the issue is the code uses startDate.fromNow() to calculate the date offset, but fromNow() uses wall clock time (hours/minutes) which causes date rounding..

the code needs to be changed to use startDate.from(moment().format("MMDDYYY"))

timeWrapper.innerHTML = this.capFirst(moment(event.startDate, "x").from(moment().format("YYYYMMDD")));
to use start of day comparisons..

will attach a PR with the changes.

**Comment by MichMich** [comment]
The PR is merged.
