### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Saartje1997** [MichMich/MagicMirror#1574]
Can some help me with these errors

npm ERR! path /root/.npm/_cacache/index-v5/ad/83/9f5e6196c4aff975b74d4aab924ab2416c48679ed9bb91e08bec18e547b4
npm ERR! code ENOTDIR
npm ERR! errno -20
npm ERR! syscall open
npm ERR! ENOTDIR: not a directory, open '/root/.npm/_cacache/index-v5/ad/83/9f5e6196c4aff975b74d4aab924ab2416c48679ed9bb91e08bec18e547b4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-15T08_07_37_732Z-debug.log

 Thanks

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
