### ISSUE TITLE
autostart only after second restart

### ISSUE THREAD

**Issue by geoffrey51** [MichMich/MagicMirror#1576]
hi guys,

I'm totally new at GitHub. I build a Magic Mirror with the manual. Works very well, so thanks for the great description, programs and moduls. 
I decided to autostart the Magic Mirror and to shutdown the raspberry after 15minutes. Therefor I used pm2 and the command: sudo shutdown -h 15. This works also.

But, the problem is, to start the raspberry pi. 
I have to switch the energy of the raspberry off/on. Then starts the raspberry and autostarts the MagicMirror program. But after a view seconds it shutdowns by itself.
So I have to swtich the energy off/on again. And only now works the program as it should, and the raspberry shutdown by itself after 15min.
So can anybody tell me, why I need 2 tries to run the program correctly?

Best regards
Geoffrey51

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
