### ISSUE TITLE
Calendar module not loading out of no where

### ISSUE THREAD

**Issue by dhuckla** [MichMich/MagicMirror#1583]
The following is the code that is put in for the defualt module "calendar".
When I turned on my pi this morning my calendar is just stuck on loading...
It worked fine the night before.
Any suggestions?
{
			module: "calendar",
			header: "My Calendar",
			position: "top_left",
			config: {
				maximumEntries: 6,
				timeFormat: "absolute",
				getRelative: 1,
				dateEndFormat: "h:mm A",
				fullDayEventDateFormat: "MMMM Do",
				showEnd: true,
				dateFormat: "MMMM Do",
				wrapEvents: true,
				urgency: 1,
				colored: true,
				coloredSymbolOnly: true,
				calendars: [
					{
						symbol: "futbol",
						url: "https://calendar.google.com/calendar/ical/xxxxxxxxx/public/basic.ics",
						color: "#3aff00",
						maximumEntries: 1
					},
					{
						symbol: "calendar-alt",
						url: "https://calendar.google.com/calendar/ical/xxxxxxxxx/public/basic.ics",
						color: "#ff9300"
					},
					{
						symbol: "calendar-alt",
						url: "https://calendar.google.com/calendar/ical/xxxxxxxxx/public/basic.ics",
						color: "#00ffd4"
					},
				]
			}
		},

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
