### ISSUE TITLE
french no upper characters for date

### ISSUE THREAD

**Issue by mattcasper** [MichMich/MagicMirror#1584]
hello
when the mirror is switched to french we lose all uppercase character for the date .
is there a way to change that?

![capture d ecran 2019-02-21 a 9 37 11 pm](https://user-images.githubusercontent.com/47028081/53200272-6fdbb080-3621-11e9-82b6-74f2580e6e04.png)

also,  probably noob question but i scouted the internet without finding an answer
how to remove the FR at the end of the location and how to make all the "e" and "é" look the same
![capture d ecran 2019-02-21 a 9 36 44 pm](https://user-images.githubusercontent.com/47028081/53200573-2770c280-3622-11e9-9176-9c6e00b3d288.png)

thanks you very much for all the good work and infos you're sharing here
best regards

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
