### ISSUE TITLE
Question on node_helper

### ISSUE THREAD

**Issue by jacob-ebey** [MichMich/MagicMirror#1585]
Is there currently a way to broadcast a message from a node_helper to all client modules?

I expected to be able to do something similar to:

modules/default/weatherforecast.js
```js
...
notificationRecieved(notifiction) {
    console.log(notification); // Should log "NOTIFICATION_FROM_EXTERNAL_HELPER"
}
...
```

anothermodule/node_helper.js
```js
...
start: function () {
    this.sendNotification("NOTIFICATION_FROM_EXTERNAL_HELPER");
}
...
```
The reasoning for this is to move the auto location code that I contributed a while ago to a single module that contains JUST a node_helper, and share the information between any number of modules that may be able to make use of it.

Any thoughts on how to accomplish this in the current codebase?

**Comment by MichMich** [comment]
There is one node helper per module type. So if you use one module twice in your config, one node_helper will be started. If you want to broadcast a message to all other modules, this should be done via the "frontend part" of the module. 

Also, please ask these kind of questions on the forum. I'd like to use the GitHub issues for code bug reports only.

Thanks!
