### ISSUE TITLE
ELECTRON window starts on top of MM window after clean install!

### ISSUE THREAD

**Issue by Gryglas** [MichMich/MagicMirror#1593]
Hi.
Firstly, thanks for awesome programming!

Now, I have followed this tutorial EXACTLY:
https://howchoo.com/g/ntcymzbimjv/how-to-install-magic-mirror-on-your-raspberry-pi exactly.

And **at step 8** (see my screenshot) after the reboot a stupid blank black "electron" window shows up on top of my MagicMirror window. So I have to go on to my pi gui and minimize it.
If I try to close it another new "Electron window" pops up on top.
:(

I'm using the Raspberry Pi 3 B+.

How can I get rid of the "electron window"???

Kindest regards, Håkan

<img width="710" alt="skarmavbild 2019-02-27 kl 23 06 25" src="https://user-images.githubusercontent.com/19389298/53526449-82079400-3ae4-11e9-9ec7-9ca40a282aa1.png">

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
