### ISSUE TITLE
No autostart of MagicMirror²

### ISSUE THREAD

**Issue by Tom-Hirschberger** [MichMich/MagicMirror#1596]
After a fresh installation of Raspbian Strech i had problems with the autostart of MagicMirror².
The Problem seems to be that the script /etc/systemd/system/pm2-root.service starts in the root environment.
I changed the lines:
USER=root to USER=pi
Environment=PM2_HOME=/root/.pm2 to Environment=PM2_HOME=/home/pi/.pm2
PIDFile=/root/.pm2/pm2.pid to PIDFile=/home/pi/.pm2/pm2.pid

Now everything works as expected.
I'm not sure if it is an Raspbian, PM2 or an MagicMirror² Issue

Edit: "sudo pm2 startup systemd -u pi" generates the /etc/systemd/system/pm2-pi.service file but with the Environment and PIDFile set to the root directory

**Comment by websterjazz** [comment]
To setup the Startup Script, copy/paste the following command:
`sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u pi --hp /home/pi`

**Comment by sdetweil** [comment]
or use my script which does all the work 
see  fixuppm2.sh  (last entry on the page here)

https://github.com/sdetweil/MagicMirror_scripts

**Comment by Tom-Hirschberger** [comment]
Hi,

did not have these issue in my last installations. I already use your the scripts of you @sdetweil.
That's why I closed the ticket two years ago.
