### ISSUE TITLE
Wifi issue display on the magic mirror

### ISSUE THREAD

**Issue by mcnahum** [MichMich/MagicMirror#1601]
Hello,
I'm using a Pi3 and as multiple other users I've Wifi issue. Sometimes, with no reason the wifi drop. but here I've no questions for troubleshooting the issue, it's not the place... but it will be good if natively the magicmirror have a way to tell me that the wifi is down... today I notice it as my RSS is not getting updated and it's always the same news...

What do you think?

**Comment by MichMich** [comment]
https://github.com/PoOwAa/MMM-network-signal :)

**Comment by mcnahum** [comment]
Perfect!
