### ISSUE TITLE
icon order

### ISSUE THREAD

**Issue by apm1007** [MichMich/MagicMirror#1603]
Hi there, testet out the new weather module.
![grafik](https://user-images.githubusercontent.com/11927080/54443496-02fb9800-4741-11e9-8b9d-cbc3f8f69475.png)
Is it possible to get feel like under current weather? Thx. e.g. with an icon?

Rain ammount doesnt work.

thx for your great work!

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
