### ISSUE TITLE
Special characters won't appear correctly on newsfeed module

### ISSUE THREAD

**Issue by radokristof** [MichMich/MagicMirror#1605]
**Platform**: Raspberry Pi 3B with Raspbian Stretch (Full version, not Lite)

**Node Version**: 10.15.3

**MagicMirror Version**: 2.6.0

**Description**: Special characters won't appear correctly in newsfeed module (ő, ű). All other standard and even non-standard (á, é, ú, etc..) characters are viewed in the normal Roboto font. Also other modules show these characters correctly (for example the default Calendar module).

**Steps to Reproduce**: Setup the newsfeed module and configure an RSS channel which uses these characters in their RSS feeds (eg.: hungarian news).

**Expected Results**: View these characters in the same font (Roboto).
An example photo that it is working in the Calendar module:
![calendar](https://user-images.githubusercontent.com/36210568/54498787-9f719600-490b-11e9-80c4-304534cd47ac.jpg)

**Actual Results**: The characters appear in the newsfeed module like this:

![newsfeed](https://user-images.githubusercontent.com/36210568/54498784-984a8800-490b-11e9-941a-a317396458ce.jpg)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
