### ISSUE TITLE
Default calendar module stopped showing iCloud events

### ISSUE THREAD

**Issue by HaViGit** [MichMich/MagicMirror#1606]
After working correct (Raspberry Pi 3B) for several months the calendar module stopped displaying events from my iCloud calendar a few days ago and shows no events. There are many events within my iCloud calender and they are still visable on https://www.icloud.com/#calendar. The public webcal URL in config.js is unchanged and matches with iCloud public URL generated online by Apple. Newsfeeds and weather forecast works fine so I can exclude network issues. Please see my calendar config below. Are there issues with the module or iCloud? Any suggestions to solve this?

                {
                        module: "calendar",
                        header: "Agenda",
                        position: "top_left",
                        config: {
                                fade: false,
                                maximumEntries: 7,
                                displaySymbol: false,
                                calendars: [
                                        {
                                                symbol: "calendar-check-o ",
                                                url: "webcal://p01-calendarws.icloud.com/ca/subscribe/1/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                                       }
                                ]
                        }
                },

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
