### ISSUE TITLE
Never ending dependency problems

### ISSUE THREAD

**Issue by lastrastuff** [MichMich/MagicMirror#161]
I keep getting to the end of the install process and it is telling me `/home/pi/MagicMirror/node_modules/electron-prebuilt/dist/electron: error while l                                             oading shared libraries: libnotify.so.4: cannot open shared object file: No such                                              file or directory` but the library changes every time I install the proper one. Am I missing a package or do I just need to get through all of these one by one?
[debug.txt](https://github.com/MichMich/MagicMirror/files/214281/debug.txt) Here is my debug file as well.

**Comment by MichMich** [comment]
Thanks for your report!

Would you mind testing the [electron-quick-start](https://github.com/electron/electron-quick-start) to see if that one works?

**Comment by lastrastuff** [comment]
Same error, unfortunately.

```
/home/pi/electron-quick-start/node_modules/electron-prebuilt/dist/electron error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

npm ERR! Linux 4.1.19+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-quick-start@1.0.0 start: `electron main.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
npm ERR! This is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/electron-quick-start/npm-debug.log
```

**Comment by MichMich** [comment]
I notice you are running a very old version of Node. (v0.12.6). Try upgrading to 5.10.1.

**Comment by lastrastuff** [comment]
I successfully upgraded but now I am running into this issue. I don't even particularly know where to start with this, thanks for your help nevertheless!

```
We're ready! Run [DISPLAY=:0 npm start] from the MagicMirror directory.
pi@raspberrypi:~ $ DISPLAY=:0 npm start
npm ERR! Linux 4.1.19+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
```

**Comment by MichMich** [comment]
You are not in your MagicMirror folder. 
Try:

    cd ~/MagicMirror
    npm start

**Comment by lastrastuff** [comment]
You're right! Sorry, I made that mistake earlier and posted the wrong copy. Here is what happens once I am correctly inside the directory

```
> magicmirror@2.0.0 start /home/pi/MagicMirror
> electron js/electron.js

/home/pi/MagicMirror/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

npm ERR! Linux 4.1.19+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! magicmirror@2.0.0 start: `electron js/electron.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the magicmirror@2.0.0 start script 'electron js/electron.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the magicmirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron js/electron.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs magicmirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls magicmirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/npm-debug.log

```

**Comment by moinahmed001** [comment]
I have this same issue as the output above!

**Comment by bbreton3** [comment]
Hello, I have the same issue as above, I run node v6.4.0, have any of you guys found a way to solve the issue?

**Comment by JtheB** [comment]
It looks like electron is not correctly installed, if I'm not wrong.
Maybe you could try _npm install_ again.

**Comment by SimJim** [comment]
Same here...
tryed to _npm install_ again....still the same issue

**Comment by MichMich** [comment]
@SimJim what version of Node are you running?

**Comment by SimJim** [comment]
![error](https://cloud.githubusercontent.com/assets/19064678/18677801/530ca002-7f5a-11e6-84ad-0351918db0c7.JPG)

**Comment by MichMich** [comment]
Could you give this repository a try to see if it works for you?
https://github.com/electron/electron-quick-start

**Comment by SimJim** [comment]
i just tried...same error-message :/

**Comment by MichMich** [comment]
Then I suggest to open an issue in that repository. It seems there is a problem with Electron.

**Comment by hkapanen** [comment]
See here: https://github.com/electron/electron/issues/2472

> The only way is to make your app automatically run after the user has login, which is also how all other GUI applications do.

So I made the raspi to do desktop autologin at boot time and it fixed it for me.

**Comment by BoxSo** [comment]
I ran into the same problem. Fresh install on rpi3 on latest raspbian. Is there any workaround available?

**Comment by Jopyth** [comment]
In the meanwhile you could try using an older [version](https://github.com/electron/electron/releases) of electron, which does not have this bug? I.e. `npm install electron@1.3.1`.

**Comment by matteos1** [comment]
here same error on electron
