### ISSUE TITLE
Magic Mirror npm ERR!

### ISSUE THREAD

**Issue by mrkus21** [MichMich/MagicMirror#1612]
Anyone can help me, I'm really new to this...

Cant start Magic Mirror with the following output...
pi@raspberrypi:~ $ sudo npm start
(node:899) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.98-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! path /home/pi/package.json
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
pi@raspberrypi:~ $ 

Log says: 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v8.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart magicmirror@2.6.0
6 info start magicmirror@2.6.0
7 verbose unsafe-perm in lifecycle true
8 info magicmirror@2.6.0 Failed to exec start script
9 error magicmirror@2.6.0 start: `sh run-start.sh`
9 error Exit status 127
10 error Failed at the magicmirror@2.6.0 start script.
10 error This is most likely a problem with the magicmirror package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     sh run-start.sh
10 error You can get their info via:
10 error     npm owner ls magicmirror
10 error There is likely additional logging output above.
11 error System Linux 4.14.98-v7+
12 error command "/usr/bin/node" "/usr/bin/npm" "start"
13 error cwd /home/pi/MagicMirror

My first Try on Raspberry so Im a Newbee...
Please Help. Thanks.

**Comment by MichMich** [comment]
You should run nstart from within your MagicMirror² folder.

Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
