### ISSUE TITLE
when i want to add a iFrame, my config file doesent work anymore

### ISSUE THREAD

**Issue by JeroenV99** [MichMich/MagicMirror#1614]
![image](https://user-images.githubusercontent.com/35964877/54640844-01a7d380-4a91-11e9-8845-f27d8e91086b.png)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
