### ISSUE TITLE
Missing info to get into it

### ISSUE THREAD

**Issue by flobee** [MichMich/MagicMirror#1616]
Hi, the readme doesnt help me to get into it. tutorials or any docs to "why should i install it" needed!

I came around (from some press news) to check how to build the mirrow hardware or maybe more "smart" stuff but i just get software instalation informations... hmm. 

Thx! :)

**Comment by lavolp3** [comment]
This is a software repo.  It's just not the place to discuss the building of a mirror although there are recommendations for the glass. I'd suggest to visit the forum http://forum.magicmirror.builders for more information of that kind. The readme page here is quite comprehensible as it is.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
