### ISSUE TITLE
Display time in calendar

### ISSUE THREAD

**Issue by djsunrise19** [MichMich/MagicMirror#162]
Hi,

actually I test the new MagicMirror² a little bit and I've seen some differences between the old and the new version in the calendar functions (time). The old version has more functionality in my opinion. For example:

old version: ManCity - PSG **in 2 hours** 
same moment on the new version: ManCity - PSG **Today**

There are a few more examples with **since 2 hours** etc. Will you implement those features in future?

Regards
Maurice

**Comment by MichMich** [comment]
I'll probably add this in the future. Feel free to send a pull request.

**Comment by djsunrise19** [comment]
It's the same like #166 . I tested it: Those entry's aren't whole day events and it shows no exact time.

**Comment by MichMich** [comment]
Thanks for reporting ... I put it on the todo list.

**Comment by MichMich** [comment]
Could you supply a test feed?

**Comment by djsunrise19** [comment]
I have a nice example:

Right now on my MM² Raspi:
![dates](https://cloud.githubusercontent.com/assets/14234570/14558920/a0820e52-0305-11e6-91ea-0d2dd9b7fc90.jpg)

Right now on my MM1 Raspi:
![datesold](https://cloud.githubusercontent.com/assets/14234570/14558940/cf53d616-0305-11e6-91d6-ace202adf9a9.jpg)

The first event is over since 4 hours (on MM1 everything is correct). Actually I think MM² thinks all events are whole day events.

**Comment by MichMich** [comment]
Yes, I understand the issue. Do you have a test .ics feed which gives you this issue?

**Comment by djsunrise19** [comment]
Yes. I made a new open feed in my icloud with a couple of events:

webcal://p35-calendars.icloud.com/published/2/qsud2R2XlRhT3puEVfrzkeSd3X_QSfCMBmpgTsjVqOD2W_fyy0Y-5QskbvWw2jOQB_cPsmcjpGtcg1a3jBQ_QIS2H0XWSxjqCa8LX0dznpE

**Comment by MichMich** [comment]
Thanks, I will look into it.

**Comment by MichMich** [comment]
I've just pushed an update. Could you give it a try?

**Comment by djsunrise19** [comment]
Looks a little bit better, but now event "Test 1" isn't there anymore. But Test 1 is from 12 to 15 o clock. So it has already begun.

**Comment by MichMich** [comment]
Exactly. It is in the past, so it is filtered out.

**Comment by MichMich** [comment]
It only shows future events.

**Comment by djsunrise19** [comment]
Yes, thats clear. But on MM1 it was possible to see how long the event goes. Do you understand what I mean?

**Comment by MichMich** [comment]
So it showed the event while it was still going ... ?

**Comment by djsunrise19** [comment]
Example: Test 1 12-15 o' clock. We have 13 o'clock. So MM1 says: 2 hours left

**Comment by MichMich** [comment]
Hmm, ok ... let met look at it.

**Comment by MichMich** [comment]
Did you remove Test 1 from your feed?

**Comment by djsunrise19** [comment]
No, I don't.

![test1](https://cloud.githubusercontent.com/assets/14234570/14559604/3a4c2a32-030a-11e6-97e5-65fceea2bcc0.jpg)

**Comment by MichMich** [comment]
Ok ... let me check.

**Comment by MichMich** [comment]
Ok, give it an other try. 

Make sure you set the `runningText` text property in your config to the german string. (The default is: `ends in`). So it needs to be something like: `endet am`

**Comment by djsunrise19** [comment]
Thanks! Still no Test 1 event.

**Comment by MichMich** [comment]
Are you sure you restarted the backend?
![screen shot 2016-04-15 at 13 21 11](https://cloud.githubusercontent.com/assets/210954/14559997/fa65ba3e-030c-11e6-8f98-f95015ebe632.png)

**Comment by djsunrise19** [comment]
Yes, but I'll make a `shutdown -r 0` now.

**Comment by djsunrise19** [comment]
Ah, great Michael, looks good now!

PS: In this case, in german we say `noch` :)

**Comment by MichMich** [comment]
Ah, just like "Nog" in dutch! ;)

Can I close this issue?

**Comment by djsunrise19** [comment]
Yes, you can :).

**Comment by djsunrise19** [comment]
Hi Michael,

I've seen another constellation. As you can see, MM1 says: "Tomorrow at ***" and MM² "in 19 hours". Perhaps it's possible to use the whole event/time function from MM1 for MM²

MM²:
![tomorrowneu](https://cloud.githubusercontent.com/assets/14234570/14568110/bcb39c08-0337-11e6-816c-4febe6642e73.jpg)

MM1:
![tomorrowalt](https://cloud.githubusercontent.com/assets/14234570/14568125/c16ee554-0337-11e6-8618-c1356a24ba7c.jpg)

Here is a test-feed for you:
webcal://p35-calendars.icloud.com/published/2/Biw06VYAVT31nDd3JqdQkTjbAzFrzU2zZjtbhH40WZ-frGU2hWaZDyG3nXBZUgk7rvBJ0x6T-SdsFyDkzkYbVP4Onr4Eb1_4BptAPzWALA4

Thanks,
Maurice

**Comment by djsunrise19** [comment]
Did you see that or should I open a new issue?

**Comment by MichMich** [comment]
All get back to this asap.

**Comment by MichMich** [comment]
This is fixed. If a event is within 48 hours, it shows the absolute time. 
Note: This does not happen for fullday events.

I close the issue for now, if you still like some changes, feel free to let me know.

**Comment by djsunrise19** [comment]
I hope it's okay that I use this "issue" again:

Today I've seen another behavior. I had an event at 16 o'clock. I looked on the mirrors at 15 o'clock:
MM1: in 1 hour
MM²: today at 16 o'clock
Is it possible to put this absolute time function in your MM² app?

Another point is, that there might be another issue. On 22.04 I had a whole day event (birthday). But today I can see this event on the MM² calendar (he says that the event is tomorrow?! I checked my event in icloud, everything is fine.

I made a feed for you:
webcal://p35-calendars.icloud.com/published/2/0gmYv_8AnTjRjR2SWtoyc7_eCWfFKOEj-ZVz7-eJ0elAZ4SDdsiCZVslxdjR-NxRhcM6N4hwTKuay0bpJSR7a9THwnMmyHEzyYFB4cpSxlA

**Comment by MichMich** [comment]
`today at 16 o'clock` is an 'absolute time'. Or do you prefer a relative time?

**Comment by djsunrise19** [comment]
I don't know how you solve that in MM1. A few hours before the event starts MM1 says not `today at *****` anymore but `in 3 hours` or `in 23 minutes`. I hope you understand what i mean.

BTW: Did you change anything in the calendar module? `runningText: 'noch'` doesn't work anymore. In german I see `Endet in` (like ends in).

**Comment by MichMich** [comment]
Yes, but that's a personal preference. We could make it configurable. I suggest you open a separate issue for that, I'll mark it as "enhancement" and might add the feature when I have time. (Could take a while).

Also, I checked your example feed. Which event is incorrect?

About the translation: that's correct. We implemented a translation system. The strings are now translated in the language files (only the calendar for now.) See: https://github.com/MichMich/MagicMirror/issues/191

**Comment by djsunrise19** [comment]
Okay I'll do that. For me, your solution in MM1 was great. 

Event "Test 8" is incorrect. It's a whole day event yesterday.

I understand. So you should update the wiki, if it doesn't work anymore :).

**Comment by MichMich** [comment]
Please send a pull request to fix both the documentation and the translation if you can.

**Comment by djsunrise19** [comment]
First I made an new issue for the "personal" feature. What should I do next? Create one pull request for the whole day issue and another pull request for the language problem?

**Comment by MichMich** [comment]
I'll look into the incorrect Test 8 date. If you could create a pull request for the language issues, that would be awesome.

**Comment by djsunrise19** [comment]
I've never done a pull request, I can try ;).

**Comment by MichMich** [comment]
Looking forward to it! :)

**Comment by MichMich** [comment]
Your Test 8 issue is fixed. Please update and restart :)

**Comment by djsunrise19** [comment]
Thanks, I'll check that. 

Do you see my pull request?

**Comment by MichMich** [comment]
Nope :(

**Comment by djsunrise19** [comment]
Sorry, it's the first time. I forked the project, edit the file and made the request:

![pull](https://cloud.githubusercontent.com/assets/14234570/14762458/f87ca57e-097a-11e6-9203-46ff085778eb.jpg)

**Comment by MichMich** [comment]
You are probably trying to merge an update from MM to your fork. It should be the other way around. If you go to the MM repo (not your fork), You'll see a green Pull Request button.

**Comment by djsunrise19** [comment]
No I've done shit.

**Comment by Robiv8** [comment]
@djsunrise19 
Ich kann dir etwas Helfen, Wenn du MM geforkt hast mußt du die Änderungen mit deinem GitHub Account machen.
Sieht bei mir so aus: Robiv8/MagicMirror dann erscheint auch der Grüne button §New pull request"

**Comment by djsunrise19** [comment]
@Robiv8 
Danke dir! Ich hab's schon gefunden und Michael hat's auch schon gemerged :).

**Comment by CommanderB** [comment]
In this theme I would like to suppress the exact time - its good enough to know the day it happens. So as an enhancement suggestion I created a new config variable, defaulting to true, but false for my need

`displayTime: false,`

then added the conditional in the building loop - I'm sure the conditional logic could be improved, but this works for me.

```javascript
			if (this.config.displayTime){
				if (event.fullDayEvent) {
					if (event.today) {
						timeWrapper.innerHTML = this.translate("TODAY");
					} else if (event.startDate - now < 24 * 60 * 60 * 1000 && event.startDate - now > 0) {
						timeWrapper.innerHTML = this.translate("TOMORROW");
					} else {
						timeWrapper.innerHTML =  moment(event.startDate,"x").fromNow();
					}
				} else {
					if (event.startDate >= new Date()) {
						if (event.startDate - now > 48 * 60 * 60 * 1000) {
							// if the event is no longer than 2 days away, display the absolute time.
							timeWrapper.innerHTML = moment(event.startDate,"x").fromNow();
						} else {
							timeWrapper.innerHTML = moment(event.startDate,"x").calendar();
						}
					} else {
						timeWrapper.innerHTML =  this.translate("RUNNING") + ' ' + moment(event.endDate,"x").fromNow(true);
					}
			}} else {
				if (event.today) {
					timeWrapper.innerHTML = this.translate("TODAY");
				} else if (event.startDate - now < 24 * 60 * 60 * 1000 && event.startDate - now > 0) {
					timeWrapper.innerHTML = this.translate("TOMORROW");
				} else {
					timeWrapper.innerHTML =  moment(event.startDate,"x").fromNow();
				}};

**Comment by KirAsh4** [comment]
CommanderB: I would recommend starting a new post, as opposed to tagging along on this one as it's a different issue.

**Comment by KirAsh4** [comment]
Hey @MichMich, you can probably close this issue now as the request from the original OP has been released. And what @CommanderB has requested above is a different issue all together.

**Comment by MichMich** [comment]
Great, thanks.
