### ISSUE TITLE
2.7.0 tag with some develop text

### ISSUE THREAD

**Issue by vincep5** [MichMich/MagicMirror#1630]
package.json and package-lock.json for the master branch in the 2.7.0 tag, says 2.8.0-develop

It should say 2.7.0.  When I was upgrading my mirrors, the output of some lines in the command window was saying 2.8.0-develop

**Comment by MichMich** [comment]
Thanks for reporting. Will push a fix tomorrow!

**Comment by MichMich** [comment]
Fixed: https://github.com/MichMich/MagicMirror/tree/v2.7.1
