### ISSUE TITLE
[Improvement] Calender excludedEvents per calendar instead of global

### ISSUE THREAD

**Issue by jorgh6** [MichMich/MagicMirror#1639]
Currently the excludedEvents is a global configuration. I would like the excludedEvents to be configurable per calendar, this would allow for instance to generate custom icons, depending on a regex filter.
For example, using one calendar configured to use a regex to exclude birthdays for calendar events using the standard icon, and another instance of the same source with the inverse regex to use the birthday-cake icon.
In general, it would allow to use different calendar configuration options within a single calendar source, like symbol, color and counts.

**Comment by MichMich** [comment]
A change like this is not on the roadmap. Feel free to send a non breaking PR.
