### ISSUE TITLE
undefinded in header since update

### ISSUE THREAD

**Issue by apm1007** [MichMich/MagicMirror#1640]
Where is this undefined coming from? Seem to be there since the last update
![grafik](https://user-images.githubusercontent.com/11927080/55666974-74b59600-5856-11e9-872e-577c3f3d7784.png)

**Comment by pvyParts** [comment]
![image](https://user-images.githubusercontent.com/861417/55669096-f97bd080-58a5-11e9-843c-53569ca6d59f.png)
i added this line to my config and it removed it.
`appendLocationNameToHeader: false,`

**Comment by apm1007** [comment]
Tried it. Isnt working for me.

Gesendet von Mail für Windows 10

Von: Aaron
Gesendet: Samstag, 6. April 2019 13:56
An: MichMich/MagicMirror
Cc: Ap Mielke; Author
Betreff: Re: [MichMich/MagicMirror] undefinded in header since update (#1640)


i added this line to my config and it removed it.
appendLocationNameToHeader: false,

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by victor-paumier** [comment]
Sorry to re-open this issue but I agree that there is a problem with the header.

I am not a JS expert but what I see is that as the weatherforecast do not define any header value, the value of `this.data.header` from [l.211](https://github.com/MichMich/MagicMirror/blob/447c0bffdcd2667c2d982cd2a1e5a7d43e45f112/modules/default/weatherforecast/weatherforecast.js#L211) of `weatherforecast.js` is equal to `undefined` and is concat to the `fetchedLocationName`.
To solve that, either add `header: '',` on the module definition of weatherforecast in the `config.js` file, remove `this.data.header` from this line or define a default empty value of `header` in `weatherforecast.js` (or even directly in `js/loader.js` to avoid the problem in other modules).

Anyway, this project is really great and thank you very much for that!!
