### ISSUE TITLE
clientonly issues

### ISSUE THREAD

**Issue by bachoo786** [MichMich/MagicMirror#1641]
hi so everything is working fine and I can access magicmirror if I go to the web browser of my raspberry pi hit the address of the server running magic mirror.

However when I try to run it from terminal with this command i.e. pi@raspberrypi:~ $ node clientonly --address 192.168.0.27 --port 82 I get the following error:

module.js:549
    throw err;
    ^

Error: Cannot find module '/home/pi/clientonly'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

can you please help?

thanks.

**Comment by bastilimbach** [comment]
Answered in: https://github.com/bastilimbach/docker-MagicMirror/issues/20#issuecomment-480507590

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
