### ISSUE TITLE
Compliments integration with python

### ISSUE THREAD

**Issue by omaralomar** [MichMich/MagicMirror#1643]
Hi 

im using node_helper.js to communicate between compliments module and my python program which is "Emotion_Recognition"

it only sends a string throw node helper and socketNotificationReceived to compliments.js 
The problem is when i receive the string and try to make a condition with it 
it tells me it's false always 
which is not a string !! soo Weird 

i tried with numbers too also it didnt work 
i cant make the condition work 

im using spawn for python and node helper 
and converting object(ArrayBuffer) to string using this line of code : 
      var result = String.fromCharCode.apply(null, new Uint8Array((data)))

      console.log(typeof result) // this one String shows 
      this.sendSocketNotification("I_DID", result)

Please Help

**Comment by omaralomar** [comment]
My goal is Creating "Emotion_Recognition" Module to show a "Quote " depending on the mood the face .

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
