### ISSUE TITLE
Tried To Do Some Commands via the wiki and now my entire system is blank?

### ISSUE THREAD

**Issue by dxfan227** [MichMich/MagicMirror#1645]
I was trying to follow the commands in the configuration wiki for hiding the pointer, disabling wifi power mode etc..etc..

and all of a sudden now when I reboot its just a blank screen.....when I right click I'm in something called open box. I can't get back to my desktop. I'd really rather not have to restart EVERYTHING from scratch is there any help someone out there could provide

**Comment by dxfan227** [comment]
fixed! I somehow removed everything from the autostart file when adding the in uncluttered command.

**Comment by sdetweil** [comment]
can u close this issue

**Comment by dxfan227** [comment]
yes, how do I do it? I'm new
