### ISSUE TITLE
Unable to set time zone on individual calendars.

### ISSUE THREAD

**Issue by citadella** [MichMich/MagicMirror#1648]
I have multiple calendars I want to include, some of which are on my local time zone, others of which are on a different one. MM only reads the date/time off the calendar, so if I have a calendar on EST but I am in PST, all my events appear 3 hours off. Ideally I'd like MM to presume all calendars are in the local time zone of the box hosting the mirror, but then add either a time zone offset setting or a setting for the time zone specifically at the calendar level.

**Comment by MichMich** [comment]
This is currently not supported. Feel free to send a PR.
