### ISSUE TITLE
I can't update

### ISSUE THREAD

**Issue by jasb1011** [MichMich/MagicMirror#1649]
hello Every time I try to update my Magic Mirror I am hit with this error:

Updating de57daa..b508a62
error: Your local changes to the following files would be overwritten by merge:
	modules/default/calendar/calendar.js
	package-lock.json
	package.json
Please commit your changes or stash them before you merge.
Aborting
I would be incredibly grateful if you could help me.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
