### ISSUE TITLE
officeholidays not working

### ISSUE THREAD

**Issue by szuniverse** [MichMich/MagicMirror#1650]
I would like to use this https://www.officeholidays.com/ics/ics_region_iso.php?region_iso=ZH&tbl_country=Switzerland calendar, but its not working. Would be good to support this format as well.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by szuniverse** [comment]
I thnk the most popular site for ics calendars is the OfficeHolidays.com. And unfortunately the calendar  plugin is not able to handle their format, so i think you should reopen this Issue, it could fix many other case not just OfficeHolidays.com
