### ISSUE TITLE
sliceMultiDayEvents isn't respecting maximumNumberOfDays

### ISSUE THREAD

**Issue by michaelarnauts** [MichMich/MagicMirror#1651]
**Platform**: Docker server only.

**Node Version**: v11.13

**MagicMirror Version**: latest develop branch

**Description**: 
When using `sliceMultiDayEvents`, the splitted dates aren't respecting the `maximumNumberOfDays` setting.
![image](https://user-images.githubusercontent.com/1193779/55831658-f1c16380-5b13-11e9-940e-e41d544ee69a.png)

**Steps to Reproduce**: List the step by step process to reproduce the issue.
Use config like below.

**Expected Results**: 
Only the next 3 days should be shown.

**Actual Results**: 
See screenshot

**Configuration**: 
```
        {
            module: 'calendar',
            position: 'bottom_left',
            config: {
                maximumNumberOfDays: 3,
                fade: false,
                getRelative: 0,
                broadcastEvents: false,
                sliceMultiDayEvents: true,
		showEnd: false,
                calendars: [
                    {
                        name: 'Michaël',
                        symbol: ['male'],
                        url: '...',
                    }
                ]
            },
        },
```

**Comment by MichMich** [comment]
Fix merged.
