### ISSUE TITLE
after updating 2.7.1 Magic mirror not loading. raspberry Pi 3 b+

### ISSUE THREAD

**Issue by eddy2969** [MichMich/MagicMirror#1656]
Please only submit reproducible issues. 

If you're not sure if it's a real bug or if it's just you, please open a topic on the forum: [https://forum.magicmirror.builders/category/15/bug-hunt](https://forum.magicmirror.builders/category/15/bug-hunt)
Problems installing or configuring your MagicMirror? Check out: [https://forum.magicmirror.builders/category/10/troubleshooting](https://forum.magicmirror.builders/category/10/troubleshooting)

When submitting a new issue, please supply the following information:

**Platform**: Place your platform here... give us your web browser/Electron version *and* your hardware (Raspberry Pi 2/3, Windows, Mac, Linux, System V UNIX).

**Node Version**: Make sure it's version 0.12.13 or later.

**MagicMirror Version**: Now that the versions have split, tell us if you are using the PHP version (v1) or the newer JavaScript version (v2).

**Description**: Provide a detailed description about the issue and include specific details to help us understand the problem. Adding screenshots will help describing the problem.

**Steps to Reproduce**: List the step by step process to reproduce the issue.

**Expected Results**: Describe what you expected to see.

**Actual Results**: Describe what you actually saw.

**Configuration**: What does the used config.js file look like? Don't forget to remove any sensitive information!

**Additional Notes**: Provide any other relevant notes not previously mentioned. This is optional.

**Comment by eddy2969** [comment]
after updating 2.7.1 Magic mirror not loading. raspberry Pi 3 b+ just now
![Annotation 2019-04-14 101753](https://user-images.githubusercontent.com/48259440/56090797-ec12a780-5e9e-11e9-8e1a-1923571c1527.png)

**Comment by sdetweil** [comment]
agter installing the update with npm pull, you must run npm install, 
and also run npm install in any module folder that has a package.json file. 

some modules may need extra attention... snowboy is certainly one of them

do 
in the MMM-Hotword folder
```
npm install electron-rebuild
```
then run it
```
./node_modules/.bin/electron-rebuild
```

**Comment by eddy2969** [comment]
Please.. can someone help how to fix this 
![Annotation 2019-04-15 195030](https://user-images.githubusercontent.com/48259440/56157591-ca591380-5fb7-11e9-8094-93de0ff12858.png)

**Comment by sdetweil** [comment]
those are just advisory, not blocking you...

**Comment by eddy2969** [comment]
thanks for reply!  I installed magicmirror it work fine then module hotword  evething stop working it came just a black screen  what should I do?

**Comment by sdetweil** [comment]
npm start dev
in the developers window, select the console tab, and scroll up for errors (red text)..

did u work thru the MMM-Hotword install 'in case of errors'...

**Comment by eddy2969** [comment]
Thank you very much. I really appreciate  for your help I will  start all over again will let you know I need your brain for this I'm very new. Thank you!

**Comment by kumarsatish23** [comment]
Even I faced the same issue after updating mm2 just you have to re install Hotword module again follow instruction provided in https://github.com/eouia/MMM-Hotword.
In my case 
`cd ~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
npm install --save-dev electron-rebuild
npm install nan
./node_modules/.bin/electron-rebuild `
these command worked for me.

**Comment by MichMich** [comment]
Disable all non default modules. Most of the time those are the reason.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
