### ISSUE TITLE
Default calendar isn't updating

### ISSUE THREAD

**Issue by DERPNYS** [MichMich/MagicMirror#1658]
Hi. I found out that my Magic Mirror calendar (I'm the using the default one) doesn't update events anymore. It just shows me the ones I had yesterday but none of the ones that I add to my google calendar today.
The only difference between yesterday and today is that I've been installing and uninstalling modules (basically MMM-Background and some similar) but I'm pretty sure that doesn't affect to the calendar. (git clone xxx, npm install)

What can I do? Has someone ever experienced this?

**Comment by MichMich** [comment]
See https://github.com/MichMich/MagicMirror/issues/1631
