### ISSUE TITLE
Enable auto play for videos

### ISSUE THREAD

**Issue by Stant0n** [MichMich/MagicMirror#1663]
I understand that Chromium has defaulted to stop videos from auto playing. This seems to have been propagated to Electron. Is there a method to turn auto play on?

**Comment by sdetweil** [comment]
yes, edit MagicMirror/js/electron.js
add the line shown below..
```
let mainWindow;

function createWindow() {
    app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');  //< -------- added
```
save
then restart  MagicMirror

**Comment by Stant0n** [comment]
Thank You!  I was searching for that for a couple of days.
