### ISSUE TITLE
How to disable the "blinking" button LED when google assistant is listening?

### ISSUE THREAD

**Issue by therushery** [MichMich/MagicMirror#1670]
Hi, I have the Google voice kit V1 running it from a raspberry pi 3+ with the latest image installed. This is part of my Magic Mirror build. I have the goggle assistant library demo set up to auto start from boot. I have wired up a LED light strip instead of the button LED. Does anyone know how to disable the LED blinking every few seconds? I still want the light to come on when triggered. I have poked around in the leds.py and the board.py codes but with no luck. Thanks

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
