### ISSUE TITLE
Deprecation of this.path?

### ISSUE THREAD

**Issue by ferferga** [MichMich/MagicMirror#1671]
Good morning. I'm trying to build my own module. I want to reference to an image path inside the ``getDom`` function, so I need to concatenate the module's path to point correctly to my image. I've been reading the documentation [here](https://github.com/MichMich/MagicMirror/tree/master/modules#thispath) and everything seems good on my side: I also looked at some other modules' code and they use the ``they.path`` without any problem and inside any function: However, all I get is an "undefined" if I do ``wrapper.innerHTML = this.path``.

Is ``this.path`` deprecated or am I missing something from the documentation and not using it properly?

**Comment by sdetweil** [comment]
this.path is only available to the node_helper.  and is listed in the node_helper section of the doc
```
Available module instance properties
this.name
String

The name of the module

this.path
String

The path of the module
```

you could send it to the module with a sendSocketNotification so that the module will have it.

another way is to use the this.file() function..  
as documented in the getScripts  method of the module 
```
The getScripts method is called to request any additional scripts that need to be loaded. This method should therefore return an array with strings. 

If you want to return a full path to a file in the module folder, use the this.file('filename.js')   //< --
```

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
