### ISSUE TITLE
npm install fails on fontawesome

### ISSUE THREAD

**Issue by PunkHaz4rd** [MichMich/MagicMirror#1673]
**Platform**: Windows 10

**Node Version**: v8.11.3

**MagicMirror Version**: v2

**Description**: I cloned the repo, typed npm install && npm start, then I get this error:
Error: 401 Unauthorized: @fortawesome/fontawesome-free@https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/fontawesome-free-5.6.3.tgz

**Comment by MichMich** [comment]
Duplicate: https://github.com/MichMich/MagicMirror/issues/1597
