### ISSUE TITLE
Why currentweather module is using lockString?

### ISSUE THREAD

**Issue by eouia** [MichMich/MagicMirror#1684]
It is unable to hide default `currentweather` and `weatherforecast` modules, because those modules are using `.show()` and `.hide()` **with `lockString`** to beautify its' appearance. So other module cannot hide them easily. 
Is there any reason or profit ? I cannot figure out.

**Comment by MichMich** [comment]
A lock string does not prevent an other model from hiding it. It only prevents it from showing. 

Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by eouia** [comment]
You are right. Just using `Othermodule.hide({lockString:"something")` could work. Sorry for bothering you.

**Comment by MichMich** [comment]
No worries! Enjoy developing!
