### ISSUE TITLE
Display emoji

### ISSUE THREAD

**Issue by tisnatch** [MichMich/MagicMirror#1687]
As an example, Google Calendar allows you to display emoji in event titles. The emoji are not imported correctly into the MM interface. Would it be possible to correctly show emoji? 

**Platform**: Electron 5.0.2 / Raspberry Pi 3 B+ / Stretch.

**Node Version**: 10.15.3

**MagicMirror Version**:  JavaScript version (v2).

**Description**: Emoji not being displayed.

**Configuration**: Nothing special; calendar displays correctly except for emoji

**Comment by MichMich** [comment]
Not sure if the Raspberry Pi Desktop environment is able to display emoji's. If so, it might be an encoding issue.

**Comment by tisnatch** [comment]
I'll see if I can solve it by installing different emoji centric fonts in
the OS. Do you know if Electron depends on the OS to render fonts?

**Comment by MichMich** [comment]
I think so. Yes.

**Comment by ASSYANA** [comment]
You can label columns with status indicators like,

**Comment by MichMich** [comment]
Closed due to inactivity.
