### ISSUE TITLE
Proper way to have module loading screen

### ISSUE THREAD

**Issue by isaac2004** [MichMich/MagicMirror#1700]
I have a module that takes time to load and update the dom, so there is a delay. I want to add a loading notification somehow to my mirror so I know the command was submitted. I tried to add a loading div to the dom wrapper, but got nowhere. Does anyone have a good example of this?

**Comment by sdetweil** [comment]
i answered in the forum

but pretty easy
dataready:false,

getDom: function(){
  var wrapper = document.createElement('div')
  if(!dataready){
     var textElement= document.createElement('text')
     textElement.innerHtml="<p>Module Loading, please wait...</p>";
     wrapper.appendChild(textElement)
  }
  else {
     // do whatever now that you have good data
  }
 return wrapper
}

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
