### ISSUE TITLE
magic mirror default calendar

### ISSUE THREAD

**Issue by yomaldyw** [MichMich/MagicMirror#1712]
how to configure magic mirror default calendar in monthly view,

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by yomaldyw** [comment]
![1464670059911-cal2](https://user-images.githubusercontent.com/46584499/60103118-b16d9b00-977c-11e9-9f9a-8d1b7cbf277e.png)
Thank you for your reply, But I'm trying to figure out how to make it look like the one pictured above. Calendar and Event Separately.

**Comment by sdetweil** [comment]
yomaldyw where did u see that layout?  I don't think the default calendar or datetime can do that.
