### ISSUE TITLE
ZabbixAPI

### ISSUE THREAD

**Issue by anisimovevgeniy** [MichMich/MagicMirror#172]
HI,

Can you give an example of a module that works with the API?
I see that the weather module uses API. Unfortunately, I do not have enough knowledge to understand how it works. But I have time. Could you give more information about this module?
I want to use zabbix API.
Thank you.

**Comment by MichMich** [comment]
The full API documentation can be found here:
https://github.com/MichMich/MagicMirror/tree/v2-beta/modules

Check out the modules in the default folder to see how they are used.
