### ISSUE TITLE
Problem with repeating events (birthday)

### ISSUE THREAD

**Issue by k-0** [MichMich/MagicMirror#1725]
I use a Raspberry Pi2b with MM 2.8.0.
My Node-Version is 10.16.0.

I tried different google calendars and have still the same problem.
The calendar tells me, that there are no events. But i created many birthdays (repeating yearly) but i only get shown normal events (without repeating) in the module. 
Same problem with a all-day event. Some hours are ok, but all-day events are not in the calendar.

**Comment by renansiqueira** [comment]
Be sure to take the private link .ics or check if the events are as public.

**Comment by k-0** [comment]
The events are public.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
