### ISSUE TITLE
Unable to Install MagicMirror dependencies - npm error

### ISSUE THREAD

**Issue by quintinjvr** [MichMich/MagicMirror#1728]
**Platform**: Raspberry Pi 3B

**Node Version**: 10.15.2

**MagicMirror Version**: V2

**Description**: For some reason I am not able to  install MagicMirror on my Raspi 3B. This is straight after loading a brand new NOOBS setup (3.1.1.1) and then using the Automatic install url to install npm and MagicMirror. It Installs npm but when installing the MagicMirror depencies I get an error saying 'npm ERR! cb()never called!' followed by 'Unable to install dependencies' . Log file attached.
Strange thing is that I used the same NOOBS installation on a Raspi 2 last Wednesday and it installed MagicMirror without any issues. Did anyone else experience the same issue when trying to install it on Raspi 3B with the lastest Raspbian Buster (June 2019 release)?

**Steps to Reproduce**: See description above

**Expected Results**: Smooth installation of MagicMirror

**Actual Results**: Errors during installation, not able to install dependencies.

**Configuration**: N/A
[2019-07-15T06_14_28_892Z-debug.log](https://github.com/MichMich/MagicMirror/files/3391326/2019-07-15T06_14_28_892Z-debug.log)

**Additional Notes**: I've tried checking for a later version of npm and reinstalling node.Js without any success.

Help would be appreciated. Thanks

Terminal response below:

>npm installation Done!
Cloning MagicMirror ...
Cloning into 'MagicMirror'...
remote: Enumerating objects: 315, done.
remote: Counting objects: 100% (315/315), done.
remote: Compressing objects: 100% (282/282), done.
remote: Total 315 (delta 39), reused 192 (delta 21), pack-reused 0
Receiving objects: 100% (315/315), 655.07 KiB | 412.00 KiB/s, done.
Resolving deltas: 100% (39/39), done.
Cloning MagicMirror Done!
Installing dependencies ...
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8,                                              9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated time-grunt@2.0.0: Deprecated because Grunt is practically un                                             maintained. Move on to something better. This package will continue to work with                                              Grunt v1, but it will not receive any updates.
npm WARN tar write after end
npm WARN tar write after end
npm WARN tar write after end
npm WARN tar write after end
npm WARN tar write after end
npm WARN tar write after end
npm WARN tar write after end
npm WARN tar write after end
npm WARN tar write after end
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-07-15T06_14_28_892Z-debug.log
Unable to install dependencies!

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
