### ISSUE TITLE
Magic Mirror

### ISSUE THREAD

**Issue by 9170895137** [MichMich/MagicMirror#1735]
I'm new to this. I'm in the process of building a magic mirror and I bought a LoveRPi Raspberry Pi 3 B+ 8GB Quick Start Kit with Raspbian Desktop, Raspberry Pi Mini Camera Video Module 5 Megapixels 1080p Sensor OV5647 Webcam for Raspberry Pi Model A/B/B+, Pi 2 and Raspberry Pi 3, 3b+ and 
Raspberry Pi RASPBERRYPI-SENSEHAT Sense HAT with Orientation, Pressure, Humidity and Temperature Sensors. The issues I'm having is loading the software for the magic mirror. I have tried numerous times and everything starts to load but than toward the end is fails to load the last batches of files. I did get the screen to go vertical and I did a software update under preferences and everything is up to date but I still can not get the magic mirror file to work. I could use some serious help. Or do I need to add more software?

**Comment by NamanSharma2703** [comment]
Can you specify your exact problem?? Also is that your number 9170895137? Are u from India?

**Comment by 9170895137** [comment]
no I'm in reno nv

**Comment by 9170895137** [comment]
raspberry.sh | bash how do you get that symbol between sh and bash?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
