### ISSUE TITLE
Video Chat

### ISSUE THREAD

**Issue by 9170895137** [MichMich/MagicMirror#1736]
Is there a module to allow video chat? I have alexa and a alexa spot and was wondering how I can tie them into the magic mirror. I got it finally running but how do I change the layout and add modules?

**Comment by MichMich** [comment]
http://modules.magicmirror.builders

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by 9170895137** [comment]
I found out how to get tot he terminal screen but about 10 seconds later the magic mirror starts back up

**Comment by sdetweil** [comment]
thats what the pm2 software does.. it keeps the mirror running... alt-spacebar, n will minimize the mirror app (just like windows).. so you can do pm2 stop 0 

u need to read the documentation, and go to the forum as Mich has mentioned.

**Comment by 9170895137** [comment]
Im new at this 

Sent from Mail for Windows 10

**Comment by sdetweil** [comment]
we can tell...
go here  https://forum.magicmirror.builders/category/10/troubleshooting
ask questions.. Mykle1 has some great guides for beginners..
