### ISSUE TITLE
the screen shows the time, date and hoildays and wow you look hot and headlines

### ISSUE THREAD

**Issue by 9170895137** [MichMich/MagicMirror#1737]
How can I change these and how do I get to the terminal screen

**Comment by 9170895137** [comment]
how can I change colors

**Comment by NamanSharma2703** [comment]
You have to go to the config file present in the magic mirror repository..

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
