### ISSUE TITLE
missing modules

### ISSUE THREAD

**Issue by 9170895137** [MichMich/MagicMirror#1739]
I installed the magic mirror but noticed when it got to the end of just be asking to have it auto start and disable screen saver it said library and modules missing.

**Comment by MichMich** [comment]
This is the fifth issue you open. As said please use the forum. No support is given via GitHub. Please stop opening issues. Thanks. 

Please refer to http://forum.magicmirror.builders for support and troubleshooting.

**Comment by 9170895137** [comment]
I don’t see the issues when I do a search and as for that forum everything is grouped together. Like troubleshoot 1 topic and a lot of threads

Sent from Mail for Windows 10
