### ISSUE TITLE
Default calendar shows no items when a series is in the calendar

### ISSUE THREAD

**Issue by iceythegreatest** [MichMich/MagicMirror#1750]
Platform: raspberry 3
Nodeversion 10.x
raspbian Buster

i am using MM version 2.8.0 with the default calendar. Because the module is not able to get my caldav directly i download it via curl into a locally file and in the config of the calendar i am just pointing to the local caldav like this:
```
		{
			module: "calendar",
			header: "Chaoskalender",
			position: "top_left",
				config: {
					colored: false,
					coloredSymbolOnly: false,
				calendars: [
						{
					url: "http://127.0.0.1:8080/modules/calendars/chaos.ics",
					symbol: "calendar",
					
					}
			]
		}

	},

```
Works good so far BUT as soon as i create a series of events i get following error messages:
```
No toISOString function in curr.start 00)":20190909T164500
Whoops! There was an uncaught exception...
TypeError: event.start.getFullYear is not a function
    at /home/pi/MagicMirror/modules/default/calendar/calendarfetcher.js:270:33
    at Request._callback (/home/pi/MagicMirror/modules/default/calendar/vendor/ical.js/node-ical.js:18:4)
    at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```
In outlook, on the iphone or even in the groupware it is displayed perfectly without any issues. 
So if anyone has an idea or solution to fix this issue i would be very glad in getting help here because i don´t have any ideas anymore.

Posted in the forum already with the suggestion to report this as a bug. (10896)

Thanks in advance
icey

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
