### ISSUE TITLE
MMM-Google Assitant Download script

### ISSUE THREAD

**Issue by csoler11** [MichMich/MagicMirror#1754]
Hello, I was trying to install the Google assistant module (MMM-Googleassistant), and I don’t know how to make the last step, Download the script and install, if someone Can explain me how to  do it I will apracite it. I’m a noob with raspberry and I need help to finish it, because IS for a school work. Thanks

**Comment by sdetweil** [comment]
seems odd... if you have already done the git clone of the module, then the script (pi/assistant.py) is located in the MMM-Googleassistant/pi folder
