### ISSUE TITLE
Can't run dev tools for client in clientonly mode

### ISSUE THREAD

**Issue by tillig** [MichMich/MagicMirror#1757]
**Platform**: Linux (Ubuntu on WSL)

**Node Version**: 10.16.3

**MagicMirror Version**: 2.8.0

**Description**: There is no way to start the Chrome dev tools when starting the Electron app in clientonly mode.

**Steps to Reproduce**:

Run `node clientonly --address xxx.xxx.xxx.xxx --port yyyy dev` to try firing up the client with dev tools enabled.

**Expected Results**: Expected to see dev tools.

**Actual Results**: Client started, no dev tools.

**Additional Notes**:

It appears the [line that spawns the electron application](https://github.com/MichMich/MagicMirror/blob/a77128d5f716becd34822b5eebc17c43569dc4b0/clientonly/index.js#L75) doesn't include the `dev` argument if it's present on the `node` command line so [when `electron.js` checks `argv` to see if `dev` is present, it's not](https://github.com/MichMich/MagicMirror/blob/a31546b1ff8c7c10e12d7acbab063297d59c6b93/js/electron.js#L54).

**Comment by sdetweil** [comment]
ctrl-shift-i  will open the dev tools window once running

**Comment by tillig** [comment]
Ah, I see that in the readme now, though it's referred to as "mirror mode" instead of "client mode" and there's no mention of it in the "client-only" section. Might help for n00bs like me to have a second reference in the readme. I'm still really figuring out how Electron works and there's a lot here that sort of assumes "you just know."

**Comment by sdetweil** [comment]
>Sort of assumes "you just know.".. ain't that the truth!!!   and there is a LOT going on inside the mirror code..

**Comment by MichMich** [comment]
If this problem still occurs, feel free to reopen this issue.
