### ISSUE TITLE
Problems with umlauts in newsfeed (äöüß)

### ISSUE THREAD

**Issue by djsunrise19** [MichMich/MagicMirror#176]
![umlaute](https://cloud.githubusercontent.com/assets/14234570/14555012/6fecc53a-02f0-11e6-9d24-6aef4320a3c9.jpg)

Problem exists directly on raspi and with my computer (`raspi_ip`:`port`)

**Comment by MichMich** [comment]
In your newsfeed config, add the following property:

    encoding:'ISO-8859-1'

For more info see the [newsfeed documentation](https://github.com/MichMich/MagicMirror/tree/v2-beta/modules/default/newsfeed) and issue #126.

**Comment by djsunrise19** [comment]
Thank you very much, certainly it works. I'm sorry, I have to read a little bit more before I open issues.

**Comment by MichMich** [comment]
No problem. Glad I could help!

**Comment by KX900** [comment]
And how to solve the same problem in compliements?
When i add this in compliments, magic mirror doesnt show the module anymore.
