### ISSUE TITLE
Approval request for commercial and distribution use

### ISSUE THREAD

**Issue by zikotrance** [MichMich/MagicMirror#1763]
Hi guys,

I’m new in coding and my questions may seems stupid but I didn’t find an answer somewhere else.
Can we use the magicmirror code to adjust it to our needs and integrated into our production line for commercalization purpose.

Do we have access to source code? Legaly what our limitation to use it? 

In resume can we have your approval for distribution and commercialization purpose?

We’re considering offering a good donation to support. But for now this is out main question befor going further

Thanks a lot guys

**Comment by JolokHD** [comment]
The License is defined here:
https://github.com/MichMich/MagicMirror/blob/master/LICENSE.md
You can sell this software if you include this license file.
