### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by Darkmx-6** [MichMich/MagicMirror#1771]
Please only submit reproducible issues. 

If you're not sure if it's a real bug or if it's just you, please open a topic on the forum: [https://forum.magicmirror.builders/category/15/bug-hunt](https://forum.magicmirror.builders/category/15/bug-hunt)
Problems installing or configuring your MagicMirror? Check out: [https://forum.magicmirror.builders/category/10/troubleshooting](https://forum.magicmirror.builders/category/10/troubleshooting)

When submitting a new issue, please supply the following information:

**Platform**: Raspberry Pi Zero w running DietPi v6.25.3

**Node Version**: ?

**MagicMirror Version**:  v2

**Description**: During install I get a  Error: Cannot find module 'semver' when I do step 4 on the manual Install : npm install && npm start  

This happened on both the manual and bash command

**Steps to Reproduce**: step 4: Install and run the app with: npm install && npm start

**Expected Results**: I just want magic mirror to work

**Actual Results**: root@DietPi:~# bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"

$$\      $$\                     $$\           $$\      $$\ $$\                                          $$$$$$\
$$$\    $$$ |                    \__|          $$$\    $$$ |\__|                                        $$  __$$\
$$$$\  $$$$ | $$$$$$\   $$$$$$\  $$\  $$$$$$$\ $$$$\  $$$$ |$$\  $$$$$$\   $$$$$$\   $$$$$$\   $$$$$$\  \__/  $$ |
$$\$$\$$ $$ | \____$$\ $$  __$$\ $$ |$$  _____|$$\$$\$$ $$ |$$ |$$  __$$\ $$  __$$\ $$  __$$\ $$  __$$\  $$$$$$  |
$$ \$$$  $$ | $$$$$$$ |$$ /  $$ |$$ |$$ /      $$ \$$$  $$ |$$ |$$ |  \__|$$ |  \__|$$ /  $$ |$$ |  \__|$$  ____/
$$ |\$  /$$ |$$  __$$ |$$ |  $$ |$$ |$$ |      $$ |\$  /$$ |$$ |$$ |      $$ |      $$ |  $$ |$$ |      $$ |
$$ | \_/ $$ |\$$$$$$$ |\$$$$$$$ |$$ |\$$$$$$$\ $$ | \_/ $$ |$$ |$$ |      $$ |      \$$$$$$  |$$ |      $$$$$$$$\
\__|     \__| \_______| \____$$ |\__| \_______|\__|     \__|\__|\__|      \__|       \______/ \__|      \________|
                       $$\   $$ |
                       \$$$$$$  |
                        \______/

this appears not to be a Raspberry Pi 2 or 3, do you want to continue installtion (y/N)?y
Updating packages ...
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease                
Hit:2 https://archive.raspberrypi.org/debian buster InRelease                  
Reading package lists... Done                            
Installing helper tools ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.6).
curl is already the newest version (7.64.0-4).
git is already the newest version (1:2.20.1-2).
unzip is already the newest version (6.0-23+deb10u1).
wget is already the newest version (1.20.1-1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Check current Node installation ...
Node currently installed. Checking version number.
Minimum Node version: v5.1.0
Installed Node version: v8.11.3
No Node.js upgrade necessary.
Check current NPM installation ...
NPM currently installed. Checking version number.
module.js:549
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Minimum npm version: V6.0.0
Installed npm version: V
npm should be upgraded.
Installing npm ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
npm is already the newest version (5.8.0+ds6-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
npm installation Done!
Cloning MagicMirror ...
Cloning into 'MagicMirror'...
remote: Enumerating objects: 315, done.
remote: Counting objects: 100% (315/315), done.
remote: Compressing objects: 100% (282/282), done.
remote: Total 315 (delta 39), reused 193 (delta 21), pack-reused 0
Receiving objects: 100% (315/315), 655.08 KiB | 771.00 KiB/s, done.
Resolving deltas: 100% (39/39), done.
Cloning MagicMirror Done!
Installing dependencies ...
module.js:549
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Unable to install dependencies!

**Configuration**:  Don't have one yet?

**Additional Notes**: I have worse problems when installing on raspbian, seems like some major failure. The message below isn't while installing Magic Mirror, but I get a similar message

  
Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.668667] Internal error: Oops: 17 [#1] ARM

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.767644] Process dpkg (pid: 739, stack limit = 0x5c2e8ed1)

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.774598] Stack: (0xd595dcc0 to 0xd595e000)

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.781256] dcc0: 00000000 da4bcc38 d4f0bc68 d595dcd8 c0117840 d595dec0 000004bc d595de20

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.788363] dce0: db0dc0e4 0000159a 00000000 000007ff d595de20 0000000c d595dd2c d595dd08

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.795253] dd00: c022226c c0242884 00000000 c01094e0 000004bd d595dd90 00058cbd 00000000

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.802477] dd20: d595ddcc d595dd30 c0227894 c02221f4 00000800 00000000 c02226fc c011cab4

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.809800] dd40: d595de07 d4f0bc68 d595de38 d8cd2118 d4f0bc68 0000000f 000004bf d595010f

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.816850] dd60: db0dbf34 db0dbf58 db0dbf7c db0dbfa0 db0dbfc4 db0dbfe8 db0dc00c db0dc030

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.824296] dd80: db0dc054 db0dc078 db0dc09c db0dc0c0 db0dc0e4 db0dc108 db0dc12c 2c58bbb1

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.831383] dda0: 00000002 d4f0bc68 d595dec0 00000000 d8cd2118 00000000 d595dec0 00000000

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.838804] ddc0: d595dea4 d595ddd0 c0228374 c0227628 00000000 0000000c d595de14 d595dde8

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.845941] dde0: 00000001 00000000 da502000 d4f0bd54 00000000 00000001 da5022d0 7fffffff

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.853406] de00: dacc28d0 0000000c d595de08 d595de08 da55a430 da55a430 d595de18 d595de18

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.860810] de20: d4f0bc68 d595dec0 000004bc 00000801 ffffffff d5934320 00058800 00000000

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.868242] de40: 00000000 00000800 00000060 0000000c d595dec0 d93e4460 d8d0e1e0 c019147c

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.875972] de60: 00058cbc 00000000 d595c001 d595dec0 00000024 2c58bbb1 00000000 d595dec0

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.883474] de80: d4f0bd54 d4f0bc68 7fffffff 00000000 00000000 00000000 d595debc d595dea8

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.891298] dea0: c01189d4 c0227d8c d4f0bd54 c09e3028 d595df34 d595dec0 c0108880 c01189b0

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.898817] dec0: 7ffffb43 00000000 00000000 00000000 ffffffff 7fffffff 00000000 00000000

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.906657] dee0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.914127] df00: c09e3028 2c58bbb1 d58bfaa0 00000000 00000000 d5958aa0 d4f0bd54 00000002

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.921870] df20: 00000000 d5958aa0 d595df7c d595df38 c01a8508 c01087d4 ffffffff 7fffffff

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.929337] df40: 00000000 0000009a ffffffff 7fffffff d595df94 00000000 00000000 beb49ad0

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.937129] df60: 00000155 c00091a4 d595c000 00000000 d595dfa4 d595df80 c01a8594 c01a83b0

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.944709] df80: 00000000 00000000 00000002 d595df98 00000000 00000000 00000000 d595dfa8

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.952390] dfa0: c0009000 c01a8578 00000000 00000000 0000000b 00000002 00000000 00000000

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.960192] dfc0: 00000000 00000000 beb49ad0 00000155 0159af66 00de4280 ffffffff 00de4218

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4500.967783] dfe0: 0000006c beb496c0 00013de8 b6ef4d0c 60000010 0000000b 00000000 00000000

Message from syslogd@raspberrypi at Sep 24 18:13:12 ...
 kernel:[ 4501.075602] Code: e1a02000 e1a01005 e5980000 ebfd77db (e1c821d0)

**Comment by MichMich** [comment]
Thanks for opening an issue!

To allow us to help you it's extremely important that we have all the details about your setup. During the creation of this issue, important details were asked to fill in. Because you did not provide (any) of these details we are unable to help you. 

If you are running into errors, please provide as many detailed error logs as possible in addition to the requested details.

If you are unaware how to retrieve all the requested information, feel free to ask for help on http://forum.magicmirror.builders.

This issue will be closed. Feel free to open a new issue with all the requested information.

**Comment by Darkmx-6** [comment]
Is this a canned response? Because I did have lots of details in my post,
may be I didn't have all the details asked for but I had most.

**Comment by Darkmx-6** [comment]
Anyhow the problem I was having was because of some shorted GPIO pins, killing all GPIOs and causing the kernel errors.

It now works and I'm having a problem auto starting videos but that is a problem for another thread.
