### ISSUE TITLE
Suggestion: include some screenshots on the front page

### ISSUE THREAD

**Issue by campbellkerr** [MichMich/MagicMirror#1774]
Sounds dumb, but I stumbled across MM and I *think* it might do what I need - but without screenshots it's hard to tell!

We all know that this project is Magic Mirror, but that doesn't limit it to mirrors - I'd like to be shown what it can do as just a normal screen - the mirror part is optional right? Thanks!

**Comment by msands** [comment]
As someone who's installed it w/o the "mirror" functionality, it is literally the same exact thing, but without being able to see your reflection.

**Comment by MichMich** [comment]
Not seeing any value in this. Closing.
