### ISSUE TITLE
Updating problem 

### ISSUE THREAD

**Issue by That-Guy-Jack** [MichMich/MagicMirror#1778]
Platform: rasparry pi 3 b in pi top (laptop edition) raspian (think its most recent lees than 2 months old install )

**Node Version**: dont know how to find 
**MagicMirror Version**: Magic mirror 2 

**Description**: cant update thorugh SSH and on the pi directly getting error 

**Steps to Reproduce**: just try updating 

**Expected Results**: it to update

**Actual Results**: this error pi@raspberrypi:~/MagicMirror $ git pull && npm install
Updating a31546b..500147e
error: Your local changes to the following files would be overwritten by merge:
        package-lock.json
Please commit your changes or stash them before you merge.
Aborting
pi@raspberrypi:~/MagicMirror $

**Configuration**: basicly stock 

**Additional Notes**: Provide any other relevant notes not previously mentioned. This is optional.

**Comment by sdetweil** [comment]
try my new upgrade script,  see here in the form for instructions

https://forum.magicmirror.builders/topic/10859/new-update-upgrade-script-ready-for-testing

**Comment by That-Guy-Jack** [comment]
> 
> 
> try my new upgrade script, see here in the form for instructions
> 
> https://forum.magicmirror.builders/topic/10859/new-update-upgrade-script-ready-for-testing

ill try that in a sec thanks

**Comment by That-Guy-Jack** [comment]
> 
> 
> try my new upgrade script, see here in the form for instructions
> 
> https://forum.magicmirror.builders/topic/10859/new-update-upgrade-script-ready-for-testing

seemed to have fixed it by doingthant and removing the lock file as thier was nothing in it soo that has fixed it thanks for your help

**Comment by sdetweil** [comment]
cool.. can u close this issue now?
