### ISSUE TITLE
Log messages not being displayed

### ISSUE THREAD

**Issue by Adman** [MichMich/MagicMirror#1779]
Hello!
Once I want to call `Log.log` inside the module, the message is not displayed. Is this standard behaviour?

**Platform**: Raspbian

**Node Version**: 10.16.3

**MagicMirror Version**: 2.9.0

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
