### ISSUE TITLE
Please create a config file.

### ISSUE THREAD

**Issue by nickroz7** [MichMich/MagicMirror#178]
Hey guys, I'm generally pretty new to the Raspberry Pi and coding in general. I followed the steps for configuring my raspberry pi, but I am still getting this message. Can anyone help? Thanks a bunch guys!

![img_0197](https://cloud.githubusercontent.com/assets/18489156/14571056/3f90562a-0315-11e6-848c-ef7129f47c7a.JPG)

**Comment by skibol3k** [comment]
Duplicate config/config.js.sample to config/config.js.
Modify your required settings and save.

**Comment by MichMich** [comment]
Your config is probably malformed. Check your web inspector.

**Comment by nickroz7** [comment]
How do I duplicate config/config.js.sample?

**Comment by jferch** [comment]
cp config/config.js.sample config/config.js

**Comment by MichMich** [comment]
Uh.... copy the file and rename?!

**Comment by skibol3k** [comment]
Go to config folder and rename config.js.sample to config.js and modify the config file in order to make your mirror your own.

**Comment by MichMich** [comment]
Preferably copy the config.js.sample. If you simply rename it, the old .sample file gets deleted and this your git folder is "dirty" which doesn't allow you to simply update using `git pull`.

But since @nickroz7 doesn't know how to copy a file, this is probably too much info ...
