### ISSUE TITLE
Question I do not find an answer for

### ISSUE THREAD

**Issue by milkywade** [MichMich/MagicMirror#1780]
Say I have the Air quality and PIR modules: when the air level gets to "very bad", how can I

- Start the Monitor using the PIR module (module B calls function in module X)

- Show a notification in the screen

- Play a sound file

- Put a red ring around the screen

thanks!!

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
