### ISSUE TITLE
Reinstall a default module

### ISSUE THREAD

**Issue by JohnB7777** [MichMich/MagicMirror#1782]
Hello,

I have a problem and maybe my question is stupid but I want to reinstall a default module and I don't know how I can do.
Since the last update of magic mirror, I had a problem with the calendar module. I haven't touched it but the magic mirror refuses to start because of it and I don't know why, so I decided to erase, but now I have to reinstall it and I would like to know how I can do this (git clone https://github.com/MichMich/MagicMirror/tree/master/modules/default/calendar dosen't work).

Thanks !

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
