### ISSUE TITLE
armv6l SBCs no longer supported by electron, install fails, must run serveronly mode

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#1787]
When submitting a new issue, please supply the following information:

**Platform**: Place your platform here... give us your web browser/Electron version *and* your hardware (Raspberry Pi 2/3, Windows, Mac, Linux, System V UNIX).
pi0 or pi1, or early pi3b+ (armv6l)

**Node Version**: Make sure it's version 0.12.13 or later.
not important

**MagicMirror Version**: Now that the versions have split, tell us if you are using the PHP version (v1) or the newer JavaScript version (v2).
2.9.0
**Description**: Provide a detailed description about the issue and include specific details to help us understand the problem. Adding screenshots will help describing the problem.
electron 3.0+ armv6l not available  

**Steps to Reproduce**: List the step by step process to reproduce the issue.
install on pi0, pi1

**Expected Results**: Describe what you expected to see.
install succeeds and somehow runs

**Actual Results**: Describe what you actually saw.
install fails, user must figure out how to make something run
pm2/screensaver setup not completed

**Configuration**: What does the used config.js file look like? Don't forget to remove any sensitive information!
default config

**Additional Notes**: Provide any other relevant notes not previously mentioned. This is optional.

**Comment by MichMich** [comment]
Merged.
