### ISSUE TITLE
Is there a way to load the walmart/amazon page in magic mirror

### ISSUE THREAD

**Issue by PengIvanSun** [MichMich/MagicMirror#1792]
Is there a way to load the walmart/amazon page in magic mirror, even in the popup window?

Can someone provide the idea for the possibility or code change suggestion?

Thanks,

**Comment by sdetweil** [comment]
please come to the forums.. there are many different ways. MMM-IFrame for example

https://forum.magicmirror.builders/category/10/troubleshooting

**Comment by PengIvanSun** [comment]
In fact, IFRAME won't work as Amazon/Walmart does not allow this. They have the SAMEORIGIN settings in the header. but thanks I will check the forum and see if I can get something useful.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
