### ISSUE TITLE
2.9.0 untrack-css.sh fails on mac, cut utility downlevel

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#1794]
When submitting a new issue, please supply the following information:

**Platform**: Place your platform here... give us your web browser/Electron version *and* your hardware (Raspberry Pi 2/3, Windows, Mac, Linux, System V UNIX).
MacOS Catalina

**Node Version**: Make sure it's version 0.12.13 or later.
12.8.1
**NPM version 
6.9.0
**MagicMirror Version**: Now that the versions have split, tell us if you are using the PHP version (v1) or the newer JavaScript version (v2).
2.9.0
**Description**: Provide a detailed description about the issue and include specific details to help us understand the problem. Adding screenshots will help describing the problem.

untrack-css runs on every start, fails on macos, as cut is downlevel

**Steps to Reproduce**: List the step by step process to reproduce the issue.
install 2.9.0 on macos
npm start

**Comment by MichMich** [comment]
Merged.
