### ISSUE TITLE
Not refresh result, only displaying 'loading' initially for Weather forecast and current weather

### ISSUE THREAD

**Issue by pdnandakumargym** [MichMich/MagicMirror#1799]
Weather forecast configuration settings set from API response
First in start i'm having API request and check if true then i call scheduleUpdate function, but randomly not displaying result only show loading

1. Im calling api request in start function, after the result i do schedule update 
	start: function() {
		Log.info("Starting module: " + this.name);

		// Set locale.
		moment.locale(config.language);

		this.forecast = [];
		this.loaded = false;
		this.sendSocketNotification("ADD_WEATHERFORECAST", this.config);
		//this.scheduleUpdate(this.config.initialLoadDelay);
		
		this.updateTimer = null;
	},
	
2. 	scheduleUpdate function
scheduleUpdate: function(delay) {
		var nextLoad = this.config.updateInterval;
		if (typeof delay !== "undefined" && delay >= 0) {
			nextLoad = delay;
		}

		var self = this;
		//self.updateWeather();
		clearTimeout(this.updateTimer);
		this.updateTimer = setTimeout(function() {
			self.updateWeather();
		}, nextLoad);
	},
	
3. getDom function
	getDom: function() {
		var wrapper = document.createElement("div");

		if (this.config.appid === "") {
			this.scheduleUpdate(this.config.initialLoadDelay);
			//wrapper.innerHTML = "Please set the correct openweather <i>appid</i> in the config for module: " + this.name + ".";
			wrapper.innerHTML = "Weather error";
			wrapper.className = "dimmed light small";
			return wrapper;
		}

		if (!this.loaded) {
			this.scheduleUpdate(this.config.initialLoadDelay);
			wrapper.innerHTML = this.translate("LOADING");
			wrapper.className = "dimmed light small";
			return wrapper;
		}
		...
	}

4. configuration settings
	{
			module: "weatherforecast",
			position: "top_left",
			header: "Weather Forecast",
			config: {
				requestUrlBase: "http://mmapi.com/api/v1/dev/def/",
				updateInterval: 5 * 1000, 
				//location: "",
				//locationID: "", 
				//appid: ""
			}
		},

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
