### ISSUE TITLE
Day of the week repeated twice

### ISSUE THREAD

**Issue by OhhJared** [MichMich/MagicMirror#18]
![screen shot 2015-04-17 at 7 46 34 pm](https://cloud.githubusercontent.com/assets/9522932/7212773/87d8c6d2-e53a-11e4-9183-49e62ebb3323.png)

The JavaScript is displaying the current temperature as well as the low and high for the day.

**Comment by fallen293** [comment]
I noticed that as well today, and it turns out it shows the current day twice because of the day/night forecast breakdown.

**Comment by OhhJared** [comment]
@fallen293 Did you find any solutions to the issue?

**Comment by fallen293** [comment]
I don't think it is an issue. The first one is the day portion, and the 2nd is the night forecast. Gives you more detail with regards to the day's forecast

**Comment by OhhJared** [comment]
True. I wish my JS wasn't awful so I could edit it to ignore that data.
