### ISSUE TITLE
Calendar Error!

### ISSUE THREAD

**Issue by powerscooter** [MichMich/MagicMirror#180]
Hello,

you have today changed the Calendar. But now i became a Error when i start the Magic Mirror.
I have looked from which data the error came. And it´s the "node_helper.js"

The exact error can you see on the picture.
I have today the Magic Mirror installed with your Autoinstaller data for the Raspberry Pi!
![20160415_220118 1](https://cloud.githubusercontent.com/assets/18429672/14573544/fa85289e-0355-11e6-8533-5374824cdb5d.jpg)

**Comment by MichMich** [comment]
Just pushed a fix, can you give it a try?

**Comment by jferch** [comment]
I experienced the same issue just now and it worked for me, thanks for the fix!

**Comment by MichMich** [comment]
@jferch Thanks for testing.
