### ISSUE TITLE
Black Screen after hours  

### ISSUE THREAD

**Issue by skywalkerpavel** [MichMich/MagicMirror#1819]
Hi together, 

my MM works fine with all of my modules, but after hours of good performence  the mm switch to black screen.  I've no Idea what happend. 
It seems that the MM GUI crash. It is not the screensaver. (Sry for my english) 

mp2 logs MagicMirror (after crash): 

i@raspberrypi:~ $ pm2 logs MagicMirror
[TAILING] Tailing last 15 lines for [MagicMirror] process (change the value with --lines option)
/home/pi/.pm2/logs/MagicMirror-out.log last 15 lines:
0|MagicMir | [SPOTIFY_AUTH] Token is written.
0|MagicMir | [SPOTIFY_AUTH] Token refreshing...
0|MagicMir | [SPOTIFY_AUTH] Token is written.
0|MagicMir | [SPOTIFY_AUTH] Token refreshing...
0|MagicMir | [SPOTIFY_AUTH] Token is written.
0|MagicMir | [SPOTIFY] API Request fail on : /v1/me/player
0|MagicMir | { Error: socket hang up
0|MagicMir |     at createHangUpError (_http_client.js:313:15)
0|MagicMir |     at TLSSocket.socketOnEnd (_http_client.js:416:23)
0|MagicMir |     at TLSSocket.emit (events.js:187:15)
0|MagicMir |     at endReadableNT (_stream_readable.js:1090:12)
0|MagicMir |     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' } undefined
0|MagicMir | Whoops! There was an uncaught exception...
0|MagicMir | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|MagicMir | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir |     at TLSSocket.socketErrorListener (_http_client.js:382:9)
0|MagicMir |     at TLSSocket.emit (events.js:182:13)
0|MagicMir |     at emitErrorNT (internal/streams/destroy.js:82:8)
0|MagicMir |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
0|MagicMir |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|MagicMir | TypeError: Cannot read property 'statusCode' of undefined
0|MagicMir |     at Request.request [as _callback] (/home/pi/MagicMirror/modules/MMM-Spotify/Spotify.js:189:23)
0|MagicMir |     at self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
0|MagicMir |     at Request.emit (events.js:182:13)
0|MagicMir |     at Request.onRequestError (/home/pi/MagicMirror/node_modules/request/request.js:881:8)
0|MagicMir |     at ClientRequest.emit (events.js:182:13)
0|MagicMir |     at TLSSocket.socketOnEnd (_http_client.js:416:9)
0|MagicMir |     at TLSSocket.emit (events.js:187:15)
0|MagicMir |     at endReadableNT (_stream_readable.js:1090:12)
0|MagicMir |     at process._tickCallback (internal/process/next_tick.js:63:19)

Any Ideas? 

After restart of pm2 everything is fine...

**Comment by sdetweil** [comment]
```
0|MagicMir | [SPOTIFY] API Request fail on : /v1/me/player
0|MagicMir | { Error: socket hang up
0|MagicMir | at createHangUpError (_http_client.js:313:15)
0|MagicMir | at TLSSocket.socketOnEnd (_http_client.js:416:23)
```
looks like the spotify module had an error and didn't handle it correctly
the default modules do not connect to spotify
