### ISSUE TITLE
Calendar only show "Loading event

### ISSUE THREAD

**Issue by sigster** [MichMich/MagicMirror#182]
Hi
Thanks for great app

I remove MaticMirror and install again but know Calendar only show "Loading events...
can ics file be local on Raspberry Pi 

Regards
Sigster

**Comment by nhubbard** [comment]
I'm not sure about that... you could try using the `file:` protocol, like `file:///home/yourname/calendar.ics`. Please report back if that works.

**Comment by sigster** [comment]
Thanks
I try file:///home/foldername/calendar.ics with no luck

it was error in the url I was using http:
url: 'webcal://http://www.google.com

**Comment by MichMich** [comment]
Local files are not supported. Only http:// and https:// (webcal:// will automatically be converted to http://).

**Comment by mwuethri74** [comment]
Hi
Is there no possibility to display a calendar that is stored in a local file? I have my birthday calendar exported from my address book into a local file. And this now cant be displayed... ;-(
I did  not find a solution, to show the birthdays, which are stored in my address book (and not in the calendar app on my mac) into a icloud calendar, which is accessible with http. Any ideas?

Thank you and best regards.

Michael

**Comment by paviro** [comment]
https://github.com/bitte-ein-bit/MMM-iCloud-Client

**Comment by mwuethri74** [comment]
Thank you...
