### ISSUE TITLE
BLACK SCREEN AFTER RUN: pi@raspberrypi:~/MagicMirror $ npm install IN TERMINAL.

### ISSUE THREAD

**Issue by Ulrick124** [MichMich/MagicMirror#1823]
I intend to install a new module, but I run wrong folder. 
I had type "npm install" in  " pi@raspberrypi:~/MagicMirror $ ". After that, I continue to install that new module. But when i run magic mirror, it's totally black screen. I remove the new module's code from config.js but the problem was not fixed. But when i used default config.js (config.js.sample), it work. Here is the warning from terminal: (I also include it in file and link): There is an error " Error: ENOTDIR: not a directory, open '/home/pi/MagicMirror/modules/package-lock.json/package-lock.json.js' "

[https://pastebin.com/pvEYN705](url)

npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: calendar_monthly.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
Initializing new module helper ...
Check MagicMirror version for node helper 'MMM-LocalTemperature' - Minimum version:  2.2.1 - Current version: 2.9.0
Version is ok!
Module helper loaded: MMM-LocalTemperature
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
No helper found for module: MMM-page-indicator.
Initializing new module helper ...
Module helper loaded: MMM-Api
Initializing new module helper ...
Module helper loaded: MMM-Buttons
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-LocalTemperature
MMM-LocalTemperature: module loaded! Path: /home/pi/MagicMirror/modules/MMM-LocalTemperature
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Api
WARNING! Could not load config file. Starting with default configuration. Error found: Error: ENOTDIR: not a directory, open '/home/pi/MagicMirror/modules/package-lock.json/package-lock.json.js'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: calendar_monthly.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
Initializing new module helper ...
Check MagicMirror version for node helper 'MMM-LocalTemperature' - Minimum version:  2.2.1 - Current version: 2.9.0
Version is ok!
Module helper loaded: MMM-LocalTemperature
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
No helper found for module: MMM-page-indicator.
Initializing new module helper ...
Module helper loaded: MMM-Api
Initializing new module helper ...
Module helper loaded: MMM-Buttons
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-LocalTemperature
MMM-LocalTemperature: module loaded! Path: /home/pi/MagicMirror/modules/MMM-LocalTemperature
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Api
App threw an error during load
Error: ENOTDIR: not a directory, open '/home/pi/MagicMirror/modules/package-lock.json/package-lock.json.js'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at Class.loadModules (/home/pi/MagicMirror/modules/MMM-Api/node_helper.js:108:19)
    at Class.start (/home/pi/MagicMirror/modules/MMM-Api/node_helper.js:40:8)
    at /home/pi/MagicMirror/js/app.js:225:18
    at new Server (/home/pi/MagicMirror/js/server.js:74:3)
    at /home/pi/MagicMirror/js/app.js:218:18
    at loadNextModule (/home/pi/MagicMirror/js/app.js:167:5)
Whoops! There was an uncaught exception...
{ Error: ENOTDIR: not a directory, open '/home/pi/MagicMirror/modules/package-lock.json/package-lock.json.js'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at Class.loadModules (/home/pi/MagicMirror/modules/MMM-Api/node_helper.js:108:19)
    at Class.start (/home/pi/MagicMirror/modules/MMM-Api/node_helper.js:40:8)
    at /home/pi/MagicMirror/js/app.js:225:18
    at new Server (/home/pi/MagicMirror/js/server.js:74:3)
    at /home/pi/MagicMirror/js/app.js:218:18
    at loadNextModule (/home/pi/MagicMirror/js/app.js:167:5)
  errno: -20,
  syscall: 'open',
  code: 'ENOTDIR',
  path:
   '/home/pi/MagicMirror/modules/package-lock.json/package-lock.json.js' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: MMM-LocalTemperature
Stopping module helper: newsfeed
Stopping module helper: MMM-AssistantMk2
Stopping module helper: MMM-Api
Stopping module helper: MMM-Buttons
Whoops! There was an uncaught exception...
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Class.stop (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:70:20)
    at App.stop (/home/pi/MagicMirror/js/app.js:247:16)
    at App.app.on (/home/pi/MagicMirror/js/electron.js:110:7)
    at App.emit (events.js:182:13)
    at Object.exports.execute (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item-roles.js:263:19)
    at MenuItem.click (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item.js:53:16)
    at Function.executeCommand (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/menu.js:30:13)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

[ADD.txt](https://github.com/MichMich/MagicMirror/files/3921614/ADD.txt)

**Comment by sdetweil** [comment]
erase that file /home/pi/MagicMirror/modules/package-lock.json/package-lock.json.js
