### ISSUE TITLE
Does this work on Raspberry Pi 4?

### ISSUE THREAD

**Issue by dmathisen** [MichMich/MagicMirror#1829]
The readme says that this works on Raspberry Pi 2/3, but I see that 4 is now available. Does anyone know if this will work on a 4?

**Comment by maximiliano2018** [comment]
Hi dmathisen;

Yes, it works. I have installed in Rasp 4 2gb. 
Regards

**Comment by dmathisen** [comment]
Thanks! Closing.
(And sorry for creating an issue for this - I didn't know how else to get an answer)
