### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by AliDjango** [MichMich/MagicMirror#1831]
Will there be support for RTL languages like Persian/Arabic?
3 things must be done for RTL support:
1. Fonts for Arabic/Persian(i can provide Persian ones)
2. Adding dir="rtl" to the <html> tag or "direction:RTL;" to all elements
3. (optional)because they are RTL  and you start reading /seeing things from right and continue to the left side, you may want to swap everything that was right to left
for example in the default RTL config the time and date must be on the left side and weather on the right side.

**Comment by MichMich** [comment]
Feel free to send a PR.
