### ISSUE TITLE
Symbol?

### ISSUE THREAD

**Issue by GoodWillGustin** [MichMich/MagicMirror#1833]
To change the 'symbol' icon, do we need to download the icons from the site you mentioned? I have set several different icons from the names on http://fontawesome.io/icons/ -- but the icons just show as empty boxes. Am I doing something wrong?

**Comment by sdetweil** [comment]
what module is this in? weather?

**Comment by GoodWillGustin** [comment]
Sorry, I think I may have posted this in the wrong place somehow. I was referring to the 'calendar' module. 

https://github.com/MichMich/MagicMirror/tree/master/modules/default/calendar

**Comment by GoodWillGustin** [comment]
The 'calendar' module.

https://github.com/MichMich/MagicMirror/tree/master/modules/default/calendar

**Comment by sdetweil** [comment]
code uses the "font-awesome.css".. I don't know what symbols are supported by what css files..
(I am just another user like you)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
