### ISSUE TITLE
Pi will start but won't run MagicMirror

### ISSUE THREAD

**Issue by tkauf32** [MichMich/MagicMirror#1845]
I have had my mirror for months, however, I was moving and haven't run it in a while. It was working without an issue before and now it will turn on and just sit on a black screen (I presume the desktop). I have tried to trouble shoot, however, I am no wiz when it comes to the programming. 

 "You do not have enough free space in var/cache/apt/archives/". 

when typing "npm start" in the magic mirror directory it displays "no helper found for module: alert" for every module. 

Does the pi store data as it runs 24/7? Does this take up space/is the stored data needed? I have multiple APIs running from the mirror, I thought this data was accessed from the web and deleted once it updates (every minute I believe?). 

I guess this is pretty broad question, but I am trying to understand how this program works all together.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
