### ISSUE TITLE
Request - Easier custom configs

### ISSUE THREAD

**Issue by BKeyport** [MichMich/MagicMirror#1854]
Please consider moving all user files to a new "user" directory... would be nice to be able to just access everything in one directory. -- this would include recommendations to the modules to also hunt in this directory for specific options that don't get included in the main config.js and custom.css 

To make it a non-breaking change, still look for the config and css files in their old directory until the next major update.

**Comment by sdetweil** [comment]
there are only 2 user files   config.js and custom.css, and they do different things

**Comment by MichMich** [comment]
As @sdetweil, this would overcomplicate things, so I don't see the value.
