### ISSUE TITLE
Update Notification stays on after updating

### ISSUE THREAD

**Issue by Okiev** [MichMich/MagicMirror#1855]
I did the update as described:

1.  bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/upgrade-script.sh)"
2.  	bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/upgrade-script.sh)" apply

After restart the Mirror the update notification still appears, also after a reboot of the rpi. Am I'm doing something wrong? 

Thanks in advance!

**Comment by sdetweil** [comment]
there is a bug in the master upgrade script (testing fix now)..  sorry, please use this one
see
https://forum.magicmirror.builders/topic/10859/new-update-upgrade-script-ready-for-testing

**Comment by sdetweil** [comment]
yeh,   2832 commits..

I don't understand that either.. that is a git  message, not generated by MM code anywhere or the installer.. and is shown by the updatenotification  module.. direct from the github  master branch

if u do a git fetch/ git merge u get return code 1 , but it appears successful, but not complete
if you do SECOND git merge, you get 112 changes actually applied..

**Comment by MichMich** [comment]
Can I close this issue?

**Comment by Okiev** [comment]
Yes and thanks a lot!
