### ISSUE TITLE
Images resized after Update

### ISSUE THREAD

**Issue by gielekee** [MichMich/MagicMirror#1868]
Yesterday I updated MagicMirror. After the update images started resizing out of nowhere.

I already reinstalled the modules that we're effected by this.

I hope somebody has a solution for this because on the internet I couldn't find anything.

**Comment by MichMich** [comment]
What images do you mean?

**Comment by gielekee** [comment]
This image with the MMM-NowPlayingOnSpotify module.
With other images i have the same thing
![2B56FC10-5D70-4478-BE01-570277CA56F9](https://user-images.githubusercontent.com/44063951/71887031-91606080-313d-11ea-8ada-3fca127f43f7.jpeg)

**Comment by MichMich** [comment]
This is a CSS issue in the `MMM-NowPlayingOnSpotify` app. Please open a issue in the respective model repo.

**Comment by sdetweil** [comment]
@gielekee   how did you update?  and from what version? 

this sounds like the old custom.css overlayed problem, before 2.9
