### ISSUE TITLE
MMM-RandomBackground black screen after update

### ISSUE THREAD

**Issue by mcnahum** [MichMich/MagicMirror#1869]
After updating MM2 I now have a black background and a loading with MMM-RandomBackground.

All the other module are ok.

if I comment my MMM-RandomBackground module lines on config.js all is ok.

When the module load, I can see my picture for half a second and the screen become black with a "loading" on the top left.

the module is not updated this is why I'm posting here .. any idea? even to have log to understand what could be the issue...?

**Comment by MichMich** [comment]
Please open an issue in that repo of  heck the forum. These issues are only for core issues. Thanks!
