### ISSUE TITLE
Weather out of sync 

### ISSUE THREAD

**Issue by CFenner** [MichMich/MagicMirror#187]
![image](https://cloud.githubusercontent.com/assets/9592452/14586529/0e83fc1c-049b-11e6-9825-3f32dd606e8b.jpeg)

Just realized that my forecast is out of sync, shows Friday but today is Sunday. Anyone having similar problems? Source is pretty up to date.

**Comment by jferch** [comment]
Is your system time correct otherwise?

**Comment by jferch** [comment]
Ah sorry shows on the clock

**Comment by MichMich** [comment]
Not sure why this happens. Is this still the case? Did it fix itself after a while?

**Comment by CFenner** [comment]
It's still stuck, but one of my custom modules is also, so maybe it's a coincidence.

**Comment by MichMich** [comment]
Please check your web inspector console. It probably generated an error. Because of this it stopped updating.

**Comment by CFenner** [comment]
Most likely the problem was my wifi, ssh couldn't be established. Working fine after restart.
