### ISSUE TITLE
Text Style

### ISSUE THREAD

**Issue by iBoy1211** [MichMich/MagicMirror#1878]
Hi i need help with text style

How can i align it to right and max width with 50%, Because now when i make it top_right or top_left its moving all my modules to other side. I guess this is the code for text changes.

getDom: function () {
        let wrapper = document.createElement("div");
        let quoteTextDiv = document.createElement("div");
        let quoteAuthorDiv = document.createElement("div");

        quoteTextDiv.className = "normal";
        quoteAuthorDiv.className = "small dimmed";
        

        if (this.result.quoteText && this.result.quoteAuthor){
            quoteTextDiv.innerHTML = this.result.quoteText;
            quoteAuthorDiv.innerHTML = this.result.quoteAuthor;
        }else{
            quoteTextDiv.innerHTML = "Loading";
            quoteAuthorDiv.innerHTML = "";
        }

        wrapper.appendChild(quoteTextDiv);
        wrapper.appendChild(quoteAuthorDiv);
        return wrapper;

    },

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
