### ISSUE TITLE
Error while building Opencv for MMM-Facial-Recognition-OCV3

### ISSUE THREAD

**Issue by bigman183** [MichMich/MagicMirror#1902]
I received this error while building opencv:

make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:128: modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8811: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

It was after entering "make -j4" in the command line.

There were a few red marked words before the code up here. Let me know if you would like to take a look.

**Comment by HorstBaerbel** [comment]
You are cross posting from [there](https://github.com/normyx/MMM-Facial-Recognition-OCV3/issues/34), which is the correct place. This is the MagicMirror "base module" and has nothing to do with OpenCV.
