### ISSUE TITLE
Recurring Google calendar events which start on or after 6pm CST (GMT-6) not displaying (UPDATE: displaying on prior day)

### ISSUE THREAD

**Issue by amywitty** [MichMich/MagicMirror#1909]
**Platform**: Raspberry Pi 3B rev1.2, 

**Node Version**: 10.18.1

**MagicMirror Version**: 2.10.1

**Description**: 
I am pulling (5) Google calendars into the MagicMirror calendar module and displaying 7 days worth of events using the "dateheaders" timeFormat. I am in Central Standard time zone (CST = GMT-6). Non-recurring events seem to display correctly regardless of what day they are on or at what time they start. Recurring events with a CST start time of 6pm or later do not appear anywhere in the display listing, regardless of whether no end date is specified or if the end date is within the same Standard Time (before March 8, 2020 -- see 2nd screenshot). Recurring appointments with a specified start time in UTC time zone _will_ display during that same time window (UTC 12am = 6pm CST and later). 

I have also had a couple of other weird calendar issues which I cannot reproduce (see Additional Notes section at bottom).

**Steps to Reproduce**: 
1. Create Google calendar recurring and non-recurring appointments with start times (in CST) on every hour of one day. (In screenshot below, I created appointments from 3pm to 10pm CST.) 
2. Also, create Google calendar recurring appointments with start times on or after 6pm CST but specified in UTC time zone. (See 2nd screenshot.)

![SharedScreenshot](https://user-images.githubusercontent.com/4389595/73230000-64eaa380-4141-11ea-9ca2-c67182896249.jpg)

![SharedScreenshot3](https://user-images.githubusercontent.com/4389595/73230102-b3983d80-4141-11ea-905c-d0bba14344d8.jpg)

**Expected Results**: Recurring and non-recurring calendar events displaying at the correct dates and times

**Actual Results**: 
- The recurring appointments which start at 6pm CST or later (and are specified in **CST**) will _not_ display at all. 
- The recurring appointments which start at 6pm CST or later (and are specified in **UTC**) will display at the correct times on the correct dates.
- It does not seem to matter whether there is a specified end date or if that end date is before Standard Time switches to Daylight Time.

**Configuration**: 
```
    {
	module: "calendar",
	header: "Family Calendar",
	position: "top_left",
	config: {
		colored: false,
		coloredSymbolOnly: false,
		dateFormat: "dddd, MMMM D",
		fade: false,
		hidePrivate: true,
		maximumEntries: 40,
		maximumNumberOfDays: 7,
		nextDaysRelative: true,
		showEnd: true,
		showLocation: false,
		sliceMultiDayEvents: true,
		timeFormat: "dateheaders",
		wrapEvents: true,
		calendars: [
			{
				symbol: "users",
				url: "https://calendar.google.com/calendar/ical/....ics"		 
   },
			{
				symbol: "coffee",
				url: "https://calendar.google.com/calendar/ical/.....ics"		},
			{
				symbol: "train",
				url: "https://calendar.google.com/calendar/ical/....ics"					 
   },
			{
				symbol: "dog",
				url: "https://calendar.google.com/calendar/ical/.....ics"				 
   },
			{
				symbol: "music",
				url: "https://calendar.google.com/calendar/ical/.......ics"		},
			{
				symbol: "calendar-check",
				url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					 
   },
		]
	}
    },
```

**Additional Notes**: 
- In addition, one recurring appointment (1st Sunday of each month until April 6, 2020) from 12:30-2:30 pm CST on Sunday, February 2, 2020 displays at a start time of 11:30 am (one hour earlier than it should be). I am unable to reproduce this issue.
- In addition, an appointment that I deleted from one of the Google calendars is still being displayed on the MagicMirror (though it no longer exists in Google Calendar). I am unable to reproduce this issue.
- This is my first Pi MagicMirror -- please be kind.

**Update 1:**
I can now reproduce the 2nd "additional note" issue. I deleted all of the "test 1-time" calendar events from Tuesday (1st screenshot), and all of those 1-time appointments are still being displayed after the MagicMirror was restarted.

**Update 2:**
The missing, recurring, Tuesday evening events now appear on my MM calendar on Monday evenings. (Last night when I posted the original post, it was late Monday evening, and the next Monday did not yet fall within the date range of my display.) So **the events starting 6pm or later are displaying at the correct time but one day early (or actually 6 days late)**.

![SharedScreenshot4](https://user-images.githubusercontent.com/4389595/73264525-a22e5000-4198-11ea-9da1-f4a1c924863b.jpg)

**Comment by MichMich** [comment]
Duplicate: #1718
