### ISSUE TITLE
Electron Doesn't opening

### ISSUE THREAD

**Issue by vishwapinnawala** [MichMich/MagicMirror#1913]
![image](https://user-images.githubusercontent.com/45973257/73559977-2116d780-447c-11ea-9a02-7226a2b40a5d.png)

works fine with chrome when i go to the link but it doesn't open automatically in electron Anyone had this issue ?

**Comment by MichMich** [comment]
Could you give the following command a try from within the MagicMirror folder?
```
DISPLAY=:0 ./node_modules/.bin/electron js/electron.js
```

**Comment by khassel** [comment]
may related to #1859 
Looking at his logs the run-start.sh starts `node serveronly` instead of electron.

**Comment by MichMich** [comment]
Working on removing the ‘run-start.sh’. That’s why I want to test the mentioned line.

**Comment by vishwapinnawala** [comment]
hell yeah it works!!!

**Comment by vishwapinnawala** [comment]
added this as khassel says in his thread 

if [ -z "$DISPLAY" ]; then #If not set DISPLAY is SSH remote or tty
	export DISPLAY=:0 # Set by default display
else
	xorg=xwindowsrunning
fi

no it works normally

**Comment by MichMich** [comment]
Could you please try if the `develop` branch solves your issue? Run the following commands from within your MagicMirror folders:
```
git checkout develop

git pull

npm install

npm start
```

**Comment by vishwapinnawala** [comment]
![image](https://user-images.githubusercontent.com/45973257/73656383-016af380-46b6-11ea-8bc5-7ce51aef9744.png)

**Comment by khassel** [comment]
can you try `git checkout -b develop --track origin/develop` instead?

In case of error, can you provide more info:
* `git branch -a`
* `git show-ref`
* `git version`

**Comment by sdetweil** [comment]
@vishwapinnawala 

can u tell me your environment? 

run-start tries to enable running in more env than the raw start..

if u could add -x to the bash line
and start and post the results of the npm start
so I can see the reason for the misdetection...

i am the new run-start author

**Comment by vishwapinnawala** [comment]
@khassel tried can you try git checkout -b develop --track origin/develop it  
![image](https://user-images.githubusercontent.com/45973257/75241577-577e1300-57ec-11ea-888e-acf918dedc5d.png)

![image](https://user-images.githubusercontent.com/45973257/75241623-741a4b00-57ec-11ea-9982-d3b781eafc77.png)

**Comment by vishwapinnawala** [comment]
@khassel 

![image](https://user-images.githubusercontent.com/45973257/75241788-c78c9900-57ec-11ea-9553-9d8f5cd170d5.png)

**Comment by vishwapinnawala** [comment]
@sdetweil which bash line u want me to add "-x" ??

**Comment by sdetweil** [comment]
The 1st line of run-start.sh

What is DISPLAY=:1?

Typically the display on pi is :+1: 0

**Comment by vishwapinnawala** [comment]
ahh im on vncserver mode thats why :1

**Comment by sdetweil** [comment]
Do u have real display? I don't think this works over vnc

**Comment by vishwapinnawala** [comment]
no the previous version worked on my pi with vnc without any error and i tried this version with a monitor too it's the same error but i fixed the issue like @khassel  says in his thread it works for me now

**Comment by sdetweil** [comment]
Ok. 

The problem is/was I added code to auto detect when electron could not be used.
Your case I see it starts in server only mode

**Comment by sdetweil** [comment]
Can u show me the output of
```
xdpyinfo
```

**Comment by sdetweil** [comment]
@vishwapinnawala  how can I recreate this?  I have pi setup to boot and start vnc server. no displays, forced hdmi and display size...

when I vnc in, and logon.. I get the same desktop as with display and DISPLAY=:0.0
not :1 as i your case

using realvnc server  and client. 

if the display is connected, the real display and vnc display are the same. 

when I logon thru vnc (no display connected), pm2 starts MagicMirror, using the run-start.sh on display=:0 just fine..

**Comment by vishwapinnawala** [comment]
this is how i do first i setup my pi using a monitor (turning on ssh)and then i remove the monitor and then go headless with ssh using putty in putty i execute "vncserver" command then vncviewer on given ip address in putty

**Comment by sdetweil** [comment]
Would really love to see the bash debug output of the run-start.sh.
U can get another copy of it from here
https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/run-start.sh

The stop existing mm. And do

bash -x ~/MagicMirror/run-start.sh > sometime
And send me somefile @ sdetweil at gmail

**Comment by sdetweil** [comment]
@vishwapinnawala I might have missed a step, I see some configs that use ssh to create a secure tunnel onto the viewer system, and then use vncviewer  to connect to THAT session.

this also works unchanged.  MagicMirror comes up as before. on display :1

here is the bash trace of that with my comments 
```
+ '[' -z :1.0 ']'                           // if $DISPLAY is not set (is)
++ uname -m
+ arch=armv7l                       //  arm processor type
+ false=false
++ grep -v '^[[:blank:]]*//' config/config.js
++ grep -i serveronly:
++ tr -d ',"'\'''
++ awk '{print tolower($2)}'
+ serveronly=
+ serveronly=false                     // find config.js setting, default false
++ pgrep Xorg                           // check if X is running
+ xorg=539                                      // X is running
++ uname
+ mac=Linux                                   // linux OS
+ '[' false. '!=' false. -o armv7l == armv6l ']'   // if not explicit serveronly -o not armv6 
+ '[' 539. == . -a Linux '!=' Darwin ']'       // if Xwindows runnan d and not Mac
+ node_modules/.bin/electron js/electron.js    // execute electron 

```
