### ISSUE TITLE
JavaScript error in RSS

### ISSUE THREAD

**Issue by ayendeignacio** [MichMich/MagicMirror#193]
Hi, I'm having this problem with RSS reader, i tried Google, CNN, BBC, NYTimes, and some other RSS channels. RSS crash after some hours of use, 4 to 8.

![img-20160417-wa0002](https://cloud.githubusercontent.com/assets/18516930/14588924/a197aadc-048a-11e6-9dd6-94d429d3c34f.jpg)
![img-20160416-wa0001](https://cloud.githubusercontent.com/assets/18516930/14588925/a1994cca-048a-11e6-9096-00066751f06c.jpg)

**Comment by MichMich** [comment]
It looks like an issue with your DNS which is unable to resolve the hostname of the feed. Will look into it ...

**Comment by MichMich** [comment]
It turned out this happened when there was no internet connection available. This should be solved now. Please update your MM.
