### ISSUE TITLE
stopping MM

### ISSUE THREAD

**Issue by erkilic** [MichMich/MagicMirror#1931]
Hi,
I have a question regarding stopping MagicMirror via shell or terminal command. So if I have started MM with "npm start" is there also a possibility to stop it with a command (not only with shortcut). 
Rational: I want to stop working MM with a Python code.

Thx in advance.
Gürkan

**Comment by sdetweil** [comment]
i wrote a script to do that..

needs the moreutils package installed

sudo apt-get install moreutils

I call this 
clear_node
have to make it executable 
chmod +x clear_node
```
#!/bin/bash

ps -ef | grep pocket | grep -v "grep"  | awk '{print $2}'  | ifne xargs sudo kill -9
ps -ef | grep node | grep -v "grep"  | awk '{print $2}' | ifne xargs sudo kill -9
ps -ef | grep chromium-browser | grep -v "grep"  | awk '{print $2}' | ifne xargs sudo kill -9
sudo killall  chromium-browser
sudo killall  /usr/lib/chromium-browser/chromium-browser
sudo killall electron
```

**Comment by erkilic** [comment]
thanks a lot MichMich. And thanks for your amazing MagicMirror Project! 

⁣BlueMail for Android herunterladen ​

**Comment by sdetweil** [comment]
this can be closed
