### ISSUE TITLE
Logo Asisstant don't show in MagicMirror

### ISSUE THREAD

**Issue by huynhquoctoan** [MichMich/MagicMirror#1933]
Although I have followed the instructions on the web. I installed Asisstant MK2 V3.1, Raspberry Pi 3+ and Raspbian 26-9-2019 but the Asisstant logo is still not displayed on the screen MagicMirror

**Comment by buxxi** [comment]
You should probably report it to the module developer here instead:
https://github.com/eouia/MMM-AssistantMk2/issues/new/choose

And you probably need to supply more information about where it goes wrong, log files etc.
