### ISSUE TITLE
extract config to json

### ISSUE THREAD

**Issue by CFenner** [MichMich/MagicMirror#195]
It happened to me a some times, that I had typos in my config. What do you think about pulling the config into a json file and enable the user to run jsonlint with npm on the file to validate its content. In the config.js we the n would only need to import the json file.

**Comment by MichMich** [comment]
The downside of json is that it doesn't support commenting. So I prefer the javascript method. (Aside from the fact that it's a major breaking change.)

It would be no problem to add some script informing the user that the current config is malformed/incorrect. So I think we could better focus on that.
