### ISSUE TITLE
MagicMirror.NET (Windows version based on WPF)

### ISSUE THREAD

**Issue by jdahan91** [MichMich/MagicMirror#1950]
Hi, yesterday I started a port of an existing system I wrote in WinForms to WPF and I think it has the potential to become a modular system for Windows-based systems which has similar capabilities as the one written in js. 

The thing is, the current one is only for linux based systems which is limited. My solution is to write one for Windows and even make it (in the future) cross platform. Of course the communication will be based on Telegram (or any other interface) and will have many features written as plugins either by me or individuals and a similar gui.

My question is, is it ok for me to use the name "MagicMirror".NET as a Windows based port to the system? Thanks.

**Comment by MichMich** [comment]
Thanks for reaching out. It can run on windows without any problems. That being said, I prefer to not use MagicMirror as project name to prevent any confusion.

**Comment by jdahan91** [comment]
> Thanks for reaching out. It can run on windows without any problems. That being said, I prefer to not use MagicMirror as project name to prevent any confusion.

Alright, I will rename the solution/project.
