### ISSUE TITLE
setting MM_CONFIG_FILE causes MM to fail to load

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#1964]
version 2.10.1

set the full path to the new config on env var
```
cp config/config.js $HOME/somefile.js
export MM_CONFIG_FILE=/home/$HOME/somefile.js
npm start
```
says missing config file on web page, but loaded the config (in terminal window)

**Comment by khassel** [comment]
Did tests with `node serveronly` and the browser make something like this with your variable: `http://192.168.0.143:8080/home/pi/somefile.js`

AFAIS this is not possible at the moment. You can only use files under the mm root dir (e.g. `config` or `modules`) and you have to use the relative path, e.g. `MM_CONFIG_FILE=config/somefile.js` works ...

Not tested but think you need to use one of these subdirs (defined in `server.js`):
````
var directories = ["/config", "/css", "/fonts", "/modules", "/vendor", "/translations", "/tests`/configs"];
````
