### ISSUE TITLE
1 cm of black border on rPi4 with 7" touch screen

### ISSUE THREAD

**Issue by Toontje** [MichMich/MagicMirror#1965]
On my Pi4 with 7" touch screen i have a 1cm wide black border around MM. Is there a way to get rid of this? My LXDE desktop does fill the complete screen.

node v10.19.0
MM 2.10.1 (according to CHANGELOG.md) In any case the latest. I did a git pull yesterday.

All default settings in config.js

Any ideas?

**Comment by hipitihop** [comment]
@Toontje Check your overscan setting in rasperry settings/preferences. I found this helped me on a 23" touch screen

**Comment by all3kcis** [comment]
Maybe you can try this on your custom.css
```
body {
    margin: 10px 10px;
    height: 100%;
}
```

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
