### ISSUE TITLE
Unable to post pictures on forum topics.

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#1969]
Topic says it all..

We have asked for help in forum for over a month w no response

**Comment by MichMich** [comment]
@roramirez Do you have any idea?

**Comment by sdetweil** [comment]
@roramirez   @MichMich anything?

**Comment by MichMich** [comment]
I tried to find a solution past Friday, but couldn't find a solution. I just got a word from @roramirez. Unfortunately he can't take a look because of the Covid-19 situation. I will dive into it again end of this week.

**Comment by sdetweil** [comment]
@MichMich   thanks... we are also seeing more and more postings fail with Askimet.. really need this to go away..

**Comment by MichMich** [comment]
Will check that as well. Thanks for your patience.

**Comment by MichMich** [comment]
Image uploading is solved. Let's see if the Askimet improves as well. 

Closing this for now, feel free to contact me if there are any issues.

**Comment by sdetweil** [comment]
sorry, new problems
