### ISSUE TITLE
endless events

### ISSUE THREAD

**Issue by CFenner** [MichMich/MagicMirror#197]
The handling of endless events has changed somehow, now endless events are rendered first.

Calendar: `webcal://ifeiertage.de/bw-s.ics`

![img_0670](https://cloud.githubusercontent.com/assets/9592452/14620919/d21eb62e-05bf-11e6-8e40-628b34d19c7c.JPG)

**Comment by CFenner** [comment]
If I reload, one time the endless events disappear, the next time they come back again.

**Comment by MichMich** [comment]
I did not experience the issue myself. I did change a few calendar issues, though... Could you see if the issue is solved?

**Comment by CFenner** [comment]
When I looked in the mirror this morning, the events where gone, I'll check if they reappear tonight.

**Comment by MichMich** [comment]
I made another small change to the calendar. Please update. :)

**Comment by CFenner** [comment]
Just updated the mirror: now everything is today :) 

![img_0673](https://cloud.githubusercontent.com/assets/9592452/14652191/94bc6286-0673-11e6-997b-f4fc83742dd4.JPG)

**Comment by MichMich** [comment]
LOL... Will look into it again tomorrow.

**Comment by MichMich** [comment]
I just found a HUGE bug that was caused by using an old ical parser. I've updated the parser to the latest version which should solve the issue. Please let me know if this solves the issue.

**Comment by MichMich** [comment]
@CFenner, were you able to test the fix?

**Comment by EngMatt** [comment]
forgive my very newbish question... but can you pull in a new update without manually going through and replacing all the files?  I have the same endless events issue I can try the fix

**Comment by CFenner** [comment]
type `git pull` in the magic mirror folder

**Comment by MichMich** [comment]
I'll add some info about this in de readme tomorrow. But indeed, all you need to do is
    git pull

**Comment by EngMatt** [comment]
ah okay easy.  With this fix I no longer have an event that "ends in 12 months" show up.  Events now show correctly as "Today at 3:30pm", "Tomorrow at 3:00pm", "in 5 days" etc, so works for me.

**Comment by CFenner** [comment]
btw, the problem is fixed. Just one little thing.. :)

It shows an all day event that is tomorrow with "in one day/in einem Tag". I would prefer "tomorrow".

**Comment by MichMich** [comment]
I used a small fix that does this, but note that 'Tag ter Erde' is not planned for tomorrow. Its planned in 26 hours, which shows "in one day/in einem Tag" (done by moment.js).
