### ISSUE TITLE
problem with npm start

### ISSUE THREAD

**Issue by Teenshali10** [MichMich/MagicMirror#1971]
[npm.txt](https://github.com/MichMich/MagicMirror/files/4421322/npm.txt)

Teenshali@DESKTOP-M6H39SM MINGW64 ~/MagicMirror
$ npm start

> magicmirror@2.11.0 start C:\Users\Teenshali\MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

'DISPLAY' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.11.0 start: `DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the magicmirror@2.11.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Teenshali\AppData\Roaming\npm-cache\_logs\2020-04-02T13_24_03_240Z-debug.log

Teenshali@DESKTOP-M6H39SM MINGW64 ~/MagicMirror

**Comment by sdetweil** [comment]
not supported on Cygwin/MinGW ..  

u need to run in serverOnly mode (as there is no graphical UI on Mingw)
execute 
node serverOnly
then use a browser to connect to the http://localhost:8080 (default port)
or replace the start line with 
"start":"./run_start.sh"
and get runs-start.sh from my repo (removed in 2.11)
curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/run-start.sh >run-start.sh
chmod+x run-start.sh

then the script will figure it out.. 
(but you still have to access via browser on window side)

**Comment by Teenshali10** [comment]
Thank you so much for your response! That really worked for me and now I can run in browser...
But with the browser I am facing one more issue.. can't understand what to do...!
The resource from “http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
localhost:8080
downloadable font: download failed (font-family: "Roboto Condensed" style:normal weight:400 stretch:100 src index:2): status=2147746065 source: http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
The resource from “http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
localhost:8080
Loading failed for the <script> with source “http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js”. localhost:8080:41:1

**Comment by sdetweil** [comment]
@Teenshali10 

Usually this error
>blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
is because the file was not found. 
a .js file should be script, not text

so, that means the install didn't complete correctly..

you did an npm install in the MagicMirror folder, right? 
it should have run a step to 

cd to vendor and then npm install there

**Comment by sdetweil** [comment]
so, I think this is a newly discovered roboto-fontface install problem..

do this

edit vendor/package.json 
and change the version of  roboto-fontface like this 
from
```
   "dependencies": {
    "roboto-fontface": "^0.8.0"
  }
```
to
```
  "dependencies": {
    "roboto-fontface": "latest"
  }
```
them in the vendor folder do npm install

then try to restart mm..  

please advise your results

**Comment by rhortal** [comment]
I have serverOnly: true in my config, since updating to the latest version it seems npm start ignores that setting and tries to open a UI. Can start with node serveronly.

**Comment by MichMich** [comment]
Try `node serveronly`

**Comment by rhortal** [comment]
I tried that and it works. However node keeps the program in the foreground so had to start using pm2 as a workaround. Has the config option serverOnly been deprecated?

**Comment by sdetweil** [comment]
@rhortal  I guess deprecated is a term you could use..   all the scripts were removed from the base repo in 2.11

u can add the capability back, by 

changing package.json start script back to unstart
change to
```
"start":"./run-start.sh $1"
```
and if u need to run-start again
```
curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/run-start.sh >~/MagicMirror/run-start.sh
chmod +x ~/MagicMirror/run-start.sh
```
