### ISSUE TITLE
changes in socketclient.js stops MMM-RemoteControl to work

### ISSUE THREAD

**Issue by khassel** [MichMich/MagicMirror#1973]
The changes in `socketclient.js` introduced with this PR https://github.com/MichMich/MagicMirror/pull/1937 in v2.11.0 breaks MMM-RemoteControl, maybe other modules too.

See https://github.com/Jopyth/MMM-Remote-Control/issues/185

After reverting the changes in `socketclient.js` the module works again.

**Comment by khassel** [comment]
Found 2 issues:

-  we can't use `window.location.pathname` because modules can use own html sites referencing `socketclient.js`. E.g. in `http://192.168.xxx.yyy:8080/remote.html` `window.location.pathname` has the value `/remote.html` instead of expected `/`. This could may solved defining a `subPath` value in the config and using this value instead of `window.location.pathname`.

-  in `index.html` the line
  `<script type="text/javascript" src="/socket.io/socket.io.js"></script>`
  was replaced in the above PR with
  `<script type="text/javascript" src="socket.io/socket.io.js"></script>`
  which is a good correction, but many module developers copied this line in their html site. 
  This is a minor issue: If someone will use such a module with a subpath <> `/`, the above line must corrected in the module html.

**Comment by Legion2** [comment]
This can be resolved by defining a `basename` in the configuration with a default value of `/`. `basename` is the used instead of `window.location.pathname`.

**Comment by Legion2** [comment]
@khassel I created a PR to fix the broken socket.io path #1976

**Comment by MichMich** [comment]
Merged.
