### ISSUE TITLE
Mime (text/html) incorrect

### ISSUE THREAD

**Issue by axenc** [MichMich/MagicMirror#1977]
Hi, 

I heve the same issue for somes modules :

Refused to apply style from 'http://192.168.1.39:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Please help...

**Comment by sdetweil** [comment]
the manual install does not create a custom.css file, so it doesn't exist, which produces the error..
do this
```
cd ~/MagicMirror/css
touch custom.css
```

my automated install script does this for you 
see https://github.com/sdetweil/MagicMirror_scripts
