### ISSUE TITLE
Black screen with mouse cursor 

### ISSUE THREAD

**Issue by chen32g** [MichMich/MagicMirror#1979]
Hello,

Once a week (after 3 / 4 days) the Magic Mirror disappear and the screen is black with mouse cursor.
Restart pm2 Magic Mirror solve the issue.

I work with RPI3, Magic Mirror v2.11.0 , before I was with v2.9.0 and I also have this issue.

Please advise.
Thank you.

**Comment by sdetweil** [comment]
sounds like an out of memory error or a module failing..

I would install the MMM-Logging module 
then pm2 flush to clear the logs and restart mirror..

when crashed, pm2 logs --lines=100  might show the error

I just helped another user that had a similar failure once a day. MMM-Logging captured the problem

should really bring this discussion to the forums, as its probably not a MM problem itself 

https://forum.magicmirror.builders/  
probably troubleshooting area
