### ISSUE TITLE
Black screen w/ mouse cursor

### ISSUE THREAD

**Issue by Mahieedaboss** [MichMich/MagicMirror#1983]
This again,

tried the alternative and manual installation but keep getting same warning
The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Checked out the guthub but doesnt make sense to me
how do i change it to true??

**Comment by sdetweil** [comment]
that doesn't matter, its a warning.. we are on electron 6. 

show the output of the console log (pm2 logs --lines=100)
and open the developers window, ctrl-shift-i, select the console tab, and scroll up

there is a fatal error somewhere
