### ISSUE TITLE
HTTPS wrong loadurl for electron

### ISSUE THREAD

**Issue by cspeers** [MichMich/MagicMirror#1988]
Is this an issue when using https and still trying to run electron normally (not serveronly)? 
I had to make the following change to have electron request https otherwise no content would load
```javascript
var scheme = config.useHttps ? 'https':'http'
mainWindow.loadURL(`${scheme}://${address}:${config.port}`);
```

**Comment by khassel** [comment]
I think this is already fixes in [this unmerged PR](https://github.com/MichMich/MagicMirror/pull/1963/files).
