### ISSUE TITLE
calendar & forecast collide…

### ISSUE THREAD

**Issue by desq42** [MichMich/MagicMirror#199]
Hi,
since the last commit my calendar and weather-forecast collide in my "mini-pi-resolution" 800x480.
![screen](https://cloud.githubusercontent.com/assets/18470786/14635329/2e303dfa-0626-11e6-9878-007f194e0d28.png)

Has anyone the same issue?

Thanks,

desq

**Comment by paviro** [comment]
How have you managed to add the camera feed? :)

**Comment by desq42** [comment]
I´m struggling with it. (flicker) see other thread. (feature request).

**Comment by MichMich** [comment]
There is a property You can set to limit the max length of a calendar title.

**Comment by desq42** [comment]
a there it is. thank you.
