### ISSUE TITLE
Thank you for your help @scienceman1972   u mean create a module?

### ISSUE THREAD

**Issue by scienceman1972** [MichMich/MagicMirror#1990]
@scienceman1972   u mean create a module? 

coding is using some descriptive structure to solve a problem. 
1st understand the problem , and how you would solve it manually.. what steps would you take, be detailed.. 

then use the environment and the available descriptive structure (language and libraries) to implement that...

u can use my sample module  as a starting point 
https://github.com/sdetweil/SampleModule

also, module doc here 
https://docs.magicmirror.builders/development/introduction.html#general-advice

_Originally posted by @sdetweil in https://github.com/MichMich/MagicMirror/issues/1986#issuecomment-615878563_

**Comment by sdetweil** [comment]
@scienceman1972  also better to  take this duscussion to discord channel 
https://discord.gg/dAnntW

or the forums 
https://forum.magicmirror.builders/

this area is for trouble with MM itself..
