### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by Sezer84** [MichMich/MagicMirror#2001]
as soon as I want to add a new module it says errors in the config file. can someone please help me where it is? do I have to install anything else?
best regards

**Comment by sdetweil** [comment]
run the tester tool, 
cd ~/MagicMirror
npm run config:check

module format rules are as follows
```
{
  module: "modulename",
  position: "????",
  config: {
    ???
    ???
  }
}
```
note that there is a list of  modules,   inside a [ ]  group,
so the instructions are 
find the ] at the bottom of the page
got up to the first } above the ]
add a comma after the } if not present (comma means  'more comming')
then add the module structure like above..
usually copy the sample in the modules readme, if there is one,
