### ISSUE TITLE
MMM-GoogleTasks	jayked -Stuck Loading

### ISSUE THREAD

**Issue by xplod609** [MichMich/MagicMirror#2008]
Hello I am new to all this and I installed MMM-Google Task and read the readme.
Google Task api is setup, Auth2 is setup , google task can see my different task titles but does not show any of my tasks. 
Pleas help. 

![image](https://user-images.githubusercontent.com/64826306/81037336-544c7680-8e70-11ea-88e5-ed50c6d6e8a9.png)
![image](https://user-images.githubusercontent.com/64826306/81037352-63cbbf80-8e70-11ea-8d57-bd6b9bc3fdb6.png)

**Comment by MichMich** [comment]
Please open a issue in the mmm-googletasks repo.
