### ISSUE TITLE
Different symbols for all day vs timed events in calendar

### ISSUE THREAD

**Issue by rossburton** [MichMich/MagicMirror#2023]
It would be useful if there was a way to set a different symbol for all day events vs events with specific times.

**Comment by MichMich** [comment]
Feel free to send a PR.

**Comment by MichMich** [comment]
Closing this issue for now. Feel free to reopen.

**Comment by rossburton** [comment]
I'll hopefully get around to doing this at some point.

**Comment by rejas** [comment]
I found some time today to code a little, was it something like my PR you wanted @rossburton ?

**Comment by hangorazvan** [comment]
this change my calendars custom symbols to default calendar symbol, no useful for me
