### ISSUE TITLE
bash: 404:: command not found

### ISSUE THREAD

**Issue by drk-geek** [MichMich/MagicMirror#2029]
Not found 404 while executing command 
bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"
please help

**Comment by sdetweil** [comment]
the installer script has been removed from the repo and instructions.. 

please use the script from here https://github.com/sdetweil/MagicMirror_scripts

read the readme online for the instruction to copy/paste

**Comment by drk-geek** [comment]
Thank you @sdetweil
