### ISSUE TITLE
embed other sites as mirror module

### ISSUE THREAD

**Issue by CFenner** [MichMich/MagicMirror#203]
I would like to show the upcoming wind for a certain location. But windfinder.com has no api to fetch the data. Would it be possible to embed a part of the [wind forecast](https://www.windfinder.com/forecast/fehmarn_gold_2) into the mirror? Has anyone experience with this and can help me?

**Comment by MichMich** [comment]
You could simply create an iFrame. but thats not very subtle ... 

The open weather api I currently use for the two other weather modules, has wind info too. Maybe you could built something on this API?

**Comment by CFenner** [comment]
The open weather api is tool general, there is only one value per day. I would need the data on an hourly basis.
<img width="259" alt="bildschirmfoto 2016-04-19 um 21 05 57" src="https://cloud.githubusercontent.com/assets/9592452/14652000/97aa450e-0672-11e6-9cf6-a7c119df4bc7.png">

I thought about the iframe too, but I would only need a part of the page.

**Comment by Bibliofile** [comment]
Not a perfect solution by far, but you could use wkhtmltoimage to get a picture of the site and then either crop the image to get the part of the image you want, or embed the whole image as a background in your page and use background-position to show only the part of the page you need. 

Alternatively, fetch the page through the calendar.php page, and build your own UI with data stripped from the page. Something like this will scrape the data you are looking for. 

````JavaScript
var windData= [];
Array.from(document.querySelectorAll('.weathertable__row')).splice(0, 8).forEach((node) => { 
    var time = node.querySelector('.data-time').textContent.trim(); 
    var degrees = Number(node.querySelector('.units-wd').textContent.trim().replace(/[^\d]/, ''));
    var direction = node.querySelector('.units-wd + span').textContent.trim();
    var speed = Number(node.querySelector('.speed .units-ws').textContent.trim());
    var gusts = Number(node.querySelector('.data-gusts .units-ws').textContent.trim());
    windData.push({time, direction, degrees, speed, gusts});
});
````

**Comment by CFenner** [comment]
Ok, I did the iframe thing... not pretty, but it's working.
I had forgotten what a pain in the ass iframe are..
<img width="530" alt="preview" src="https://cloud.githubusercontent.com/assets/9592452/14935778/1cd25ee8-0edd-11e6-8f7e-9b906d8ec89b.png">

[Windfinder Module](https://github.com/CFenner/MagicMirror-Windfinder-Module)

**Comment by MichMich** [comment]
iframes should be banned from this earth ... ;)

Can I close this issue? ;)
