### ISSUE TITLE
Clock can be off by a minute

### ISSUE THREAD

**Issue by Martin-Palringo** [MichMich/MagicMirror#2030]
With MagicMirror (confirmed on 2.11.0), when the clock module is configured to show only minutes, it updates every minute. This update, however, does not correctly happen on (or just after) the minute changes - so the displayed time often drifts to be a minute out from the real time.

eg. time is 22:15, MM2 shows 22:14.

I would propose calculating how long is left till the next minute, setting the next setTimeout to refresh the clock shortly after the next minute happens.

**Comment by rejas** [comment]
That seems reasonable. Would you be able to send a PR for this or do you need help`with it?

**Comment by Martin-Palringo** [comment]
I'm happy to send a PR - hopefully I'll get a moment to do this in the next few days.
