### ISSUE TITLE
Update module

### ISSUE THREAD

**Issue by Doudy** [MichMich/MagicMirror#2034]
hello
I have two MMM-Domoticz modules.
MMM-Domoticz-1 : displays the temperatures
MMM-Domoticz-2 : displays other informations
With the MMM-Domoticz-1.js and MMM-Domoticz-2.js  depending on the module.
MM tells me that I have to update my modules.
I made a copy of the .js file because I made changes to it.

I tried with git pull but MM refuses to update.

As I changed the name is there not a problem for the update?

![Capture](https://user-images.githubusercontent.com/28684288/83260402-fcc4d080-a1b9-11ea-9253-28535b6e2168.PNG)

**Comment by sdetweil** [comment]
because you made changes,  you will have to make the same changes manually

i suggest u install a new copy and then migrate the changes over to the new folder and swap folders one for each set of modifications..
git clone  ... new-name

did u change the file for code reasons, or settings?

**Comment by rejas** [comment]
you can also "stash" your current changes with git and re-apply them after updating

**Comment by Doudy** [comment]
>@ sdetweil
>did u change the file for code reasons, or settings?

I made the changes in order to have a display of certain data in color.
Thanks for your advices.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
