### ISSUE TITLE
can I help you by sorting the module list ?

### ISSUE THREAD

**Issue by framboise-pi** [MichMich/MagicMirror#2037]
maybe not in a 'one time' move, but maybe it could help you if I (or someone else) try to keep list in alphabetical order ?

**Comment by rejas** [comment]
do you mean that one https://github.com/MichMich/MagicMirror/wiki/3rd-party-modules ?

**Comment by framboise-pi** [comment]
exactly

**Comment by rejas** [comment]
sure, if @MichMich has no objections?

**Comment by MichMich** [comment]
Absolutely not! :)

**Comment by framboise-pi** [comment]
:+1:
