### ISSUE TITLE
trouble with gpio

### ISSUE THREAD

**Issue by erkilic** [MichMich/MagicMirror#2040]
Hi
hope someone can help me, as I'm trying to solve this issue since hours, but no success :-((

if I include the command:
const Gpio = require('onoff').Gpio;
in my node_helper
I get this error during start of MM:

/home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js: symbol lookup error: /home/pi/MagicMirror/node_modules/epoll/build/Release/epoll.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! magicmirror@2.10.1 start: `./run-start.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.10.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-06-10T10_31_46_539Z-debug.log

working on raspi4
raspian is up to date
gpio -v  brings 2.5
sudo usermod -a -G gpio pi  -> no error
sudo npm install onoff brings: -> no error

I really hope soemeone can help. I only want to switch a relais on/off within MagicMirror.
Switching the relais outside MM, with separate js file works fine.

Gürkan

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
