### ISSUE TITLE
MM is working with Armbian?

### ISSUE THREAD

**Issue by uok825** [MichMich/MagicMirror#2043]
Hello everyone, i have Orange Pi zero 512mb.
Can i install mm to armbian, i was wondering.
Thanks.

**Comment by sdetweil** [comment]
yes, use the install script from here https://github.com/sdetweil/MagicMirror_scripts

read the page and cut/paste the one line command to run install..

we tested this last fall..   let mw know how it goes.. come to the forum 
https://forum.magicmirror.builders/
