### ISSUE TITLE
Contribution available to revise default/weather/providers/weather.gov per API guidelines

### ISSUE THREAD

**Issue by easyas314** [MichMich/MagicMirror#2045]
The weather.gov api needs to call several URLs to collect weather information. I have revised the code for this and I'd like to contribute it. Interested? And I'll ask for proper submission guidance in advance. Should I sync my fork/branch specifically with the develop branch? I have similar and more questions about a documentation update. Thanks.

**Comment by MichMich** [comment]
Sorry for the slow response. Feel free to send a PR to discuss the implications.

**Comment by MichMich** [comment]
PR Merged.
