### ISSUE TITLE
This site can't be reached.

### ISSUE THREAD

**Issue by uok825** [MichMich/MagicMirror#2049]
There was no problem for up to 10 minutes. But after installing the MMM-Screencast module, I started getting such an error. I made the address from the config file 0.0.0.0 but nothing changed. How should I proceed?

**Comment by uok825** [comment]
This problem caused by Screencast, how we can fix it?

**Comment by MichMich** [comment]
Please open an issue in the MMM-Screencast repo. This is not a Core issue. Thanks!
