### ISSUE TITLE
Embed Video Streaming

### ISSUE THREAD

**Issue by derekzed** [MichMich/MagicMirror#205]
I would like to work on a module that streams video and audio.  The idea is to have sports center in the bottom corner of the mirror.

Thoughts?

**Comment by polzy** [comment]
good idea, or a little box with airplay

**Comment by paviro** [comment]
I like the Airplay idea!

**Comment by polzy** [comment]
i just find Rplay by vmlite for airplay mirroring... but it's not a free soft and doesn't work with ios9.. 
I find PiCAST 3  (Chromecast like ) https://github.com/lanceseidman/PiCAST
Or blissflixx  https://github.com/blissland/blissflixx 

You have something better for model ?

**Comment by derekzed** [comment]
Maybe this module would have to hide itself when unwanted.  Is that easy to do?  Maybe hide it with a keystroke? hmm seems like lots of work

**Comment by PtrBld** [comment]
Is there any progress?

**Comment by MichMich** [comment]
Would it be ok for you to proceed any further discussion of this issue on: https://forum.magicmirror.builders? This way I can limit the use of GitHub issues to bug reports.
