### ISSUE TITLE
Wi-fi Connectivity Issues

### ISSUE THREAD

**Issue by shadymonkey13** [MichMich/MagicMirror#2053]
This is the third time I have loaded the MM OS onto my SD card and started working on configuring it on the Raspberry Pi. Unfortunately, this is also the third time my Wi-fi won't connect upon a reboot. I open my connection settings and I can see all the routers nearby but I just can't connect to my router. I am able to connect on other devices, just not the Raspberry. Any thoughts? Suggestions? Should I try a new SD card? a whole new Raspberry board?

Thank you for the help,
Hares

**Comment by sdetweil** [comment]
you'll have to open issues over on the MMOS github page
https://github.com/guysoft/MagicMirrorOS
