### ISSUE TITLE
Seconds after AM, PM

### ISSUE THREAD

**Issue by ayendeignacio** [MichMich/MagicMirror#206]
Maybe isn't a bug, but I think is strange see seconds after AM or PM tokens.
After update fix #181 that correct 12 hours format.
![moecdks - imgur](https://cloud.githubusercontent.com/assets/18516930/14666491/990f7862-068e-11e6-9a20-b81b2c4ed55d.png)

**Comment by MichMich** [comment]
That is weird, indeed! Will put it on my todo list.

**Comment by MichMich** [comment]
Fixed!
