### ISSUE TITLE
Ends in 7 months

### ISSUE THREAD

**Issue by paviro** [MichMich/MagicMirror#207]
Well that is a bit strange! The event is recurring and all but why does it display its end date?
![sdsdsd](https://cloud.githubusercontent.com/assets/992826/14674357/37fadabe-0704-11e6-93f4-9e22a22c78fb.png)

**Comment by MichMich** [comment]
Will look into this.

**Comment by MichMich** [comment]
What should be the starting time & endtime for Physik?

**Comment by paviro** [comment]
Physik is every Wednesday (07:45-09:15) and every Monday (11:20-12:55).

**Comment by MichMich** [comment]
Got the feed, just checking if I got it right.

**Comment by MichMich** [comment]
Fixed!
