### ISSUE TITLE
Invalid svg clock faces

### ISSUE THREAD

**Issue by hangorazvan** [MichMich/MagicMirror#2072]
All new 2.12.0 verison svg files in clock faces folder are invalid svg format, use the old ones.
I think replacing unsecure links with https ones make format invalid.

https://forum.magicmirror.builders/topic/13190/no-numbers-in-analog-watch-face

**Comment by MichMich** [comment]
Does it prevent them from loading in electron? 
Feel free to send a PR. Although I think this is caused by prettier. So sending a PR might fail on Travis.

**Comment by MichMich** [comment]
Fix merged into develop thanks to @rejas.

**Comment by hangorazvan** [comment]
face-006.svg still not working

**Comment by MichMich** [comment]
Should be fixed now. Thanks @rejas!
