### ISSUE TITLE
News feed configuration issue

### ISSUE THREAD

**Issue by paviro** [MichMich/MagicMirror#208]
Probably I am just stupid but why doesn't this work? It just fetches the standard feed without any errors.
```
{
			module: 'newsfeed',
			position: 'bottom_bar',
			classes: 'for_all default',
			config: {
				feeds: [
					{
						title: "Spiegel Topmeldungen",
						url: "http://www.spiegel.de/schlagzeilen/tops/index.rss"
					},
					{
						title: "Spiegel Eilmeldungen",
						url: "http://www.spiegel.de/schlagzeilen/eilmeldungen/index.rss"
					}
				],
			showPublishDate: true,
			showSourceTitle: true,
			showDescription: true
			}
},
```

Also it does not show the `showSourceTitle` even tough this should default to `true` shouldn't it?

**Comment by MichMich** [comment]
I just copy/pasted your above code directly in my config, and it seems to work.

**Comment by paviro** [comment]
Well that is totally strange 😳

**Comment by MichMich** [comment]
Did you restart the backend? ;)

**Comment by CFenner** [comment]
We need a validator for this :)

**Comment by paviro** [comment]
Yes twice!

**Comment by paviro** [comment]
@CFenner Definitely! But syntax does not even seem to be the problem here..

**Comment by MichMich** [comment]
@CFenner I am the validator ... ;) Just kidding.

Does it work for you, @CFenner

**Comment by CFenner** [comment]
I had that issue as well some times. Can't check right now, but maybe some white spaces or line breaks?

**Comment by paviro** [comment]
But shouldn't I get an error in the console then?

**Comment by MichMich** [comment]
If it shows the default feed, the custom config doesn't seem to be loaded somehow.

**Comment by MichMich** [comment]
In your terminal, do you see something like: 
```
Create new news fetcher for url:  ...
```

What url does it say?

**Comment by paviro** [comment]
That's exactly the strange thing: 
`Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000`

**Comment by MichMich** [comment]
that is weird. Could you try doing some debugging by adding some logging in de newsfeed.js module?

**Comment by paviro** [comment]
Sure, will let you know what I can find.

**Comment by pvyParts** [comment]
is your git up to date? i tired to test then i realized my git was behind 1 commit. pulled again all working.

**Comment by paviro** [comment]
Yes it is 😐

**Comment by paviro** [comment]
Ah I see.... I updated my fork a few minutes ago but this feature did not exist there yet...

**Comment by MichMich** [comment]
So it's fixed?

**Comment by MichMich** [comment]
You scared me ... ;)

**Comment by MichMich** [comment]
Now you have to bake me a cake.

**Comment by paviro** [comment]
Yep my bad 😀 You are welcome! 😂 If we ever happen to meet I shall do that!
