### ISSUE TITLE
news feed: encoding doesn't work anymore

### ISSUE THREAD

**Issue by djsunrise19** [MichMich/MagicMirror#209]
Since the new update it seems that encoding doesn't work anymore:

![feed2](https://cloud.githubusercontent.com/assets/14234570/14687872/f24d7ce2-073f-11e6-9466-c13f5cfc82e9.jpg)

![newsfeed](https://cloud.githubusercontent.com/assets/14234570/14687842/ce592890-073f-11e6-9799-007525f5c714.jpg)

**Comment by MichMich** [comment]
Check the docs, it's now part of the feed array.

**Comment by djsunrise19** [comment]
Sorry, didn't see that. Thank you!

**Comment by MichMich** [comment]
No problem! :)
