### ISSUE TITLE
calendar maximumEntries not working for individual calendars

### ISSUE THREAD

**Issue by emwtur** [MichMich/MagicMirror#2098]
Setting 
maximumEntries =10 for main calendar and maximumEntries=3 for a individual calendar will show 10 entries ! 
- if other settings produces more than 10 entries

**Comment by rejas** [comment]
This should already be fixed in the develop branch with #2079 in commit https://github.com/MichMich/MagicMirror/pull/2079/commits/73aa35ea2c1310a8953c3c380bf6153db8899b30
