### ISSUE TITLE
How does one move the bottom bar to the right?

### ISSUE THREAD

**Issue by yurMoThEr** [MichMich/MagicMirror#2102]
This isn't an issue, but I have a module pretty near the bottom bar and was wondering how I could move it for the sake of aesthetics. Thanks for any help.

**Comment by sdetweil** [comment]
you could use css in the custom.css file to change the size, location of the bottom bar.

if css/custom.css doesn't exist, just create it
```
touch ~/MagicMirror/css/custom.css
```

**Comment by yurMoThEr** [comment]
I hate to ask you this, but I know nothing of CSS. Could you tell me how to do it?

**Comment by sdetweil** [comment]
read this
https://forum.magicmirror.builders/topic/6808/css-101-getting-started-with-css-and-understanding-how-css-works?_=1596288932213

I am not looking to make changes for other users.
