### ISSUE TITLE
Weather Module - Update Wiki and Example Config for OpenWeatherMap Forecast Requirements

### ISSUE THREAD

**Issue by stopspazzing** [MichMich/MagicMirror#2117]
I was having issues getting weather module working (using free version of OpenWeatherMap) using default config example, seems the default example with api code will work just fine with showing current weather, however, for it to work and properly show the forecast, **requires** `type: "forecast",` and `weatherEndpoint: "/forecast"` otherwise it will fail to load forecast at all. My current config below for weather module:

```
{
            module: "weather",
            position: "top_right",
            header: "Weather",
            disabled: false,
            config: {
                // See "Configuration options" for more information.
                type: "current",
                locationID: "####",
                apiKey: "#######"
            }
        },
        {
            module: "weather",
            position: "top_right",
            header: "Weather Forecast",
            disabled: false,
            config: {
                // See "Configuration options" for more information.
                type: "forecast",
                locationID: "###",
                apiKey: "#######",
                weatherEndpoint: "/forecast"
            }
}
```

https://docs.magicmirror.builders/modules/weather.html

**Comment by MichMich** [comment]
At the bottom of every documentation page, there is a link saying *help us to improve this page*. Using that link you can easily send Pull Requests to fix the documentation. Would it be possible fo you to do so?

https://github.com/MichMich/MagicMirror-Documentation/edit/master/modules/weather.md
