### ISSUE TITLE
Calendar and news feed stuck loading

### ISSUE THREAD

**Issue by kyle-ayn** [MichMich/MagicMirror#212]
I just updated to the latest version and now my calendar is stuck on "loading events..." and news feed is stuck on "loading news..." (using new config format for news feed)

it used to work before

**Comment by CFenner** [comment]
Did you restart the server?

**Comment by kyle-ayn** [comment]
yes I tried to restart the server its still not working

**Comment by MichMich** [comment]
Could you check your web inspector console to see if it gives any errors?

**Comment by kyle-ayn** [comment]
looks like there are no errors
https://www.dropbox.com/s/inxkjexyay6t5pd/Screenshot%20%28138%29.png?dl=0

**Comment by MichMich** [comment]
Looks like a problem with your backend. Any issues reported in your terminal log?

**Comment by kyle-ayn** [comment]
I'm out of town right now.. I'll check tomorrow.

**Comment by kyle-ayn** [comment]
i fixed it..just reinstalled raspian
