### ISSUE TITLE
Interest in OpenWeatherMap OneCall API and Hourly Forecasts

### ISSUE THREAD

**Issue by JimHutchins** [MichMich/MagicMirror#2124]
I wanted to use MagicMirror as a giant clock and weather info center. I loved what was already there in the weather module, but I wanted even more. I've implemented support for OpenWeatherMap's new onecall API endpoint. I've got the code working well enough for my purposes and I read the contribution guide so I'm posting an issue here. 

Is there enough interest in the module for me to clean up the code an submit it? As implemented right now, it is an addition to the standard Weather module and standard openweathermap.js provider. It definitely needs some polish before I would submit it, so I wanted to throw it out here before I did any more. Here's a screenshot of my implementation (including a lot of entries in custom.css).

![2020-09-07-102450_1920x1080_scrot](https://user-images.githubusercontent.com/25532805/92398481-a2aba380-f0f6-11ea-98d8-6c44edd1d73d.png)

**Comment by sdetweil** [comment]
has been added already, https://github.com/MichMich/MagicMirror/pull/2078

switch to the develop branch to access the new code not yet released

this may not be the same as what u want

**Comment by hangorazvan** [comment]
@JimHutchins Can you share with me your code please? New weather module It lacks a lot of information given by onecall

**Comment by ThSGM** [comment]
@JimHutchins Just chiming in as well to say that I was interested in the script that generates the detailed weather info.

**Comment by JimHutchins** [comment]
The files I modified are attached.

I suspect there may be a better (more official) way to do this, but it worked for me.

Sorry for the slow reply. I've been buried.

________________________________

**Comment by JimHutchins** [comment]
The files I modified are attached.

I suspect there may be a better (more official) way to do this, but it worked for me.

Sorry for the slow reply. I've been buried.

________________________________
