### ISSUE TITLE
Forecast module only 2days forecasting...

### ISSUE THREAD

**Issue by joinsik** [MichMich/MagicMirror#2126]
I have a problem for Weather Forecast module.
The default forecasting days is 7days, but My module return only 2days.

my confing.js is below..

Can I know what is the problem?

raspberry 3B+ buster
magic mirror version : "2.12.0"

================================
{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Wonju",
				locationID: "1833105", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "868918dfbf6fb44203c74ab50xxxxxxx"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "Wonju",
				locationID: "1833105", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "868918dfbf6fb44203c74ab50xxxxxxx"
			}
		},

**Comment by sdetweil** [comment]
please read the top item on the forum section  for the workaround til next release
https://forum.magicmirror.builders/category/10/troubleshooting
