### ISSUE TITLE
MagicMirror run error due to MMM-Google Assistant error

### ISSUE THREAD

**Issue by alectunney** [MichMich/MagicMirror#2131]
## I found a bug in MagicMirror

Please make sure to only submit reproducible issues. You can safely remove everything above the dividing line.
When submitting a new issue, please supply the following information:

**Platform**:  Raspberry Pi 4 with Magic Mirror 2.12, MMM-GoogleAssistant Version: 2.4.11,    [A2D] MMM-Assistant2Display Version: 2.3.15
(Updated GA Module and MM today)

**Node Version**: Make sure it's version 8 or later.

**MagicMirror Version**: 2.12
**Description**: MM Runs and then stops due to errors:
[2020-09-20 15:37:43.963] [LOG]    [A2D] MMM-Assistant2Display Version: 2.3.15
[2020-09-20 15:37:44.158] [INFO]   Checking git for module: MMM-GoogleAssistant
[2020-09-20 15:37:44.198] [INFO]   Checking git for module: MMM-Assistant2Display
[2020-09-20 15:37:44.266] [INFO]   Checking git for module: MMM-Globe
[2020-09-20 15:37:44.314] [INFO]   Checking git for module: MMM-ModuleScheduler
[2020-09-20 15:37:44.374] [INFO]   Checking git for module: MMM-GoogleBirthdaysProvider
[2020-09-20 15:37:44.422] [INFO]   Checking git for module: MMM-Screencast
[2020-09-20 15:37:44.458] [INFO]   Checking git for module: MMM-Remote-Control
[2020-09-20 15:37:44.503] [INFO]   Checking git for module: MMM-Formula1
[2020-09-20 15:37:44.554] [INFO]   Checking git for module: MMM-GooglePhotos
[2020-09-20 15:37:44.611] [INFO]   Checking git for module: MMM-CurrencyExchange
[2020-09-20 15:37:44.658] [INFO]   Checking git for module: MMM-MoonPhase
[2020-09-20 15:37:46.069] [LOG]    [CAST] Cast v1.0.0 Initialized...
[2020-09-20 15:37:46.178] [LOG]    [SPOTIFY] Launch Librespot...
[2020-09-20 15:37:46.193] [LOG]    [NPM] Initialized v0.9.9
[2020-09-20 15:37:46.631] [LOG]    [A2D] Assistant2Display is initialized.
[2020-09-20 15:37:46.633] [ERROR]  Whoops! There was an uncaught exception...
[2020-09-20 15:37:46.634] [ERROR]  Error: listen EADDRINUSE: address already in use :::8569
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at Function.listen (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/express/lib/application.js:618:24)
    at DialServer.start (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/@bugsounet/cast/index.js:90:23)
    at Class.addons (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_helper.js:1:5119)
    at Class.initialize (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_helper.js:1:3606)
    at MD5.cb (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_helper.js:1:847)
    at MD5.start (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/@bugsounet/md5/index.js:1:1820) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8569
}
[2020-09-20 15:37:46.645] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-09-20 15:37:46.646] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-09-20 15:37:46.706] [ERROR]  [MD5] MMM-GoogleAssistant sources edited !
[2020-09-20 15:37:46.707] [ERROR]  [MD5] You don't have permission to do this
[2020-09-20 15:37:46.707] [ERROR]  [MD5] Maybe... You don't have permission to USE MMM-GoogleAssistant in MagicMirror! (thx to @MichMich)
[2020-09-20 15:37:46.708] [ERROR]  [MD5] Exiting MagicMirror...

**Steps to Reproduce**: ~/MagicMirror $ npm run start
(Since getting update notification for GA and GA2D

**Expected Results**: MM Run

**Actual Results**: [2020-09-20 15:37:46.645] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-09-20 15:37:46.646] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-09-20 15:37:46.706] [ERROR]  [MD5] MMM-GoogleAssistant sources edited !
[2020-09-20 15:37:46.707] [ERROR]  [MD5] You don't have permission to do this
[2020-09-20 15:37:46.707] [ERROR]  [MD5] Maybe... You don't have permission to USE MMM-GoogleAssistant in MagicMirror! (thx to @MichMich)
[2020-09-20 15:37:46.708] [ERROR]  [MD5] Exiting MagicMirror...

**Configuration**: 

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "0.0.0.0", 	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
					// you must set the sub path here. basePath must end with a /
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.0.1/180", "192.168.0.1/24"], 	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"],
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "alert",
		},
		{
			 module: "MMM-GoogleAssistant",
			 position: "fullscreen_above",
			 config: {
			   debug: false,
			   assistantConfig: {
			     lang: "en-US",
			     projectId: "", // Required to use gaction.
			     modelId: "", // (OPTIONAL for gaction)
			     instanceId: "", // (OPTIONAL for gaction)
			     latitude: ,
			     longitude: ,
			   },
			   responseConfig: {
			     useScreenOutput: true,
			     screenOutputCSS: "screen_output.css",
			     screenOutputTimer: 5000,
			     screenRotate: false,
			     activateDelay: 250,
			     useAudioOutput: true,
			     useChime: true,
			     newChime: false,
			     useNative: false,
			     playProgram: "mpg321"
			   },
			   micConfig: { // put there configuration generated by auto-installer
			     recorder: "arecord",
			     device: "plughw:2",
			   },
			   customActionConfig: {
			     autoMakeAction: false,
			     autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
			     actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
			   },
			   snowboy: {
			     usePMDL: false,
			     audioGain: 2.0,
			     Frontend: true,
			     Model: "jarvis",
			     Sensitivity: null
			   },
			   A2DServer: {
			     useA2D: true,
			     stopCommand: "stop"
			   },
			   recipes: [ "with-MMM-TelegramBot.js" ],
			   NPMCheck: {
			     useChecker: true,
			     delay: 10 * 60 * 1000,
			     useAlert: true
			   }
			 }
		},
		{
		  module: "MMM-Assistant2Display",
		  position: "top_left",
		  config: {
		    debug:false,
		    useYoutube: true,
		    links: {
		      useLinks: true,
		      displayDelay: 60 * 1000,
		      scrollStep: 25,
		      scrollInterval: 1000,
		      scrollStart: 5000,
		      scrollActivate: false,
		      verbose: false
		    },
		    photos: {
		      usePhotos: true,
		      displayDelay: 10 * 1000
		    },
		    volume: {
		      useVolume: true,
		      volumePreset: "ALSA",
		      myScript: null
		    },
		    briefToday: {
		      useBriefToday: false,
		      welcome: "brief Today"
		    },
		    screen: {
		      useScreen: false,
		      delay: 5 * 60 * 1000,
		      turnOffDisplay: true,
		      ecoMode: true,
		      displayCounter: true,
		      displayBar: false,
		      displayStyle: "Text",
		      text: "Auto Turn Off Screen:",
		      detectorSleeping: false,
		      governorSleeping: false,
		      displayLastPresence: true,
		      LastPresenceText: "Last Presence:",
		      rpi4: false
		    },
		    pir: {
		      usePir: false,
		      gpio: 21,
		      reverseValue: false
		    },
		    governor: {
		      useGovernor: false,
		      sleeping: "powersave",
		      working: "ondemand"
		    },
		    internet: {
		      useInternet: false,
		      displayPing: false,
		      delay: 2* 60 * 1000,
		      scan: "google.fr",
		      command: "pm2 restart 0",
		      showAlert: true
		    },
		    // Deprecied since 2.3.13, already installed on MMM-TelegramBot
		    //TelegramBot: {
		    //  useTelecastSound: false,
		    //  TelecastSound: "TelegramBot.ogg"
		    //},
		    cast: {
		      useCast: true,
		      castName: "",
		      port: 8569
		    },
		    spotify: {
		      useSpotify: true,
		      useIntegred: true,
		      useLibrespot: true,
		      connectTo: "Lt",
		      playDelay: 3000,
		      minVolume: 10,
		      maxVolume: 100,
		      updateInterval: 1000,
		      idleInterval: 10000,
		      username: "",
		      password: "",
		      CLIENT_ID: "",
		      CLIENT_SECRET: "",
		      deviceDisplay: "",
		      usePause: true
		    },
		    NPMCheck: {
		      useChecker: true,
		      delay: 10 * 60 * 1000,
		      useAlert: true
		    }
		  }
		},
		{
			module: 'MMM-Globe',
			position: 'center',
			config: {
				style: 'europeDiscNat',
				imageSize: 600,
				ownImagePath:'',
				updateInterval: 10*60*1000
			}
		},
		{
       			module: 'MMM-ModuleScheduler'
    		},
		{
    			module: "MMM-GoogleBirthdaysProvider",
    			config: {}
		},
        	{
			module: 'MMM-Screencast',
			position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
			config: {
				position: 'center',
				height: 600,
				width: 1000,
			}
      		},  
		{
			module: 'MMM-Remote-Control',
			// uncomment the following line to show the URL of the remote control on the mirror
			// , position: 'bottom_left'
			// you can hide this module afterwards from the remote control itself
			config: {
			    apiKey: ''
			}
		},
		{
      			module: 'MMM-Formula1',
        		position: 'bottom_right',
        		header: 'F1 Standings',
        		config: {
            		// Optional configuration options - see https://github.com/ianperrin/MMM-Formula1#configuration-options
       																	 }
    		},
		{
  			module: "MMM-GooglePhotos",
  			position: "bottom_left",
  			config: {
				albums: [""], // Set your album name. like ["My wedding", "family share", "Travle to Paris"]
				updateInterval: 1000 * 10, // minimum 10 seconds.
				sort: "random", // "old", "random"
				uploadAlbum: null, // Only album created by `create_uploadable_album.js`.
				condition: {
					fromDate: null, // Or "2018-03", RFC ... format available
					toDate: null, // Or "2019-12-25",
					minWidth: null, // Or 400
					maxWidth: null, // Or 8000
					minHeight: null, // Or 400
					maxHeight: null, // Or 8000
					minWHRatio: null,
					maxWHRatio: null,
					// WHRatio = Width/Height ratio ( ==1 : Squared Photo,   < 1 : Portraited Photo, > 1 : Landscaped Photo)
				},
				showWidth: 216, // These values will be used for quality of downloaded photos to show. real size to show in your MagicMirror region is recommended.
				showHeight: 384,
				timeFormat: "YYYY/MM/DD HH:mm", // Or `relative` can be used.
  			}
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: ""				}
					
				]
			}
		},
		{
 			module: "calendar",
			header: "Birthdays",
 			position: "top_left",
 			config: {
				maximumEntries: 5,
				displayRepeatingCountTitle: true,
 				calendars: [
 					{
 						url: '',
 						symbol: 'birthday-cake',
 						color: '#ff0000'										}
 				]
 			}
 		},
		{              
          		module: "calendar",
                        header: "F1 Calendar",
                        position: "top_left",
                        config: {
                                maximumEntries: 3,
				calendars: [
                                        {
                                                symbol: 'flag-checkered',
                                                url: "http://localhost:8080/MMM-Formula1/schedule.ics"                                }
                                ]
                        }
                },

		{
			module: "compliments",
			position: "bottom_bar"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Pretoria",
				locationID: "", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: ""
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "Pretoria",
				locationID: "
![Error](https://user-images.githubusercontent.com/71595582/93713034-be349680-fb59-11ea-8231-88e3de28942c.png)
", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: ""
			}
		},
		{
			disabled: true,
			module: "MMM-NewsFeedTicker",
			position: "top_bar",
			//classes: "day_scheduler",
			config: {
	    			feeds: [
				{
					title: "News24",
					url: "http://feeds.news24.com/articles/News24/TopStories/rss",
					customLogo: "news24.png"
				},
				{
					title: "My Broadband",
					url: "https://www.feedspot.com/infiniterss.php?_src=feed_title&followfeedid=4885742&q=site:https",
					customLogo: "MB.jpeg"
				},
                                {
                                        title: "MoneyWeb",
                                        url: "moneyweb.co.za/rss",
                                        customLogo: "MW.png"
                                },
				{
					title: "eNCA",
					url: "http://www.enca.com/rss/top-stories",
					customLogo: "enca.jpeg"
				}
		    	    ]
			}
    		},
		{
		  module: 'MMM-CurrencyExchange',
		  position: 'top_right',
		  config: {
		    base: 'USD',
		    symbols: ['ZAR']
		  }
		},
		{
			module: "MMM-MoonPhase",
			position: "top_right",
			config: {
				updateInterval: 43200000,
				hemisphere: "S",
				resolution: "detailed",
				basicColor: "white",
				title: true,
				phase: true,
				x: 200,
				y: 200,
				alpha: 0.7
			}
		},	
		{
			module: "newsfeed",
			position: "top_bar",
			config: {
				feeds: [
					{
						title: "News24 SA",
						url: "http://feeds.news24.com/articles/News24/TopStories/rss"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Additional Notes**: Provide any other relevant notes not previously mentioned. This is optional.p
![Error](https://user-images.githubusercontent.com/71595582/93712710-cb508600-fb57-11ea-8c55-ba89c907bb5e.png)
![Error](https://user-images.githubusercontent.com/71595582/93713040-ca205880-fb59-11ea-9c60-93093d6b1be4.png)

**Comment by rejas** [comment]
I see these lines:
"
[2020-09-20 15:37:46.706] [ERROR] [MD5] MMM-GoogleAssistant sources edited !
[2020-09-20 15:37:46.707] [ERROR] [MD5] You don't have permission to do this
[2020-09-20 15:37:46.707] [ERROR] [MD5] Maybe... You don't have permission to USE MMM-GoogleAssistant in MagicMirror! (thx to @MichMich)
"

The MMM-GoogleAssistant seems to complain that you edited the sources. Not sure what the core of MagicMirror can do here, so please redirect your issue to the MMM-GoogleAssistant repository of @bugsounet...

**Comment by bugsounet** [comment]
`Maybe... You don't have permission to USE MMM-GoogleAssistant in MagicMirror!` 

I force update GA to not using it in Original MagicMirror and close the MM app (Yes ... the Little developer can do this, sorry)

@rejas: You can close this issue ;)
