### ISSUE TITLE
in #2135 we removed the ical nodejs module, as the default modules don't need it. but 3rd party calendar modules may. 

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2138]
## I'm not sure if this is a bug

should we keep it to support those other calendar modules?

**Comment by MichMich** [comment]
That's an interesting point. I would say: just keeping removed. But let's see what the forum users say.

**Comment by rejas** [comment]
How about leaving ical in there but add a warning notice, that it will go away with 1.1.2021 ?

**Comment by MichMich** [comment]
Yeah, that sounds like a reasonable idea.

**Comment by MichMich** [comment]
Closed, since we merged the solution. Thanks Sam!

**Comment by sdetweil** [comment]
see https://forum.magicmirror.builders/topic/13745/warning-warning-2-13-advisory-calendar-module-changes
