### ISSUE TITLE
MMM-Freebox

### ISSUE THREAD

**Issue by jeff44850** [MichMich/MagicMirror#2148]
Bonjour
Je ne sais pas si je suis au bon endroit.
Ce module de bugsounet est superbe.
Je donne des news sur l'installation avec la Freebox pop.
Tout fonctionne parfaitement mise a part l'affichage de la free tv comme il s'en doutait ( Android TV ).
Superbe taf en tout cas .!!

**Comment by rejas** [comment]
Please post questions and problems with @bugsounet s modules directly at his repos.

**Comment by sdetweil** [comment]
I think you can close this one as 'wrong repo'.

**Comment by MichMich** [comment]
Please open an issue in the MMM-Freebox repo. Thanks.
