### ISSUE TITLE
How do you quit?

### ISSUE THREAD

**Issue by LimeBlast** [MichMich/MagicMirror#215]
Sorry if this is a silly question, but if you've used `npm start` on the v2 beta branch to run electron, how do you then quit out of it - such as because you want to modify the config.

I've had a look at the readme, but haven't been able to find the answer.

Thank you

**Comment by MichMich** [comment]
`ctrl-c` :)

**Comment by LimeBlast** [comment]
Sorry, tried that, it didn't work.

**Comment by CFenner** [comment]
Restart :)

I recommend the [pm2](https://github.com/MichMich/MagicMirror/wiki/Auto-Starting-MagicMirror), its's great.

**Comment by paviro** [comment]
Where did you try? In the command line or the interface? You can toggle the menus with "alt" I think and quit from there.

**Comment by LimeBlast** [comment]
I tried it from the interface (because the command line was hidden by the fullscreen interface).

However, hitting `alt` made the menus appear, from which I could quit, but also revealed that `ctrl-w` also works to quit.

Thank you everyone.

**Comment by shivanraptor** [comment]
As of the latest version on Raspbian Jessie on Raspberry Pi 3 , **Ctrl-Q** did the trick.

**Comment by issagak** [comment]
Thanks Paviro

**Comment by Caraballo114** [comment]
Thanks shivanraptor!!

**Comment by onkararj** [comment]
how can i stop mm from restarting bcoz of pm2. .plz help..

**Comment by dexterbeng** [comment]
Thanks shivanraptor!

**Comment by mfread** [comment]
After some experimentation, I found ctrl-q on my Pi2B with Raspbian Stretch to work.

**Comment by guillaumesoul** [comment]
maybe pm2 stop mm

**Comment by OllieBoi** [comment]
Please help me it's taken over my pi and I can't quit it. When I do ctrl Q it quits it then restarts. I need help

**Comment by CassBru** [comment]
@OllieBoi Connect a Keyboard & Mouse to the pi
1. Press Windows Key
2. Open up Terminal
3. Type pm2 stop mm
4. Press Windows Key
5. Open up Terminal
6. Type pm2 stop MagicMirror

When your ready to get it going again just type the same commands but with start.
Hope that works,

**Comment by gilmedel** [comment]
You can use ctrl-M to minimize the window and return to the desktop, and from there return to the terminal where you typed npm start.

**Comment by amansingh9097** [comment]
well `Ctrl+Q` exits you out of the MagicMirror session.
(you don't really have to minimize or go to Ctrl or anything)

**Comment by syedazharali880** [comment]
Press ctrlQ the go to terminal and type "pm2 stop MagicMirror" then hit enter.

**Comment by jningtho** [comment]
> Please help me it's taken over my pi and I can't quit it. When I do ctrl Q it quits it then restarts. I need help

> ctrl+Q
> pm2 stop magicmirror <enter>

** This worked for me.
