### ISSUE TITLE
when multiple calendars are configured, subsequent fetches only fetch the last entry in the array

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2160]
this is a timing problem. 

the list of cals is processed, and a timer is started for each

but, when the timer invokes the refresh addCalendar , the variable 'calendar' has long since been set to the last cal entry in the array, and will never change

fix,
move the setInterval (actually setTimer)  into the addCalendar routine to have non-volatile access to the parameters

pr coming

**Comment by MichMich** [comment]
Merged.
