### ISSUE TITLE
Nao funciona no Win 10

### ISSUE THREAD

**Issue by deniscdartes** [MichMich/MagicMirror#2179]
> magicmirror@2.13.0 start C:\Users\Denis\MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

'DISPLAY' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.13.0 start: `DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the magicmirror@2.13.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Denis\AppData\Roaming\npm-cache\_logs\2020-10-27T00_33_04_321Z-debug.log

**Comment by sdetweil** [comment]
not supported on Windows out of the box

do the following
```
cd MagicMirror
cd vendor
npm install
cd ..
cd fonts
npm iinstall
cd ..
```
edit package.json and change the start line from 
```
  "start":"DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js"
```
to
```
  "start":"node_modules/.bin/electron js/electron.js"
```

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
