### ISSUE TITLE
Pi & Wifi connection

### ISSUE THREAD

**Issue by CFenner** [MichMich/MagicMirror#218]
Hi,

my magic mirror is up and running, but after some days the wifi is going down. Now the pi is unreachable again and the weather is out of sync like here #187.

Did anyone also encounter this problem? Any Ideas how to solve this? 

I use the [EDIMAX](http://www.amazon.de/EDIMAX-EW-7811UN-Wireless-Adapter-IEEE802-11b/dp/B003MTTJOY) wifi adapter.

**Comment by MichMich** [comment]
You could try this: https://learn.adafruit.com/adafruits-raspberry-pi-lesson-3-network-setup/test-and-configure#fixing-wifi-dropout-issues

Also make sure You have a powerfull power supply. (2A minimum). That solved the issue for my 3D Printer Pi Connectivity Issues.

**Comment by CFenner** [comment]
hm.. I'm using a standard Apple power adapter, but the small one for iPhones. 

Thanks for the link..

**Comment by CFenner** [comment]
Ok, change the settings, I'll report in 3 days if the problem is solved ;)

**Comment by CFenner** [comment]
It's down again :(

**Comment by MichMich** [comment]
:( Maybe try an other wifi adapter. Or check your access point settings.

**Comment by CFenner** [comment]
So I restarted today and did a fresh pull. 
Now here it's Thuesday but the forecast shows Monday and all other modules are working and have a connection. SSH is working as well.

**Comment by CFenner** [comment]
Btw is the forecast supposed to display today's or tomorrow's weather?

**Comment by MichMich** [comment]
Forecast shows whatever it gets from open weather. Usually that starts from today.

**Comment by CFenner** [comment]
Which wifi adapter do you use?

**Comment by MichMich** [comment]
Would it be ok for you to proceed any further discussion of this issue on: https://forum.magicmirror.builders? This way I can limit the use of GitHub issues to bug reports.

**Comment by CFenner** [comment]
Good idea.

**Comment by ArmandoRodriguez94** [comment]
To piggy back on this if I may I recently started setting mine up and was wondering if when I move the Pi to a different location will it auto connect to wifi that it has had in the past and if not is there something I can install that will make it do so?

**Comment by sdetweil** [comment]
it will reconnect if it can get a signal
