### ISSUE TITLE
No config file 

### ISSUE THREAD

**Issue by jasb1011** [MichMich/MagicMirror#2181]
Hello, I had recently finished updating my magic mirror to 2.13 but I had problems along the way so I followed the steps in the first picture but when I restarted MM it lead me to a screen that said I had no config file.

Any help would be appreciated thank you.

![F9F6615C-9F2C-424A-81E6-8EFDC7B4C03C](https://user-images.githubusercontent.com/46883092/97761196-12288880-1ad3-11eb-9be3-5c8cb9d64a32.png)
![3DE7E6A7-224A-420A-BEB5-B13ECE36EC19](https://user-images.githubusercontent.com/46883092/97761198-1359b580-1ad3-11eb-8535-9a6370a14d4a.jpeg)

**Comment by sdetweil** [comment]
what did u do to update? 

did the npm install work?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
