### ISSUE TITLE
Windspeed convertion error in ukmetoffice Weather module 

### ISSUE THREAD

**Issue by Sub028** [MichMich/MagicMirror#2189]
Hi,
I think that formula which convert mph to m/s in default module Weather is wrong.

**MagicMirror Version**: v2.13.0

**Description**: to convert windInMph to metric units (m/s), the value should be divided by 2.23694, not multiplied.

https://github.com/MichMich/MagicMirror/blob/3220702034ec9975c3c86c858124bf2245f0ec30/modules/default/weather/providers/ukmetoffice.js#L214

should be:

`return this.windUnits === "metric" ? windInMph / 2.23694 : windInMph;`

**Actual Results**: if windInMph is equal to 8 (and this.windUnits === metric), then result is 17.89552

**Expected Results**: the expected result is 3.57632

**Additional Notes**: [Google converter](https://www.google.com/search?client=firefox-b-d&ei=SdCnX9GOBKiI1fAPtvC_yAI&q=mph+to+ms&oq=mph+to+ms&gs_lcp=CgZwc3ktYWIQAzICCAAyBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BAgAEEc6BAgAEEM6BwgAELEDEEM6CAgAELEDEIMBOggILhCxAxCDAToFCAAQsQM6BwguELEDEEM6BAgAEApQhyVYsTFggjNoAHACeACAAZcBiAHdB5IBAzMuNpgBAKABAaoBB2d3cy13aXrIAQjAAQE&sclient=psy-ab&ved=0ahUKEwiR17uP5vLsAhUoRBUIHTb4DykQ4dUDCAw&uact=5)

**Comment by rejas** [comment]
Can this be closed now @Sub028 since the PR got merged?
