### ISSUE TITLE
Show event ocurring today

### ISSUE THREAD

**Issue by tacul** [MichMich/MagicMirror#22]
Hi, is there a way to show the events in the calendar which are ocurring the same day?

Thanks!

**Comment by dmbrenneman** [comment]
In calendar.js find
![image](https://cloud.githubusercontent.com/assets/16940571/12649197/8e0c7e7a-c5ab-11e5-957c-7801b7aeef5f.png)
and change to:
![image](https://cloud.githubusercontent.com/assets/16940571/12649211/9d9b2382-c5ab-11e5-8f07-781ae3173a05.png)

**Comment by MichMich** [comment]
This might be a nice (or configurable) default behavior. Feel free to send a pull request.
