### ISSUE TITLE
change base branch for pull requests

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2203]
Mich, could u change the base branch in the repo settings so we can't accidentally PR to master..

**Comment by rejas** [comment]
As long as it gets documented in the docs, I approve this!

**Comment by sdetweil** [comment]
I don't think anything about PRs is in the docs now..  and everyone does pr to master, which is wrong.. 

lets prevent all that trouble

**Comment by sdetweil** [comment]
but it says this

The default branch is considered the “base” branch in your repository, against which all pull requests and code commits are automatically made, **unless you specify a different branch.**

**Comment by MichMich** [comment]
Yes. But it also specifies which branch somebody sees at first glance when he/she visits the repo. Or which branch they pull when they don't define a specific branch while pulling.

**Comment by sdetweil** [comment]
booooooo

**Comment by sdetweil** [comment]
closing...dang it!..

**Comment by MichMich** [comment]
But maybe good to know. You can always simply change the branch to which you made a PR. You don't need to make a new PR. 

And usually when I see it's the wrong branch, I just change it. 

(Can't make a screenshot on how to do it since I'm on mobile.)

Also good to know: the master branch is protected. So I can never accidentally merge into master.

**Comment by sdetweil** [comment]
yes, I knew all that, but just another annoying thing to take care of.. 

my problem is catching up to where develop is.. without having to make a new fork..

**Comment by MichMich** [comment]
Never tried it but can't you do something like `git merge origin/master`?

**Comment by sdetweil** [comment]
not master.. develop..   I got behind, you did a bunch of merges, I want to submit a new PR but am behind..  so I pull from develop to my local, should be in synch.. now push to my fork... oops..  unknown commits.. so when I create a PR they all come too... look at the closed PR 2201

**Comment by MichMich** [comment]
Yeah. Sorry develop. Edited my reply but you were to quick. 
Maybe you can do a rebase in stead of a merge.

**Comment by sdetweil** [comment]
will try rebase next time
