### ISSUE TITLE
Google assistant virtual environment- not launching after input of device id and model id

### ISSUE THREAD

**Issue by akeysny** [MichMich/MagicMirror#2218]
## I'm not sure if this is a bug

If you're not sure if it's a real bug or if it's just you, please open a topic on the forum: [https://forum.magicmirror.builders/category/15/bug-hunt](https://forum.magicmirror.builders/category/15/bug-hunt)

## I'm having troubles installing or configuring MagicMirror
![GoogleAssistDemo](https://user-images.githubusercontent.com/69605343/100533529-8e49e500-31d3-11eb-84d8-9e9155399979.gif)
#2217 

Problems installing or configuring your MagicMirror? Check out: [https://forum.magicmirror.builders/category/10/troubleshooting](https://forum.magicmirror.builders/category/10/troubleshooting)

## I found a bug in the MagicMirror installer

If you are facing an issue or found a bug while trying to install MagicMirror via the installer please report it in the respective GitHub repository:
[https://github.com/sdetweil/MagicMirror_scripts](https://github.com/sdetweil/MagicMirror_scripts)

## I found a bug in the MagicMirror Docker image

If you are facing an issue or found a bug while running MagicMirror inside a Docker container please create an issue in the GitHub repository of the MagicMirror Docker image:
[https://github.com/bastilimbach/docker-MagicMirror](https://github.com/bastilimbach/docker-MagicMirror)

---

## I found a bug in MagicMirror

Please make sure to only submit reproducible issues. You can safely remove everything above the dividing line.
When submitting a new issue, please supply the following information:

**Platform**: Place your platform here... give us your web browser/Electron version _and_ your hardware (Raspberry Pi 2/3, Windows, Mac, Linux, System V UNIX).

**Node Version**: Make sure it's version 8 or later.

**MagicMirror Version**: Please let us now which version of MagicMirror you are running. It can be found in the `package.log` file.

**Description**: When running env in Google Assistant module a sample code- says that there's an unexpected error when inputting model id
**Steps to Reproduce**: pi@raspberrypi:~/MagicMirror/modules/MMM-GoogleAssistant $ 

python -m pip install --upgrade google-auth-oauthlib[tool]

googlesamples-assistant-pushtotalk --project-id my-dev-project --device-model-id my-model
/After this step I get an error
**Expected Results**: Describe what you expected to see.

**Actual Results**: Describe what you actually saw. 
Usage: googlesamples-assistant-pushtotalk [OPTIONS]

Error: Got unexpected extra argument (_______)
**Configuration**: What does the used config.js file look like? Don't forget to remove any sensitive information!

**Additional Notes**: Provide any other relevant notes not previously mentioned. This is optional.
So, I am looking for the assistant start chatting with me, where could be the problem? My credentials.json file works just fine giving me auth code.

**Comment by MichMich** [comment]
Please open an issue in de repo of the module.
