### ISSUE TITLE
Black page / no helper started

### ISSUE THREAD

**Issue by paviro** [MichMich/MagicMirror#222]
I just updated my mirror to the latest version, now all I get is a black page. The node helpers also do not seem to get loaded. No errors. Not in the web inspector and not in the command line.

**Comment by MichMich** [comment]
Which node version are you running? What does 'node serveronly' do?

**Comment by paviro** [comment]
Same thing with `node serveronly`.
Node Version: `v5.10.1`
System: `Mac OS X`

**Comment by MichMich** [comment]
What's the output in your terminal?

**Comment by paviro** [comment]
Output is like always.

> Loading config ...
> Loading module helpers ...
> Initializing new module helper ...
> No helper found for module: clock.
> No helper found for module: test_module.
> No helper found for module: alert.
> Initializing new module helper ...
> Initializing new module helper ...
> Initializing new module helper ...
> No helper found for module: compliments.
> No helper found for module: current weather
> No helper found for module: weather forecast
> Initializing new module helper ...
> Initializing new module helper ...
> All module helpers loaded.
> Starting server op port 8080 ... 
> Server started ...
> Connecting socket for: MMM-Facial-Recognition
> Staring module helper: MMM-Facial-Recognition
> Connecting socket for: MMM-FRITZ-Box-Callmonitor
> Starting module: MMM-FRITZ-Box-Callmonitor
> Connecting socket for: MMM-Traffic
> MMM-Traffic helper started ...
> Connecting socket for: calendar
> Starting node helper for: calendar
> Connecting socket for: MMM-Wunderlist
> Connecting socket for: newsfeed
> Starting module: newsfeed
> Sockets connected & modules started ...
> 
> Ready to go! Please point your browser to: http://localhost:8080..

**Comment by MichMich** [comment]
Try removing all modules and adding them one by one.

**Comment by paviro** [comment]
Removing the calendar did the trick.

**Comment by MichMich** [comment]
Did you make any changes to the calendar module?

**Comment by paviro** [comment]
No

**Comment by MichMich** [comment]
And no console errors?

**Comment by paviro** [comment]
Nop 😐

**Comment by MichMich** [comment]
![](http://weknowmemes.com/wp-content/uploads/2011/11/impossibru-guy.jpg)

**Comment by paviro** [comment]
Yeah.... Exactly my reaction 😳

**Comment by MichMich** [comment]
So it stops with the calendar. It doesn't continue.

**Comment by paviro** [comment]
Seems like it but how isn't there any error?

**Comment by MichMich** [comment]
Got no clue.

**Comment by paviro** [comment]
Any idea how to debug? 😕

**Comment by MichMich** [comment]
What if you leave the config part of the calendar empty?

**Comment by paviro** [comment]
No changes.

**Comment by paviro** [comment]
Problem only seems to appear with multiple calendars!

**Comment by MichMich** [comment]
Ok. If you find the big and send a pull request with fix, you don't have to bake me that pie anymore. ;)

**Comment by MichMich** [comment]
*bug

**Comment by paviro** [comment]
Could this be a problem with the new translation feature, when the same module is loaded twice?

**Comment by MichMich** [comment]
Could be. Does it occur when you use two calendar modules? Or when you use two calendar feeds in one module?

**Comment by paviro** [comment]
Two modules!

**Comment by MichMich** [comment]
Ok, give me one sec.

**Comment by MichMich** [comment]
Fixed. Please pull.

Thanks for the bug hunt.

**Comment by paviro** [comment]
Nice thanks! :)
