### ISSUE TITLE
when i enable my calender module my magic mirror gets blank 

### ISSUE THREAD

**Issue by Milen511999** [MichMich/MagicMirror#2220]
{
			module: "calendar",
			header: "CANADA Holidays",
			position: "top_left",
			config: {
					colored: false,
	coloredSymbolOnly: false,
	calendars: [
		{
			url: 'https://**********.ics',
			symbol: 'calendar',
		},
this is my code for my module

**Comment by sdetweil** [comment]
U are missing the 
end bracket ], for the calendar array
 brace }, for the config block
  and brace },  for the module entry

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
