### ISSUE TITLE
Calendar Enhancement - Set timezone like clock moodule

### ISSUE THREAD

**Issue by tomwoodhams** [MichMich/MagicMirror#2223]
## Enhancement

I like many people are having problems with timezones in Magic Mirror.
If we could configure the calendar to have an overriding timezone (like we can with the clock) it would solve this problem.

**Comment by sdetweil** [comment]
The calendar entries have timezones specified. There are many updates coming on next release , jan 1.

U xan test them in the develop branch. See the topic at the top of the troubleshooting  section of the forums for instructions

**Comment by sdetweil** [comment]
the calendar gets its timezone from the local system date/time setting

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
