### ISSUE TITLE
Compliments not loading

### ISSUE THREAD

**Issue by Try2Fly** [MichMich/MagicMirror#226]
I made the list with compliments longer. About 9-12 compliments per timeperiod. However, it seems the module is not loaded correctly anymore. Is there a limit on the number of compliments?

**Comment by MichMich** [comment]
No, it should be unlimited. Could you show the config? Maybe there is a typo.

**Comment by Try2Fly** [comment]
While making the file, I discovered a small " ' " in the beginning of a line. Deleted it, and its working. Thanks for your response. This can be closed
