### ISSUE TITLE
Stop Restarting of Mirror

### ISSUE THREAD

**Issue by nickroz7** [MichMich/MagicMirror#230]
What do I type into the terminal to stop the restarting of the magic mirror application? I need to make a few more changes to my code and I am unable to do this since the mirror autostarts every time I restart my raspberry pi. Thanks!

**Comment by MichMich** [comment]
How did you start it? Did you use the [PM2 method](https://github.com/MichMich/MagicMirror/wiki/Auto-Starting-MagicMirror)?

In that case: `pm2 stop mm`

**Comment by KirAsh4** [comment]
Personally I SSH into my rPi when I need to make changes to MM's config, then issue the pm2 restart command.
