### ISSUE TITLE
How to change modules size

### ISSUE THREAD

**Issue by finius04** [MichMich/MagicMirror#2358]
Hi,
How can I change the size of all of the modules, or effectively make my monitor into a bigger canvas.
Thanks,

**Comment by ashishtank** [comment]
@finius04 Did you tried zoom in or zoom out ?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
