### ISSUE TITLE
updateDom() should not fade header

### ISSUE THREAD

**Issue by paviro** [MichMich/MagicMirror#236]
When a module updates it content the header fades as well as the content. Since a module can't change the header I think it should be static, would look better if only the content would change.

**Comment by MichMich** [comment]
That's because it's (currently) tied to the show and hide method.

**Comment by paviro** [comment]
Any chance this could be changed in the future?

**Comment by MichMich** [comment]
You're free to send a pull request. ;)

**Comment by paviro** [comment]
Will see if I find the time. Currently working on my modules.

**Comment by MichMich** [comment]
Since this now updates the header as well, this is the correct behavior. Therefor closing this issue. :)
