### ISSUE TITLE
Translator can't substitute empty strings

### ISSUE THREAD

**Issue by MikeBishop** [MichMich/MagicMirror#2389]
**Platform**: Raspberry Pi 4

**Node Version**: 10.23.0

**MagicMirror Version**: 2.13.0

**Description**: In translator.js, the code checks whether a variable is present with the following code:

    return variables[varName] || "{" + varName + "}";

However, when the content of the variable is an empty string, this erroneously substitutes `{varName}` back in.    

**Steps to Reproduce**: Call `this.translate("something with {VAR}", {VAR: ""})`

**Expected Results**: If the variable is present with the empty string, the empty string should be substituted.  This could be achieved by using `return varName in variables ? variables[varName] : "{" + varName + "}";` instead.

**Actual Results**: Variable is not subsituted

**Comment by rejas** [comment]
Thanks for the report. Would you like to submit a PR for this issue?

**Comment by MichMich** [comment]
Could you give an example when this would be usefull?

**Comment by MikeBishop** [comment]
I initially used a substitution that contains "{HOURS}{LISTSEP}{MINUTES}", where each element is an empty string if that value is zero, and LISTSEP is `", "` if both are non-zero but `""` if only one is non-zero.  (If both are zero, we won't reach this code.)

There are other ways to build it, of course --  you can insert the string `" "` and let HTML collapse the whitespace, you can pick from multiple possible strings for the different possible combinations, etc.  But more generally, it's simply unexpected behavior that a variable that's present isn't substituted, no matter its value.

**Comment by MichMich** [comment]
Makes sense. Feel free to send a PR.

**Comment by rejas** [comment]
This issue can be closed I guess?
