### ISSUE TITLE
2.14 regression, not installed module produces no error

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2403]
I was helping user with MMM-WiFiPassword, it just displays a qr code

he had misspelled the name

to recreate
add this to your config.js 
```
        {
            module: "MMM-WiFiPassword1",
            position: "center",
              config: {
              //See 'Configuration options' for more information.
              network: "xxxxx",
              password: "xxxxxx",
	            showAuthType: false,
	            showNetwork: false,
	            showPassword: false,
	            debug: false
        		}
        }
```
i got  
No helper found for module: MMM-WiFiPassword1.

but not failure, because the module was missing

**Comment by rejas** [comment]
What was the behaviour pre-2.14 for this case?

**Comment by sdetweil** [comment]
magicMirror could not validate the config file
will not stop.....
(i think) have to go test

**Comment by MichMich** [comment]
I think this behavior did not change.

**Comment by sdetweil** [comment]
does not fail on 2.11...
should fail

**Comment by rejas** [comment]
Tried as far as v2.7.0 (below wouldnt start anymore on my Ubuntu). No warnings or error besides the " No helper found for module: MMM-WiFiPassword1. "

So not sure when / or if it was changed. But maybe something worth discussing: Shouldnt there be a more obvious warnin/error log that you have a config entry for a module that isnt there?

**Comment by sdetweil** [comment]
@rejas > Shouldnt there be a more obvious warnin/error log that you have a config entry for a module that isnt there?

thats my opinion...   users coming from windows make mistakes on letter casing and nothing works.. but they don't know why..

**Comment by rejas** [comment]
Re-opening since this might be useful feature (just ran into it myself)

**Comment by khassel** [comment]
This is the part of `app.js`

```js
		let loadHelper = true;
		try {
			fs.accessSync(helperPath, fs.R_OK);
		} catch (e) {
			loadHelper = false;
			Log.log(`No helper found for module: ${moduleName}.`);
		}
```

It is correct to do only a `log` here because not every module has a `node_helper.js`.

We could test before this part e.g. if the directory exists (and may its not empty) and otherwise do a `Log.error()`.

Would this solve this issue?
Other ideas?

**Comment by sdetweil** [comment]
directory and modulename js existing. not node_helper as optional

**Comment by khassel** [comment]
would be this:

```js
	function loadModule(module, callback) {
		const elements = module.split("/");
		const moduleName = elements[elements.length - 1];
		let moduleFolder = `${__dirname}/../modules/${module}`;

		if (defaultModules.includes(moduleName)) {
			moduleFolder = `${__dirname}/../modules/default/${module}`;
		}
// begin new
		const moduleFile = `${moduleFolder}/${module}.js`;

		try {
			fs.accessSync(moduleFile, fs.R_OK);
		} catch (e) {
			Log.error(`No ${moduleFile} found for module: ${moduleName}.`);
		}
// end new

		const helperPath = `${moduleFolder}/node_helper.js`;

		let loadHelper = true;
		try {
			fs.accessSync(helperPath, fs.R_OK);
		} catch (e) {
			loadHelper = false;
			Log.log(`No helper found for module: ${moduleName}.`);
		}
...
```

**Comment by sdetweil** [comment]
I guess. They should be able to resolve no file if the folder is missing too.  altho many times it's a case mismatch

some have no idea that all these things must match.
