### ISSUE TITLE
Magic Mirror will start with Gray screen only

### ISSUE THREAD

**Issue by MKS-ARI** [MichMich/MagicMirror#2418]
I installed Magic mirror on my Raspberry Pi. After installation, I am getting only a Gray screen and my camera turning on and showing camera video in this area. 
I am not sure what could be causing this. I took a picture on the startup screen not much conversant with the error EADDRINUSE !

![IMG-5106](https://user-images.githubusercontent.com/77482436/104698403-2c333980-56c6-11eb-8fa9-289b517bd1d0.PNG)

I installed it on my already installed Raspbian system not newly installed one.

Thanx

**Comment by rejas** [comment]
yeah, looks like something is already running in that adress/port. Thats why MM cant start.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
