### ISSUE TITLE
MMM-Climacell-Hourly by mykle1. Climacell data...

### ISSUE THREAD

**Issue by Mateo193** [MichMich/MagicMirror#2437]
Hello i have problem with module MMM-Climacell-Hourly by mykle1
logs:

> 0|MagicMirror  | Checking git for module: MMM-Climacell-Hourly
> 0|MagicMirror  | [2021-01-26 16:48:17.099] [INFO]
> 0|MagicMirror  | Checking git for module: MMM-Screencast
> 0|MagicMirror  | [2021-01-26 16:48:17.958] [ERROR]
> 0|MagicMirror  | Whoops! There was an uncaught exception...
> 0|MagicMirror  | [2021-01-26 16:48:17.963] [ERROR]
> 0|MagicMirror  | TypeError: result.slice is not a function
> 0|MagicMirror  |     at Request._callback (/home/pi/MagicMirror/modules/MMM-Climacell-Hourly/node_helper.js:46:33)
> 0|MagicMirror  |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
> 0|MagicMirror  |     at Request.emit (events.js:200:13)
> 0|MagicMirror  |     at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1154:10)
> 0|MagicMirror  |     at Request.emit (events.js:200:13)
> 0|MagicMirror  |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1076:12)
> 0|MagicMirror  |     at Object.onceWrapper (events.js:288:20)
> 0|MagicMirror  |     at IncomingMessage.emit (events.js:205:15)
> 0|MagicMirror  |     at endReadableNT (_stream_readable.js:1154:12)
> 0|MagicMirror  |     at processTicksAndRejections (internal/process/task_queues.js:84:9)
> 0|MagicMirror  | [2021-01-26 16:48:17.970] [ERROR]
> 0|MagicMirror  | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> 0|MagicMirror  | [2021-01-26 16:48:17.973] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

[Foto and config.js](https://imgur.com/EMNFLP0)

**Comment by sdetweil** [comment]
why didnt u.open this issue on his module site? he would look at it there, not a magicmirror problem
