### ISSUE TITLE
Is there any way that I can make Spotify to play from the magic mirror itself.

### ISSUE THREAD

**Issue by badshah424** [MichMich/MagicMirror#2444]

**Comment by rejas** [comment]
That question is better asked at the official forum:

https://forum.magicmirror.builders/

**Comment by sdetweil** [comment]
yes  you have to install librespot or raspotify.
libraries outside mm

**Comment by badshah424** [comment]
> yes  you have to install librespot or raspotify.
> 
> libraries outside mm

https://github.com/skuethe/MMM-Spotify
Using the above I modified my code using my premium account and yet the google assistant was not taking my commands to play songs on Spotify.

Can you please help.

Thanks

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
