### ISSUE TITLE
Calendar don't shows "It xx days"

### ISSUE THREAD

**Issue by Mateo193** [MichMich/MagicMirror#2445]
Hello, My Calendar module don't show "It xx days" "It xx weeks"
![image](https://user-images.githubusercontent.com/78036250/106392326-8dab1600-63f1-11eb-9451-67bf45d90e4b.png)

My config:

```
    {
      module: 'calendar',
      position: 'top_left',
      header: 'Calendars',
      config: {
        urgency: 7,
        timeFormat: "absolute",
        
          calendars: [
            {
              symbol: 'calendar-check',
              url: 'webcal://calendar.google.com'
            },
            {
              symbol: 'calendar',
              url: 'webcal://calendar.google.com'
            }
          ],
        }
    },
```

![image](https://user-images.githubusercontent.com/78036250/106392257-4c1a6b00-63f1-11eb-8278-c437334590ae.png)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
