### ISSUE TITLE
Clock Dissapeared

### ISSUE THREAD

**Issue by ChristianClover7** [MichMich/MagicMirror#2446]
For some reason my clock has dissapeared. any help would be greatly appreciated!

**Comment by rejas** [comment]
Hi @ChristianClover7 thanks for your report. Have you read the issue template while creating yours?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
