### ISSUE TITLE
Error in .jscsrc

### ISSUE THREAD

**Issue by paviro** [MichMich/MagicMirror#245]
```
Unexpected token (2:9) at ./.jscsrc.js :
     1 |{
     2 | "preset": "google",
-----------------^
     3 | "validateIndentation": "\t",
     4 | "validateQuoteMarks": "\"",
```

**Comment by MichMich** [comment]
Can you be a bit more specific? :)
- What file is this?
- Where was this error generated?
- What did you do?
- Can you recreate this issue?

**Comment by paviro** [comment]
The file is `jscsrc.js` in the root directory.
Error is generated when executing `jscs ./`.

**Comment by CFenner** [comment]
Looks like json, maybe js object notation is required?

**Comment by MichMich** [comment]
Honestly, I never use jscs ;) so can't help you with this. Check the history to see who added it. ;)

**Comment by MichMich** [comment]
Fixed.
