### ISSUE TITLE
Text in light grey

### ISSUE THREAD

**Issue by mcnahum** [MichMich/MagicMirror#2460]
I recently had to fully re-install my Magic Mirror and I can see that some of the text is "light grey" so I cannot clear read it.

any way to fix it?

![image](https://user-images.githubusercontent.com/30963862/108103058-ab32dd80-7089-11eb-97fa-8086b56eded6.jpeg)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by sdetweil** [comment]
@mcnahum did u have a custom.css before u reinstalled?  did u put it back

**Comment by mcnahum** [comment]
Yes I forgot about it ... and yes put it back it's fixing it
Thanks @sdetweil
