### ISSUE TITLE
How can i add my Nextcloud Calendars?

### ISSUE THREAD

**Issue by poltrian** [MichMich/MagicMirror#2467]
Nowadays it's good to have your data at home and not on Google or Apple. That's why I have a Nextcloud at home. How can I display the appointments in Magic Mirror?

**Comment by sdetweil** [comment]
you will have to download them to a local file... 
lots of folks do this..
i know the forums have people doing this..
https://forum.magicmirror.builders

**Comment by poltrian** [comment]
I tried these, put the local path in the cinfig file, but the ics would not be shown. Most online calendars have no ics, most you gent a link like http:zztztt.com/caldav.php/user/8787765654 or http:zztztt.com/caldav.php/user/calendarname

No other solution possible?

**Comment by sdetweil** [comment]
local path must be in MagicMirror folder tree.

mm web server root is the mm foldr  so /modules...... whereever.. it works..

of fike:///....

**Comment by poltrian** [comment]
Thanks, these is working very well 

url: "https://nextcloud.MYDOMAIN.xyz/remote.php/dav/calendars/USER/personal/?export",
user: "USER",
pass: "PASSW",
method: "basic",

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
