### ISSUE TITLE
replace request

### ISSUE THREAD

**Issue by khassel** [MichMich/MagicMirror#2468]
The `request` package is deprecated, see https://www.npmjs.com/package/request

So we should replace it with e.g. `node-fetch`.

It is used in 
- calendarfetcher.js
- newsfeedfetcher.js
- and several e2e tests

Can submit a PR, but want to discuss this before if this is wanted and if `node-fetch` is the right replacement.

**Comment by fewieden** [comment]
I also started moving my modules to `node-fetch` a while ago

**Comment by MichMich** [comment]
That sounds like a good idea!

**Comment by khassel** [comment]
thanks, will start working on this.

**Comment by khassel** [comment]
after looking into `package-lock.json` I realised that some dependencies are also still using `request`. These are
- `node-ical`
- `spectron` (only dev dependency)
- `jsdom` (only dev dependency)

So I can send my PR but instead of removing dependeny count we would get 4 more. Any suggestions?

**Comment by rejas** [comment]
I would still go for it. Having it replaced here is helpful. Waiting for the other libraries to remove it would take too much time. 

Maybe one could look if one can help the libraries (especially node-ical since it is the only non.dev dependency) to replace request?

**Comment by MichMich** [comment]
Closing this since it's merged. Let me know if I need to reopen.
