### ISSUE TITLE
is ical still needed?

### ISSUE THREAD

**Issue by khassel** [MichMich/MagicMirror#2469]
Found no require in the code, but comments in changelog that `ical` is replaced by `node-ical`. So can this be removed?

It produces some vulnerabilities (last release is older than 1 year).

**Comment by sdetweil** [comment]
yes, we left it in case there was a module that needed it

**Comment by khassel** [comment]
hmm, shouldn't modules install the needed dependencies on their own?

Or do you mean such things `const ical = require("../../node_modules/ical/ical.js");`?

Was removed in v2.13.0, may we should set an end date to get rid of it?

**Comment by MichMich** [comment]
I have no problem with just removing it ... a module can easily add it. And for users there is a super simple fix if it affects their installation.
