### ISSUE TITLE
iFrame Module

### ISSUE THREAD

**Issue by snrlaxx** [MichMich/MagicMirror#248]
Is it possible to create a model to show a simple iFrame?  I am new to these stuff so bear with me.

The iFrame I am trying to show is the following: 
`<Iframe src = "http://www.buienalarm.nl/widget/radar?location=Tilburg&color=4395c7" width = "500" height = "380"> </ iframe>
`

**Comment by MichMich** [comment]
This shouldn't be to difficult. A great way to learn how to make modules yourself :)
Just duplicate the helloworld module and start from there. More documentation can be found here: https://github.com/MichMich/MagicMirror/tree/v2-beta/modules
