### ISSUE TITLE
app.js folder

### ISSUE THREAD

**Issue by shgtjgh** [MichMich/MagicMirror#2497]
LS,
I changed something in the app.js file. and now the magicmirror won't start up anymore.
what is the default last sentence  wher it begins with " module.exports"
please help!

**Comment by rejas** [comment]
Assuming that you are using the latest release from MM (and that you might not have git skills) you can just copy the contents of this file:
https://raw.githubusercontent.com/MichMich/MagicMirror/master/js/app.js

**Comment by shgtjgh** [comment]
YES! thx very much!! I'm in again.

**Comment by shgtjgh** [comment]
Can I ask you another question what started this mishapp in the first place?
I run PM2 in the background but the refresh time is 3 seconds. Where can I change this? I thought it was in the app.js file, but nothing happened when i changed 3000 in 10000ms in process.on SIGINT and SIGTERM

**Comment by rejas** [comment]
PM2 is not part of the MM code, so there wont be anything in app.js that will change that.
From the top of my head I dont know how to change that so I suggest you ask that question in the official forums http://forum.magicmirror.builders (thats the place for support and troubleshooting).

**Comment by shgtjgh** [comment]
Thx I will do that. 

Verstuurd vanaf mijn iPhone

**Comment by sdetweil** [comment]
@shgtjgh what refresh time are u talking about?
mm is live, no delay. pm2 also has no delay. it is triggered by commands, file changes or some possible system interrupts... come to the forums so we can discuss your issue

**Comment by rejas** [comment]
Can this be closed now @shgtjgh ?
