### ISSUE TITLE
Wetter.de

### ISSUE THREAD

**Issue by Sammydk1984** [MichMich/MagicMirror#250]
Ist es möglich Wetter.de einzubinden?

**Comment by Sammydk1984** [comment]
Wenn ja kann mir das einer erläutern

**Comment by MichMich** [comment]
If you want any assistance, please use English for any communication.

**Comment by Sammydk1984** [comment]
Is it possible to integrate Wetter.de ?
Sorry vor my englisch.

**Comment by polzy** [comment]
follow this Issue https://github.com/MichMich/MagicMirror/issues/248

**Comment by MichMich** [comment]
@Sammydk1984 Currently not by default, but you can built your own module of course. Please check https://github.com/MichMich/MagicMirror/tree/v2-beta/modules for more info.
