### ISSUE TITLE
newsreader rewrite has wrong test for content wrap.. (should be if not) 

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2502]
## I found a bug in MagicMirror 2.15-develop

**MagicMirror Version**: Please let us now which version of MagicMirror you are running. It can be found in the `package.log` file.
2.15-develop

**Description**: Provide a detailed description about the issue and include specific details to help us understand the problem. Adding screenshots will help describing the problem.
old code says (!this.config.wrapDescription)? "noWrap":""
new code has if wrapDescription "noWrap" : ""

**Comment by rejas** [comment]
So this issue can be closed now @sdetweil ?
