### ISSUE TITLE
how does MM set the require path to include the module node_modules? (per module)

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2507]
##  this is not a bug, it is informational 

I have a require that is failing, but I thought it would be resolved by the node_modules in my module folder....
the required submodule IS there

**Comment by rejas** [comment]
Is there some code we can take a look at in github für your module?

**Comment by sdetweil** [comment]
not that I am ready to share...

but during runtime, I need to use a function from one of my dependencies(hardly ever needed) and I do the typical require('library_name') 
my module npm install put this library in the node_modules of my module (as expected) 

but the require fails, unable to locate  (so it seems to be searching the root node_modules folder)

I see ways to change the path dynamically FOR ALL using code..  but that doesn't seem to be how it works in MM.. 

but all that leads me to how does it ever work?  i don't see any override for require, and I don't know how you would change it on the fly (time, promise then.)  for module context.. so I am confused..

**Comment by rejas** [comment]
Normally what you describe should work: requiring your modules library in the node_module. I dont do it in my modules but looking at https://github.com/deg0nz/MMM-PublicTransportBerlin it doesnt require anything special... Maybe some typo?

**Comment by sdetweil** [comment]
which node_modukes? 

no  adding the path to it works,  but worries me

**Comment by rejas** [comment]
Weird, I cloned your repository, did the "npm install" and your module works.... What is the error you get?

**Comment by sdetweil** [comment]
that was just an example module.  why/how does it work?

**Comment by rejas** [comment]
the node js on the server side resolves that. you can go into your modules directory and start the node runtime (`node`) and issues this command in it to see where it looks:
`module.paths`

**Comment by sdetweil** [comment]
but we are not in the module folder during mm execution, we are in the mm folder. if I write a file with no pathname, it is located in the mm folder

**Comment by rejas** [comment]
See: https://www.freecodecamp.org/news/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8/
"The paths list is basically a list of node_modules directories under every directory from the current directory to the root directory."

**Comment by sdetweil** [comment]
yes, but the 'current' directory is mm. , NOT the module folder
AND the current directory doesn't change during mm execution

**Comment by rejas** [comment]
Mh..... I guess its some node magic or @MichMich knows it :-)

**Comment by sdetweil** [comment]
@khassel  yes, it has a setPath, but what has that got to do with it?

**Comment by rejas** [comment]
I think that path has nothing to do with the node_modules. Still, I can only imagine its some node.js magic that happens here....

**Comment by MichMich** [comment]
> HOW does module a find ITS dependencies in node_modules(a) (which won't be in node_modules(m))
Node looks in any `node_modules` folder relative to the script that includes the `require` call.

> HOW does module b find ITS dependencies in node_modules(b) (which won't be in node_modules(a) or node_modules(m))
This is the same situation: node looks in any `node_modules` folder relative to the script that includes the `require` call.
 
> later during execution (socket notification, or setTimeout or express inbound request) , module b needs access to one of its dependencies (q) using lazy loading and does a require('q')
> this dependency is loaded in node_modules(b) and NOT in node_modules(m)
> the current folder is STILL MagicMIrror
This is the same situation: node looks in any `node_modules` folder relative to the script that includes the `require` call.

> the modules.path (require path) WAS set to MagicMirror/node_modules...
I think this only impacts which path comes first. It will alway use the default locations if it can't find the module. It will look in the node_modules folder in the same folder as the script, and will traverse to parent folders to look for other node_module folders.

Does this answer the mystery?

**Comment by MichMich** [comment]
(Closed accidentally. Reopened.)

**Comment by sdetweil** [comment]
ok, maybe this is the explanation  that makes sense except for a few words
https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders

quoted test
Loading from node_modules folders#
If the module identifier passed to require() is not a core module, and does not begin with '/', '../', or './', then Node.js starts at the parent directory of the current module, and adds /node_modules, and attempts to load the module from that location. Node.js will not append node_modules to a path already ending in node_modules.

If it is not found there, then it moves to the parent directory, and so on, until the root of the file system is reached.

the few words are 
starts at the parent directory of the current module

**Comment by sdetweil** [comment]
i guess I answered my own question again!...
