### ISSUE TITLE
silly question. is it just the black reflection? what am i doing wrong?

### ISSUE THREAD

**Issue by jaydubelew** [MichMich/MagicMirror#2516]
I installed and ran MagicMirror successfully without any issues. So I see the weather and all the other cool stuff. 

However - the background of the screen is just black. Is the background of the screen supposed to change into something that shows a more mirror-type reflection, or is it that the black of the screen and the faint reflection you see is the mirror? I was expecting something that literally is almost indistinguishable from a mirror. Maybe I was hoping too much. 

The screen is a 65" vizio flatscreen. Using a Raspberry pi4. Fresh install. And again, all loaded well and without issue. Please advise. Thank you.

**Comment by sdetweil** [comment]
that's just the  tv screen reflection. mm doesnt provide any background other than black. there are extension modules that show pictures.

**Comment by rejas** [comment]
Or you modify your screen with a foil that turns it into a two way mirror. See the wiki entry here: https://github.com/MichMich/MagicMirror/wiki/Two-way-Mirror-Vendors

**Comment by jaydubelew** [comment]
> Or you modify your screen with a foil that turns it into a two way mirror. See the wiki entry here: https://github.com/MichMich/MagicMirror/wiki/Two-way-Mirror-Vendors

- thank you! knew I was missing something!
