### ISSUE TITLE
cc

### ISSUE THREAD

**Issue by B1gG** [MichMich/MagicMirror#2524]
### Fix wrong treatment of appendLocationNameToHeader when using ukmetofficedatahub
in the ukmetofficedatahub module you have 
```
		if (this.config.appendLocationNameToHeader) {
			queryStrings += "&includeLocationName=" + true;
		}
```
you should remove the if ... and leave just:
```
queryStrings += "&includeLocationName=" + true;
```
this will allow `appendLocationNameToHeader` parameter at weather.js to resolve if include or not in the header (title).

**Comment by B1gG** [comment]
Thanks guys

**Comment by MichMich** [comment]
Merged. Closing.
