### ISSUE TITLE
Codecov makes tests fail.

### ISSUE THREAD

**Issue by MichMich** [MichMich/MagicMirror#2528]
It's great to have some feedback on code coverage, but in some (useless) cases it makes the tests fail, marking the PR's as failed. 

IMHO CodeCov should just give some feedback as an insentive to add tests. But shouldn't have any effect on the status of a PR. 

A PR to fix this would be great, since I have no idea how to change this. (Haven't checked the docs yet, either. ;))

**Comment by rejas** [comment]
Agree. I opened an issue over there to ask if thats possible: https://github.com/codecov/codecov-action/issues/274

**Comment by MichMich** [comment]
Closed thank you @rejas' awesome detective work. :)
