### ISSUE TITLE
[Weather Module] decimalSymbol has no effect

### ISSUE THREAD

**Issue by KristjanESPERANTO** [MichMich/MagicMirror#2530]
I set the `decimalSymbol` in the config of the new weather module to `,`, but that has no effect. The values still have points. I saw that the PR #1510 should have fix that, but it doesn't work (anymore?).

I noticed this with a just freshly installed MagicMirror instance.

Or am I doing something wrong in my config?

```
    {
      module: "weather",
      position: "top_right",
      header: "Wetter in ?????",
      config: {
        appendLocationNameToHeader: false,
        decimalSymbol: ",",
        weatherProvider: "openweathermap",
        type: "forecast",
        location: "?????????",
        locationID: "?????????",
        maxNumberOfDays: 5,
        apiKey: "?????????",
      }
    }
```

**Comment by rejas** [comment]
Hi @KristjanESPERANTO I dont think you are doing somethign wrong. I took a quick look at the code and it seems to me the decimal point isnt used (yet) in the forecast part (only in the current weather part) of the module.

Maybe you want to write a fix for it? ;-)

**Comment by rejas** [comment]
Nevermind, I think I can fix that if you give me a day :-)

**Comment by KristjanESPERANTO** [comment]
I'm on it :slightly_smiling_face:

**Comment by rejas** [comment]
Nice. So lets see if your PR fixes my tests :-D

**Comment by rejas** [comment]
Did you have the time to test the latest develop branch to see if it fixes your problem for good now? So that we can close this ticekt?

**Comment by KristjanESPERANTO** [comment]
Yes, with the develop branch it works fine. Thank you :slightly_smiling_face:
