### ISSUE TITLE
open up discussions tab - please

### ISSUE THREAD

**Issue by B1gG** [MichMich/MagicMirror#2539]
GitHub has been supporting a discussions tab for some time now (basically issues but in a forum like a layout) and now it is also possible to transfer existing issues to discussions, to easy separate Q&A from code related topics.
I think this could be beneficial so you can have a central point to check all, also because it will enable an easy way to ask questions and discuss about features (I need that :) )

Here the how-to guide.
https://docs.github.com/en/discussions/quickstart

**Comment by MichMich** [comment]
We have the existing forum for this: http://forum.magicmirror.builders

**Comment by rejas** [comment]
Maybe add an explicit link to the core related part of the forum (https://forum.magicmirror.builders/category/11/core-system) to the README would be a start so that people who come to Github for technical stuff (maybe) find that?

**Comment by B1gG** [comment]
Thanks, let me go over there
