### ISSUE TITLE
2.15 using address:"0.0.0.0" on windows causes black screen

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2550]
windows 10, install 2.15

start up , works
change the config.js to 
```
address:"0.0.0.0",
ipWhitelist:[].
```

restart MM.. black screen, looking at the browser dev window.. nothing is loaded
u can get to the url from another browser and it works..

u can also set the actual ip address (from ipconfig /all) and that works

this was running in a vmware workstation virtual machine

**Comment by sdetweil** [comment]
Windows/Electron has some issue with 

loadUrl("http://0.0.0.0:8080")

invalid address

fix so if address:"0.0.0.0" (server is already working on all adapters)
edit js/electron.js

and change this , approx line 70 in the develop branch
```
let address = (config.address === void 0) | (config.address === "")  ? (config.address = "localhost") : config.address;
```
to this
``
let address = (config.address === void 0) | (config.address === "") | (config.address === "0.0.0.0") ? (config.address = "localhost") : config.address;
```

**Comment by khassel** [comment]
I tested this with my linux/docker setup and it seems the fix has no negative impact. If you do a PR, I'd like to get a warning in the logs that says something like "config address changed from ... to ...".

**Comment by khassel** [comment]
@sdetweil will you provide a PR for this? Otherwise I would create one, let me know ...
