### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by luc1997** [MichMich/MagicMirror#2564]
![IMG_2387](https://user-images.githubusercontent.com/84082038/117979880-ab164700-b333-11eb-881e-b7595f3ba8a4.jpg)

**Comment by luc1997** [comment]
![IMG_2387](https://user-images.githubusercontent.com/84082038/117979985-c7b27f00-b333-11eb-90b9-40a32f96eca3.jpg)
![IMG_2387](https://user-images.githubusercontent.com/84082038/117980033-d39e4100-b333-11eb-83b4-38a1d86c6d14.jpg)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
