### ISSUE TITLE
could we move the forum summary report collection further west.. midnight  pacific time. 

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2569]
its 9pm central now.  so, plus 2 (9pm pacific), plus 3(midnight pacific), so 5 hours later than now

**Comment by MichMich** [comment]
That would mean it would run at 09.00 where I'm located. Which is not ideal for me. How about 3 hours later than it is now?

**Comment by Tv-igtmomsp** [comment]
Perfect

**Comment by sdetweil** [comment]
thats ok.. i was trying not to impact west coasters.. but this is better than now
