### ISSUE TITLE
Monitor goes dim after about five minutes

### ISSUE THREAD

**Issue by nickroz7** [MichMich/MagicMirror#257]
My monitor goes to black after about five minutes and stops displaying the magic mirror. I followed the deactivation of the screensaver in the online instructions, so I'm not sure what else could be causing this. Any suggestions?

**Comment by djsunrise19** [comment]
Be sure to read and do this:

https://github.com/MichMich/MagicMirror/wiki/Configuring-the-Raspberry-Pi

**Comment by MichMich** [comment]
@nickroz7: if you are sure you've disabled all power saving features on the Raspi using info in the Wiki, it could be that your monitor has some a power save option that you can disable.

**Comment by MichMich** [comment]
Would it be ok for you to proceed any further discussion of this issue on: https://forum.magicmirror.builders? This way I can limit the use of GitHub issues to bug reports.

**Comment by nickroz7** [comment]
@MichMich yes, I'll further the discussion on that forum. Thanks!
