### ISSUE TITLE
Make RSS more readable

### ISSUE THREAD

**Issue by mcnahum** [MichMich/MagicMirror#2570]
I'm using the RPi 7 touch screen, I've a picture ( who change often) on background and my RSS feed (mix of news) on the bottom of the screen)

maybe I'm getting older but It's could be difficult to read the text, it's not the size but may be the white could be more white or may be we could have a blur rectangle on the back of the text to improve it ... I don't have the solution but looking for idea to put in place...

**Comment by MichMich** [comment]
You can change the full appearance of anything on the MagicMirror² using the custom.css. Please check the docs or refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
