### ISSUE TITLE
two modules use the same library name, but at different levels, how to resolve

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2582]
my MMM-Config and MMM_WifiPassword both use  a QRCode

i get mine from the nodejs catalog 
he has his copied from somewhere

whichever is loaded last  wins...
but the other module doesn't work

I changed his code to be explict path like mine, but no help 
so its the function names INSIDE the file that wins.. 

I could use his lib, but no guaranty it will continue to work.. 

is there a known solution to this problem?  can I somehow scope my getscripts() response to my module only?

**Comment by sdetweil** [comment]
looks like there are different ways IF you control the loading process (and so can replace the name with a local instance)
but I don't ...

**Comment by sdetweil** [comment]
anyone have any ideas how to solve this generically?

**Comment by MichMich** [comment]
The server side is easy. But the client side is difficult because we don't use something like webpack.

**Comment by sdetweil** [comment]
but there has GOT to be something...   this isn't a new problem with MM I don't think

**Comment by MichMich** [comment]
I haven't come across it before. Is it. Prefect that it is a client side framework?

**Comment by sdetweil** [comment]
sorry, don't understand the last sentence.. 

it is a framework for homolgating content from disparate sources. 
how should I protect my code from old, abandoned modules?

**Comment by MichMich** [comment]
Haven't tried it, but maybe you can import the lib as a module.

**Comment by sdetweil** [comment]
yes I could use it in my node_helper,  I already have it as a dependency. 

but why should I have to redesign my code.. grrrr

https://www.npmjs.com/package/qrcode#tofilepath-text-options-cberror

https://stackoverflow.com/questions/13938686/can-i-load-a-local-file-into-an-html-canvas-element

**Comment by MichMich** [comment]
Dealing with edge cases is the fun of programming. 😂
