### ISSUE TITLE
module configuration with external config.js or json file (for 3rd party)

### ISSUE THREAD

**Issue by bugsounet** [MichMich/MagicMirror#2585]
I purpose to create a new feature for MM

What about `configFile: "My_module_config.json"`
`My_module_config.json` will be located in the module directory

naturaly, we can also use `config:{}` but not at the same time

What do you this about this ?
Personaly, i think i could be better for more visibility
and any user will be not `lost` in the config.js file

**Comment by sdetweil** [comment]
my MMM-Config goes sort of in this direction.. one can save and customize the information for the modules form presentation.
drops downs, date,  name,  etc fields. 
and then generates the config file.. user never sees it.  if there is a schema.json file in the module folder my module will use it. (similar to your idea)   

MM doesn't change
for abandoned modules, i will collect customized schemas from users and use those when needed

the users get form based admin to their Magic Mirror

**Comment by bugsounet** [comment]
lol ... I do it too with MMM-Setup too but i have to done it ;)

**Comment by sdetweil** [comment]
I don't see that on github,, do you do this for every/any module? without their participation?

**Comment by bugsounet** [comment]
naturally not for all modules ... only for mine !
and Naturally too ... I don't ads it ;) [module config creator with user interaction i config.js]

But ... it's not the main subject
