### ISSUE TITLE
Current Weather with a radio sensor?

### ISSUE THREAD

**Issue by powerscooter** [MichMich/MagicMirror#259]
Hello,

i have a question.
Gives a possibility to use a radio sensorfür the current weather on the Magic Mirror?
I have a 433mhz radio sensor and a 433 mhz radio receiver. 
With the programm pilight i can decode the informationen they send the radio sensor.

regards,
Phil

**Comment by CFenner** [comment]
You need to build a custom module for that. It shouldn't be too hard if you already have the data on the Pi.

**Comment by powerscooter** [comment]
hm, I´ve never programmed a module. 
I'll see how that goes.

**Comment by MichMich** [comment]
Check out this module as an example: https://github.com/MichMich/mmm-systemtemperature

**Comment by MichMich** [comment]
Would it be ok for you to proceed any further discussion of this issue on: https://forum.magicmirror.builders? This way I can limit the use of GitHub issues to bug reports.
