### ISSUE TITLE
MMM-MonthlyCalendar private events not showing up

### ISSUE THREAD

**Issue by FlorjanKlancar** [MichMich/MagicMirror#2596]
I have a problem with MMM-MonthlyCalendar model. Widget is displaying events that are in public google calendar but can’t display events that are linked to my private google account calendar…
Is there any reason why? I give him the url just like the default magic mirror calendar view (it works there)?

Btw ignore the overlaying modules the screen is supposed to be a larger screen.

Config:
{
                        module: "MMM-MonthlyCalendar",
                        position: "bottom_bar",
                        config: {
                                updatesEvery: 30,
                                weeksInFuture: 5,
                                calendars: [
                                {
                                        url: "<filename>",
                                        priority: 1
                                },
                                {
                                        url: "<filename>",
                                        priority: 2
                                },

                                ]
                        }
                },
![image](https://user-images.githubusercontent.com/48727773/122022988-6b75cb80-cdc7-11eb-9a87-013fbfba1581.png)

**Comment by rejas** [comment]
Hi @FlorjanKlancar since this is not one of the default modules please refer to http://forum.magicmirror.builders for support and troubleshooting.

**Comment by rejas** [comment]
Ah I see you already did: https://forum.magicmirror.builders/topic/15132/mmm-monthlycalendar?page=1
so this issue can be closed then?
