### ISSUE TITLE
Newsfeed module bug

### ISSUE THREAD

**Issue by zoldev** [MichMich/MagicMirror#2616]
Hello!

I found a bug in newsfeed module.
When i was modify this config: 'truncDescription' and 'lenghtDescription', nothing happen.

Thanks for your answer.

**Comment by sdetweil** [comment]
can u show the config entry for newsfeed from config.js

**Comment by zoldev** [comment]
`{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "hvg h�rek",
						url: "http://www.hvg.hu/rss/tudomany"
					}
				],
				updateInterval: 60000,
				showSourceTitle: false,
				showPublishDate: false,
				broadcastNewsFeeds: false,
				broadcastNewsUpdates: false,
				showDescription: true,
				wrapTitle: true,
				wrapDescription: true,
				truncDescription: true,
				lenghtDescription: 200
			}
		},`

**Comment by zoldev** [comment]
{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "hvg h�rek",
						url: "http://www.hvg.hu/rss/tudomany"
					}
				],
				updateInterval: 60000,
				showSourceTitle: false,
				showPublishDate: false,
				broadcastNewsFeeds: false,
				broadcastNewsUpdates: false,
				showDescription: true,
				wrapTitle: true,
				wrapDescription: true,
				truncDescription: true,
				lenghtDescription: 200
			}
		},

**Comment by zoldev** [comment]
> can u show the config entry for newsfeed from config.js

{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "hvg h�rek",
						url: "http://www.hvg.hu/rss/tudomany"
					}
				],
				updateInterval: 60000,
				showSourceTitle: false,
				showPublishDate: false,
				broadcastNewsFeeds: false,
				broadcastNewsUpdates: false,
				showDescription: true,
				wrapTitle: true,
				wrapDescription: true,
				truncDescription: true,
				lenghtDescription: 200
			}
		},

**Comment by sdetweil** [comment]
ok, this one is wrong
```
lenghtDescription: 200
```
misspelled,h & t reversed,  should be 
```
lengthDescription:200
```

showDescription:true 
is the default, 

the code in the template is 
```
            {% if config.showDescription %}
                <div class="newsfeed-desc small light{{ ' no-wrap' if not config.wrapDescription }}">
                    {% if config.truncDescription %}
                        {{ description | truncate(config.lengthDescription) }}
                    {% else %}
                        {{ description }}
                    {% endif %}
                </div>
            {% endif %}
```

**Comment by zoldev** [comment]
:D ooh my god! :D
THANKS!

**Comment by rejas** [comment]
While you are here @zoldev might I ask you if you could help me out? See, I am wondering why people often dont seem to answer the questions we ask them in the issue template. Those questions are really helpful and can help get an answer faster. So I am wondering if the people dont see them (for technical reasons) or if the language is too complicates or the text is too long? NO offence ment, just hoping to improve that template. Thanks in advance!
