### ISSUE TITLE
forum won't send change password email to user

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2618]
user trying to login, did thru github, but that not working.

I can email him using his account email and it goes thru, and he replied (both on gmail.com)

user kiina

can someone check the forum logs? I cannot

**Comment by sdetweil** [comment]
works for my email

**Comment by sdetweil** [comment]
there are no blocks or bans on the user

**Comment by MichMich** [comment]
Can he login with user&pass?

**Comment by Kiina** [comment]
Well login with user and password won't work since I used github oauth in the past and don't have an password. So I need to reset it to even try to login with it.

**Comment by MichMich** [comment]
Is that an option to try? I know there have been some issues with the GitHub connection in the past.

**Comment by Kiina** [comment]
Well the github login option is gone, that's why i'm kinda stuck in that weird limbo of no chance to login via github but also no chance to get a password to login via email and password

**Comment by MichMich** [comment]
Ah, ok... I get the issue now. Let me check.

**Comment by MichMich** [comment]
@Kiina could you give it a try to see if you can now request an password via email. It turns out the email service was broken.

**Comment by Kiina** [comment]
Works great, thanks!

**Comment by MichMich** [comment]
Good to know! Thanks! Can I close this issue?

**Comment by Kiina** [comment]
Yes, thanks!
