### ISSUE TITLE
Error with modules 'newsfeed' and 'calendar'

### ISSUE THREAD

**Issue by Paddolietsch** [MichMich/MagicMirror#262]
I'm not sure if it's even an error. I might as well be, me being a dumb person.

I've recentrly build my own magic mirror. Everything works fine except for the 2 modules named in the title. When adding the modules to 'config.js' i recieve an error. Im not well known with coding so i would appreciate all tips and hints.

The error:
Uncaught TypeError: Cannot read property 'getElementsByClassName' of null (Main.js:130)
which keeps stacking every second.

Code of 'config.js':
https://ghostbin.com/paste/drcdo

The modules itself are left in their original state.

Link of the website:
http://magic.riksnoeicomputerservice.nl/

I will leave the error on the page for now. If somebody knows what im doing wrong i would like to hear the tips.

Thanks in advance.

**Comment by estres** [comment]
Hi,
your url is not a rss feed (http://www.riksnoeicomputerservice.nl) try this one : http://www.tagesschau.de/xml/rss2
