### ISSUE TITLE
Magic Mirror Config problem

### ISSUE THREAD

**Issue by Tig3458** [MichMich/MagicMirror#2622]
Hi,

Im completely new to MM2 and programming. I loaded the program and it worked fine. I then decided that I wanted to remove the greetings module.  Successfully achived.  The I tried to load a new module and things went south quickly. Now MM2 won't load and i get the following error message when i run npm run config:check

i@raspberrypi:~ $ npm run config:check
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/pi/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-08-03T18_30_34_873Z-debug.log
pi@raspberrypi:~ $ ^C
pi@raspberrypi:~ $ 

Can someone please tell me what I have screwed up?

Cheers, Don

**Comment by MichMich** [comment]
It seems like you are not running the commands from within the magicmirror folder. 

Please refer to http://forum.magicmirror.builders for support and troubleshooting.
