### ISSUE TITLE
Start fail Magic 

### ISSUE THREAD

**Issue by Jan-2005** [MichMich/MagicMirror#2626]
pi@MagicMirror:~ $ pm2 log MagicMirror
[TAILING] Tailing last 15 lines for [MagicMirror] process (change the value with --lines option)
/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index                                          .js:8:29)
0|MagicMir |     at Module._compile (internal/modules/cjs/loader.js:1152:30)
0|MagicMir |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10) {
0|MagicMir |   code: 'MODULE_NOT_FOUND',
0|MagicMir |   requireStack: [
0|MagicMir |     '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js',
0|MagicMir |     '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js',
0|MagicMir |     '/home/pi/MagicMirror/js/app.js',
0|MagicMir |     '/home/pi/MagicMirror/js/electron.js',
0|MagicMir |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|MagicMir |     undefined
0|MagicMir |   ]
0|MagicMir | }
0|MagicMir | [07.08.2021 12:31.37.939] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this ha                                          ppened. Maybe no internet connection?
0|MagicMir | [07.08.2021 12:31.37.940] [ERROR] If you think this really is an issue, please open an issue on GitHub: https                                          ://github.com/MichMich/MagicMirror/issues

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
