### ISSUE TITLE
Calendar: end date missing for multi day events (like holidays) (followup to #2529)

### ISSUE THREAD

**Issue by waldmeisterx** [MichMich/MagicMirror#2629]
Platform: Raspberry Pi 3, current OS
uname -r: 5.10.52-v7+

Node Version: what is this? how do I get this info?

MagicMirror Version: 2.16.0 (problem occured after upgrading from 2.13.0, problem still existed in 2.15.0).

Description: I show holidays with start and end dates. The shown config worked well with 2.13.0, after upgrading to 2.15.0/2.16.0 the end date disappeared. Now, only the current day of the current holiday is shown.

Steps to Reproduce: With my config in MM 2.16.0

Expected Results: start (or current) date AND end date "Sa 10. Apr. - Fr. 16. Apr."

Actual Results: only start (or current) date "Sa 10. Apr."

Configuration:
```
{
	module: "calendar",
	header: "Ferien Hessen",
	position: "top_bar",
	config: {
		tableClass: "medium",
		colored: true,
		fetchInterval: 900000,
		fullDayEventDateFormat: "dd DD. MMM",
		timeFormat: "absolute",
		urgency: 0,
		getRelative: 0,
		maximumEntries: 1,
		maxTitleLength: 50,
		showEnd: true,
		dateEndFormat: "dd DD. MMM",
		calendars: [
			{
				// Ferien Hessen 2021
				symbol: "democrat",
				color: "#ffbbbb",
				url: "https://www.ferienwiki.de/exports/ferien/2021/de/hessen"
			},
		]
	}
},

```
Additional Notes:
The option "showEnd" is shown two times in the Calenders doku with similiar descritions!

**Comment by sdetweil** [comment]
@waldmeisterx 
>The option "showEnd" is shown two times in the Calenders doku with similiar descritions!

yes, you can set it once for ALL calendars (above the section calendars:)
or you can set it individually for each calendar... (in the section where u code url)

all overrides individual

**Comment by waldmeisterx** [comment]
@sdetweil ok, good to know, that ALL overrides individual, I'd have expected the opposite behaviour.
And for me it is not clear in docu, the entries I see are both in the same table "Configuration options", 4 lines away from each other. 

So you agree, my config should show an end date? It has showEnd = true in ALL and I added it in calender too for this next test

No end date appear:
![image](https://user-images.githubusercontent.com/2168391/129493027-31d6df83-da0a-4e2f-8c57-92b50d10ae04.png)

It seems, the parameter does only shows end TIME, but not end day of multi day events (like holidays).
![image](https://user-images.githubusercontent.com/2168391/129493173-2a1bca18-c97e-400b-8518-ff5bc0d68f2c.png)
The last line here is a multi day event.

**Comment by sdetweil** [comment]
as I understand it, showEnd is for multi-day events only.  showOngoing is for multi-day that has started but not ended. 

I spent a lot of time working on getting the data right. but not the presentation of the data.

**Comment by waldmeisterx** [comment]
I added (hidden?) parameter showOngoing = true but no change.
As you describe showOngoing should be the one, the holidays are now and ongoing.

**Comment by sdetweil** [comment]
what do you mean by 'hidden'?  its in the doc. and its showOngoing:true, right? 
and its only for events that HAVE STARTED not WILL start

download the ics (put the calendar url in a browser) and edit the ics file (its just text)

show me the BEGIN:VEVENT thru END:VEVENT for the holiday 
it should have a RRULE: that shows repeating on some schedule

**Comment by sdetweil** [comment]
BTW the documentation style is module parms 1st (override any following), and calendar parms second, same for RSS feeds ..

**Comment by waldmeisterx** [comment]
The docs I'm looking in is this https://docs.magicmirror.builders/modules/calendar.html
There I can not find any info for a parameter showOngoing

In the ics I do not find a RRULE, because it's not repeating. It is our summer holidays lasting 6 weeks and I'd like to see how long they last. 
I'd expect to see the value of DTEND.

```
BEGIN:VEVENT
DTSTAMP:20210816T070023Z
UID:6ec55230-6942-4ce3-9c39-391448b654ba
DTSTART;VALUE=DATE:20210719
DTEND;VALUE=DATE:20210828
DESCRIPTION:Sommerferien 2021 in Hessen - Importiert von Ferienwiki.de
SUMMARY:Sommerferien
END:VEVENT

```

**Comment by sdetweil** [comment]
thanks.. very helpful...  I created a matching one with an RRULE.. 
i see they flipped ongoing to now hideOngoing vs showOngoing.. 

but the net is, I think there is a bug , the code (in calendar.js)
```
				if (this.config.showEnd) {     //  if end requested, format it 
						timeWrapper.innerHTML += "-";
						timeWrapper.innerHTML += this.capFirst(moment(event.endDate, "x").format(this.config.dateEndFormat));
					}  /* FIX else */   // uncomment this 
				// For full day events we use the fullDayEventDateFormat
				if (event.fullDayEvent) { // if this is a full day event, replace content above with this -----regardless of other settings ---- bug.. 
						//subtract one second so that fullDayEvents end at 23:59:59, and not at 0:00:00 one the next day
						event.endDate -= oneSecond;
						timeWrapper.innerHTML = this.capFirst(moment(event.startDate, 
"x").format(this.config.fullDayEventDateFormat));
					}
```

if u add an 'else' in between 
and set the settings like this 
```
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
						timeFormat:'absolute',
						showEnd: true,
						dateEndFormat:"MMM Do",
						getRelative:0,
						urgency:0,
				calendars: [
					{
						symbol: "calendar-check",
						//url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"
						url: "http://localhost:8090/modules/default/calendar/sams-test.ics",

					}
				]
			}
		},
```
then u get the start/end		as u expect

**Comment by waldmeisterx** [comment]
@sdetweil Yes! You found it. This correction in calendar.js and the config showEnd: true results in exactly in what I was looking for

![image](https://user-images.githubusercontent.com/2168391/129615356-d8112f60-30e4-44c4-bbe4-ee83bdc2dcb9.png)

Thank you a lot.

**Comment by rejas** [comment]
great to hear this got resolved thx a lot @sdetweil will you create a PR for your fix?

**Comment by jupadin** [comment]
> @sdetweil Yes! You found it. This correction in calendar.js and the config showEnd: true results in exactly in what I was looking for
> 
> ![image](https://user-images.githubusercontent.com/2168391/129615356-d8112f60-30e4-44c4-bbe4-ee83bdc2dcb9.png)
> 
> Thank you a lot.

@waldmeisterx: If I correctly understood this issue and given your screenshot, the name of the weekday on which the holidays start, is missing isn't it ?

Can you tell me which icon and color code this is ? I really like it !

**Comment by sdetweil** [comment]
@jupadin  the cal entry shown does not show THE event start date, but TODAY thru the end.  we don't know WHEN it started in the past.. could be yesterday, or in this case last month.   you could change the fulldateFormat (check the spelling) to include the day I supposed..

**Comment by jupadin** [comment]
Ahhh, got it.
@sdetweil: Thank you for the explanation !!

**Comment by waldmeisterx** [comment]
@jupadin: You can find my configures symbol and color in the first post, it is
```
symbol: "democrat",
color: "#ffbbbb",

```
There you also see the set configured formats @sdetweil mentioned too. 

```
fullDayEventDateFormat: "dd DD. MMM",
dateEndFormat: "dd DD. MMM",
```
But I think it should be dateEndFormat according to https://docs.magicmirror.builders/modules/calendar.html

**Comment by sdetweil** [comment]
the code actually uses 
```
					// Use dateFormat
					timeWrapper.innerHTML = this.capFirst(moment(event.startDate, "x").format(this.config.dateFormat));
// then above code 
                                        if (this.config.showEnd) {     //  if end requested, format it 
						timeWrapper.innerHTML += "-";
						timeWrapper.innerHTML += this.capFirst(moment(event.endDate, "x").format(this.config.dateEndFormat));
					}  /* FIX else */   // uncomment this 
				// For full day events we use the fullDayEventDateFormat
				if (event.fullDayEvent) { // if this is a full day event, replace content above with this -----regardless of other settings ---- bug.. 
						//subtract one second so that fullDayEvents end at 23:59:59, and not at 0:00:00 one the next day
						event.endDate -= oneSecond;
						timeWrapper.innerHTML = this.capFirst(moment(event.startDate, 
"x").format(this.config.fullDayEventDateFormat));
					}
```
dateFormat for the startDate

**Comment by waldmeisterx** [comment]
@sdetweil with dateFormat set it now shows both dates in same format
![image](https://user-images.githubusercontent.com/2168391/130109881-90cc6da9-6c45-47db-9ca7-0607bbb55ac9.png)
I'm very happy with this.

**Comment by jupadin** [comment]
Just another question, maybe worth another issue or discussion...
Wouldn't it be more convenient to put those configuration options inside each url ?

The following use case:
I would like to have one calendar, containing birthdays, holidays (multiple day events + single day events (both full days)) as well as usual events inside the (single) calendar.
Given the (multiple full day event) holidays, I would like them to be shown as discussed above (Start + End), (single full day event) holidays should only be shown with its start day.
The birthdays should be shown relative, starting 6 days before the actual event and the usual events as usual.

Since the most of the options can only be set globally, such a use case is not possible - or do I (again) understood something wrong ?

**Comment by waldmeisterx** [comment]
you can set up more than one calender, each with its own settings

**Comment by jupadin** [comment]
Yes, but given the documentation, it is only possible to set the time format (absolute, relative) for all of the urls of the calendar and not for each of the urls...
Or is there any misunderstanding ?

**Comment by waldmeisterx** [comment]
No, i think you are right. You should address it in a new issue (feature request).

**Comment by waldmeisterx** [comment]
The code correction (in calendar.js) mentiened by @sdetweil was not considered in the last release 2.18.0?
The format of multi day events is now again broken and has to be fixed again manually :-(

**Comment by sdetweil** [comment]
hm. I added the else in one of the other fixes, did I get it wrong?

**Comment by waldmeisterx** [comment]
@sdetweil 
In 2.18.0 it is not included.
I reassigned your correction from above and this fixes it again

**Comment by waldmeisterx** [comment]
fixed in 2.19.0

**Comment by TesterAufLebenszeit** [comment]
Hello together.

I had the same problems as waldmeisterx but did find a solution without changing the code of _calendar.js_.
It seems that the fix is not working.
I left a comment. Maybe this can be a solution.

**Comment by rejas** [comment]
> I left a comment. Maybe this can lead to a solution.

Where did you leave a comment?
