### ISSUE TITLE
MM2 not showing text when booting up

### ISSUE THREAD

**Issue by beth606** [MichMich/MagicMirror#2642]
**Platform**: mac

**Node Version**: cant check

**MagicMirror Version**: cant open

**Description**: hi i made my MM2 a year or so ago and it has worked fine but recently on boot it will show the mm2 screen and then not load the text it just shows a black screen i have tried to log into vnc but the RPI refuses the connection i tried swapping RPI’s and that didn’t work i also can’t open a command window or shut it down what should i do?

**Configuration**: cant check

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
