### ISSUE TITLE
electron 16

### ISSUE THREAD

**Issue by khassel** [MichMich/MagicMirror#2656]
Electron 14 is released.

We should move to v14 **after** the October release and we have to wait until the corresponding spectron version v16 is released.

**Comment by sdetweil** [comment]
why do u want to be that close to release cycle?
almost nothing good comes of it

**Comment by khassel** [comment]
wrote already after next release so it would be in the January release and we have 3 months to test it on `develop`. I think we are totally contrary concerning update frequencies ...

**Comment by MichMich** [comment]
3 months should be enough indeed.

**Comment by khassel** [comment]
changed the title to v15, new electron main releases will come every 8 weeks, see [release blog](https://www.electronjs.org/blog/electron-15-0/).

**Comment by khassel** [comment]
meanwhile electron v16 is out. The electron upgrade here depends on the [replacement of spectron](https://github.com/MichMich/MagicMirror/issues/2408#issuecomment-980452767).

**Comment by khassel** [comment]
v16 is now on the `develop` branch.

In my docker setup on raspi 4 I get some errors concerning gpu on startup, but mm is running.

For getting rid of these messages there are 2 possibilities describes e.g. [here](https://jorgeavante.com/posts/running-an-electron-app-in-a-raspberry-pi-4/).

So before writing a PR adding `app.disableHardwareAcceleration();` to `js/electron.js` it would be good if someone else can test and confirm this, thanks!

Tested this already with a raspi 3 with electron v13 and v16 with no side effects.

**Comment by rejas** [comment]
Mh... mm starts fine without that line 

After adding the line from the link right after app is declared, this line is in the logs:

0|MagicMir | [1048:1129/081539.472114:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

**Comment by khassel** [comment]
yes, I'm aware of the sandbox error ...

But can you tell me more about your setup?
- pi version
- buster or bullseye
- node version
- electron v16?

Thanks.

**Comment by rejas** [comment]
pi 4
bullseye "Linux mirrorpi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux"
node v16.13.0
electron v16 

:-)

**Comment by rejas** [comment]
of course with latest apt-updates

**Comment by khassel** [comment]
thanks, so this seems a problem of my docker setup and no general problem of mm ...
