### ISSUE TITLE
local ics

### ISSUE THREAD

**Issue by Cobby67** [MichMich/MagicMirror#2663]
In the default calendar module, is it possible to use an ics file local instead of a url link ?

**Comment by sdetweil** [comment]
sure.. just put it in the calendar module folder

then use a url like this 
```
"http://localhost:8090/modules/default/calendar/????.ics" 
```
???? whatever the ics filename is

**Comment by MichMich** [comment]
And just to prevent any confusion: the default port is 8080. 👍🏻

**Comment by sdetweil** [comment]
yeh, should make that MM_port

**Comment by Cobby67** [comment]
Wow!, thank you very much! I'll be able to see my prefered hockey team calendar (junior hockey)

**Comment by sdetweil** [comment]
@Cobby67  problem? (re-open)

**Comment by Cobby67** [comment]
I'm not a great programmer in javascript or nodejs... Can we see the date of the game, the team and the hour or it's just possible to see date and title?

**Comment by Cobby67** [comment]
Ok, that will be allright!
Thank you!

**Comment by Cobby67** [comment]
I can always import the ics in a mysql table and use the mmm_mysql... to see more column 
Have a nice day!

**Comment by sdetweil** [comment]
yep... lots of ways to solve specific issues
