### ISSUE TITLE
help notifications

### ISSUE THREAD

**Issue by Cobby67** [MichMich/MagicMirror#2667]
Hello, Can you give me a link that explains how the notifications works, how to send command from a module to another... Do we have to change something in the main .js file of both modules...  
Ex. can I ask jarvis in Googleassistant  to 'GO TO PAGE x' with page_selector ?

**Comment by sdetweil** [comment]
any module in the module name.js can do
```
this.sendNotification(string,value)
```

where string is the notification identifier, and value is the value that goes with it.

any module receiving the notification (all)
can ignore it, or process it, assuming it understands the value
