### ISSUE TITLE
Calendar module refuses to load

### ISSUE THREAD

**Issue by jferg368** [MichMich/MagicMirror#267]
I've managed to get my Magic Mirror working with time, comments, and local weather forecasts. However, trying to insert the calendar module into config.js results in the index page loading the default.js script. I've inserted the calendar module verbatim from the readme file, as well as attempting to modify it with my own iCal link with no success.  

Possibly of note, it's all or nothing,and the same thing happens with the Newsfeed module. If either module is called in config.js, the main page reverts to the default.js script displaying a bunch of 'Hello world' modules.

I'm still pretty noobtastic when it comes to javascript, so please forgive my ignorance if I've made some kind of blatant error editing my config file.

**Comment by MichMich** [comment]
If it shows the "no config file" message, there is a syntax error in your config. Try finding the error using a Javascript linter.

**Comment by MichMich** [comment]
Would it be ok for you to proceed any further discussion of this issue on: https://forum.magicmirror.builders? This way I can limit the use of GitHub issues to bug reports.

**Comment by jferg368** [comment]
Of course. Feel free to close the issue, I'll post it on the builders forum.

Thanks for the response, and for all your work on a great project.
