### ISSUE TITLE
sendNotification from external process...

### ISSUE THREAD

**Issue by desq42** [MichMich/MagicMirror#268]
Hi,

I´m fairly new to the whole node/socket thingy, but I´m wondering if it´s possible to send
a notification from an external process outside the MagicMirror Universe.
Specifically I would like to send a Notification from MotionEye, which has the ability to call a URL if it detects a Movement. This notification could perhaps show a picture of your frontdoor etc...
Perhaps somebody can give me a hint, if somethings like this would be possible, so I can dive into it.

Thank you.

**Comment by nhubbard** [comment]
You would probably use the NodeHelper to expose a URL, which MotionEye calls as a WebHook, triggering the notification.

**Comment by desq42** [comment]
I got the same idea. A node_helper is already working... I´ll keep you posted.

**Comment by MichMich** [comment]
One simple solution could be:

(in your node helper)
```javascript
    start: function() {
        var self = this;
        this.expressApp.get(this.name + '/foo', function (req, res) {
            res.send('OK');
            self.doSomething();
        }
    },
    doSomething: function() {
        // Do something here, like sending a socket message to the frontend.
    }
```

You could now invoke the `doSomething()` method by calling: `http://localhost:8080/modulename/foo'.

(Code is not tested, but something like the above should work ...)

**Comment by desq42** [comment]
start: function() {
        var self = this;
        this.expressApp.get(this.name + '/foo', function (req, res) {
            res.send('OK');
            self.doSomething();
        }
    },
    doSomething: function() {
        // Do something here, like sending a socket message to the frontend.
    }

Thanks for the Code-Snippet. Missing ")" bracket after ´/foo´?
I´m getting a "Cannot GET /urlserver/foo", if I´m calling the URL.

**Comment by MichMich** [comment]
Sorry, missing `);` below the `self.doSomething()'. Fixed it in my example.

**Comment by desq42** [comment]
Thanks. I´m still getting a "Cannot GET /urlserver/foo" from my browser when I´m calling the url.
No "doSomething()" invoked.

**Comment by MichMich** [comment]
What is the exact url you are calling?

**Comment by desq42** [comment]
I´m running the whole thing on my mac. so : http://localhost:8080/urlserver/foo

**Comment by MichMich** [comment]
and `urlserver` is the exact name of your module?

**Comment by desq42** [comment]
correct.

**Comment by MichMich** [comment]
Should work. You could try debugging by checking all registered routes, using something like:

```javascript
console.log(this.expressApp.stack);
```

(Not sure of that works ...)

**Comment by desq42** [comment]
okay. now it works. here is my node_helper code. - 
Seems as the Express.App path doesn´t work if it´s dynamically build. 
(BTW How do I tag my code correctly for viewing? 
![bildschirmfoto 2016-05-02 um 15 50 52](https://cloud.githubusercontent.com/assets/18470786/14955974/b5087066-107d-11e6-8985-e5e7fae94d0e.png)
(the insert code tag doesn´t work for me)

`
var NodeHelper = require("node_helper");
var express = require('express');
var app = express();

module.exports = NodeHelper.create({
		start: function () {
			var self = this;
			**this.expressApp.get("/urlserver/foo", function (req, res) {**
			//this.expressApp.get(this.name + '/foo', function (req, res) {
				res.send('Welcome');
			  self.doSomething();
			});
		},
    doSomething: function() {
				console.log("Called!");
				this.sendSocketNotification('URLSERVER'," called!");
    }
});
`

**Comment by MichMich** [comment]
use:

```
    ```javascript
    // your code here
    ```
```

**Comment by MichMich** [comment]
Would it be ok for you to proceed any further discussion of this issue on: https://forum.magicmirror.builders? This way I can limit the use of GitHub issues to bug reports.

**Comment by desq42** [comment]
Of course. Thanks for your assistance.
