### ISSUE TITLE
Black Screen after update to MM v2.17.1

### ISSUE THREAD

**Issue by SdeGeata** [MichMich/MagicMirror#2684]
Hello;

   So like many users, I am having the Black Screen issue since updating to MM v2.17.1.  I have isolated the problem to one particular module; MM-Parcel, and have posted the issue on that page too - still haven't got any answer back yet. Any idea how I can fix this? I have updated everything that I can find in the suggestions made to others with this same issue. I need this module to work! Any help would be very much appreciated.

Magic Mirror: v2.17.1
Node: v14.18.0
npm: 8.0.0

Log output:

`/home/pi/.pm2/logs/mm-error.log last 100 lines:
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js:9:18)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:935:32) {
0|mm       |   code: 'ERR_REQUIRE_ESM'
0|mm       | }
0|mm       | [03.10.2021 16:56.10.889] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [03.10.2021 16:56.10.890] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | /home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
0|mm       | Wrote 0x00000000 to 0xfec02020
0|mm       | [03.10.2021 17:01.21.552] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js
0|mm       | require() of ES modules is not supported.
0|mm       | require() of /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js from /home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
0|mm       | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/package.json.
0|mm       | 
0|mm       | [03.10.2021 17:01.21.572] [ERROR] App threw an error during load
0|mm       | [03.10.2021 17:01.21.572] [ERROR] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js
0|mm       | require() of ES modules is not supported.
0|mm       | require() of /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js from /home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
0|mm       | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/package.json.
0|mm       | 
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:935:32)
0|mm       |     at Module._load (internal/modules/cjs/loader.js:776:14)
0|mm       |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|mm       |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js:9:18)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:935:32)
0|mm       | [03.10.2021 17:01.21.573] [ERROR] Whoops! There was an uncaught exception...
0|mm       | [03.10.2021 17:01.21.579] [ERROR] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js
0|mm       | require() of ES modules is not supported.
0|mm       | require() of /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js from /home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
0|mm       | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/package.json.
0|mm       | 
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:935:32)
0|mm       |     at Module._load (internal/modules/cjs/loader.js:776:14)
0|mm       |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|mm       |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js:9:18)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:935:32) {
0|mm       |   code: 'ERR_REQUIRE_ESM'
0|mm       | }
0|mm       | [03.10.2021 17:01.21.580] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [03.10.2021 17:01.21.580] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | /home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
0|mm       | Wrote 0x00000000 to 0xfec02020
0|mm       | Gdk-Message: 17:03:17.875: electron: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
0|mm       | 
0|mm       | Wrote 0x00000000 to 0xfec02020
0|mm       | Wrote 0x00000000 to 0xfec02020
0|mm       | /home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
0|mm       | Wrote 0x00000000 to 0xfec02020
0|mm       | [10.10.2021 10:53.25.572] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js
0|mm       | require() of ES modules is not supported.
0|mm       | require() of /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js from /home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
0|mm       | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/package.json.
0|mm       | 
0|mm       | [10.10.2021 10:53.25.591] [ERROR] App threw an error during load
0|mm       | [10.10.2021 10:53.25.592] [ERROR] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js
0|mm       | require() of ES modules is not supported.
0|mm       | require() of /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js from /home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
0|mm       | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/package.json.
0|mm       | 
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:935:32)
0|mm       |     at Module._load (internal/modules/cjs/loader.js:776:14)
0|mm       |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|mm       |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js:9:18)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:935:32)
0|mm       | [10.10.2021 10:53.25.593] [ERROR] Whoops! There was an uncaught exception...
0|mm       | [10.10.2021 10:53.25.599] [ERROR] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js
0|mm       | require() of ES modules is not supported.
0|mm       | require() of /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js from /home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
0|mm       | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/package.json.
0|mm       | 
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:13)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:935:32)
0|mm       |     at Module._load (internal/modules/cjs/loader.js:776:14)
0|mm       |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|mm       |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js:9:18)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:935:32) {
0|mm       |   code: 'ERR_REQUIRE_ESM'
0|mm       | }
0|mm       | [10.10.2021 10:53.25.600] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | [10.10.2021 10:53.25.600] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
`

**Comment by rejas** [comment]
I  created a PR in the MMM-Parcel repo, lets this if it gets merged... 

https://github.com/martinkooij/MMM-Parcel/pull/31
