### ISSUE TITLE
MagicMirror Forum

### ISSUE THREAD

**Issue by paviro** [MichMich/MagicMirror#270]
@MichMich and I are currently setting up a forum for the MagicMirror community. What kind of categories would you guys like to see? Currently there are:
![sdsd](https://cloud.githubusercontent.com/assets/992826/14921266/a37ccbf6-0e31-11e6-863c-0993691774bd.png)

**Comment by KirAsh4** [comment]
In an attempt to avoid the General Discussion to become a catch-all for everything, how about adding categories such as 'Installation Troubleshooting', or maybe 'Troubleshooting' in general? I can see where someone who has just discovered the project would get to the forum, hit the General Discussion and get overwhelmed by folks having errors, install problems, and who knows what else. Maybe all they want to ask is something like _'will this run on such-n-such hardware?'_, or _'hey, I forked this, and here's my design'_.

**Comment by paviro** [comment]
Just a quick update, this is how it looks right now 🙂
![sdsd](https://cloud.githubusercontent.com/assets/992826/14926861/add072ac-0e4e-11e6-9c65-c56183478c48.png)

**Comment by KirAsh4** [comment]
Yeah, that would make more sense. Over time you can see what's being used the most, and how, and perhaps consolidate things then. It's a start.

**Comment by MichMich** [comment]
I think that Core System Bug Reports should remain on Github. Otherwise we get two places were we should check stuff (and retire info about a bug).

**Comment by KirAsh4** [comment]
Agreed. One place to report, and resolve bugs.

**Comment by paviro** [comment]
Maybe lock it and add a post describing on how you should fill a bug report on GitHub?

**Comment by MichMich** [comment]
Yes, that would be a good way.

**Comment by Paule08** [comment]
hi . here is paul . paviro knows me as paul the nagger from his blog .😉
cool idea with the forum .

**Comment by paviro** [comment]
Alright guys 🙂 Check out the [forum](https://forum.magicmirror.builders)!

**Comment by MichMich** [comment]
Thanks for your hard work, @paviro!

**Comment by paviro** [comment]
You are welcome :) Hope it helps you to getting a bit less issues here!

**Comment by nhubbard** [comment]
I'll work on a `gh-pages` branch when I have time, and @paviro can add it to the domain as the root when done. Good work!

**Comment by paviro** [comment]
The Domain is owned by @MichMich :) Talk to him for that matter.

**Comment by MichMich** [comment]
@nhubbard If it's sexy enough ... I'll link it to the domain! ;) Looking forward to your work.

**Comment by MichMich** [comment]
@paviro Wasn't it something you wanted to work on, too? Maybe you guys can collaborate?

**Comment by paviro** [comment]
Happy to hand that over, since I haven't started anything yet anyway :)

**Comment by KirAsh4** [comment]
Tried different browsers, same result:
![http://www.thekirchners.net/captcha.png](http://www.thekirchners.net/captcha.png)

**Comment by paviro** [comment]
Mhh strange... Will remove it for now give me a second :)

**Comment by paviro** [comment]
Go for it (should be back online any second)

**Comment by KirAsh4** [comment]
I know I've ran into captcha issues before when serving an httpS:// domain when the certificate wasn't valid ... which both browsers complained about (unknown issuer).

**Comment by paviro** [comment]
Mhh no problem about that with my browsers. Used https://letsencrypt.org <https://letsencrypt.org/> for the certificates.

**Comment by KirAsh4** [comment]
Yep, I've used them too (still do in fact.)

**Comment by paviro** [comment]
Any idea why they are not yet in your browser? Which OS and browser are you using?

**Comment by KirAsh4** [comment]
Confirmation e-mail taking the long scenic route now ... <grin>

Eh, one's Firefox (46.0 which is latest), and the other is Chrome which is the latest as well. It just updated this morning. It's possible that I have a higher security setting too. I'm at the office and I run a (very) tight ship as far as security goes for the entire building. Part of my job. We got fined before for having lax security so that's not a scenario I'm willing to go through again. So yeah, don't worry too much about it, certainly not if others can register just fine.

**Comment by paviro** [comment]
Forum will be back shortly!

**Comment by paviro** [comment]
Sorry for the downtime. It's back :)

**Comment by paviro** [comment]
You can now use your GitHub Account for logging :)

**Comment by MichMich** [comment]
![image](https://cloud.githubusercontent.com/assets/210954/14963352/8375dd38-10a3-11e6-8084-aef229565fe7.png)

Is image uploading enabled?

**Comment by paviro** [comment]
Yes. Will check what the problem is. Can you send me the file via email so I can try with your header?

**Comment by paviro** [comment]
Does it work now?

**Comment by MichMich** [comment]
Yes!

**Comment by paviro** [comment]
Nice! Moved the forum to another user because it was running as root when I set it up. Node could not write into the uploads folder anymore; fixed now :)

**Comment by KirAsh4** [comment]
The joys of running apps on servers. :)

**Comment by KirAsh4** [comment]
The one annoyance (so far) for me is the constant pop-up at the top about enabling desktop notifications. I don't want them, I blocked them in browser, I clicked the 'x' on the bar .... _it continues to pop up, constantly._

**Comment by MichMich** [comment]
@KirAsh4 Why would you not want MagicMirror Forum Notifications?! (Just kidding ... ;))

**Comment by paviro** [comment]
Mhh too bad this plugin does not use cookies or saves the choice in the database... Looks like other people [complained](https://github.com/psychobunny/nodebb-plugin-desktop-notifications/issues/19) about that too.. Not really sure what we should do about that, remove it?

**Comment by MichMich** [comment]
Yes, I think we should. I don't think many users will use it.

**Comment by paviro** [comment]
Alright will remove it.

**Comment by KirAsh4** [comment]
If it saved the user's settings, sure. But if it doesn't, to me that's a poor implementation of the feature. Particularly when others have also complained about it.

**Comment by polzy** [comment]
I have problem with cert. i use IE 11 and Firefox 45.0.1

Code temps :   	1462350458.610 (Wed, 04 May 2016 08:27:38 GMT)
URL :   	https://forum.magicmirror.builders/
Problème :   	Certificat du serveur distant non valide
Code erreur :   	INVALID_CERT, UNRECOGNIZED_ROOT_CERT, forum.magicmirror.builders)

Thanks

**Comment by paviro** [comment]
Looks like your System does not accept the https://letsencrypt.org certificate. Not sure why that is. Are you running the latest Firefox version? If not you can just ignore the warning (should be a button their) for now even tough that is not a god practise so you should not do that in general!

**Comment by danito** [comment]
Same here (latest Chrome for Android)

**Comment by MichMich** [comment]
@paviro Apparently there really is a certificate issue. Maybe you should contact https://letsencrypt.org?

**Comment by paviro** [comment]
Will do, strange that it only effects some 😯

**Comment by fcorin** [comment]
Are you using the correct cert file?
http://letsencrypt.readthedocs.io/en/latest/using.html#where-are-my-certificates

`Please note, that you must use either chain.pem or fullchain.pem. In case of webservers, using only cert.pem, will cause nasty errors served through the browsers!`

Similar problems:
https://community.letsencrypt.org/t/lets-encrypt-certificate-not-working-for-andriods-google-chrome/7184

**Comment by paviro** [comment]
Does it work now? Thanks @fcorin!

**Comment by polzy** [comment]
yes very good ! Thanks :) :)

**Comment by GlenNicholls** [comment]
Hey, I´m not sure if this is the right place to ask this because I am navigating on my pi. Anyways, I am trying to get location for weather services modules to automatically find the pis location using google maps geolocation API. How do I go about adding this to the existing module? If I put in the url with the API inside the location field, will that return a usable lat/long coordinate that the code can use to send to OpenWeather?

**Comment by MichMich** [comment]
Please ask this question on http://forum.magicmirror.builders 👍🏻

**Comment by Dietmar-Franken** [comment]
Can´t do anything everytime forum says invalid session.No login ,no password reset. :-(

**Comment by paviro** [comment]
Try deleting your cookies!

**Comment by Dietmar-Franken** [comment]
No luck in Firefox.I have installed Chrome and everything works.

**Comment by SouthDeer** [comment]
I bought some glass samples, It was an one-way glass, like the interrogation room, but it's too darker than the normal glass, Can you give me some advice? about which glass is better?  thanks a lot.

**Comment by MichMich** [comment]
@SouthDeer This GitHub issue is not a forum itself. Please check out this topic regarding your question: https://forum.magicmirror.builders/topic/22/where-to-buy-good-two-way-mirrors

**Comment by Corvis1984** [comment]
Hello,

Is MagicMirror2 supposed to work on a RPI 3 ? I have an issue related to electron that is not found.

Does it sound familiar to anyone ?

**Comment by MichMich** [comment]
@Corvis1984 Please check http://forum.magicmirror.builders for support.

**Comment by Anachor1988** [comment]
Hello!

i can't login to the forum, when i open the site it spams a "invaild session" message on the right side and when i wanna log in it says "Login Unsuccessful We were unable to log you in, likely due to an expired session. Please try again". Did i do anything wrong or what is the problem ?

**Comment by paviro** [comment]
Does it work now?

**Comment by Anachor1988** [comment]
No :-( Got the same errors... "ERROR invalid-session" on the right side in a message box and the "Login Unsuccessful We were unable to log you in, likely due to an expired session. Please try again". Can't even make a new account, got the same errors... at home and even at work on phone, mac, pc and even raspberry :-/

**Comment by paviro** [comment]
Please clear your cookies so you have a fresh start after what I changed.

**Comment by Anachor1988** [comment]
That was the problem, now everything works great again! Thanks for your help :-)

**Comment by paviro** [comment]
Forum has a little outage, working on it :)

**Comment by paviro** [comment]
Back online, make sure to read: https://forum.magicmirror.builders/topic/420/forum-outage-and-restore-from-backup :)

**Comment by KirAsh4** [comment]
Almost, but no cigar ... dead again.

**Comment by paviro** [comment]
Old Server just came back... Going to restore database.

**Comment by KirAsh4** [comment]
Put a leash on it ... it's not allowed to just go on a walk in the park like that.

**Comment by jtyle6** [comment]
I'm getting: 

ERROR

invalid-session

From login with github.

**Comment by MichMich** [comment]
@jtyle6 did you remove your cookies yet?

**Comment by jtyle6** [comment]
It didn't  work,   I'm trying to login with the Alternative Logins. 

I will try again tomorrow morning when mac is back on.

**Comment by berlincount** [comment]
Right now, I'm lacking a Confirmation Email to be able to use the Forum, after registering via Github.

Hmm.

I'm in Berlin with a 42" FullHD MagicTouchMirror, but would want a slightly different setup to what I've seen - I'd rather want to have something in the borders and corners instead of using screen real estate in the middle ...

**Comment by Jopyth** [comment]
It probably sends the confirmation Email to your non-reply github email.

**Comment by MichMich** [comment]
@berlincount I've manually validated your account.

**Comment by paviro** [comment]
This thread is about the forum not the magic mirror software! If you need help go to said forum :) http://forum.magicmirror.builders

**Comment by mikecy22** [comment]
Hello. I have a problem with my confirmation email. I haven't received it. I resend it a couple of times i even changed my email to another one but still havent received anything.
