### ISSUE TITLE
3rd Party Modules not Appearing

### ISSUE THREAD

**Issue by bzoit** [MichMich/MagicMirror#2710]
Hello everyone! I'm trying to add the MMM-Jast and the MMM-cryptocurrency modules to my mirror but they either partially or don't appear at all. The cryptocurrency is just showing the bar at the top but no logo or price, and the jast module isn't appearing at all. My config.js is correct so I'm stumped. If anyone could help, that'd be very appreciated.

Config.js: pastebin.com/MPbD9kpW

![image](https://user-images.githubusercontent.com/71105100/141882788-5adc97e5-9508-4326-abc2-4884e68176c6.jpeg)

**Comment by sdetweil** [comment]
you should post issues to the module GitHub site, for the module author to address.

**Comment by bzoit** [comment]
> you should post issues to the module GitHub site, for the module author to address.
> 
> 
> 
> and possibly post in the forum

Sorry, I'll do that.
