### ISSUE TITLE
htilburgs / MMM-MyTraffic Module Not Found

### ISSUE THREAD

**Issue by mnooijen** [MichMich/MagicMirror#2719]
Beste meneer Tilburgs,

Ik heb deze module geïnstalleerd en heb de juiste handelingen uitgevoerd, echter krijg ik bij het opstarten van het script een foutmelding in het groen te zien ''module not found''. Doe ik iets verkeerd?

Met vriendelijke groet,

Marcel Nooijen

**Comment by sdetweil** [comment]
see this 
https://forum.magicmirror.builders/topic/15778/fix-for-black-screen-in-2-16-and-later
