### ISSUE TITLE
Proper way to update MM

### ISSUE THREAD

**Issue by KirAsh4** [MichMich/MagicMirror#272]
What's the proper way to update MM? Do we simply clone the repository in the same folder that it's currently installed in? Any caveats?

**Comment by MichMich** [comment]
Update from version 1? Or from a previous version 2?

**Comment by KirAsh4** [comment]
Currently running v2-beta, which I installed several days ago. I see some files have already changed since I installed it.

**Comment by MichMich** [comment]
See: https://github.com/MichMich/MagicMirror/tree/v2-beta#updating-you-magicmirror
