### ISSUE TITLE
on forums, is there a way to blank user profile when banned?

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2726]
users are using forum to advertise, jamming stuff in their profile

I can delete posts and marked them banned but cannot delete the profile advertising info.
this pollutes the forum site user registry

**Comment by MichMich** [comment]
What do you recommend?

**Comment by sdetweil** [comment]
well, it would be nice to clear their profile.. remove the advertising that is on the profile.  we can't delete the userid, as they would just reregister it..  getting regular spam.. 

but I know nothing about the forum tool, so I don't know whats possible..

**Comment by MichMich** [comment]
I have to look into it. But im flooded with work. Will get back to it. (And if not, feel free to poke me! :))

**Comment by sdetweil** [comment]
I didn't mean this instant.. thats why I posted an issue.. when u(or someone else) gets around to it..

**Comment by khassel** [comment]
using [this](https://forum.magicmirror.builders/user/poojaa) as example we would have to blank several fields to get rid of all possible link locations.

Found with google:
- https://community.nodebb.org/topic/14292/disable-about-me sadly with no answer
- hacking in mogodb, here example for clearing signature https://community.nodebb.org/topic/9141/deleting-all-user-signatures

So nothing out of the box so far.

**Comment by sdetweil** [comment]
new reputation limits have eliminated advertising..

**Comment by MichMich** [comment]
Great to hear! Thanks!
