### ISSUE TITLE
weatherprovider.js couldn't POST data, also is it possible to add retry?

### ISSUE THREAD

**Issue by winstonma** [MichMich/MagicMirror#2727]
I was trying to make a POST API call and send some data. However I failed to do so. Then I went to [weatherprovider.js in develop branch](https://github.com/MichMich/MagicMirror/blob/develop/modules/default/weather/weatherprovider.js) and found that the code is sending `this.config.mockData` instead. Even I replaced `this.config.mockData` to `data` the POST still have problem. Eventually I sort of fixed the problem.

Original:
```
	// A convenience function to make requests. It returns a promise.
	fetchData: function (url, method = "GET", data = null) {
		const getData = function (mockData) {
			return new Promise(function (resolve, reject) {
				if (mockData) {
					let data = mockData;
					data = data.substring(1, data.length - 1);
					resolve(JSON.parse(data));
				} else {
					const request = new XMLHttpRequest();
					request.open(method, url, true);
					request.onreadystatechange = function () {
						if (this.readyState === 4) {
							if (this.status === 200) {
								resolve(JSON.parse(this.response));
							} else {
								reject(request);
							}
						}
					};
					request.send();
				}
			});
		};

		return getData(this.config.mockData);
	}
```

Modified:
```
	// A convenience function to make requests. It returns a promise.
	fetchData: function (url, method = "GET", data = null) {
		const getData = function (data) {
			return new Promise(function (resolve, reject) {
				const request = new XMLHttpRequest();
				request.open(method, url, true);
				request.onreadystatechange = function () {
					if (this.readyState === 4) {
						if (this.status === 200) {
							resolve(JSON.parse(this.response));
						} else {
							reject(request);
						}
					}
				};
				if (data) {
					request.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
					request.send(JSON.stringify(data));
				} else {
					request.send();
				}
			});
		};

		return getData(data);
	}
```

Lastly would it be possible to add retry? Thanks a lot

**Comment by khassel** [comment]
What do you mean with `make a POST API call and send some data`? Are you writing a new provider?

I looks like the `data = null` variable is not used in the current implementation.

Your code would break the tests because of `return getData(data);`.

Can you test if this code would work in your use case:

```js
	// A convenience function to make requests. It returns a promise.
	fetchData: function (url, method = "GET", data = null) {
		const getData = function (mockData) {
			return new Promise(function (resolve, reject) {
				if (mockData) {
					let mdata = mockData;
					mdata = mdata.substring(1, mdata.length - 1);
					resolve(JSON.parse(mdata));
				} else {
					const request = new XMLHttpRequest();
					request.open(method, url, true);
					request.onreadystatechange = function () {
						if (this.readyState === 4) {
							if (this.status === 200) {
								resolve(JSON.parse(this.response));
							} else {
								reject(request);
							}
						}
					};
					if (data) {
						request.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
						request.send(JSON.stringify(data));
					} else {
						request.send();
					}
				}
			});
		};

		return getData(this.config.mockData);
	}
```

**Comment by winstonma** [comment]
@khassel I am writing a new module and uses weather module as a reference. Yes I modified this because the `data` is not being used.

To test the function using `this.config.mockData`, should it call `fetchData(url, method = "POST", data = this.config.mockData)` instead?

**Comment by khassel** [comment]
The test case doesn't use an extra provider so I used the workaround with the `getData` function. If the `config.js` has a section `mockData` the above `fetchData` function use this instead of making a fetch to an url. You can see what I implemented for the tests if you compare this file between `develop` and `master`.

So did you test if `return getData(this.config.mockData);` also works in your case?

I think `fetchData(url, method = "POST", data = this.config.mockData)` is no solution because then in `data` are different formats and we can't decide if the content is for mocking or real data.

**Comment by winstonma** [comment]
Yes I tried your code and it works. I may not understand `this.config.mockData` in your use case. It just seems to me that the function `getData` looks a bit weird.

Also, I also wonder if [adding retries](https://stackoverflow.com/questions/38520438/how-to-retry-an-xhr-request-which-returns-a-promise-recursively-for-atleast-n-ti) would be great.
