### ISSUE TITLE
News Feed shows "Loading" if RSS feed is empty

### ISSUE THREAD

**Issue by MacG-DD** [MichMich/MagicMirror#2731]
## I found a bug in MagicMirror

**Platform**: Raspberry Pi 4 with Raspberry Pi OS with desktop

**MagicMirror Version**: 2.17.0

**Description**: If the subscribed RSS feed is empty (I use a traffic warning message feed), then "Loading ..." is displayed, although "hideLoading: true" is set.

**Steps to Reproduce**: The RSS feed is empty or you set the time after which the news is outdated to a very short one.

**Expected Results**: The news feed module should be hidden. Because I have set `hideLoading: true`.

**Actual Results**: "Loading ..." is displayed and refreshed after the updateInterval.

**Configuration**: 
`{`
`	module: "newsfeed",`
`	position: "bottom_center",`
`	config: {`
`		feeds: [`
`			{`
`				title: "Verkehrswarnmeldung",  // = Traffic warning message` 
`				url: "https://www.polizei.sachsen.de/vwd/LMSSN-Bestand.RSS_STD.xml",`
`				encoding: "ISO-8859-1" // default is "UTF-8"`
`			}`
`		],`
`		hideLoading: true,`
`		showSourceTitle: true,`
`		showPublishDate: true,`
`		broadcastNewsFeeds: false,`
`		broadcastNewsUpdates: false,`
`		showDescription: true,`
`		ignoreOldItems: true, `
`		ignoreOlderThan: 24 * 60 * 60 * 1000,  // 1 day`
`		updateInterval: 15 * 1000, // 15 seconds default is 10`
`		prohibitedWords: ['A9', 'A38', 'A72']`
`	}`
`},`

**Comment by khassel** [comment]
can reproduce this but have no idea how to solve this at the moment ...

**Comment by rejas** [comment]
I created a PR that displays a message if the newsfeed is empty ATM. Maybe later we can make it configurable (show info message OR hideCompletly)?
