### ISSUE TITLE
Awesom alexa issue 

### ISSUE THREAD

**Issue by Hamzacos** [MichMich/MagicMirror#2733]
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'node-pre-gyp' Require stack: - /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js - /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js - /home/pi/MagicMirror/js/app.js - /home/pi/MagicMirror/js/electron.js - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js

**Comment by sdetweil** [comment]
https://awesome-alexa.js.org/#/installation?id=step-2-install-module

**Comment by sdetweil** [comment]
I made those into a script a year or so ago, hate copy/paste so much

https://www.dropbox.com/s/omrx3vztjp738hf/do-install.sh?dl=0

**Comment by Hamzacos** [comment]
i follow this instruction but i have the same errure

**Comment by Hamzacos** [comment]
yess i have same result

**Comment by sdetweil** [comment]
sorry. no idea.
 that module hasn't been updated in years, and the author doesn't respond to issues. 

it's not a MagicMirror problem tho.

**Comment by sdetweil** [comment]
i posted in #2732
