### ISSUE TITLE
Module.createRequire is not a function, 2.18

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2772]
this is for documentation

**note: this does not work for pi0w**
use my scripts during install or update
see https://forum.magicmirror.builders/topic/16223/pi0w-status-jan-2022

if u encounter this error when doing  
```
npm run config:check 
```
after upgrading to MagicMirror 2.18, it is because the eslint package requires node 14 or above.

please check your node and npm versions by doing 
```
node -v
npm -v
```

the easiest way to upgrade node is to use the npmjs package called n (node version manager written in node js) 

do
```
sudo npm install n -g
```

then to upgrade node (and npm) do 
```
#upgrade node to version 16
sudo n 16
#fix path for this terminal session, it will be ok for new started sessions
PATH="$PATH"
```

n is pretty cool, it will let you switch between node versions too. we are only using a tiny bit of its function.
do n --help 
to see all it can do

**Comment by wwats** [comment]
thanks a lot. i'm a beginner and do not understand this or what i have to do exactly:

#fix path for this terminal session, it will be ok for new started sessions
PATH="$PATH"

Can You explain this? Thank You very much !

**Comment by sdetweil** [comment]
you just cut and paste the text

leading # is a comment

**Comment by wwats** [comment]
Thanks a lot.
My npm version is 8.1.2 - i need 8.3? i can't install because: error: eacces: permission denied, rename xxxxx
You know the solution?
My screen is still black ;-) 
i can delete this post if he is not for here... 
thanks you very much!

**Comment by sdetweil** [comment]
no, whatever comes with node 16 is fine.. 

black screen is another problem .. 
see 
https://forum.magicmirror.builders/topic/15778/fix-for-black-screen-in-2-16-and-later

**Comment by onisuk** [comment]
sudo n 16 gives me 

 Error: no version found for '16'

**Comment by sdetweil** [comment]
what pi is this?

**Comment by sdetweil** [comment]
no direct route to node 16 on pi 0w
