### ISSUE TITLE
error npm command not found 

### ISSUE THREAD

**Issue by misbahbhutto** [MichMich/MagicMirror#2781]
There is an error on raspberry pi 4 while Installing magic mirror

npm command not found

And another error is 
unable to acquire the dpkg frontend lock are you root 
How can I solve

**Comment by sdetweil** [comment]
if you do not use my install script, see https://github.com/sdetweil/MagicMirror_scripts
then u have to install node and npm manually

a google search will show you how.. 
https://www.makersupplies.sg/blogs/tutorials/how-to-install-node-js-and-npm-on-the-raspberry-pi

dpkg lock usually means some other process is already doing updates
