### ISSUE TITLE
102730091 ms: Mark-sweep 881.5 (983.0) -> 880.4 (983.3) MB, 6928.0 / 0.5 ms  (average mu = 0.346, current mu = 0.311) allocation failure scavenge might not succeed

### ISSUE THREAD

**Issue by Fredi009sg** [MichMich/MagicMirror#2803]
102730091 ms: Mark-sweep 881.5 (983.0) -> 880.4 (983.3) MB, 6928.0 / 0.5 ms  (average mu = 0.346, current mu = 0.311) allocation failure scavenge might not succeed

Got this after a while. How can i fix it ?

**Comment by rejas** [comment]
where did you get this message and why is that a problem?

**Comment by Fredi009sg** [comment]
got this when i'm doing pm2 logs

**Comment by sdetweil** [comment]
@Fredi009sg 

can you do what the issue template asked for

what pi
when did you download the PI OS?


uname -a
lsb_release -a
node -v
npm -v
free -m
df -k
 
how did you install?  manual, automated script? 
 
what did you do BEFORE u attempted install?
   any system updates, or installs of other things?

**Comment by Fredi009sg** [comment]
> @Fredi009sg
> 
> can you do what the issue template asked for
> 
> what pi when did you download the PI OS?
> 
> uname -a 

Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

> lsb_release -a 

No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

> node -v 

v16.13.2

> npm -v 

8.1.2


> free -m 

                      total        used        free      shared  buff/cache   available
Mem:          3838       1399         242         205        2196        2300
Swap:          1023         125         898

> df -k

Dateisystem                                     1K-Blöcke    Benutzt Verfügbar Verw% Eingehängt auf
/dev/root                                        30358348   13121948  15951904   46% /
devtmpfs                                          1800564          0   1800564    0% /dev
tmpfs                                             1965428      17220   1948208    1% /dev/shm
tmpfs                                             1965428      17060   1948368    1% /run
tmpfs                                                5120          8      5112    1% /run/lock
tmpfs                                             1965428          0   1965428    0% /sys/fs/cgroup
/dev/mmcblk0p1                                     258095      49283    208812   20% /boot
192.168.160.70:/volume1/Backups/Full_Backup_Pi 1917962752 1003842816 914001152   53% /backup
tmpfs                                              393084          4    393080    1% /run/user/1000


> how did you install? manual, automated script?

with your script..

> what did you do BEFORE u attempted install? any system updates, or installs of other things?

**Comment by jboucly** [comment]
I had this problem when I created my module... 
I hadn't anticipated the available memory allocation of an RPI.

I'm guessing you've either developed a module that takes more memory allocation than the RPI suggests. Either you used a module that was not very well developed due to the memory size of an RPI. 

Can you list the modules you use ?
