### ISSUE TITLE
[Tracking Issue] ESLint, JSCS Deprecation, and Tests

### ISSUE THREAD

**Issue by nhubbard** [MichMich/MagicMirror#281]
If any of you follow the JSCS project that we use for coding style, they have deprecated the project in favor of merging with ESLint. I have been reading up on ESLint, and found that I have been doing it wrong all along! :fearful: 

So, this is a tracking issue. We make a checkmark list to show what progress is happening here.

- [x] Remove JSCS and replace it with ESLint.
- [x] Add Travis tests to enforce ESLint, StyleLint, and HTML Validator rules.

I expect this entire system to be done by the end of the beta.

**Comment by MichMich** [comment]
Add travis test on ESLint would make any contribution much more difficult. Maybe we should force this?

**Comment by MichMich** [comment]
Scratch that. I ran into some issues cased by a PR that wasn't JS linted. FORCE IT! 😈
