### ISSUE TITLE
Wrong sunset/sunrise time (only on physical screen)

### ISSUE THREAD

**Issue by lory9894** [MichMich/MagicMirror#2811]
Platform Raspberry Pi 3b+, running  MagicMirror in docker

Node Version: v16.14.0

MagicMirror Version: 2.18.0

Description:

The sunset/sunrise time is one hour early, both in the weather module and in the clock module, but only on the physical monitor
![WhatsApp Image 2022-02-11 at 10 46 34](https://user-images.githubusercontent.com/48431431/153569933-1cffdfc6-dcf2-4b2c-8f9d-aa4d894cd4d6.jpeg)

If I instead connect to the magic mirror from another device the time is correct
![image](https://user-images.githubusercontent.com/48431431/153569717-04ba13ed-0c0d-4e3c-acd8-fdfd42bd39cb.png)

This is the relevant part of my config file:

```
{
	module: "clock",
	position: "top_left",
	config: {
		timezone : "Europe/Rome",
		showSunTimes : "true",
		lat : "45.07008305582845",
		lon : "7.5027800551310175"
	}
}
```

```
{
	module: "weather",
	position: "bottom_right",
	header: "Weather Forecast",
	config: {
		weatherProvider: "openweathermap",
		type: "current",
		location: "Rivoli",
		locationID: "3169231", 
		apiKey: "[hidden]"
                showHumidity : "true"
	}
```

**Comment by khassel** [comment]
may the timezone settings of your pi are wrong. If you login and run `date` is this 1h earlier?

**Comment by lory9894** [comment]
No, the timezone is correct.
Ran `date` and it was correct

**Comment by khassel** [comment]
tested your setup, works, no differences.

But if I set timezone to London with `export TZ=Europe/London` then I can reproduce your behavior.

**Comment by lory9894** [comment]
This morning when I woke up it was correct.....,so i can't reproduce the behaviour anymore.

I'm closing the issue, if someone encounter the same problem can be reopened
