### ISSUE TITLE
Calendar: Repeating events with time are not displayed 

### ISSUE THREAD

**Issue by Psycho0verload** [MichMich/MagicMirror#2813]
# Calendar: Repeating events with time are not displayed
## Enviroment
- Raspberry Pi 3
- Raspbian GNU/Linux 11 (bullseye)
- PM2 5.1.2
- npm 8.3.1
- node v16.14.0
- MM 2.18.0
- Calendar selfhostet Nextcloud

## Problem:

- ❌ A repeating event with a fixed time is not displayed in the calendar.

## Working:

- ✅ Repeat of the full day event is displayed
- ✅ A non-repeating event with a fixed time is displayed
- ✅ A non-repeating full day event is displayed

## Configuration 
```
{
    module: "calendar",
    header: "Tagesübersicht",
    classes: "daily-overview",
    position: "middle_center",
    config: {
        carouselId: "1",
        tableClass: "large daily-overview-table wachenaufgaben",
        fetchInterval: 600000, /* 600000 */
        maxTitleLength: 50,
        displaySymbol: true,
        showLocation: false,
        maxTitleLines: 1,
        maximumEntries: 9,
        maximumNumberOfDays: 1,
        calendars: [
            {
                url: 'https://mydomain.it/remote.php/dav/public-calendars/ZMGgBLGxxxxxDw?export',
                symbolClass: 'todo-symbol',
                titleClass: 'todo-title',
                timeClass: 'todotime',
                symbol: 'clipboard-list-check'
            },
            {
                url: 'https://mydomain.it/remote.php/dav/public-calendars/WW49cKGxxxxxq8?export',
                symbolClass: 'clean-symbol',
                titleClass: 'clean-title',
                timeClass: 'clean-time',
                symbol: 'vacuum',
            },
            {
                url: 'https://mydomain.it/remote.php/dav/public-calendars/eMQW6xxxxxbXq?export',
                symbolClass: 'info-symbol',
                titleClass: 'info-title',
                timeClass: 'info-time',
                symbol: 'circle-info',
                maximumNumberOfDays: 7,
            }
        ]
    }
},
```

## Expected Results
It would be desirable to display repeating events with time as well as it works with all day events.

## Actual Results
The event disappears completely as soon as it is no longer an all-day event.

## Bug Hunt
https://forum.magicmirror.builders/topic/16372/calendar-repeating-events-with-time-are-not-displayed

**Comment by Psycho0verload** [comment]
It also makes no difference whether I enter it in the web interface of nextcloud or in the calendar app from apple.

**Comment by sdetweil** [comment]
@Psycho0verload the event is inside the relative window, so shown as tomorrow or Thursday

change relative  and look at urgency

**Comment by sdetweil** [comment]
@Psycho0verload were u able to resolve this?

**Comment by Psycho0verload** [comment]
I will check this again. I will have access to the system again tomorrow

**Comment by Psycho0verload** [comment]
What do you mean? So at what point should I change something?

It is difficult to change something in the source code of the appointment itself, because the end user is not able to do that.

I have now tested the whole thing again with:
`timeFormat: absolute / relative / dateheaders`

In any case the date is displayed correctly as long as it is not repeated.

I don't see any more value to set the option `urgency`, because in every display whether absolute, relative or dateheaders the error occurs.

**Comment by sdetweil** [comment]
@Psycho0verload 

looking back over this., with the failing cal entry above, 

```
RRULE:FREQ=WEEKLY;INTERVAL=1
   DTEND;TZID=Europe/Berlin:20220217T190000  // indented to align date/time for discussion
DTSTART;TZID=Europe/Berlin:20220217T090000
```
it starts and ends on the same day, and requests weekly... so would only show one event.

**Comment by khassel** [comment]
seems not to be a bug, can this be closed @sdetweil ?

**Comment by sdetweil** [comment]
yes, can close

**Comment by khassel** [comment]
please close @Psycho0verload @MichMich
