### ISSUE TITLE
Install error: Playwright does not support firefox on ubuntu18.04-arm64

### ISSUE THREAD

**Issue by MMM-Jasmin** [MichMich/MagicMirror#2821]
Hi,

i am trying to install the newest version on an arm64 system.
Since the last version playwright was added as it seems.
When I try to execute the npm install I receive the the error:

ERROR: Playwright does not support firefox on ubuntu18.04-arm64
even firefox is not installed on the system.

edit: @khassel I guess you added playwright instead of spelectron, right?

[2022-03-14T11_57_07_251Z-debug-0.log](https://github.com/MichMich/MagicMirror/files/8244505/2022-03-14T11_57_07_251Z-debug-0.log)

**Comment by sdetweil** [comment]
playwright is for testing.

do 

npm install only=prod

**Comment by khassel** [comment]
as addition to @sdetweil's answer: There is already a [PR in the documention repository](https://github.com/MichMich/MagicMirror-Documentation/pull/105) reflecting this which will be hopefully merged soon.

Only users who wants to run the tests needs the devDependencies (including playwright), so for 99% of the installations running `npm install only=prod` (or `npm install omit=dev` depending on the npm version) is the better choice. Its quicker and needs less space on disk.

**Comment by MichMich** [comment]
@khassel merged it!

**Comment by MMM-Jasmin** [comment]
Cool thanks for the clarification! It works with --omit=dev.
But i guess it is "--only=prod" or "--omit=dev", isn´t it? They documentation now stats both

"Install the application: npm install --only=prod --omit=dev"

**Comment by sdetweil** [comment]
I have updated the scripts, install and upgrade to handle the different options for prod only/omit dev

https://github.com/sdetweil/MagicMirror_scripts

**Comment by khassel** [comment]
Tested now `npm install --only=prod --omit=dev` with node v16 and v17 and this works. I think the contributor of the documentation PR testet this for older versions too.

The `--omit` was introduced with npm 7.x (Node v15) so we can remove the `--only` option with end of life of Node v14 (2023-04-30).

**Comment by sdetweil** [comment]
I changed my scripts to use --omit for npm 8

**Comment by khassel** [comment]
should be closed @MMM-Jasmin @MichMich
