### ISSUE TITLE
on forum can we get reputation and anti spam installed. 

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2823]
see #2726

we a flooded with users for advertising. 
need reputation to prevent them using forum system space
anti spam as well

**Comment by MichMich** [comment]
Unfortunately I couldn't find any working (maintained) reputation plugins, but I did add some additional anti spam checks. Especially for the creation of new accounts. Let me know if this helps.

**Comment by sdetweil** [comment]
no help, sorry.

**Comment by sdetweil** [comment]
can e get spam-be-gone installed and configured?
https://community.nodebb.org/topic/15119/spam-registration-amount-and-handling-is-unbearable

still supported it says. 

 we get 20-30 new spam registrations a day

**Comment by MichMich** [comment]
Spam-be-gone is already installed an active (at is has been for the past few months). 

Not sure how to catch more spam.

![Screenshot 2022-04-05 at 09 25 00](https://user-images.githubusercontent.com/210954/161700911-96d627c0-e632-467b-abc2-be814cdde188.png)

![Screenshot 2022-04-05 at 09 25 06](https://user-images.githubusercontent.com/210954/161700917-22469d6b-c9b9-4272-ac3c-ef728612d1bc.png)

![Screenshot 2022-04-05 at 09 25 11](https://user-images.githubusercontent.com/210954/161700919-9839f509-e8e1-46f7-86b3-3f986a28a342.png)

![Screenshot 2022-04-05 at 09 24 55](https://user-images.githubusercontent.com/210954/161700920-405f0fb4-155c-4cf3-bf89-79481b275d2e.png)

**Comment by sdetweil** [comment]
can u up the reputation required for about me and signature to 2?

![Screenshot_20220405-070248_Chrome](https://user-images.githubusercontent.com/1498142/161749744-b1d845f4-3518-476d-9197-78dc7966841b.jpg)

**Comment by MichMich** [comment]
Good catch! Done!

**Comment by sdetweil** [comment]
thx.  

can u do that for the website field?

**Comment by MichMich** [comment]
Yeah, I did it for all the fields that can be abused for spam.

**Comment by sdetweil** [comment]
thanks... can't wait to see how that affects registrations..

**Comment by sdetweil** [comment]
so, we still get a bunch of advert registration attempts, but looks like it's trending lower.
