### ISSUE TITLE
Bad font for non latin users

### ISSUE THREAD

**Issue by alexey-gamov** [MichMich/MagicMirror#2835]
## Fonts bug in MagicMirror

**Platform**: MagicMirrorOS on Raspberry Pi 2 .
**MagicMirror² Version**: 2.19.0

**Description**:

In this update fonts package was changed from `roboto-fontface-bower` to `fontsource` (2dcf55ea89f752390554d655ee819148c07e4fbc).
CSS file `roboto.css` uses only `latin` subset for loading woff files. It is not fair = fonts must consist all world chars.

**Way to fix**:

Change `roboto-latin-100-normal.woff2` to `roboto-all-100-normal.woff2` and etc.

**Expected Results**: Fonts are still great with non US characters.
**Actual Results**: Fonts are ugly. Need to add custom `@font-face` from Google.

**Comment by khassel** [comment]
> It is not fair = fonts must consist all world chars.

that was not intentional

Can you provide a PR to fix this? Otherwise I will create one ...

**Comment by alexey-gamov** [comment]
> > It is not fair = fonts must consist all world chars.
> 
> that was not intentional
> 
> Can you provide a PR to fix this? Otherwise I will create one ...

Last package was international :)
Unfortunately am not expert in node modules, it will be better if you can fix that issue..

**Comment by outlying** [comment]
I confirm that, 2.19.0 update "broke" fonts in news module and greeting module (see `ń` character)
<img width="392" alt="image" src="https://user-images.githubusercontent.com/2069751/161687041-f1a31d52-a5b3-4d91-9483-7d8182ad29fd.png">

**Comment by MichMich** [comment]
Can anyone confirm the PR of @khassel solves the issue?

**Comment by DecliningLotus** [comment]
Fontsource maintainer here. It may be better for you to reference the source CSS file itself so you can write the appropriate `@font-face` declarations instead to support international users. The `unicode-range` CSS selector is a key thing that @khassel’s PR is missing that prevents `woff2` files from being used effectively.

Example [CSS file](https://github.com/fontsource/fontsource/blob/main/fonts/google/roboto/400.css).

Additionally when [fontsource/fontsource#234](https://github.com/fontsource/fontsource/issues/234) is implemented, I think that will help simplify your build process a lot more. Feel free to keep tabs on that issue!

**Comment by rejas** [comment]
> Can anyone confirm the PR of @khassel solves the issue?

I can confirm that with his PR the ń looks better (when used in the compliments module) Not sure if that solves it for ALL possible letters.
