### ISSUE TITLE
MMM-NowPlayingOnSpotify

### ISSUE THREAD

**Issue by Henry183** [MichMich/MagicMirror#2856]
The modul is not on the MagicMirror, what should I do ? 

  module: "MMM-NowPlayingOnSpotify",
                           position: "bottom_right",

                           config: {
                           showCoverArt: "true",
                           clientID: "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
                           clientSecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                           accessToken: "BQAJjnPpz6ZUfphJMvCqG9U5NIsvTsq7Y_FwT0scihoiVPUXa5z--DOPCXj28cl2kqsTHLHij4dl2evq1kLHSgmBAXYHUQhCVagekdCwWuAjSNeUzWv$
                           refreshToken: "AQCJ6-mhJlHAJzzmtRnA-LCV5lTW8UMgkJpsVg6fp5Sc7LxcjMvdgJ-q0A_vavDLpk4VcxHctVOokmlu2G2LxAGun7KrDly9TekqEKzn-U248v5uez$

**Comment by sdetweil** [comment]
I would move to the MMM-Spotify module... that one is very old
https://github.com/skuethe/MMM-Spotify

**Comment by rejas** [comment]
@Henry183 can this be closed now? Or @MichMich just does it since it seems to be not mm2-core related...

**Comment by khassel** [comment]
should be closed @MichMich
