### ISSUE TITLE
When i put a module it wont work

### ISSUE THREAD

**Issue by JosefVega** [MichMich/MagicMirror#2859]
i have git cloned it 
this is an example error 
] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-CoinMarketCap/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js

code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-CoinMarketCap/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',

**Comment by MichMich** [comment]
Try `npm install request` from within your MagicMirror folder.

**Comment by JosefVega** [comment]
> Try `npm install request` from within your MagicMirror folder.

Thanks it works now :)

**Comment by sdetweil** [comment]
@JosefVega can u close this issue?

**Comment by khassel** [comment]
should be closed @MichMich
