### ISSUE TITLE
Individual calendar ignoring maximumEntries

### ISSUE THREAD

**Issue by JordiDeMaeyer** [MichMich/MagicMirror#2868]
Hello,

I had a magic mirror running at my sisters place. (running since october 2021)
It didn't boot anymore, but I had a cheap SD card so I know this was possibly happening.

I got a new SD card, installed magic mirror and it worked beautifully.
All the modules worked, and even had the right configuration (rss feeds and weather locations).

The only problem I have now is that the induvidual calanders don't limit their entries.
It looks like the maximumEntries:3, doesn't work anymore for me.

(Url's deleted for privacy)
`
{
			module: "calendar",
			header: "The next 7 day",
			position: "top_left",
			config: { 
					maximumNumberOfDays: 7,
					colored: "true",
					coloredSymbolOnly: "true",
					showLocation: "true",

					calendars: [
						{
							url: #######,
							maximumEntries:1,
							symbol: 'stethoscope',
							color: '#00FFFF',
							},
															
						{
							url: #######,
							maximumEntries:3,
							symbol: 'home',
							color: '#F3FF00',

							},

						{
							url: #######,
							maximumEntries:3,
							symbol: 'user-ninja',
							color: '#FF00C1',

							},
	
								],
					},
		},
`
The first calendar displays 7 entries, the second 4 and the third also 4.

If i change the 'maximumEntries: calendar.maximumEntries, ' to just 3, nothing changes.

Does anyone have an idea how to debug this, because I can't find errors and such.

Thanks in advance for the help.

**Comment by JordiDeMaeyer** [comment]
Thank you for your rapid response!

But am I missing something here?
I know it's on the list for the individual entries, I have placed it there.
But it's not limited to my set amount.

`calendars: [
					{
						url: #######,
						maximumEntries:1,
						symbol: 'stethoscope',
						color: '#00FFFF',
						}, `

**Comment by JordiDeMaeyer** [comment]
I tried setting it above the URL 
`calendars: [ { maximumEntries:1, url: #######, symbol: 'stethoscope', color: '#00FFFF', },`
but this doesn't work.

The maximumEntries global does work.

`module: "calendar",
header: "The next 7 day",
position: "top_left",
config: {
maximumNumberOfDays: 7,
colored: "true",
coloredSymbolOnly: "true",
showLocation: "true",
maximumEntries:7,`


				calendars: [
					{
						url: #######,
						symbol: 'stethoscope',
						color: '#00FFFF',
                                            maximumEntries:7,
						},`

This wil display a maximum of 7 event. 
It's just that I'd like to specify each individual calendar and that doens't work anymore.

Is this what you meant by setting it above the calendars list?

**Comment by sdetweil** [comment]
I will try to give u a temp fix later today. working in the garage right now before it becomes 100 degrees again

**Comment by sdetweil** [comment]
ok, try this 

edit modules/default/calendar,calendarutils.js

insert a line at line 501
and change  line 502 after the line add

should look like this when u are done
```
		newEvents.sort(function (a, b) {                                              // line 497
			return a.startDate - b.startDate;
		});

		let maxEvents=newEvents.slice(0,config.maximumEntries)   // new line
		return maxEvents;                                                                   // changed line
	},
```

**Comment by JordiDeMaeyer** [comment]
It looks like this fixed it.
Thank you very much for your help

**Comment by sdetweil** [comment]
cool, could u reopen,  to track the fix

**Comment by sdetweil** [comment]
this fix introduced another bug..  #2888, fixed for 2.21.0 Oct 1, 2022 release

**Comment by khassel** [comment]
can this be closed? @sdetweil

**Comment by sdetweil** [comment]
yes
