### ISSUE TITLE
How do i fix Electron issue. Magic Mirror won't run

### ISSUE THREAD

**Issue by kizzytodd** [MichMich/MagicMirror#2869]
Platform --- Raspberry Pi 4
Windows – Linux
Node Version --- 18.4.0
MagicMirror² Version --- 2.19.0
Description --- I have done all the updates and installs and when I try to start the MM I get that message regarding the electron not found 

pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.19.0 start
> .\node_modules\.bin\electron js\electron.js

sh: 1: .node_modules.binelectron: not found

**I tried to install electron, 

pi@raspberrypi:~/MagicMirror $ npm install electron@3.0.10
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.22.2',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16 || ^17' },
npm WARN EBADENGINE   current: { node: 'v18.4.0', npm: '8.12.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@38.1.6',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16 || ^17' },
npm WARN EBADENGINE   current: { node: 'v18.4.0', npm: '8.12.2' }
npm WARN EBADENGINE }

changed 1 package, and audited 765 packages in 13s

74 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**I run the command to force fix and got 3 moderate vulnerabilities. I tired fot force fix those and I am back to 1 high severity vulnerability that needs fixing. And it goes around and around again. 

**How do I resolve this. Not sure what to do. I Just want to run my MagicMiror like I used to with all my modules (weather, time pollen count, calendar, new feed, comments and globe).

**Comment by sdetweil** [comment]
we are on a later version

npm install electron@17.2.0

what version of node do you have?  must be 14 or 16

**Comment by kizzytodd** [comment]
node 18.4.0
npm 8.12.2
node js 16.15.1

**Comment by kizzytodd** [comment]
I ran the npm install electron@17.2.0 and got

i@raspberrypi:~/MagicMirror $ npm install electron@17.2.0
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.22.2',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16 || ^17' },
npm WARN EBADENGINE   current: { node: 'v18.4.0', npm: '8.12.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@38.1.6',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16 || ^17' },
npm WARN EBADENGINE   current: { node: 'v18.4.0', npm: '8.12.2' }
npm WARN EBADENGINE }

added 43 packages, removed 58 packages, changed 6 packages, and audited 750 packages in 50s

79 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by kizzytodd** [comment]
pi@raspberrypi:~/MagicMirror $ npm audit
# npm audit report

got  <11.8.5
Severity: moderate
Got allows a redirect to a UNIX socket - https://github.com/advisories/GHSA-pfrx-2q88-qq97
fix available via `npm audit fix --force`
Will install electron@6.1.12, which is a breaking change
node_modules/got
  @electron/get  *
  Depends on vulnerable versions of got
  node_modules/@electron/get
    electron  >=7.0.0-beta.1
    Depends on vulnerable versions of @electron/get
    node_modules/electron

3 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
pi@raspberrypi:~/MagicMirror $

**Comment by sdetweil** [comment]
no idea. I suggest u start over, fresh flash, pi os, 32bit, full, called bullseye (current release)

then use my install script, see
https://github.com/sdetweil/MagicMirror_scripts

it does all the setup and dependency install

**Comment by kizzytodd** [comment]
So your script will install everything needed (outside the modules and 3rd party modules) to get it going.

**Comment by sdetweil** [comment]
correct. get the base up and running. same as manual install would have done... (assuming everything was prepared correctly)
