### ISSUE TITLE
Proposal: Code Scaffolding for New Module Creation

### ISSUE THREAD

**Issue by tderflinger** [MichMich/MagicMirror#2872]
Dear Magic Mirror Community,

I really like your project and I have created modules myself as a programmer. In order to help other programmers and especially people new to Magic Mirror module development, I would propose a code scaffolding aid.

There exists a library called Hygen (https://www.hygen.io/) that facilitates rapid JavaScript code generation. Using this tool, I have developed starter templates for the rapid creation of new Magic Mirror modules.

You can find my code here: https://github.com/tderflinger/hygen-magicmirror

Basically, when starting Hygen, the tool asks for the name of the Magic Mirror module and if a package.json is needed. Then it creates a set of ready-to-use source files in the `modules` folder.

We could include the `_templates` folder of `/tderflinger/hygen-magicmirror` in the main Magic Mirror distribution and add a script to the package.json, like "create-module": "npx hygen module new". This is all that is needed to help developers create new modules more easily and rapidly.

What do you think about this?

Thanks and best,
-Thomas

P.S.: Of course the code that is generated can be changed easily in the EJS template files.

**Comment by rejas** [comment]
I do like the idea, it would help for new developers to get into it. Although once you have setup your fresh module with hygen, one still has to know enough of JS and MM to get the rest done... So yeah: helps to get into coding stuff, but doesnt take all work away :-)

**Comment by tderflinger** [comment]
HI @rejas, yes that is true. For making it even easier for beginner coders there would probably need to be some kind of low code environment.
So should I create a pull request with my code proposal or would you rather prefer to wait for some bigger improvements in the direction of low code in the future? 
Another area would be to write more detailed documentation geared for beginners. I might also be able to help there a bit. :)

**Comment by MichMich** [comment]
Hi @tderflinger, thanks for your suggestion. I appreciate the fact you want to make it easier for people to create modules. As you can read in the "[manifesto](https://docs.magicmirror.builders/about/manifesto.html)", one of the reasons I open sourced MagicMirror² was to encourage people to take their first steps in software development. 

However I do think that extracting things away, and using generators doesn't make it necessarily easier for users to learn how to built stuff. That being said, it can have it's purpose to have tools like hygen. My suggestion would be to make that an 3rd party repo, separate from the core. 

Feel free to add information about this (and the repo) in the docs. That way people can still use it without needing to maintain it in the core repo.

**Comment by tderflinger** [comment]
Hi @MichMich! Thanks for your feedback. I will add a section to the Magic Mirror documentation so that developers who are interested in it can find it.

Kind regards,
-Thomas

**Comment by khassel** [comment]
seems to have been discussed, can this be closed @tderflinger @MichMich
