### ISSUE TITLE
Calendar not showing todays "full-time"-events

### ISSUE THREAD

**Issue by Calibba** [MichMich/MagicMirror#288]
Hello, 

i just found an issue i cannot explain. The Calendar works really fine, with one exception: 
I´m using just one Calendar for my Mirror. It´s a google-Calendar that only stores full-time-events (birthdays from family&friends). 
My issue is: These events keep disappearing on the event-day. In the evening i see, that it´s happening the next day, on the next day: the event has disappeared. It would be nice if i could see the event on the day it´s happening, maybe with an text that says "today" or something like that. 

Maybe someone can help me with this issue. Thank you in advance :-)

I´m using MagicMirror1, not the  ²-Version. 

With best regards
Calibba

**Comment by MichMich** [comment]
Hi Caliber,

Try using the v2 version. A lot of effort went into issues like this.
