### ISSUE TITLE
Calendar Repeating Events one day off 

### ISSUE THREAD

**Issue by DAHines57** [MichMich/MagicMirror#2885]
Hardware: RPi 3, Stretch
Node version: v16.14.2
MagicMirror: v2.20.0

Description: 
I have repeating google calendar event set for Thursdays at 8pm to 11pm, and this displays correctly there, but in the calendar module this event is shown to be on Friday from 8 to 11pm.  I have also noticed if I set the event to be 6pm to 8pm, the event displays correctly in the module.

Timezone: America/Chicago

iCal:
```
BEGIN:VEVENT
DTSTART;TZID=America/Chicago:20220728T200000
DTEND;TZID=America/Chicago:20220728T230000
RRULE:FREQ=DAILY;COUNT=30;INTERVAL=7
DTSTAMP:20220723T162624Z
```

Calendar Config:
```{
			module: "calendar",
			header: "Calendar",
			position: "bottom_left",
			disabled: false,
			config: {
				showEnd: false,
				dateFormat: "MMM DD - hh:mm A",
				maximumEntries: 6,
				calendars: [
```

Screenshot:
![image](https://user-images.githubusercontent.com/16733851/180614012-ba7d5954-6ede-4ab9-95f4-86d8eb2ed8b4.png)

Thanks!

**Comment by sdetweil** [comment]
@DAHines57 what did u do to fix this?

**Comment by DAHines57** [comment]
@sdetweil I had noticed that my repository was acting strange, so I re-cloned the repo and tried again. However I did notice that when I create the recurring event from my iPhone the date is still off. But if I create the event directly in google calendar the dates show correctly.

**Comment by sdetweil** [comment]
ok, thanks. I will look at this.  is the ve ent above a good example?

**Comment by DAHines57** [comment]
Here's a more updated example, the first was created directly in gCal ('Test Gcal'), the second using the iphone default calendar app ('Test') .

```
BEGIN:VEVENT
DTSTART;TZID=America/Chicago:20220721T200000
DTEND;TZID=America/Chicago:20220721T230000
RRULE:FREQ=WEEKLY;BYDAY=TH
DTSTAMP:20220725T015743Z
UID:
CREATED:20220725T005851Z

BEGIN:VEVENT
DTSTART;TZID=America/Chicago:20220728T210000
DTEND;TZID=America/Chicago:20220728T220000
RRULE:FREQ=WEEKLY;BYDAY=TH
DTSTAMP:20220725T015743Z
UID:
CREATED:20220725T014034Z
```
![image](https://user-images.githubusercontent.com/16733851/180679019-c1461a24-2229-4ce2-96b2-316f32aefc21.png)

**Comment by DAHines57** [comment]
@sdetweil should I reopen this?

**Comment by sdetweil** [comment]
this is a bug in the repeating rule processor we use 
( my clock is set to Chicago as well) 

we asked for the right range, 
now  Mon Jul 25 2022 08:04:54 GMT-0500
to (year from now) 
Mon Jul 24 2023 23:59:59 GMT-0500

and it skipped 7/28, returning 08/04 as the 1st date 
 ["2022-08-04T02:00:00.000Z",

```
Search for recurring events between: Mon Jul 25 2022 08:04:54 GMT-0500 (Central Daylight Time) and Mon Jul 24 2023 23:59:59 GMT-0500 (Central Daylight Time)
[25.07.2022 08:04.54.634] [DEBUG] Title: start 28, with dates: ["2022-08-04T02:00:00.000Z","2022-08-11T02:00:00.000Z","2022-08-18T02:00:00.000Z"
```

**Comment by DAHines57** [comment]
Interesting, makes sense why just starting the event a week earlier "solves" the problem

**Comment by khassel** [comment]
seems to be fixed in v2.21.0, can this be closed @sdetweil ?

**Comment by sdetweil** [comment]
just waiting for confirmation

**Comment by DAHines57** [comment]
@sdetweil It's working for me after pulling v2.21.0

**Comment by sdetweil** [comment]
awesome. can u close this issue now.
