### ISSUE TITLE
Implement smooth weather icons

### ISSUE THREAD

**Issue by djsunrise19** [MichMich/MagicMirror#29]
Hi,

thank you very much for describing your project. Actually, I'm working on the magic mirror, too :). So, I have a question / an idea:

I saw these very smooth weather icons (https://github.com/maxdow/skycons). Is it possible to implement these?

Greets
Maurice

**Comment by jusingh2** [comment]
Dear  Maurice, 
	I believe this is could be implemented. I am not that familiar with JavaScript but at first glance, it looks possible. But it all depends on the end use of the program.

Regards,
Jus Singh

**Comment by cxdy** [comment]
Not a developer of the project but I'll take a look tonight and try it out. Should be pretty easy.

**Comment by djsunrise19** [comment]
Sounds great. Any new informations here?

Regards
Maurice

**Comment by cxdy** [comment]
I've been swamped, apologies. I'll post more when I can.

**Comment by Dom1n1c** [comment]
i migrated to a newer version of weathericons, but then the small icons disappear.. maybe i'll find a solution...
