### ISSUE TITLE
nohup message

### ISSUE THREAD

**Issue by djsunrise19** [MichMich/MagicMirror#290]
**Raspi 3, Jessie, node v.6.0.0.**

Since the last `git pull` today (last one was 2 days ago) the MM² app doesn't start anymore. cpu usage is on 25% like everytime, but I only see my desktop. I tested a few things with pm2 and so on, but still the same behavior.

With `DISPLAY=:0 nohup npm start &` I get the following: 
![hup](https://cloud.githubusercontent.com/assets/14234570/15028148/a679faf8-1247-11e6-89e0-7fd9eceaf432.jpg)

Any ideas?

**Comment by KirAsh4** [comment]
So what's in nohup.out? Should be a text file that you can read ...

**Comment by djsunrise19** [comment]
Ouh, sorry, here it is:

[nohup.txt](https://github.com/MichMich/MagicMirror/files/250086/nohup.txt)

I didn't changed anything since the latest pull.

**Comment by MichMich** [comment]
It looks like the netamo module misses a node module (vcard)

**Comment by djsunrise19** [comment]
I deactivated the modules, still the same problem:

[nohup_2.txt](https://github.com/MichMich/MagicMirror/files/250100/nohup_2.txt)

**Comment by djsunrise19** [comment]
Here is my npm debug as well:

[npm-debug.txt](https://github.com/MichMich/MagicMirror/files/250101/npm-debug.txt)

**Comment by MichMich** [comment]
It still crashed because of this module:
```
Error: Cannot find module 'vcard-json'[0m
```

I suggest you remove all modules and slowly add them one by one seeing which one causes the issue.
(Start with the sample config)

**Comment by djsunrise19** [comment]
I think I get it... The fritzbox call monitor was the problem. As it seems, he needs the vcard in config. I don't know why.

**Comment by MichMich** [comment]
Try running:
```
npm install vcard-json
```

**Comment by djsunrise19** [comment]
@MichMich Install worked, but still the same problem.
@paviro Perhaps you can have a look at it, too.

**Comment by MichMich** [comment]
I suggest you create an issue in the fritzbox call monitor repository.

**Comment by djsunrise19** [comment]
Yes, I'll do that. Thanks as always for your help, michael. :)

**Comment by MichMich** [comment]
You're welcome! :)

**Comment by paviro** [comment]
That's strange, you should not need vCard in your configuration :/
