### ISSUE TITLE
can we turn on posting moderation for the forum

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2904]
tired of the spam.  can we turn on moderation

users with reputation < 2 or posts <3 

I think that is the default

**Comment by sdetweil** [comment]
no feedback, or comments??

**Comment by MichMich** [comment]
![28DF86D4-9A2D-4A24-A794-4B4CCF11B9D4](https://user-images.githubusercontent.com/210954/188926612-c51860a9-1a54-43cf-ac64-fb3c662e6c68.jpeg)

do you mean this setting?

**Comment by sdetweil** [comment]
yes, set rep to 2.

**Comment by MichMich** [comment]
Done!

**Comment by sdetweil** [comment]
thanks.. its working
