### ISSUE TITLE
E2E tests never fail

### ISSUE THREAD

**Issue by rejas** [MichMich/MagicMirror#2911]
When working on my weather refactoring I noticed that the E2E tests never fail.

As can be seen after this commit to the branch https://github.com/MichMich/MagicMirror/pull/2849/commits/d4ef2d157e3414ec60e0b9cdc10068ce3705176d

the test suite should obviously fail, but the checks are all green. 

Not sure yet when this bug got introduced, maybe the e2e refactoring has something to do with it?  @khassel do you have an idea?

**Comment by khassel** [comment]
> do you have an idea?

not at the moment, will look into this ...

**Comment by khassel** [comment]
@rejas can this be closed? Thanks.

**Comment by rejas** [comment]
Yeah, thx. Looking into the tests still since that whole done-calls are looking somehow funky...
