### ISSUE TITLE
FEATURE:  weather -- Display hourly data for specified time period

### ISSUE THREAD

**Issue by dWoolridge** [MichMich/MagicMirror#2918]
I'm working on adding a feature to the weather module.  I think it can be implemented as an additional weather provider (e.g hourlyTimeBlock.js) that could take the hourly forecast from any other provider and modify the dataset.

My need is to see the hourly forecast winds for the next several days, but only for a certain time block (say 8AM to 5PM).  Hopefully I can make this feature general enough so the user could configure it to see winds, or temperature, or precipitation, etc.  See below for an example of the output.

If I can get this working, and there's interest in it, it would be nice to incorporate it into the default weather module (via pull request).  Please let me know what you think.  I'm a long-time programmer, but new to nodeJS so we'll see how this goes.

**Additional configuration variables (for the weather module):**
- weatherProvider:      // Would work same as always
- type: "hourlyTimeBlock",    // This value for type would trigger this feature--first calling your normal "hourly" provider to get the full dataset.
- timeblockStartTime: "08:00",
- timeblockEndTime:  "17:00",
- timeblockNumDays: 3,           // Number of days to show in the output table          
- timeblockWeatherType:  "windSpeedDirection"       // could be tempHigh / tempLow / precipitation / windSpeed / windDirection / windSpeedDirection

```
DAILY FORCAST
 TIME      TODAY     TOMORROW  WEDNESDAY
--------  --------   --------  ---------
8:00 AM     ---      NW @ 3      S @ 2
9:00 AM     ---      NW @ 5      S @ 4
10:00 AM    ---       W @ 7      S @ 4
11:00 AM  NNE @ 12    W @ 10   SSE @ 6
12:00 PM  NNE @ 14    W @ 12      ---
1:00 PM   NNE @ 10    W @ 12      ---
2:00 PM     N @ 8   WSW @ 10      ---
3:00 PM     N @ 7   WSW @ 8       ---
4:00 PM   NNW @ 5    SW @ 8       ---
5:00 PM    NW @ 5    SW @ 6       ---
```

**Comment by rejas** [comment]
Interesting idea, but maybe this should be done in a seperate Module since the weather code is already very big with edge cases (still I am refactoring it :-)

The weather module already sends out a notification with the weather data which a new module could read and display.  

That way the code would be easier to maintain and manageable.

**Comment by dWoolridge** [comment]
Thanks for the information rejas.  

I'll plan to make it a separate Module.  I'll have to look into the notifications and see how to make use of that.
