### ISSUE TITLE
Start Successful alert?

### ISSUE THREAD

**Issue by KirAsh4** [MichMich/MagicMirror#293]
After my last fork sync with the main repository, the successful start alert no longer pops up. Has it been removed, or did I break something inadvertently?

**Comment by MichMich** [comment]
I turned it of by default. But don't tell @paviro, it's his module ... 😂

**Comment by paviro** [comment]
Pfff... It's fine, has to be rewritten anyway 😅

**Comment by MichMich** [comment]
@paviro Note: the module is still in there. I just disabled the default welcome message.

**Comment by paviro** [comment]
I know :)

**Comment by KirAsh4** [comment]
Good, I thought I had broken something and even did a full repository refresh. Figured I'd ask before I do a full comparison of my files. For once I can say, '_**It's not my fault.**_' :)
