### ISSUE TITLE
re-evaluating native module sources is not supported

### ISSUE THREAD

**Issue by paviro** [MichMich/MagicMirror#295]
Reinstelled the mirror with the latest node version, now I get:
`(node:4214) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.`

**Comment by MichMich** [comment]
:( Node 6.0 isn't supported by many packages yet.
Maybe we should use a node 5.X version in the installer and mention it in the readme?

**Comment by paviro** [comment]
Probably :/
