### ISSUE TITLE
 lineageos

### ISSUE THREAD

**Issue by achillealb** [MichMich/MagicMirror#2970]
you can install magic mirror on lineageos?

**Comment by KristjanESPERANTO** [comment]
I don't know, but that sounds like a possible way: https://parzibyte.me/blog/en/2019/05/31/install-node-js-npm-android-termux/

**Comment by sdetweil** [comment]
and you can run a Linux distro as a vm
https://www.makeuseof.com/can-you-run-virtual-machine-on-smartphone/

**Comment by rejas** [comment]
so @achillealb did that answer your question? I would also suggest to ask this question in the forum (https://forum.magicmirror.builders) where it is better placed.
