### ISSUE TITLE
Magicmirror doesnt start in fullscreen after rebooting

### ISSUE THREAD

**Issue by stormyark** [MichMich/MagicMirror#2972]
Magicmirror doesnt start in fullscreen after rebooting

I followed the introduction from [link text](https://docs.magicmirror.builders/configuration/autostart.html#using-pm2) to autorun magicmirror on startup, but after rebooting this is what i see: 

![alt text](https://imgur.com/a/HmFXA24)
![mm](https://user-images.githubusercontent.com/81960990/204140713-952c63e6-7ef5-49d8-92a9-45d5ce7e3b15.png)

**Comment by rejas** [comment]
Could you upload the image again?

**Comment by stormyark** [comment]
I reuploaded the image

**Comment by sdetweil** [comment]
I've seen this a number of times. usually electron gets confused from a prior app usage.

so do this, stop MagicMirror 
```
cd ~
rm -rf .config/Electron
```

note the dot in front of config

this will erase the saved Electron info

start MagicMirror

**Comment by stormyark** [comment]
How do I stop magicmirror? If I press STRG+Q the magicmirror restarts :((

**Comment by sdetweil** [comment]
ctrl-m to minimize, and then on terminal window, pm2 stop all

**Comment by sdetweil** [comment]
pm2's job is to keep the app running

**Comment by stormyark** [comment]
![mm](https://user-images.githubusercontent.com/81960990/204143515-f580d23b-ce74-4432-8b76-e906efd5a8dc.png)

**Comment by sdetweil** [comment]
that looks like u are using VLC or some windowing system to access them system.  

does it have a real display?

**Comment by stormyark** [comment]
I am running a linux mint on virtual box to test magicmirror
![mm](https://user-images.githubusercontent.com/81960990/204146077-b4b8dda9-aaf6-45ac-afb7-ca200805afe1.png)

That are my display settings

**Comment by sdetweil** [comment]
electron appears to have some trouble getting the display size.     

its not our code, so I don't know what the constraints are ...
you might look thru the Electro github issues. 

https://github.com/electron/electron/issues?q=is%3Aissue+is%3Aopen+fullscreen+  there are 35 open related to fullscreen

what is the size definition?   1024x768?  1920X1080?

**Comment by stormyark** [comment]
Ill go through the issues, thank you so much for your help.

My size defenition is 1920x1080
and in the electon.js I changed the width to 1920 and the high to 1080 so that magicmirror at leasts covers the screen

**Comment by KristjanESPERANTO** [comment]
@stormyark Just out of curiosity: Why are you using MagicMirror in a VM?

**Comment by sdetweil** [comment]
@stormyark you can change those settings thru config.js, without editing any of the source files.

that you were able to solve part of the problem w electron options confirms that electron is confused

**Comment by stormyark** [comment]
@KristjanESPERANTO I Just wanted to test it a bit before the raspi arrives

**Comment by stormyark** [comment]
@sdetweil could I possibly write a comand in the confog.js to run fullscreen?

**Comment by sdetweil** [comment]
@stormyark the default is fullscreen, in kiosk mode (no title bar, etc)

as I said  it's 'fullscreen' that is confused in the vm

**Comment by khassel** [comment]
> Now i looks like this :(

I think this is normal behaviour in VirtualBox. MagicMirror is running fullscreen in the VM, but you have still the Windows-VirtualBox-Window around, AFAIK you cannot control this from inside the VM.

You can click on the VM-Window and play around with Ctrl(Right)+C or Ctrl(Right)+F.

This is not an electron or magicmirror problem and on a pi fullscreen will work.
