### ISSUE TITLE
Weather.js module throws error 

### ISSUE THREAD

**Issue by sprestel** [MichMich/MagicMirror#2974]
After update to MM v2.21.0 I'm not able to see the weather.

Could be related to this https://forum.magicmirror.builders/topic/17059/default-weather-module-still-not-displaying/31?lang=de

https://github.com/MichMich/MagicMirror/blob/9e0293047f8a8c0ced7d9fd8de1b839c06baf9cb/modules/default/weather/weather.js#L159

<img width="942" alt="Bildschirmfoto 2022-12-03 um 20 40 31" src="https://user-images.githubusercontent.com/386398/205458882-d4e3e14e-ea89-4f27-a31a-ab90c1df512e.png">

## workaround

I removed these new lines https://github.com/MichMich/MagicMirror/commit/df0f048ecc018d55119108d7bb7682f3ea3f80b0#diff-f72a25530e6dd944b25232a4d10475685f898a8da89055f070912fc38c35f7d4R157-R165

**Comment by sdetweil** [comment]
what browser is being used here

**Comment by sprestel** [comment]
Current chromiumAm 03.12.2022 um 20:55 schrieb sam detweiler ***@***.***>:﻿
what browser is being used here

**Comment by sdetweil** [comment]
not electron.. 

just the js engine in the browser is down level, we need es6 level

**Comment by khassel** [comment]
> I removed these new lines

removing these lines is a hack which may works for you not for others.

We need more info about your environment (as requested in the issue template) to help you.
