### ISSUE TITLE
Error with iCloud Birthday calendar

### ISSUE THREAD

**Issue by Sachin1968** [MichMich/MagicMirror#298]
It was working fine and keep getting this error now...

Whoops! There was an uncaught exception...
{ [Error: EACCES: permission denied, open '/home/pi/MagicMirror/modules/MMM-iCloud-Client/contacts.db']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/pi/MagicMirror/modules/MMM-iCloud-Client/contacts.db' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by MichMich** [comment]
This seems like a problem with the MMM-iCloud-Client module. I suggest you open an issue in that repository.
