### ISSUE TITLE
what node/npm versions are we testing w for 2.22?

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2982]
want to update my scripts

**Comment by sdetweil** [comment]
k  scripts are node 16.9
min npm 7.11

**Comment by khassel** [comment]
see https://endoflife.date/nodejs

In the docker images I will switch from v16 to v18 with upcoming release.

Considering the tests we could increase to 16/18/19 after the Jan release, if not, we should do this after the April release.

**Comment by sdetweil** [comment]
thanks 

I think I will stick to 16 for this upcoming release
