### ISSUE TITLE
Weather module using Environment Canada, days are reversed.. but not weather information!

### ISSUE THREAD

**Issue by etrefal** [MichMich/MagicMirror#2987]
Platform: Raspberry Pi 3 on Raspbian Buster
Node version: v16.19.0
MagicMirror version: 2.22.0

Description: I use the weather module with Environment Canada as provider.  It always worked well, until today when I noticed that the day names are reversed.  The weather information is *not* reversed though.  I have attached two screenshots - one is the MagicMirror display, the other is the Environment Canada webpage.  Note that these are in french.  The day names displayed on the MagicMirror are "Aujourd'hui" (Today) - which is a monday), "Demain" (Tomorrow), then "sam." (Saturday), "ven." (Friday), "jeu." (Thursday) and then "mer." (Wednesday).  These should be "Aujourd'hui, Demain, mer., jeu., ven. and sam."

Note that the weather information is correct.  The weather forecast is in the correct order when you compare to the Environment Canada screenshot. 

I did upgrade MagicMirror to the latest version yesterday afternoon.  But I only noticed the error a few minutes ago.

Configuration: My edited config.js file is also attached... but does not appear.  Here is the relevant info:

{
                       module: "weather",
                       position: "top_left",   // This can be any of the regions.
                                               // Best results in left or right regions.
                        config: {
				weatherProvider: "envcanada",
				siteCode: "xxxxxxx",
				provCode: "xx",
				location: "xxxxx, xx",
				type: "forecast",
				locationID: "",
                               showPrecipitationAmount: "true", // Ne fonctionne pas?
				colored: "true",
				tableClass: "medium",
				maxNumberOfDays: 7
                       }

![Screenshot from 2023-01-02 13-19-35](https://user-images.githubusercontent.com/36390277/210267257-cd72f9e9-5c69-4ce8-b45a-b6e6f4403a69.png)

![Screenshot from 2023-01-02 12-56-02](https://user-images.githubusercontent.com/36390277/210267270-f72c56d1-93a4-4246-b1e5-b575d62f94d7.png)

**Comment by rejas** [comment]
Thx for the report @etrefal I can reproduce this, will have a fix on the weekend ready

**Comment by etrefal** [comment]
Thank you!!

**Comment by etrefal** [comment]
I had a notification of a new commit, so I did a **git pull && npm install --only=prod --omit=dev**

Weather forecast with Environment Canada is still not fixed... today is Samedi (Saturday), tomorrow is Dimanche (Sunday).   So Sunday appears twice - as Tomorrow (Demain) and as Sunday (Dim.)  Please see attached screenshot.
![Screenshot from 2023-01-07 17-18-06](https://user-images.githubusercontent.com/36390277/211172364-f6c5bced-75b5-4369-994a-91dc1c1f1731.png)
The weather forecast is correct, and in the correct order.  Only the day names are wrong.  In the screenshot above, they should be:
Aujourd'hui (Today)
Demain (Tomorrow)
lun. (Monday)
mar. (Tuesday)
mer. (Wednesday)
jeu. (Thursday)

**Comment by khassel** [comment]
we collect all fixes on the `develop` branch, releases are only quaterly so next on April 1.

You can use the `develop` branch so far or wait until next release or do the one line fix from the PR in your code directly (in last case don't forget to revert before next git pull)

**Comment by etrefal** [comment]
Understood.  I edited the **envcanada.js** file to reflect the change, and will update again in April.

Thanks!

**Comment by sdetweil** [comment]
@etrefal if you used my upgrade script, it would detected that you were using the develop branch and would have switched u back to master before the version upgrade

**Comment by etrefal** [comment]
@sdetweil - I didn't know about your upgrade script.  I downloaded it on the Pi a few minutes ago.  I guess since I edited the envcanada.js file manually it might not help right now, but it might in April!  I'll keep that in mind when we get there, thanks!

**Comment by sdetweil** [comment]
u don't have to download, just copy/paste from the repo readme online

**Comment by rejas** [comment]
> Understood. I edited the **envcanada.js** file to reflect the change, and will update again in April.
> 
> Thanks!

Good to hear that it fixed your problem for real. Can we close this issue now?

**Comment by khassel** [comment]
> Can we close this issue now?

I thought we close such issues when the fix/feature is released, see Collaboration.md (?)

**Comment by sdetweil** [comment]
I think and confirmed by the op

**Comment by etrefal** [comment]
Yes, the issue could be closed now, the fix works!

**Comment by rejas** [comment]
> > Can we close this issue now?
> 
> I thought we close such issues when the fix/feature is released, see Collaboration.md (?)

True. Maybe we should add a label "Fix ready in next release" (or something like that) to those issues so that we can see which are "done"
