### ISSUE TITLE
"Added css class names "today" and "tomorrow" for default calendar"

### ISSUE THREAD

**Issue by Haskar** [MichMich/MagicMirror#2988]
Hi, 

how do I deactivate the colored underlines for "today" and "tomorrow" events in the default calendar? I could not find anything in the documentation. 
The classes are not defined in my calendar.css file and I don't see where the "default" values come from :(

**Comment by sdetweil** [comment]
can u post a screen shot of the cal outout?   I don't see an underline

**Comment by Haskar** [comment]
Thanks for the friendly reply and the hint. 

".today" and ".tomorrow" was defined in the CSS file of another module I use (MMM-Todoist). I commented it out and it is working fine now!

I should have been able to figure it out myself :(

**Comment by sdetweil** [comment]
so, to fix this just add

.MMM-Todoist and space

in front of those classes to make them relative to that module only

**Comment by Haskar** [comment]
Thx! :)
