### ISSUE TITLE
Version 2.22 doesn't run on Raspi OS Stretch,  undefined symbol: gbm_bo_get_modifier

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#2989]
users are reporting that after upgrade to 2.22 they are seeing a new Electron error

```
.node_modules/[…]/dist/electron: symbol lookup error: undefined symbol: gbm_bo_get_modifier.
```

the desktop env is downlevel from what is used by electron V22. (interesting coincidence) 

only fix is to upgrade OS..  I don't think the software upgrade works as next version is buster which has been superceded by bullseye.

rebuild of sd card at bullseye resolves the problem..

forum link
https://forum.magicmirror.builders/topic/17494/mirror-broken-after-v2-22-0-upgrade?page=1

**Comment by KristjanESPERANTO** [comment]
Do I understand correctly that the problem only occurs with stretch? stretch has reached its end of support. Such an old, no longer supported version should not be used for security reasons, nor should we worry about problems with it.

**Comment by sdetweil** [comment]
yes, this was really posted for others to search on. not for the mm team to DO anything

**Comment by rejas** [comment]
So we can close it?

**Comment by sdetweil** [comment]
can we leave it for one more release?  users don't know how to search closed issues

**Comment by rejas** [comment]
maybe worth putting it into the documentation then?

**Comment by khassel** [comment]
> can we leave it for one more release?

@sdetweil  so can we close it now?

**Comment by sdetweil** [comment]
sure
