### ISSUE TITLE
Weather module: add incremens for hourly

### ISSUE THREAD

**Issue by Coernel82** [MichMich/MagicMirror#2996]
It would be very great if the default weather module would be able to show the ``hourly`` weather with for instance ``increments = 2`` resulting in:

* 12:00
* 14:00
* 16:00

``increments = 3`` resulting in:
* 12:00
* 15:00
* 18:00

and so on...
as on smaller screens hourly clutters the screen very much.

I'd be very happy about this option!

**Comment by khassel** [comment]
@rejas can you may take a look at this?

**Comment by rejas** [comment]
already on it, might have something soonish ;-)

**Comment by Coernel82** [comment]
Wow, this would be great! I wish I could program more than I am able to at the moment!

**Comment by rejas** [comment]
PR created if you want to check it out

**Comment by Coernel82** [comment]
Cool! Is there a pull command I can use?
S.th. like ```git pull https://github.com/MichMich/MagicMirror/pull/2998```?

**Comment by Coernel82** [comment]
OK... I found something and tried ``git fetch origin pull/2998/head:MichMich/MagicMirror`` - let's see if it worked.

The new variable is: ``hourlyForecastIncrements: 1,`` by the way. Set it to 4 and will report back!

**Comment by Coernel82** [comment]
The git fetch command didn't work but finally figured it out:
```
git fetch origin pull/2998/head:MagicMirror
git checkout MagicMirror
```
and: It works so far. I will keep testing for the next days.

**Comment by Coernel82** [comment]
still working! Happy that this will be in the next major version in april!
