### ISSUE TITLE
Remove the title & message in the alert.

### ISSUE THREAD

**Issue by desq42** [MichMich/MagicMirror#300]
Hi,

would it be possible to remove the "title" & "message" in the alert? (feature request.)

![bildschirmfoto 2016-05-08 um 10 45 25](https://cloud.githubusercontent.com/assets/18470786/15096870/56da0630-150a-11e6-954c-c0127ff6427b.png)

**Comment by MichMich** [comment]
@paviro?

**Comment by paviro** [comment]
I will check.

**Comment by desq42** [comment]
Hi paviro,

got a chance to take a look?

**Comment by paviro** [comment]
Sorry not yet but until I have you could may check yourself and see if you can add an option that `title` and `message` can be set to `none`?

**Comment by MichMich** [comment]
Fixed! https://github.com/MichMich/MagicMirror/commit/491bbacdddcb6481b0b4ae6b41f129beaf36e4ae
