### ISSUE TITLE
Add developer mode

### ISSUE THREAD

**Issue by planetmadness** [MichMich/MagicMirror#301]
It seems that, by default, the rightclick menu is hidden, which prevents the use of inspect element. The cursor is hidden by default as well.
I completely understand that this makes sense, however, when trying to apply custom styling and debugging it is quite a setback. Perhaps there could be a developer mode added as a flag for example, which enables the rightclick menu and does not hide the cursor.

Another addition could be another flag such as a no-reload flag which loads the data once and does not reload. This prevents that you are manipulating an element with the developer tools and all of a sudden it's all gone :(

**Comment by MichMich** [comment]
For the first part of your question, you could just use the custom.css. Also, you might want to dicuss issues like this on http://forum.magicmirror.builders 👍

**Comment by planetmadness** [comment]
Good to know! Wasn't aware that the forum is already live, last time I checked it was still in development.

**Comment by KirAsh4** [comment]
There's another way. But I'll wait for you to open a topic on the forum instead.

**Comment by MichMich** [comment]
Since this is taken to the forum, I close this issue. If you want me to reopen. Please let me know.

**Comment by jtyle6** [comment]
Control+Shift+I on the pi that is running MM and that pops up Developer tools. 
![2016-05-10-190822_1280x800_scrot](https://cloud.githubusercontent.com/assets/12602985/15141374/0ecf8eac-16e3-11e6-8ba5-8146d8847440.png)
