### ISSUE TITLE
Weather module: Wind arrow is inverted

### ISSUE THREAD

**Issue by MagMar94** [MichMich/MagicMirror#3019]
If using the `showWindDirectionAsArrow`-setting, the arrow points at where the wind is blowing from. I feel it is more appropriate to point it in the direction of the wind. This is how wind arrows usually work in weather forecasts.

**Comment by MagMar94** [comment]
I am going to fix this, but should I hide it behind a setting and leave the current arrow as the default? That way no one will get the change forced on them. However, I think most people want the inverted arrow.

**Comment by rejas** [comment]
I also think that we should have the arrow pointed in the direction the wind is going. That makes most sense. Thanks for your report (and hopefully your fix ;-)

**Comment by rejas** [comment]
Thx for your PR!
