### ISSUE TITLE
White screen on page reload

### ISSUE THREAD

**Issue by planetmadness** [MichMich/MagicMirror#302]
While customizing and testing stuff, I need to reload sometimes. Everytime I do this, or if I restart the mirror the entire screen goes white. I don't know if this is possible to change, as it is the browser. But if it would be possible to get the browser to display a black screen that would be better!

**Comment by MichMich** [comment]
That's not possible to change since its part of electron. My suggestion is to use 'node serveronly' for testing and just use your browser. This was the reason why I added it ...

**Comment by paviro** [comment]
Maybe look at [this](https://github.com/electron/electron/issues/861)?

**Comment by MichMich** [comment]
I've got currently no plans to work in this, since restarting the MM is not something you usually do regularly. For developers, I suggest going for the `node serveronly` route.

Of course, a pull request to modify the white screen is welcome.
