### ISSUE TITLE
Default weather module fix: Hourly shows 4 hours ahead

### ISSUE THREAD

**Issue by Oleson-Cybersec** [MichMich/MagicMirror#3040]
Hello,

I was running into this issue where the hourly weather reports show 4 hours in advance. Currently, my clock says, 23:40, while my first hourly entry for the weather is 03:00. My calendar is accurate as events show in their proper times. I'm just not sure why this hourly one is being funky. I appreciate your help in advance.

Respectfully,
Jordan

**Comment by sdetweil** [comment]
can you show your config?   do you have the lat/lng backwards?

**Comment by sdetweil** [comment]
@Oleson-Cybersec

**Comment by khassel** [comment]
this very old issue which was transfered from the doc repo, we got no feedback since Feb., so closing for now
