### ISSUE TITLE
disabling CLOCK_SECOND notification

### ISSUE THREAD

**Issue by slametps** [MichMich/MagicMirror#3056]
is there a way to NOT send NOTIFICATION CLOCK_SECOND every single second (flooding) with `displaySeconds = true` in CLOCK module?

**Comment by sdetweil** [comment]
what does the documentation say?

**Comment by sdetweil** [comment]
no..  but you could add another option and submit a pr

sendNotification:true,

if (this.config.sendNotification)

in config.js for clock
sendNotification:false

**Comment by sdetweil** [comment]
u can also filter in the dev console
using a part of the module name u care about in the filter field

**Comment by TimeTraveller255** [comment]
comment this line in clock.js
	self.sendNotification("CLOCK_SECOND", self.second);
like this one
//	self.sendNotification("CLOCK_SECOND", self.second);

**Comment by slametps** [comment]
> comment this line in clock.js self.sendNotification("CLOCK_SECOND", self.second); like this one // self.sendNotification("CLOCK_SECOND", self.second);

Previously, I did it the hard way the same as you suggest. 
I just not OK with every second sending notification causing flooding (resource consume). Still OK with CLOCK_MINUTE.
And I did not want to disable any other notifications, CLOCK_SECOND only. But I can't find the polite way to to this.
