### ISSUE TITLE
Feature Request: CSS class name for dateheader row in Calendar module

### ISSUE THREAD

**Issue by vppencilsharpener** [MichMich/MagicMirror#3077]
When using the default calendar module in the dateheaders timeFormat I was hoping to apply style to only the table rows that contains the date (the "date headers"). In digging into this I found I could not specify only the cells or rows with the date heading without also including the rows that contained the calendar events. 

Currently the date header rows contain the class names of "normal" plus "today" or "tomorrow" as appropriate. 
Currently the calendar event rows contain class names of "normal" & "event" plus "today" or "tomorrow" as appropriate. 

I am proposing adding the class name of "dateheader" to the date heading rows just like the calendar event rows have "event". 
This way style can be applied to only the rows containing the date without affecting the event rows. 

I am submitting this as a feature request because I'm somewhat new to Magic Mirror and wanted to make sure I didn't miss an obvious way to accomplish the same thing.

I've already made this change locally and if it will better the project I am more than willing to submit it as a pull request, though it may take me a little bit of time to figure out how to properly submit one.

**Comment by sdetweil** [comment]
according to the doc, you can specify a class frlor each column of the calendar event entry
symbol, summary. date/,time

they are configured in the calendars []
list
```
{
   url:

```
![Uploading Screenshot_20230328_154358_Chrome.jpg…]()

**Comment by vppencilsharpener** [comment]
@sdetweil just to be super sure I tried all three of those and found where they were applied, and all are applied to the cells within the event rows. None of them are even present in the row that contains the date header, but based on the name & description I would not expect to find them there. 

To be super clear I'm specifically talking about when timeFormat is set to dateheaders and the row that contains the date for the events that follow in additional rows.

**Comment by kmj1104213** [comment]
I would also request more classes to be added to the calendar function.  I modified just a few lines of code to create new classes: urgent and veryurgent, which allowed me to be able to apply CSS to "urgent" and upcoming events.

For instance my events list now colors events with a background of red for events that are going to occur soon (I defined as half the getRelative hours I put in the config), orange/yellow for events within the getRelative hours from config, and green for any event happening on this calendar day (today) more than getRelative hours out.  Makes it a lot easier for me to see what's upcoming and what I need to pay attention to today.

In my case, I set getRelative to 4, which makes events within 2 hours have a red background, 2-4 hours out have an orange/yellow background and 4+ hours on the same calendar day until midnight are green.

Suggested code changes:

![image](https://user-images.githubusercontent.com/129918028/229963783-b5f560b1-3c43-4979-9f7f-cf69e79faf0d.png)
![image](https://user-images.githubusercontent.com/129918028/229963959-01c4c678-5ef2-4558-8baf-7a67b93c0640.png)
![image](https://user-images.githubusercontent.com/129918028/229964078-54f1ddb0-f2c8-4ac1-afa2-f86676fe0849.png)

This allowed me to put this into my custom.css:

![image](https://user-images.githubusercontent.com/129918028/229964190-27de4bd6-5335-4002-ac18-4c1a2fb400ca.png)

**Comment by sdetweil** [comment]
you could submit a pull request so we don't have to retype all your code changes.. 

fork the mm repo (fork button on repo page)
git clone that
make a new branch (git checkout -b branch_name
change the code, test
add test cases
git commit 
git push the changes to your fork
submit a pull request from your branch in your fork (button on your fork (contribute))

**Comment by kmj1104213** [comment]
> you could submit a pull request so we don't have to retype all your code changes..
> 
> fork the mm repo (fork button on repo page) git clone that make a new branch (git checkout -b branch_name change the code, test add test cases git commit git push the changes to your fork submit a pull request from your branch in your fork (button on your fork (contribute))

Sorry, I'm not a professional coder and this is my first time contributing to anything and first time using git hub as I usually just code on my machine locally for personal projects.  Thanks for the detailed instructions!

**Comment by sdetweil** [comment]
@kmj1104213  we all learn as we go. not professional coder here either. 1st place ever i did a pull request..

**Comment by vppencilsharpener** [comment]
I finally had time to figure refresh myself on how to create a pull request, but it looks like the dateheader class was included in release 2.23.0 from two days ago. 

Thank you.

**Comment by khassel** [comment]
so if it is already included in the latest release can we close this issue?

**Comment by vppencilsharpener** [comment]
> so if it is already included in the latest release can we close this issue?

Yes. This can be closed.
