### ISSUE TITLE
Automatic Page Reload

### ISSUE THREAD

**Issue by QuinnyPig** [MichMich/MagicMirror#3105]
Is there a roadmap item (or reason it would be a terrible idea) to alert the client that the server has been restarted / upgraded, and thus to reload the page via 'window.location.reload(true);' or similar? (I run with separate client and server devices, if this sounds ridiculous to your usage model.)

For implementation I was thinking of injecting a UUID at startup into the server response headers that the client caches in local storage, then triggers the reload if responses start coming in with a different UUID; not sure if this should be built into the updatenotifications default module, its own module, or the MM code itself; thoughts?

**Comment by sdetweil** [comment]
a general problem here is that there are no actives connections at the client side, so there is no way to know if the server stopped or was restarted.

 one could write a module that used some regular heartbeat with its node_helper, and cause a page reload . at which point the module starts over again, I think

mmm-watchdig does something similar but gets confused quite often in my experience. it uses time of response to its node_helper
