### ISSUE TITLE
Using a different PC for mic and audio

### ISSUE THREAD

**Issue by himuura** [MichMich/MagicMirror#3129]
Hey there! I have the server running without issues, MMM-GoogleAssistant installed on the server, everything is smooth.
The thing is: i'm using a remote, virtualized server running magic mirror..i cannot simply attach a mic and speaker to it. Any chance i can use a browser on a different computer to speak / listen with the MMM-GoogleAssistant module? Has anyone tried it?
Cheers and thanks, mates!

**Comment by sdetweil** [comment]
someone on the forums said that they had done that a couple years ago.. I  was unable to recreate it

https://forum.magicmirror.builders/topic/14499/mmm-googleassistant-in-server-mode/9?_=1687010783280

**Comment by bugsounet** [comment]
Hi, it's not possible

* There is no mic config (I use only pulse audio on default interface)
* Gateway have MM² "server mode only" denied

But... I've been thinking how to do it without retouching everything for a few months
So, Maybe it's will be available (or not)

**Comment by khassel** [comment]
Closing this because
- third party modules are not supported here
- not possible at the moment
