### ISSUE TITLE
v2.24.0 - Clock module - (showSunTimes: true) Retruns Undefined - formatTime is not defined

### ISSUE THREAD

**Issue by fire1ce** [MichMich/MagicMirror#3143]
MagicMirror v2.24.0 

Clock module:

**I've commneted it to render the clock black.**

```json
    {
      module: 'clock',
      position: 'top_bar',
      config: {
        clockBold: true,
        // showSunTimes: true,
        displayType: 'both',
        analogSize: '400px',
        analogPlacement: 'right',
        secondsColor: '#ff5263',
        lat: xx.xx,
        lon: xx.xx,
      },
    }
```

when showSunTimes: true
error from the console:

```log
clock.js:191 Uncaught (in promise) ReferenceError: formatTime is not defined
    at Class.getDom (clock.js:191:5)
    at main.js:110:35
    at new Promise (<anonymous>)
    at updateDom (main.js:108:10)
    at main.js:53:31
    at Array.forEach (<anonymous>)
    at createDomObjects (main.js:20:11)
    at Object.modulesStarted (main.js:485:4)
    at startModules (loader.js:42:6)
    at async loadNextModule (loader.js:218:6)
```

**Comment by khassel** [comment]
tested your above config with 

```
lat: 50,
lon: 8,
```

without getting an error

![grafik](https://github.com/MichMich/MagicMirror/assets/25914086/6fc72f9a-8452-49e0-a9aa-5549ac9497b7)

**Comment by rejas** [comment]
You got to enable showSunTimes @khassel then you can reprdocue it. Got a fix ready, but wanted to write tests for it before submitting.

**Comment by khassel** [comment]
enabled it, works for me with this config

```js
    {
      module: 'clock',
      position: 'top_bar',
      config: {
        clockBold: true,
        showSunTimes: true,
        displayType: 'both',
        analogSize: '400px',
        analogPlacement: 'right',
        secondsColor: '#ff5263',
        lat: 50,
        lon: 8,
      },
    },
```

**Comment by fire1ce** [comment]
> enabled it, works for me with this config
> 
> ```js
>     {
>       module: 'clock',
>       position: 'top_bar',
>       config: {
>         clockBold: true,
>         showSunTimes: true,
>         displayType: 'both',
>         analogSize: '400px',
>         analogPlacement: 'right',
>         secondsColor: '#ff5263',
>         lat: 50,
>         lon: 8,
>       },
>     },
> ```

Tested with this clock config, Having the same issue. ¯\_(ツ)_/¯ 

![image](https://github.com/MichMich/MagicMirror/assets/16795594/dffef915-e5ac-4ce1-ad34-13574e9bcd3b)

**Comment by fire1ce** [comment]
Btw, it happen since the last version only.

**Comment by khassel** [comment]
o.k., now I can reproduce it.

I had a weather module before the clock config in `config.js` and the weather module loads the missing script so the clock module works in this case. If I move the clock config at first place I get the error.

**Comment by fire1ce** [comment]
> o.k., now I can reproduce it.
> 
> I had a weather module before the clock config in `config.js` and the weather module loads the missing script so the clock module works in this case. If I move the clock config at first place I get the error.

Nothing better then possibility to reproduce a bug. No second thought no bugs is better 😶

**Comment by wbleek** [comment]
This issue might not be fixed entirely because it also appears when selection the time zone by text instead of lon and lat parameter. See issue https://github.com/MichMich/MagicMirror/issues/3262
