### ISSUE TITLE
All Google Calendars show no events, when broadcastPastEvents is true

### ISSUE THREAD

**Issue by Burny101** [MichMich/MagicMirror#3162]
I have multiple Google calendars and two other ones, in my MM calendar. 
As soon as i set broadcastPastEvents to true, the calendar does not show any events from the google calendars anymore.
The Google calendars are used via the private iCal-addresses.
The issue remained after updating to the newsest release as of today.

**Comment by sdetweil** [comment]
can u show the output  from where you do npm start? 

if you use pm2, then you would use the command
pm2 logs --lines=100 
to display that output

you may also have to turn on calendar debug , but change the config.js line 
```
logLevel: ["INFO", "LOG", "WARN", "ERROR","DEBUG"], // Add "DEBUG" for even more logging
```

and run mm like this 

npm start  >somefile.txt 2>&1

when the output is not displayed, press ctrl-c on the commandline  and send me somefile.txt
 my email is sdetweil   on gmail

**Comment by sdetweil** [comment]
do NOT post here as private details are in the debug output

**Comment by khassel** [comment]
any progress here?

**Comment by Burny101** [comment]
Sorry for the delay. 
I have sent the log file to @sdetweil .

**Comment by sdetweil** [comment]
received and responded via email

**Comment by khassel** [comment]
so can this be closed?
