### ISSUE TITLE
bash: line 1: Not: command not found

### ISSUE THREAD

**Issue by Labzz** [MichMich/MagicMirror#320]
Hi dear,

First at all, im using the Raspberry pi 2, with Rasbian Jessy (complete image)  
Does someone else got the same error using the following command? Or does anyone knows how to fix it? yesterday it still worked, but now i stuck. 
" curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh | bash "
I already reinstalled rasbian multiple times, and troubleshooted on internet.

Hope to hear you soon, thanks anyways. 
![raspberry](https://cloud.githubusercontent.com/assets/17926205/15220811/21273c08-1869-11e6-955e-7ec38490bce3.PNG)

**Comment by MichMich** [comment]
What do you see when you type 

    curl https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh

**Comment by Labzz** [comment]
The whole code. 
![raspberry](https://cloud.githubusercontent.com/assets/17926205/15222351/894890ba-186f-11e6-9bfa-c407f051ccfc.PNG)

**Comment by Labzz** [comment]
![capture](https://cloud.githubusercontent.com/assets/17926205/15222441/f8716c96-186f-11e6-9d8a-f3a0af7a1856.PNG)
(Without;  | bash)

**Comment by MichMich** [comment]
In your screenshots (where it fails) You are using the wrong url. /master/ is missing in the url.
