### ISSUE TITLE
Config is overwritten when running tests

### ISSUE THREAD

**Issue by rejas** [MichMich/MagicMirror#3201]
As mentioned [here](https://github.com/MichMich/MagicMirror/pull/3200#issuecomment-1722567078) by @bugsounet the config.js is overwritten when running local tests.

Possible solution: Make a backup of the config before starting the testsuite.

**Comment by bugsounet** [comment]
@rejas: is it really urgent or can it wait until v2.26?

I want to try to familiarize myself with the test suite
But if it's really urgent for you, code it :)
