### ISSUE TITLE
Using VBA in Excel to help find acronyms throughout the document. 

### ISSUE THREAD

**Issue by ECOl10** [MichMich/MagicMirror#3209]
Sub HighlightAcronyms()

    Dim rng As Range, r2 As Range

    Set rng = ActiveDocument.Content
    Set r2 = ActiveDocument.Content

    With rng.Find
        .ClearFormatting
        .Text = "<[A-Z]{2,}>"
        .Forward = True
        .Wrap = wdFindStop
        .MatchCase = True
        .MatchWildcards = True
        .Format = False

        Do While .Execute
            'look two characters past the found acroynm
            r2.Start = rng.End + 1
            r2.End = rng.End + 3
            Debug.Print rng.Text, r2.Text

            'highlight if r2 has a "(" otherwise clear highlight
            rng.HighlightColorIndex = IIf(r2.Text Like "*(*", _
                                        wdAuto, wdYellow)

        Loop
    End With

End Sub

This is the coding that I am using however when attempting to run this I am getting a compile error that says "Argument not optional"

I am not sure what that means. Any help on this would be greatly appreciated.

**Comment by sdetweil** [comment]
tell us more, run where? how?   what has this got to do with MagicMirror?
