### ISSUE TITLE
[calendar]: previous events not displaying (even when broadcastPastEvents=true)

### ISSUE THREAD

**Issue by cestorer** [MichMich/MagicMirror#3246]
Tried all sorts of combinations of maximumNumberOfDays & pastDaysCount, maximumEntries but no luck. broadcastPastEvents is true.

**Comment by sdetweil** [comment]
the default calendar never displays past events. ever.

it can send a notification to other modules with them included, MMM-CalendarEXT3 is a module that might use that data in some of its views

**Comment by cestorer** [comment]
Good insight.. that's the module I'm using. A little confusing, but maybe the keyword, **broadcast**, should have let me there. Closing, thank you.
