### ISSUE TITLE
load json file

### ISSUE THREAD

**Issue by mastrom90** [MichMich/MagicMirror#327]
Hi guys,
i have a really little problem and i think it is easy to be solved. I have created a  new module where i need to load a local json file which is created by an external program.
I cant figure out how i can read this file and where to locate that one. I have created a variable with the filetext so i know i can handle it if i read it. But i cant get it to read the file so i can remove the variable because the data changes every week.

i hope someone can help me. Sorry if im wrong here but i dont know how i can help myself :(

**Comment by paviro** [comment]
For development help check the forum: http://forum.magicmirror.builders

**Comment by mastrom90** [comment]
thank you for that
