### ISSUE TITLE
Install MM² on a ARMv8 x64

### ISSUE THREAD

**Issue by djsunrise19** [MichMich/MagicMirror#328]
**Platform** [ Odroid C2 with Ubuntu 16.04 LTS (v1.1) -> File name : ubuntu64-16.04lts-mate-odroid-c2-20160226.img.xz]:

**Node Version** [ 6.1 (newest version) ]:

**MagicMirror Version** [ V2 ]:

**Description:** Last week I bought an odroid c2 and I wanted to check if the MM² will work on it. As I expected, the installer script won't work. So I installed Node 6.1 for ARMv8 manually, `git pull` the V2 branch and `npm install`. There is an electron error, he cannt find the file to download. Is there a way for doing the last steps manually? Log is under "configuration" (scroll at the bottom in this file).

![image](https://cloud.githubusercontent.com/assets/14234570/15268402/6fcba2e8-19dd-11e6-80c2-074071077552.png)

**Steps to Reproduce:** `npm install` on a ARMv8.

**Expected Results:** -/-.

**Actual Results:** -/-

**Configuration:** 
[npm-debug.txt](https://github.com/MichMich/MagicMirror/files/264450/npm-debug.txt)

**Additional Notes:** -/-

**Comment by nhubbard** [comment]
It looks like Electron isn't prebuilt on this platform. @MichMich should probably add the enhancement tag.

**Comment by MichMich** [comment]
Indeed, Electron does not support this platform. Please open an issue in the electron repository.

**Comment by djsunrise19** [comment]
Thank you. I reported an issue: https://github.com/electron/electron/issues/5558

**Comment by MichMich** [comment]
I'll close this issue since it's an electron issue. If you want me to reopen it, feel free to let me know.

**Comment by sdetweil** [comment]
i have an odroid as well, it runs another electron based smart mirror without problem. 
i get a black screen, trying to npm install in vendor fails with 
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
```
