### ISSUE TITLE
MagicMirror/Electron ignoring "electronOptions" when enviroment variable is used. 

### ISSUE THREAD

**Issue by BKeyport** [MichMich/MagicMirror#3287]
Per the forums, https://forum.magicmirror.builders/topic/18248/magic-mirror-dual-screen/ - I have found a problem, not sure what to do or even if it's MM's fault or Electron's fault. 

When you start MM with a bash script thusly: 
```
cd /home/<username>/MagicMirror
export MM_CONFIG_FILE=${cwd}/config/config2.js
DISPLAY=:0 npm start
```

The system will ignore the ```electronOptions: { x: <width> },``` in the config.js 

When the "export" line is not present, but the bash script is otherwise identical, the system will launch and use the electronOptions item correctly. 

I figured I'd post an issue here to see if we can get it "fixed". The temporary way to fix it is to use electronOptions item in the default config.js, not the other one. 

Thanks!

**Comment by khassel** [comment]
@sdetweil where must this be fixed? In your script repo or in our documentation repo or somewhere else?

**Comment by sdetweil** [comment]
@khassel we don't describe these env variables anywhere, so it was my error in sample usage.
