### ISSUE TITLE
Help, Apache Permissions and Index.php file.

### ISSUE THREAD

**Issue by patm189** [MichMich/MagicMirror#329]
I'm new to this and getting stuck following instructions. I have two questions and would appreciate any guidenace.

1) Apache Permissions. I can't update or change anything in Apache even using sudo commands in Terminal. I am trying to copy fil ~/config.js.sample from MagicMirror2 folder (cp sudo nano /var/www/html/MagicMirror/config/config.js.sample  so that I can rename and remove the 'sample', but I am getting permissions denied. I can't simple rename the config.js.sample file either. How can I edit files in Apache server? 

2) I am seeing on the tutorials that the autostart file should be ~/MagicMirror/index.php. However.... I don't see a PHP file in the MagicMirror folder so I am getting a Not Found error when I try to type this in my browser. I am sure I'm doing something very stupid and easy so hoping someone can help!

Pat

**Comment by MichMich** [comment]
For support please check http://forum.magicmirror.builders
