### ISSUE TITLE
default calendar repeating event processing (again)

### ISSUE THREAD

**Issue by BKeyport** [MichMich/MagicMirror#3306]
I'm having a problem with specific repeating events from google processing again. If the event is repeating, and then a later repeated event is deleted, the system will still show that deleted event. 

How is repeating events handled? Does the ICS file even contain the repeats, or is it reliant on the inital rules? If the repeats are in the ICS as individual events, do we need to even process the repeat rules?

**Comment by sdetweil** [comment]
yes  the deleted are called excluded events. there was a fix put in for next release for excluded
 they will show in the ics

**Comment by BKeyport** [comment]
Good deal, I guess it's solved then.
