### ISSUE TITLE
Node ServerOnly Autostart

### ISSUE THREAD

**Issue by cyberdie** [MichMich/MagicMirror#332]
I'm trying to setup MagicMirror on a Raspberry B+
Apart from high cpu usage of npm i'm in trouble starting node with serveronly parameter on startup.
The effect is that Midori cannot open http://localhost:8080 because node is not started.
If i connect via SSH, launch "node serveronly" and reload Midori (via vnc) all works fine.

How could i start node on startup with "serveronly" parameter?

**Comment by MichMich** [comment]
Just run `node serveronly` from the MagicMirror folder.

Even though this should work, It's not officially supported. Further support questions can be asked on the forum: http://forum.magicmirror.builders

Cheers, Michael.

**Comment by cyberdie** [comment]
Thanks Michael but what if i restart the Pi?
How can i automate "node serveronly" command?
I've tried on X Autostart without success..

**Comment by MichMich** [comment]
See https://github.com/MichMich/MagicMirror/wiki/Auto-Starting-MagicMirror
