### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rustywild** [MichMich/MagicMirror#342]
Hi

Sorry i'm noob. Here is my error

plattform raspberry pi 3.

pm ERR! Linux 4.4.9-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/home/pi/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /home/pi
7 error Linux 4.4.9-v7+
8 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
9 error node v6.2.0
10 error npm  v3.8.9
11 error path /home/pi/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/home/pi/package.json'
16 error enoent ENOENT: no such file or directory, open '/home/pi/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

**Comment by MichMich** [comment]
Please use http://forum.magicmirror.builders for support questions.
