### ISSUE TITLE
Cardinal direction for NE is missing in all the language-files

### ISSUE THREAD

**Issue by OskarKlintrot** [MichMich/MagicMirror#344]
As the title says, the cardinal direction for NE is missing in all the language-files. I can make a PR for the English and Swedish translations but that's the only languages I speak. Should make a PR for those?

**Comment by MichMich** [comment]
Fixed! https://github.com/MichMich/MagicMirror/commit/611627ca97a9828fdf39e5889eb3ac54359330de
