### ISSUE TITLE
fix e2e testcase startApplication() helper to accept run  date/time like the electron helper with the same name does

### ISSUE THREAD

**Issue by sdetweil** [MichMich/MagicMirror#3482]
trying to run the e2e testcases for compliments, which have some date based , the helper does not set the system time for the run, so any date specific tests will fail 

impacts   e2e test for 
#3481 
#3471

**Comment by khassel** [comment]
AFAIR this is not possible, we moved these tests from e2e to electron.

So if you need a specific date for testing write an electron test instead an e2e test.

**Comment by sdetweil** [comment]
already in electron ,and passed i will delete the e2e tests
