### ISSUE TITLE
Impossible Load Calendar

### ISSUE THREAD

**Issue by Neokamikaze** [MichMich/MagicMirror#350]
Hi,

It's impossible to load a calendar in the interface. I have this message in Chrome:

`Uncaught TypeError: Cannot read property 'getElementsByClassName' of nullmoduleNeedsUpdate @ main.js:129updateDom @ main.js:99MM.updateDom @ main.js:396Class.extend.updateDom @ module.js:278Module.register.sendSocketNotification @ calendar.js:90Module.register.addCalendar @ calendar.js:280Module.register.start @ calendar.js:66startModules @ loader.js:55(anonymous function) @ loader.js:40stylesheet.onload @ loader.js:190
658main.js:129 Uncaught TypeError: Cannot read property 'getElementsByClassName' of nullmoduleNeedsUpdate @ main.js:129updateDom @ main.js:99MM.updateDom @ main.js:396Class.extend.updateDom @ module.js:278(anonymous function) @ clock.js:27`

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
