### ISSUE TITLE
magicmirror2 'does' work on the old model-B pi

### ISSUE THREAD

**Issue by vinceskahan** [MichMich/MagicMirror#354]
Just wanted to comment that you 'can' get MagicMirror2 working pretty simply on the original model-B  if you use the version of node from http://node-arm.herokuapp.com

I used the wget method to download it and dpkg to install it.  The resulting 'npm install' per your instructions took a 'long' time, but completed fine.

I'm running Raspbian 2016-05-27 just as a point of reference.

**Comment by MichMich** [comment]
Does Electron run as well?

**Comment by vinceskahan** [comment]
how could I tell ?

I'm running serveronly but can hook it up to a monitor if you need me to
check it that way...

On Mon, Jun 6, 2016 at 3:32 AM, Michael Teeuw <notifications@github.com>
wrote:

> Does Electron run as well?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MichMich/MagicMirror/issues/354#issuecomment-223923200>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAk2KnStW79Siv0lNc-T0WZLQtXIXzZuks5qI_dZgaJpZM4IudjO>
> .
>



-- 
-----  vinceskahan@gmail.com ----

**Comment by jtyle6** [comment]
Go to your pi ip address with Web browser with. 
```
:8080
```
At the end so it looks like xx.x.x.xx:8080

**Comment by paviro** [comment]
Server only was never a problem wasn't it?

**Comment by KirAsh4** [comment]
I suspect you'll have issues with Electron on an rpi-modelB, but till you hook up a monitor and try (re)starting it, there's no telling.

@jtyle6, going to the address like that does not actually do anything as you're using a completely different browser to do that. Electron runs on the rpi itself and is visible on a monitor connected to it.

**Comment by jtyle6** [comment]
Does not work on a B and B+ this is the same image as Pi 3.

``` 
node serveronly                                                      132 ↵
[1]    1381 illegal hardware instruction  node server only
```

@KirAsh4 fixed the ip.

**Comment by AntiElephantMine** [comment]
Do you have display issues running this on your B+? I have exactly the issue mentioned here:

https://forum.magicmirror.builders/topic/80/chromium-rpi-1-display-strange

where the newsfeed and compliments won't go to the bottom. Unfortunately I'm not very skilled at CSS so I can't see the problem.

**Comment by Fabrice5800** [comment]
Hello, i'm french i try to install the mirror 2 but i have more problems !!!
HELP PLEASE   
npm ERR! Linux 4.4.11-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v3.10.3
npm ERR! path /home/fablab/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/fablab/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/fablab/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fablab/npm-debug.log
