### ISSUE TITLE
Related Kickstarter project

### ISSUE THREAD

**Issue by Dawnkeeper** [MichMich/MagicMirror#362]
Just FYI, there seems to be an Kickstarter Project using the Magic Mirror: [here](https://www.kickstarter.com/projects/appsmith/doodlevu-the-smart-mirror/description)

**Comment by paviro** [comment]
Michaels UI definitely looks better :D

**Comment by MichMich** [comment]
I've seen many of them. None of them were successful yet. Biggest issue in making it a successful commercial product, are the patents on mirrored screens.
