### ISSUE TITLE
Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by baba-123** [MichMich/MagicMirror#364]
Installed on PI-1. getting the following error when running "node serveronly"

pi@raspberrypi:~/MagicMirror $ node serveronly

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/MagicMirror/js/server.js:8:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by MichMich** [comment]
Sorry, Pi 1 is not supported.

**Comment by baba-123** [comment]
Is there a basic version I can install...I have come a long way with
setting up all the hardware and to stop because I have the wrong version of
pi is sad....

Any work around??

**Comment by MichMich** [comment]
You might be able to find some workarounds on http://forum.magicmirror.builders - But unfortunately I can't give you any support.

**Comment by baba-123** [comment]
just to confirm, I am using Raspberry Pi Model B 512MB RAM. can you confirm
is this not supported?

On Tue, Jun 21, 2016 at 10:16 AM, Michael Teeuw <notifications@github.com>
wrote:

> You might be able to find some workarounds on
> http://forum.magicmirror.builders - But unfortunately I can't give you
> any support.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MichMich/MagicMirror/issues/364#issuecomment-227508743>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATJDEovHL_EUyl8o6vjUu0aVlVnUW-8bks5qOByGgaJpZM4I67sV>
> .
>



-- 
Naveen Patlola

<http://www.marchforbabies.org/march/personal_page.asp?w=6930219&u=naveenpatlola&bt=5>

**Comment by MichMich** [comment]
Exactly. Officially only the Pi 2 & 3 are supported.

**Comment by baba-123** [comment]
Thank you for your assistance...

On Tue, Jun 21, 2016 at 11:16 AM, Michael Teeuw <notifications@github.com>
wrote:

> Exactly. Officially only the Pi 2 & 3 are supported.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/MichMich/MagicMirror/issues/364#issuecomment-227525883>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATJDEseQqg0cn3Y7lRngGbhQgtb8YzTOks5qOCqRgaJpZM4I67sV>
> .
>



-- 
Naveen Patlola

<http://www.marchforbabies.org/march/personal_page.asp?w=6930219&u=naveenpatlola&bt=5>

**Comment by chenz0** [comment]
Officially, Pi 1 supported. I was able to get it running on my Pi 1 though on serveronly. The challenge was getting the layout right in the browser. I've since had to reformat my RPi so I can't tell you much more but it is possible. 

There's another thread discussing how to run on Pi1: 
https://github.com/MichMich/MagicMirror/issues/354

I haven't gotten this method to work yet though

**Comment by chenz0** [comment]
*is not supported. Sorry

**Comment by baba-123** [comment]
Thank you for you help. I was able to build my own magic mirror...Additionally I add a sensor to control the monitor, which will save power and also not overheat the system...

much appreciated..attached are some pictures

![img_20161028_080456](https://cloud.githubusercontent.com/assets/20071186/19819084/d405c970-9d07-11e6-9eae-5cf4918ba0e9.jpg)
![img_20161028_080509](https://cloud.githubusercontent.com/assets/20071186/19819080/d40082a8-9d07-11e6-9bad-ef0132aae78d.jpg)
![img_20161028_080553](https://cloud.githubusercontent.com/assets/20071186/19819081/d4053258-9d07-11e6-99f6-f443781805ac.jpg)
![img_20161028_080614](https://cloud.githubusercontent.com/assets/20071186/19819083/d405970c-9d07-11e6-8ef9-f59c6ce28c83.jpg)
![img_20161028_080621](https://cloud.githubusercontent.com/assets/20071186/19819082/d405428e-9d07-11e6-9f82-42431b4a1afb.jpg)
