### ISSUE TITLE
Getting 502 error with npm

### ISSUE THREAD

**Issue by Anool** [MichMich/MagicMirror#368]
[npm-debug.log.txt](https://github.com/MichMich/MagicMirror/files/349747/npm-debug.log.txt)

**Platform** [ Raspberry Pi 3 ]:

**Node Version** [ 6.2.2 ]:

**MagicMirror Version** [ V1 / V2-Beta ]:

**Description:** running the automatic script fails with 
"Error: fetch failed with status code 502"

Debug file attached. npm is having issues today, so I'm wondering if there is a way to temporarily fix this.

**Steps to Reproduce:** run 
`curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh | bash`

or

`npm install && npm start`

**Expected Results:** MagicMirror installed.

**Actual Results:** MagicMirror not installed.

**Comment by MichMich** [comment]
`error fetch failed with status code 502`

Probably an issue with NPM indeed.

**Comment by nhubbard** [comment]
Hi @MichMich, I'm back! Yes, it is an issue with NPM. I was having issues with NPM earlier today, and the best way to fix it is to wait. It's only happening in select regions, and they deployed a temporary patch as of 14:54 UTC.

**Comment by Anool** [comment]
Fixed and works now.
