### ISSUE TITLE
Add Pi Zero Support.

### ISSUE THREAD

**Issue by jfi1310** [MichMich/MagicMirror#374]
Please add support for the Pi Zero.

**Comment by MichMich** [comment]
I think it should run on the Zero. I did not try it though. What errors are you experiencing?

**Comment by jfi1310** [comment]
While trying to install it, there was this message:

![pizero](https://cloud.githubusercontent.com/assets/20475898/16873254/45be68b0-4a92-11e6-8673-887b39065f04.jpg)

**Comment by MichMich** [comment]
What do you get when you run the following command?
```
uname -a
```

**Comment by jfi1310** [comment]
That's what I get:
`Linux raspberrypi 4.4.11+ #888 Mon May 23 20:02:58 BST 2016 armv6l GNU/Linux`

**Comment by MichMich** [comment]
Hmmm ... it seems the Zero is running on `ARMv6`. Just like the the Pi 1. Unfortunately, Electron (the browser frame on which MagicMirror relies) does not support `ARMv6`. You can install MagicMirror² and just use the `serveronly` method, but you would need to setup a browser in kiosk mode yourself. Which is tricky on the `ARMv6` platform.

**Comment by kapsolas** [comment]
I successfully installed it on a Zero. 

I had to get the Electron build for the arm processor i'm using. Its available now.

**Comment by MichMich** [comment]
@kapsolas How did you install electron, simply using NPM? Or did you need to manually compile?

**Comment by kapsolas** [comment]
To be honest, I don't remember. I tried a few things before i got it. I did end up though on the electron site where I downloaded from there an arm build. Think this was the one that worked.

**Comment by MichMich** [comment]
Ok, then I need to het me a Pi zero to test it. Till then I can't add support. Thanks for the info!

**Comment by kapsolas** [comment]
No worries!

**Comment by nhubbard** [comment]
We probably should close this issue, as it was solved by commit af279df5c9845b3063d906b441ddcddef9a4493c.

**Comment by alessandroiacovella** [comment]
can you make a one-line command that makes the pi zero w work like the one that is only compatible with pi 2 and 3 or can you make it easier for us to understand server only please 

Thanks
