### ISSUE TITLE
Calender Events 

### ISSUE THREAD

**Issue by nessor** [MichMich/MagicMirror#38]
The Problem is that the calendar shows nearly all events. An so I have my events behind the compliments as well as behind the Newsfeed.
![bildschirmfoto 2015-11-18 um 10 33 45](https://cloud.githubusercontent.com/assets/3463261/11237455/49e83a70-8de0-11e5-975e-20d81322c417.png)

**Comment by MichMich** [comment]
Did you check the latest version?

**Comment by nessor** [comment]
-.-' nope. That solved my problem. Thanks!

**Comment by MichMich** [comment]
Good to hear! :)
