### ISSUE TITLE
Wont boot on pi2

### ISSUE THREAD

**Issue by pi-mad** [MichMich/MagicMirror#392]
Installed using the automated way in command prompt and all installed fine, started it up and it said about the config so I went and don't that and now when I start it I get just a black screen with nothing on it, have I not done something right?

**Comment by MichMich** [comment]
What version are you running. The master version has an issue with The 'en' language. If you run The develop branche it should be fixed.

**Comment by hazi2006** [comment]
What do you mean by Develop Branch? I have the same problem on Pi3, when i run it, it appears as a black screen.

**Comment by MichMich** [comment]
Duplicate of: https://github.com/MichMich/MagicMirror/issues/393
