### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by mohiuddinopu** [MichMich/MagicMirror#393]
After following every step mentioned in the forum, app starts without any error, but the screen is blank.

**Comment by stewartmckee** [comment]
I had the same issue and for me I used another machine and used chrome to open the console and found a javascript error in a 3rd party module.  You might find whats causing it in there?

**Comment by MichMich** [comment]
The current master version contains a bug. Please try the develop branch to see if this fixes the issue for you.

**Comment by stewartmckee** [comment]
FYI, I pulled yesterday evening from master and have it up and running in serveronly mode on a pi zero.  Not sure when the bug was introduced, but if after that, just ignore me. :)

**Comment by MichMich** [comment]
Serveronly mode doesn't contain the bug. It's an electron issue. I'll release a new Master asap.

**Comment by pi-mad** [comment]
How do you open develop branch

**Comment by MichMich** [comment]
I just release a new master version. To update:

```
cd ~/MagicMirror
git pull
```

**Comment by pi-mad** [comment]
Thanks

**Comment by cyberdude86** [comment]
I am experiencing the same blank start issue with my freshly installed rpi3 with mm2.  Is there any current bugs in the master branch?
