### ISSUE TITLE
How do I access the config/config.js on my raspberry pi 3?

### ISSUE THREAD

**Issue by vbhatti90** [MichMich/MagicMirror#396]
I have installed the MagicMirror2 program. Now i want to add the config/config.js.sample text to config/config.js. How do i access config/config.js on the raspberry pi 3?

What commands should I be using?

I'm not sure how to execute this section of the instructions:

**Configuration

Duplicate config/config.js.sample to config/config.js.
Modify your required settings.**

The MagicMirror is working but says "please create a config file", i do not know how to access that part.

**Comment by jesussanchez-a** [comment]
![screenshot from 2016-08-12 11-35-01](https://cloud.githubusercontent.com/assets/20364001/17629629/e4ca4e98-6080-11e6-8c1b-b315277c8743.png)
![screenshot from 2016-08-12 11-35-22](https://cloud.githubusercontent.com/assets/20364001/17629630/e4cb43ac-6080-11e6-8b80-84973c0ea5ee.png)


Follow the commands:
ls
cd ~/MagicMirror
ls
cd config
ls
sudo cp config.js.(prefix if any) config.js
sudo nano config.js

**Comment by MichMich** [comment]
For future support request please use http://forum.magicmirror.builders
