### ISSUE TITLE
[Feature] Humidity for Current Weather Module

### ISSUE THREAD

**Issue by amcolash** [MichMich/MagicMirror#399]
Hello, I love to see the weather with my magic mirror. It has been pretty humid lately where I live and so I decided to add in humidity to the Current Weather Module. It is really a simple addition as the open weather map api already has that data provided.

I was wondering what I should do merge my additions into the code base (as I think others might like this option as well - it is configurable). Should I just make a pull request? Thanks.

**Comment by MichMich** [comment]
Hi @amcolash, that would be a nice addition indeed! Feel free to send a pull request!
