### ISSUE TITLE
Module slideshow

### ISSUE THREAD

**Issue by barnabycolby** [MichMich/MagicMirror#401]
I'm running magic mirror on a small 4inch screen. Rather than trying to cram all of the modules on the same page, in my case it would be better to have a single module displayed on the screen and transition through a set of pages like a carousel. This could be done by adding a new configuration option defaulting to false. If true, then the modules would be shown in the order they appear in the config file. I'm happy to work on this feature but wanted your thoughts first?

**Comment by MichMich** [comment]
Nice idea! This can be done by a module. No modifications to the core are needed. If you need any help during the development of the module, check out http://forum.magicmirror.builders.
