### ISSUE TITLE
incorrect information in config.js for weather modules

### ISSUE THREAD

**Issue by commandlineent** [MichMich/MagicMirror#405]
The config.js file has comments in it that direct users to get an API key from openweather.org, but that should actually say openweathermap.org.  This has led to some confusion.

**Comment by MichMich** [comment]
What version are you looking at. Current master version seems to have the correct links?

**Comment by commandlineent** [comment]
You are absolutely right, I was looking at an older version.  I'll try to remember to read the instructions next time and get the latest version before posting.  Very sorry to have wasted your time.

**Comment by MichMich** [comment]
No problem. Thanks for contributing.
