### ISSUE TITLE
Is there a way for calendar to show 24 hour times?

### ISSUE THREAD

**Issue by dinkybluebug** [MichMich/MagicMirror#412]
Is there anyway for calendar to show 24 hours times?  as in the clock?

Many thanks.

**Comment by MichMich** [comment]
Which Locale (Language) are you using?

**Comment by dinkybluebug** [comment]
Thanks for replying.

My config.js says:

	language: 'en',
	timeFormat: 24,
	units: 'metric',

Is this what you mean?

**Comment by dinkybluebug** [comment]
@MichMich Is this the information you were after?

**Comment by MichMich** [comment]
Yeah, sorry for the slow response, I'm currently at a developers conference. Anyway, the way the time is formatted is done by moment.js. Moment formats the date/time based on the locale. You could look into the moment.js documentation if there is an other locale that has english text but a 24 hour formatting.

I agree, this is not the best route and a modification to the calendar would be a better option.

**Comment by dinkybluebug** [comment]
@MichMich No worries , enjoy your conference.  I'm a bit of a newby when it comes to all of this - but I'm learning lots.  I'll have a look and the moment.js documentation and post what I find.  Thanks for the response.

Marc

**Comment by dinkybluebug** [comment]
apparently changing the moment.js locale to 'en-gb' does this  - it reverts to 24 hr clock rather than US english - 'en'  

Any advice about what needs changing to reflect this?

**Comment by MichMich** [comment]
You only need to update your language field in the config. The value you fill in here, will be directly send to the moment.js instance.

**Comment by dinkybluebug** [comment]
it works it works.  hurrah!

Thanks!
