### ISSUE TITLE
Current weather in Kelvin

### ISSUE THREAD

**Issue by mrvanes** [MichMich/MagicMirror#429]
For some reason, current weather started showing temp in Kelvin since yesterday although config.units is set to 'metric'. I set units to metric explicitly in currentweather applet, but that didn't help. Did something change in the API?

**Comment by a-alex-z** [comment]
Pull request #427 already have a solution to this problem.

**Comment by mrvanes** [comment]
Thx, will apply as soon as I get home ;)
