### ISSUE TITLE
Enhancement: Make the "Select an artboard" resizable and/or add a title on hover

### ISSUE THREAD

**Issue by lanceplaine** [MichMich/MagicMirror#441]
Hi there,

Most of the time the input "Select an artboard" isn't long enough for me to select the right artboard.
It would be great if I can resize the artboard or at least when I hover the options of the input having a [title](http://www.w3schools.com/tags/att_global_title.asp)

<img width="718" alt="screen shot 2016-09-15 at 10 07 13 am" src="https://cloud.githubusercontent.com/assets/5476205/18559564/ad802b76-7b2c-11e6-8185-cf76e6db7db3.png">

Thanks

**Comment by MichMich** [comment]
I think you posted an issue to the wrong repository. 😁

**Comment by lanceplaine** [comment]
Oh yeah sorry 😁
Thanks
