### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by SimJim** [MichMich/MagicMirror#449]
I got a Problem with the MagicMirror...
Since this morning i cant start the MagicMirror (npm start). I was able to start it a few days ago.
![error](https://cloud.githubusercontent.com/assets/19064678/18678435/53852624-7f5c-11e6-9d7d-c912577c5927.JPG)

**Comment by MichMich** [comment]
for support, please check https://forum.magicmirror.builders

This topic might be of interest: https://forum.magicmirror.builders/topic/647/complete-setup-tutorial-npm-command-not-found-unable-to-install-dependencies
