### ISSUE TITLE
Calendar Full day events

### ISSUE THREAD

**Issue by vhgarandil** [MichMich/MagicMirror#45]
Hey,

First of all, thanks for doing this, it's awesome!

Now over to the not so fun stuff... I currently do not have the correct skills to remedy this but when I create full day events in Google Calendar it gives:
Alarm notification	in 16 days
Alarm notification	in 17 days
Alarm notification	in 25 days
Alarm notification	in 2 months
Alarm notification	in 6 months
Alarm notification	in 9 months
Alarm notification	in 9 months

While 1h long events etc shows up with correct name and all.

Any chance this could be looked at?

**Comment by thegunslingers** [comment]
Hey, This was bugging me too. I'm taking a look into it. Looks like the ICAL parser that is being used might be what is making this happen. I'll try to see if I can fix it.
