### ISSUE TITLE
Current Weather Module Not Updating

### ISSUE THREAD

**Issue by moviemanic** [MichMich/MagicMirror#458]
**Platform**: Raspberry Pi 2

**MagicMirror Version**: JavaScript version (v2).

**Description**: All of my other modules (Clock, WUnderground, Calendar, News Feed) are updating just fine however my Current Weather module will only update when MagicMirror is first launched, from then on the temperature remains the same even though open weather shows a different temp.

**Steps to Reproduce**: I did not make any changes to the Current Weather module. 

**Expected Results**: The correct temp displaying, with updating every 10 minutes.

**Actual Results**: The temp updates on launch and never again even though internet connection is maintained and my other modules update.

**Configuration**: The configuration for the Current Weather module is:
{
        module: 'currentweather',
        position: 'top_right',  // This can be any of the regions.
                                    // Best results in left or right regions.
        config: {
            // See 'Configuration options' for more information.
            location: 'location,location',
            locationID: 'ID', 
            appid: 'abcde12345abcde12345abcde12345ab' 
        }
    }
]

**Comment by MichMich** [comment]
Do you see any error or messages in your browser's console?

**Comment by MichMich** [comment]
For further support, please visit http://forum.magicmirror.builders.
