### ISSUE TITLE
magic mirror does not pick up the correct screen size

### ISSUE THREAD

**Issue by justme-1968** [MichMich/MagicMirror#463]
magic mirror does not pick up the correct screen size but uses only the top left corner of my screen.

any ideas how to fix this?

**Comment by MichMich** [comment]
Please use http://forum.magicmirror.builders for support. Closing this issue.

**Comment by justme-1968** [comment]
ok. will do.

please add autoHideMenuBar: true in js/electron.js also for kioskmode
