### ISSUE TITLE
npm is not working

### ISSUE THREAD

**Issue by NilanjPatel** [MichMich/MagicMirror#471]
![screen shot 2016-10-16 at 11 59 04 pm](https://cloud.githubusercontent.com/assets/8639339/19419781/9c65d398-93fc-11e6-92ef-92d138406473.png)

**Comment by MikhaelGerbet** [comment]
Hi, when you do npm install, you is in your MagicMirror dir ?

**Comment by MikhaelGerbet** [comment]
Try this :

    Cd MagicMirror && npm install

**Comment by NilanjPatel** [comment]
oky... got it. i thought it's a same software package like others so i go in main directory and than try to install.  thanks buddy

**Comment by MikhaelGerbet** [comment]
no problème ;) close issue if it's resolved for you ;)

**Comment by MichMich** [comment]
I suspect this solves the issue, so I close it. Feel free to reopen.
