### ISSUE TITLE
About the calendar

### ISSUE THREAD

**Issue by gzpywei** [MichMich/MagicMirror#476]
in the config.js

                                calendars: [
                                        {
                                                symbol: 'calendar-check-o ',
                                                url: 'webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics'
                                        }
                                ]
i want to use local "ics" file ,but i don't know how

**Comment by MichMich** [comment]
Local ics files are currently not supported. There are workarounds available. Please check https://forum.magicmirror.builders
