### ISSUE TITLE
Mobile app instead of raspberry pie

### ISSUE THREAD

**Issue by DeenABL** [MichMich/MagicMirror#487]
Hey guys! can anyone please help me and tell me how can i run this code on a mobile instead of raspberry pie ?!

**Comment by DeenABL** [comment]
Hey guys! can anyone please help me and tell me how can i run this code on a mobile instead of raspberry pie ?!

**Comment by DeenABL** [comment]
@MichMich can  you please help me and tell me how can i run this code on a mobile instead of raspberry pie ?!

**Comment by MichMich** [comment]
For support please visit https://forum.magicmirror.builders. Thanks!
