### ISSUE TITLE
Black screen for copy of hellowold module

### ISSUE THREAD

**Issue by titusece** [MichMich/MagicMirror#499]
Hello,
I have tried to create a new module in MM, for that I have copied helloworld module from "modules/defauls/helloworld" to "modules/Titus", I just renamed to 'Titus' as a module.

Then I changed the config.js file for a new Titus module.

I am getting black screen now for the Titus module, but just work fine for helloworld.
Why ? Any help ?
Just today I'm started to work on MM.

//Worked
/*
                      {
                      module: 'helloworld',
                      position: 'middle_center',
                      header: 'helloworld module',
                      config: {
                              text: 'I'm helloworld module'
                      } // closes config
                      }, // closes module helloworld
*/
//Not worked
                {
                        module: 'Titus',
                        position: 'middle_center',
                        header: 'Titus module',
                        config: {
                                text: 'I'm Titus module'
                        }
                },

Regards,
Titus S.

**Comment by MichMich** [comment]
For support please visit http://forum.magicmirror.builders. Thanks.

**Comment by titusece** [comment]
Thank you, sure.
