### ISSUE TITLE
Disable screensaver - Wiki

### ISSUE THREAD

**Issue by LukeSkywalker92** [MichMich/MagicMirror#502]
**Platform**: Raspberry Pi 2

**Description**: In the Wiki at [Raspberry Pi Configuration](https://github.com/MichMich/MagicMirror/wiki/Configuring-the-Raspberry-Pi) the line 
`sudo nano /etc/xdg/lxsession/LXDE-pi/autostart` 
should be changed to 
`sudo nano ~/.config/lxsession/LXDE-pi/autostart` 
to disable screensaver.

**Expected Results**: disable screensaver on Raspberry Pi 2

**Comment by MichMich** [comment]
For support Please visit http://forum.magicmirror.builders   Thanks!

**Comment by MichMich** [comment]
Fixed! For future issue: you can just edit the Wiki yourself. Thanks.
