### ISSUE TITLE
CSS-issue for third party modules

### ISSUE THREAD

**Issue by LukeSkywalker92** [MichMich/MagicMirror#511]
**Platform**: all

**MagicMirror Version**: v2

**Description**: When a third party module defines a css-class, which is already defined in a default module, the default module uses the class of the third-party module (maybe it depends on which module comes first in the config.js file)

**Steps to Reproduce**: Example: define a .title class in a third party module -> default calendars title is affected

**Expected Results**: other modules should not be affected by css styles from other modules . maybe a warning should appear if more than on module use same css-class.

**Comment by MichMich** [comment]
This is just the way css works. The best approach is to use namens like: `.mymodule-title`
