### ISSUE TITLE
New Function: Tageschau in 100 Sekunden

### ISSUE THREAD

**Issue by lolobyte** [MichMich/MagicMirror#517]
please develop a new module to display in the middle of the magicmirror a stream from Tagesschau in 100 Sekunden by pressing a switch.

**Comment by StefanBols** [comment]
Hi @lolobyte 

Submit that request on the forum :-)

**Comment by MichMich** [comment]
As said, support an feature request can be posted on http://forum.magicmirror.builders

Thanks!
