### ISSUE TITLE
Electron Prebuilt now named just "Electron"

### ISSUE THREAD

**Issue by nhubbard** [MichMich/MagicMirror#520]
The `electron-prebuilt` package is now named `electron`. Should we change it?

Source: http://electron.atom.io/blog/2016/08/16/npm-install-electron

**Comment by nhubbard** [comment]
I will probably create a pull request to fix it.

**Comment by nhubbard** [comment]
I'll reopen it for comments.

**Comment by MichMich** [comment]
Not sure but I think it's already changed in the develop branch. If not please send a PR.
