### ISSUE TITLE
Calendar recurring events not showing up.

### ISSUE THREAD

**Issue by jcbriones** [MichMich/MagicMirror#534]
**Platform**: Raspberry Pi 2/3, Mac, Linux

**Node Version**: 6.9

**MagicMirror Version**: v2

**Description**: Calendar recurring events not showing up but instead just the first event when the day its held.

**Steps to Reproduce**: I'm using the iCloud calendar. Haven't tried google nor microsoft calendars.

**Expected Results**: Should show all the recurring events not only the first one

**Actual Results**: Missing recurring events

**Comment by MichMich** [comment]
Hi There, thanks for your report: please check the forum or open a topic to see if other run into a similar issue. If this is a reproducible issue by multiple users, we kan look into it.

http://forum.magicmirror.builders

Thanks!
