### ISSUE TITLE
Electron Won't load

### ISSUE THREAD

**Issue by carruthjr** [MichMich/MagicMirror#538]
Hi. I've been working on the magic mirror and I finally got my RPi today. Then while I was working through the steps, the configuration confused me. I did 
` cp config.js.sample config.js`
then 
` mv config.js config`
Then when I tried to run electron it told me I had an error with the package.
Help?

**Comment by carruthjr** [comment]
Basically, how do I move the config files on my Pi in order to make the mirror work?

**Comment by MichMich** [comment]
The last step wasn't nessecery. You only have to do:
````
cp config.js.sample config.js
````

If you have any further questions, please visit the forum for support. http://forum.magicmirror.builders

**Comment by carruthjr** [comment]
Thanks
