### ISSUE TITLE
Few questions about PHP code

### ISSUE THREAD

**Issue by efiku** [MichMich/MagicMirror#54]
Hello @MichMich 
Project MagicMirror is awesome. :+1: !

I've few questions about PHP code here 

###  Why you decide use include for importing css? 
```php  
    <?php include('css/main.css') ?> 
```
 In my opinion better option:
```html
 <link rel="stylesheet" type="text/css" href="css/main.css">
```
 file: https://github.com/MichMich/MagicMirror/blob/master/index.php#L5

### The same code is in hash.php file 
file:  https://github.com/MichMich/MagicMirror/blob/master/index.php#L9
hash.php: https://github.com/MichMich/MagicMirror/blob/master/controllers/hash.php

###  function get_url() is really needed? 
On my vagrant machine output for calendar url is the same for both functions: `get_url` and `file_get_contents`

Could you tell me what version PHP you have? :)
```
Tested on:
PHP 7.0.2-2+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC3, Copyright (c) 2002-2015, by Derick Rethans
```

**Comment by MichMich** [comment]
I initially used this to prevent caching. I agree that this currently isn't the cleanest way.

**Comment by efiku** [comment]
Ok Issue edited. Please look now :smile: 
@MichMich I can make PR with some changes for PHP code if you allow of course.

**Comment by MichMich** [comment]
Make sure you throughly test everything on a raspberry Pi. I think php 5 should be supported. (Not only 7).

**Comment by MichMich** [comment]
Can I close this issue? Or do you need more input?

**Comment by efiku** [comment]
I have no free time right now :(

**Comment by MichMich** [comment]
Same problem here. ;)
