### ISSUE TITLE
Customizable Timezone

### ISSUE THREAD

**Issue by VikramTiwari** [MichMich/MagicMirror#544]
Please only submit reproducible issues. 

The time is derived using `moment-with-locale` which uses system default time. This results in proper time during development, but as soon as this code is uploaded to raspberry pi the system default (GMT) kicks in, and hence incorrect (to end user) time.

To fix this, we can use 'moment-timezone' which allows us to use moment and specify timezones as well.

**Comment by nhubbard** [comment]
@MichMich I believe we can close this issue.
