### ISSUE TITLE
wrong age in calendar module...

### ISSUE THREAD

**Issue by chamaeleon82** [MichMich/MagicMirror#568]
hi,

I´ve created google calendar as a birthday calendar. Birthday is created as an appointment (whole day, repeat every year). Start date is the birthday and year of birth. 
My problem is that the display of age is a year less. So instead of 35 years old only 34 is displayed (E.g. March 22th.).
![wrong_age_calendar_module](https://cloud.githubusercontent.com/assets/21147588/21152593/3f5a3426-c167-11e6-89d4-247588df58cf.jpg)

Does anyone know this problem?

**Comment by MichMich** [comment]
That's odd. I suggest discussing this issue on the forum: http://forum.magicmirror.builders

**Comment by henglert** [comment]
As I wrote in the forum: 

`--- a/modules/default/calendar/calendar.js
+++ b/modules/default/calendar/calendar.js
@@ -126,7 +126,7 @@ Module.register("calendar",{
                                repeatingCountTitle = this.countTitleForUrl(event.url);

                                if(repeatingCountTitle !== '') {
-                                       var thisYear = new Date().getFullYear(),
+                                       var thisYear = new Date(parseInt(event.startDate)).getFullYear(),
                                                yearDiff = thisYear - event.firstYear;

                                        repeatingCountTitle = ', '+ yearDiff + '. ' + repeatingCountTitle;
`

**Comment by MichMich** [comment]
Please send  PR. Thanks!

**Comment by roramirez** [comment]
Hey @MichMich  this issue need be closed.
