### ISSUE TITLE
Mirror Freezing

### ISSUE THREAD

**Issue by nhubbard** [MichMich/MagicMirror#570]
**Platform**: 
* **Electron** Latest
* **Node** Latest
* **Raspberry Pi 3**

**MagicMirror Version**: Version 2

**Description**: Over a small amount of time after starting, the mirror will work fine until seemingly random intervals of time occur, in which the mirror freezes, along with the host OS. This also disallows SSH until the system is hard reset.

**Steps to Reproduce**: Using a stock Raspberry Pi 3, set up the system with the normal setup and the snow module. The system should freeze. **No spike in CPU or RAM usage was observed!**

**Expected Results**: The system works as normal.

**Actual Results**: The system freezes, causing the need for a hard reset.

**Configuration**: What does the used config.js file look like? Don't forget to remove any sensitive information! **It looks like the basic config with the snow module.**

**Comment by nhubbard** [comment]
I have checked the snow module, and it does still freeze without it.

**Comment by roramirez** [comment]
Hi @nhubbard 

What is snow module?

**Comment by Jopyth** [comment]
@roramirez Can be found here: https://github.com/nhubbard/MagicPlugins/tree/master/snow

**Comment by MichMich** [comment]
Make sure you use a powerfull and stable powersupply. Try an other one to see if that solves the issue.

**Comment by roramirez** [comment]
Thanks @Jopyth

I 'm testing  the snow module. It's very funny for the time ... well I'm in the other side of world. Here dont snow at this time of year.

@nhubbard I sent a PL for getting the  images from local side. Maybe could be this.

**Comment by nhubbard** [comment]
Yeah, I fixed it. Turns out forgetting to install the new dependencies won't break it, but will make it freeze constantly. :-1:

**Comment by nhubbard** [comment]
It hasn't frozen for about 8 days now.
