### ISSUE TITLE
Can't access module public folder

### ISSUE THREAD

**Issue by mrvanes** [MichMich/MagicMirror#571]
I've created a copy of HelloWorld module called pvoutput and created a sub directory public in which I created a file test.txt. I assumed this file would be available on localhost:8080/pvoutput/test.txt but all I get is a "Cannot GET /pvoutput/test.txt".

**Comment by Jopyth** [comment]
Try `localhost:8080/modules/pvoutput/test.txt` or `localhost:8080/modules/pvoutput/public/test.txt`.

Also for development support, a thread in [the forum section for development](https://forum.magicmirror.builders/category/6/development) instead of an issue on github might be better.

**Comment by mrvanes** [comment]
That worked, and thx for the link to the forum! Will pick up furthere inquiries there!
