### ISSUE TITLE
Module CurrentWeather

### ISSUE THREAD

**Issue by fry0815** [MichMich/MagicMirror#573]
The module is not loading, if the given temperature from openweather.org is zero (0).
The problem is the check in line 221: 
```javascript
if (!data || !data.main || !data.main.temp) {
	// Did not receive usable new data.
	// Maybe this needs a better check?
	return;
}
```
If `data.main.temp` is 0, it goes to `return`. Yeah you are right, it needs a better check. :)

For example i fixed the problem like this:
```javascript
if (!data || !data.main || typeof data.main.temp === 'undefined') {
	// Did not receive usable new data.
	// Maybe this needs a better check?
	return;
}
```

I hope this will help you.

**Comment by roramirez** [comment]
@fry0815  Why dont send a Pull Request fixed this situation?.

The new contributions are welcome :)

**Comment by fry0815** [comment]
@roramirez I dont know, I'm new in this situation on a public project. I try to do this at home.
Thank you :)

**Comment by nhubbard** [comment]
@fry0815 I can make a pull request if you wish to allow me to.

**Comment by fry0815** [comment]
Oh sry, atm i have no time. @nhubbard yes can do it! Thank you! :)

**Comment by roramirez** [comment]
Hi @MichMich, I think this issue need stay open ;)

**Comment by Paulismo** [comment]
Hello everybody. I have an issue in the currentweather module, my time is freezing, it starts from 20:xx and stops right there, i haven`t iven a idea about what`s causing this issue and i hope you`ll help me out. I`m working with raspberry pi btw.

**Comment by fewieden** [comment]
isn't the time in current weather just a disolay for sunset and sunrise?

**Comment by Paulismo** [comment]
Oh, thank you for support, I just couldn't figure this problem out beckause
lack of information, but anyway you helped me a lot.

31 июля 2017 г. 23:46 пользователь "fewieden" <notifications@github.com>
написал:
