### ISSUE TITLE
Birthday Calendar

### ISSUE THREAD

**Issue by jakovalck** [MichMich/MagicMirror#574]
I would like to add custom birthdays to the calendar module like I could in the first magic mirror. Ive tried a couple things and cant get it to work. Is there a certain place that i need to enter the data, and a format that has to be used to get them to show.

**Comment by roramirez** [comment]
Hi @jakovalck 

This kind of question or support, please will ask into the forum
https://forum.magicmirror.builders/

The issues here is more related improvement, new feature or  bugs into MagicMirror.

**Comment by jakovalck** [comment]
Ok Thanks
