### ISSUE TITLE
Wheater Forecast can not be proxied

### ISSUE THREAD

**Issue by Dom1n1c** [MichMich/MagicMirror#578]
All Addons, that i use, can be proxied using nginx, to use the mm on another device, or to access it from another site.
But: the Weather Elements won't load behind nginx.
Maybe there are some paths that need to be adjusted within the mm installation?

Thanks.

**Comment by MichMich** [comment]
There currently is no proxy support. Feel free to send a PR.

**Comment by Dom1n1c** [comment]
The ApiBase needs to be proxied in order to allow https access.
This could be done via nginx or similar.
Then you just need to change the apibase in the two configs for current and the weather forecast,

apiBase: "https://nginx.de/openweathermap/", 
which will serve the API via https
