### ISSUE TITLE
MagicMirror v2 - electron js/electron.js [sh: 1: electron: not found]

### ISSUE THREAD

**Issue by HungoverRex** [MichMich/MagicMirror#581]
**Platform**: Raspbian installed from NOOBS running on Raspberry Pi 3 

**Node Version**: v7.3.0
**NPM Version**: v3.10.10

**MagicMirror Version**:  v2

**Description**: 
Cannot get MagicMirror to start up, I keep getting the error shown in the image attached. I have updated my node version and believe my NPM an acceptable verison.

**Steps to Reproduce**: List the step by step process to reproduce the issue.

**Actual Results**: 
NPM start  cd ~/MagicMirror
![screenshot 1](https://cloud.githubusercontent.com/assets/24819705/21536811/807bc088-cd3c-11e6-8d21-2a6eed8c9b34.png)

**Configuration**: What does the used config.js file look like? Don't forget to remove any sensitive information!

MagicMirror Debug File:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v7.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.0.0~prestart: magicmirror@2.0.0
6 silly lifecycle magicmirror@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle magicmirror@2.0.0~start: magicmirror@2.0.0
8 verbose lifecycle magicmirror@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle magicmirror@2.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle magicmirror@2.0.0~start: CWD: /home/pi/MagicMirror
11 silly lifecycle magicmirror@2.0.0~start: Args: [ '-c', 'electron js/electron.js' ]
12 info lifecycle magicmirror@2.0.0~start: Failed to exec start script
13 verbose stack Error: magicmirror@2.0.0 start: `electron js/electron.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:885:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid magicmirror@2.0.0
15 verbose cwd /home/pi/MagicMirror
16 error Linux 4.4.11-v7+
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v7.3.0
19 error npm  v3.10.10
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error magicmirror@2.0.0 start: `electron js/electron.js`
24 error spawn ENOENT
25 error Failed at the magicmirror@2.0.0 start script 'electron js/electron.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the magicmirror package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron js/electron.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs magicmirror
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls magicmirror
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by MichMich** [comment]
Please use the forum for support questions like this: http://forum.magicmirror.builders 

Thanks.
