### ISSUE TITLE
New 3rd party module

### ISSUE THREAD

**Issue by mrvanes** [MichMich/MagicMirror#606]
I've created a pvoutput.org module. How do I get this mentioned in the 3rd party module wiki?
https://github.com/mrvanes/MMM-PVoutput

I already mentioned it on the forum:
https://forum.magicmirror.builders/topic/1218/pvoutput-widget-module

**Comment by qistoph** [comment]
You can just edit the Wiki-page yourself, by clicking the Edit button on the page.

https://github.com/MichMich/MagicMirror/wiki/Home/_edit

**Comment by mrvanes** [comment]
Duh...
