### ISSUE TITLE
Calendar URLs not changeable with js anymore

### ISSUE THREAD

**Issue by paviro** [MichMich/MagicMirror#63]
I have a module changing the calendar URLs based on who is using the mirror. Before the multi-calendar update this used to work but now it does not any ideas?

`config.displaySymbol = true`

`config.calendar.urls = [
		{
			//Schule
			symbol: 'calendar-plus-o', 
			url: 'sdfsdf'
		},
		{
			symbol: 'mars',
			url: "werwer",
		}
		]`
		`calendar.updateData()`

Changing the calendar URLs still seems to work but it only changes after some time not after a `calendar.updateData()` like it did in the past. `config.displaySymbol = true` is not changeable after initial loading it seems, is there any way to change that?

**Comment by MichMich** [comment]
Check with @bitte-ein-bit, he made the changes to the calendar.

**Comment by bitte-ein-bit** [comment]
Putting the code below in $().ready function, has the desired effect. 

```
setTimeout(function() {
		calendar.displaySymbol = false;
		calendar.eventList = [];
		config.calendar.urls = [
		{
			symbol: 'calendar-plus-o', // Fontawsome Symbol see http://fontawesome.io/cheatsheet/
			url: 'http://www.ifeiertage.de/by-.ics'
		},
		];
		calendar.updateData(calendar.updateCalendar.bind(calendar))
	}, 10000);
```

The eventlist is not cleared anymore, only the events of the current calendar are purged. I think for switch calendars depending on the person I would prefer a solution with an added e.g. displayfor property which would make another round-trip to the web unnecessary. I'm not yet in this stage. so maybe I'll go down that road.

> config.displaySymbol = true 

I think you mean `config.calendar.displaySymbol` but anyway, yes this is just sourced once just like `config.calendar.maxEntries`.

Hope that helps.
