### ISSUE TITLE
npm start is only showing Windows IIS

### ISSUE THREAD

**Issue by schuesslerf** [MichMich/MagicMirror#632]
I just tried to use your app but somehow somethings seems to be wrong. I downloaded the github repo, ran npm install and then ran npm start, what happened is that an electron window started, within there was the Microsoft IIS (Internet Information Services). Is this the expected behaviour? How can I switch to the normal view if yes? Or did something went wrong when installing?

I'm trying it on windows 8, node 6.7.0 and npm 3.10.3.

Any ideas?

**Comment by MichMich** [comment]
Please open a support topic on http://forum.magicmirror.builders, Github Issues should only be used for reproducible issues. Thanks!
