### ISSUE TITLE
Blank Black screen when using MS Edge

### ISSUE THREAD

**Issue by ostfilinchen** [MichMich/MagicMirror#639]
If I open the MirrorPage on my PC via http://raspberrypi:8080 i get a blank Black screen, But only with MS Edge. With a third Party Browser like Chrome or Opera i didn't have the issue. Also on the smartphonebrowser it works without issues.

**Comment by roramirez** [comment]
Do have any log some inspector tool on MS Edge?

**Comment by nhubbard** [comment]
@ostfilinchen MS Edge is known to not work. It has to do with Edge's rendering engine.

**Comment by MichMich** [comment]
@nhubbard Is this something we should solve in your opinion?

**Comment by nhubbard** [comment]
@MichMich I don't know. We write our code for Chrome, and if you have noticed, there are significant differences in Edge vs Chrome. It's like trying to run your code on Google Chrome when it only ran on Netscape Navigator.

**Comment by MichMich** [comment]
Since Edge/Windows is a non supported platform, and this issue is inactive I'm closing this for now ...
If you feel this issue should remain open, please let me know.
