### ISSUE TITLE
News module not working

### ISSUE THREAD

**Issue by jerbookins** [MichMich/MagicMirror#66]
I just pulled the new version today and uploaded it and the news module isn't working

I just changed the rss feed to "http://www.reddit.com/r/news/.rss", as I've done with many previous versions and not changed any internal settings.

> "No feed results for: https://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20rss%20where%20url%3D'http%3A%2F%2Fwww.reddit.com%2Fr%2Fnews%2F.rss'"
> Failed to show a news story 20 times, stopping any attempts

**Comment by bitte-ein-bit** [comment]
I get an error when I click on your second link
 `{"error":{"lang":"en-US","description":"Query syntax error(s) [line 1:62 mismatched character ' ' expecting ''']"}}`

You're sure the url is correct? Maybe reddit has some issues in their rss feed? Using a different feed it works for me.

**Comment by MichMich** [comment]
@jerbookins Where you able to solve this? Can I close this issue?

**Comment by linugen** [comment]
I am getting the same error as @jerbookins after replacing the feed with the AP feed    
```
news: {
        feed: 'http://hosted2.ap.org/atom/APDEFAULT/cae69a7523db45408eeb2b3a98c0c9c5'
    }
```
`{"error":{"lang":"en-US","description":"Query syntax error(s) [line 1:98 mismatched character ' ' expecting ''']"}}`

**Comment by MichMich** [comment]
It's due to the usage of the yahoo api. In a previous version we did not use it. I'm not very happy with the Yahoo solution, but don't have the time to make a new solution for it. A pull request would be kindly appreciated.

**Comment by MichMich** [comment]
This will be solved in V2.
