### ISSUE TITLE
Current Weather giving wrong time and weather

### ISSUE THREAD

**Issue by icbinaunap4t** [MichMich/MagicMirror#665]
Platform: Raspberry Pi 3 Raspbian Jessie with Pixel. Kernel ver. 4.4
Node version is the latest node version
MagicMirror version: JavaScript version (v2)

I have the current weather module on my screen but it is showing the incorrect time and temperature as if the location was incorrect. However, I went to http://openweathermap.org/help/city_list.txt. I’m trying to display the weather for Madison WI and the id on there is ‘5261457’ but weather still off.

**Comment by icbinaunap4t** [comment]
Platform: Raspberry Pi 3 Raspbian Jessie with Pixel. Kernel ver. 4.4
Node version is the latest node version 
MagicMirror version: JavaScript version (v2)

I have the current weather module on my screen but it is showing the incorrect time and temperature as if the location was incorrect. However,  I went to http://openweathermap.org/help/city_list.txt. I’m trying to display the weather for Madison WI and the id on there is ‘5261457’ but weather still off.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
