### ISSUE TITLE
Very old google calender events shown as short running events

### ISSUE THREAD

**Issue by mwaldegg** [MichMich/MagicMirror#69]
A lot of very old events were shown as short running events (from 2007..).

Analyze showed, that the have 0 as end second.. because they had no End. T.g. Events starting and ending at 10:00.

Fixed it for me in calendar.js this way:

changed } "else if  (endSeconds >= 0)" to "} else if  (endSeconds > 0) {"

so all 

                    //m.waldegger@gmail.com better to hide them when endSecond = 0; changend endSeconds >= 0 to endSeconds > 0
                    } else if  (endSeconds > 0) {
			// TODO: Replace with better lang handling
			if (endSeconds <= 60*60*5 || seconds >= 60*60*24*2) {
				var time_string = this.shortRunningText + ' ' + moment(startDate).fromNow(true);
			}else {
				var time_string = this.longRunningText + ' ' + moment(endDate).calendar()
			}
			if (!e.RRULE) {
				this.eventList.push({'description':e.SUMMARY,'seconds':seconds,'days':time_string,'url': url, symbol: this.calendarSymbol});
			}
			this.calendarSymbol});
                                //this.eventList.push({'description':seconds,'seconds':seconds,'days':time_string,'url': url, symbol: this.calendarSymbol});
			}
			e.seconds = endSeconds;
		}

**Comment by MichMich** [comment]
This is fixed in the latest merge.
