### ISSUE TITLE
Load fonts and vendor libraries via bower.

### ISSUE THREAD

**Issue by Bruce17** [MichMich/MagicMirror#691]
Hi,

I noticed you included a lot of fonts and vendor libraries directly into your project. How about loading them via [bower](https://bower.io/)?

**Comment by paviro** [comment]
npm would make more sense wouldn't it? Most are available there too and it needs to be use anyway for the node dependencies.

**Comment by Bruce17** [comment]
Yeah sure can use npm too. Personally I like to use bower for frontend stuff only to separate them a little bit.

If you like, I can try to remove some libraries and add them via npm (or bower, what you prefer).

**Comment by roramirez** [comment]
There a related discussion about the vendor directory #592.

Bower is greats for keep externals libs into the a project without tracking the files in version control system.

Why not try a send a Pull Request about this?

**Comment by MichMich** [comment]
If we gonna use a package manager, let's stick to NPM. I don't want to overcomplicate things.

The reason why some things are in the vendor folder is because they are modified versions because of a bug in the current version. This, of course, could use a better solution.
