### ISSUE TITLE
Can´t see openweather module currentweather and forecast

### ISSUE THREAD

**Issue by Phoenxi131178** [MichMich/MagicMirror#707]
Hello Michael
At first thx for the MagicMirror Software. For me it is the first time to check the Raspberry and Linux.
I installed the Ras3 with raspbian jessie and then i installed your Magic Mirror with 
curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh | bash
I used complete your manual.
I got an account from openweather.org and filled my appid in the config.js and the module currentweather and weatherforecast.
I checked everything twice but now i have no idea.
I hope everyone can help me. Maybe i have forgotten somthing to install ??

Greetings from Germany 

Jan

**Comment by fewieden** [comment]
Hey Jan, do you get any errors in the terminal or electron console (npm start dev)? Probably some syntax errors in your config, you can check your config.js for example on jshint.com

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by Phoenxi131178** [comment]
Thank you for your help !!! I got it.
One wrong Nummer in the APPID. npm start dev showed me what was wrong.

Greeting Jan

2017-02-10 0:20 GMT+01:00 fewieden <notifications@github.com>:
