### ISSUE TITLE
[TRACKING ISSUE] Engine.io, and by extent, Socket.io, has a vulnerability

### ISSUE THREAD

**Issue by nhubbard** [MichMich/MagicMirror#709]
**Platform**: Affects all platforms.

**Node Version**: Affects all versions.

**MagicMirror Version**: v2

**Description**: Engine.io, the stack behind Socket.io, has a vulnerability caused by an out-of-date version of the `ws` module. Tracking issue in socketio/engine.io is available [here](https://github.com/socketio/engine.io/issues/479)

cc @MichMich @roramirez

**Comment by roramirez** [comment]
I can see. Its in the planning to fix soon.

I think is need it before release a new version add this fix from the new version of `ws` module. 

By other hand, If is release soon the patch of this. How w'll process to apply a patch on master branch? 

[I've mentioned before](https://github.com/MichMich/MagicMirror/pull/591#discussion_r94590779) about release label, we using [Semantic Versioning](http://semver.org/), What be the next release version name 2.1.0.1 or 2.1.1 if include only this patch?

**Comment by nhubbard** [comment]
@roramirez When they release a newer version with an updated `ws` module, we can release it with the next new version.

**Comment by roramirez** [comment]
@nhubbard My question is more related, what will happened in the future if we need add only one patch on master branch?, What version name will be?

**Comment by morozgrafix** [comment]
If you patch current version with a backwards compatible bug fix or patch, v2.1.0 would become v2.1.1 if I'm not mistaken. As far as I recall Semantic Versioning follows `vMajor.Minor.Patch` scheme.

**Comment by roramirez** [comment]
Yes, I understand the version semantic that way. The main point is next planning name version is **2.1.1** I think should be **2.2.0**

**Comment by nhubbard** [comment]
@morozgrafix Spot on.

**Comment by MichMich** [comment]
2.2.0 will be used whenever there is a breaking change in the API. (like 2.1.0 was)...

2.1.1 will include this security patch.

**Comment by nhubbard** [comment]
@MichMich They released version 2.0.2 of Engine.io... but I don't see any new version of Socket.io :cry:

**Comment by roramirez** [comment]
This  https://github.com/socketio/socket.io/releases/tag/1.7.3 ?

**Comment by nhubbard** [comment]
@roramirez Yup. 1.7.3 bumped engine.io-client to 1.8.3, which contained the bugfix.

**Comment by roramirez** [comment]
So we should be moved this in package.json. I pushed  a PR.
