### ISSUE TITLE
Current Weather Module 0° Bug

### ISSUE THREAD

**Issue by likeadoc** [MichMich/MagicMirror#717]
**Platform**: Rpi3

**MagicMirror Version**:  JavaScript version (v2).

**Description**: If the temperature is exactly 0.0° the currentweather module is suspended due to the poor checking mechanics of the initial if statement in processWeather (!data.main.temp).
It would be better to check for the pressure (data.main.pressure) instead of the temperature.

**Comment by roramirez** [comment]
This should be fix in commit 93c07b2b1e2e4218d17ceead43b63509b6beb7e0 

What version and branch are you using?

The previous change is in the develop branch. Are you using from the master branch?

**Comment by likeadoc** [comment]
sorry for your inconvenience ! I´m on the master branch - so yeah:D
