### ISSUE TITLE
Unable to modify compliments

### ISSUE THREAD

**Issue by IOFire** [MichMich/MagicMirror#73]
I changed the default phrases in js/config.js and afterwords the page will not display any content. Just a black background.

**Comment by bitte-ein-bit** [comment]
Syntax Error. Open the developer console (F12) of chrome and look for the error.

**Comment by IOFire** [comment]
evening: [
            'Wow, you look hot!',
            'I hope today went well -- I've just been hanging out thanks for asking',
            'Enjoy your evening guys!'
        ]

the error says it's a syntax issue at line 34 which is that second phrase. Is it too long or something? Hyphens not allowed?

**Comment by paviro** [comment]
Probably because of ' in I've. Use " around your sentence instead.
