### ISSUE TITLE
How to (get to) edit config? (Noob)

### ISSUE THREAD

**Issue by karlholst** [MichMich/MagicMirror#730]
I dont know how to open the config.js file ... :( I want to change the properties but idk how

**Comment by karlholst** [comment]
I dont know how to open the config.js file ... :(

**Comment by roramirez** [comment]
Please use the forum for these kind of help https://forum.magicmirror.builders/

If you want add new feature, bugfix or something related with development add here.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
