### ISSUE TITLE
What do I do now?

### ISSUE THREAD

**Issue by karlholst** [MichMich/MagicMirror#731]
1)Duplicate config/config.js.sample to config/config.js.
   2) Modify your required settings.

The following properties can be configured:

**Comment by karlholst** [comment]
I see every new module is starting by opening config. I want to add new modules, but i dont know how :,(

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
