### ISSUE TITLE
Missing translation for weather forecast

### ISSUE THREAD

**Issue by BerndKohl** [MichMich/MagicMirror#752]
When setting language to 'de' in global config.js the table header of weather forecast module still says 'WEATHER FORECAST'

Should be something like 'Wettervorhersage' in case 'appendLocationNameToHeader' is not set and 'Wettervorhersage für' if 'appendLocationNameToHeader' is set to true.

**Comment by fewieden** [comment]
there is no header set, you have to do it yourself

```
{
  module: "weatherforecast",
  position: "top_right",
  header: "Wettervorhersage",
  config: {
    //your config
  }
}
```

in case you set ```appendLocationNameToHeader``` the location will be appended to your string you defined in the header

**Comment by BerndKohl** [comment]
Thank you, missed that somehow.
