### ISSUE TITLE
Possibility to add '°C' to temperature values

### ISSUE THREAD

**Issue by BerndKohl** [MichMich/MagicMirror#753]
It would be very much appreciated if there was a setting allowing the configuration of the displayed temperature values in modules weather forecast and current weather.

Currently only ° is display (in current weather) or nothing at all (in forecast).

It would like to have °C displayed after the temperature. e.g. 8°C or 45°F.

**Comment by Speedy-one** [comment]
Just open the currentweather.js and search for 

`temperature.innerHTML =" " + thies.temperature + "&deg;";`

and add an **C** after &deg;

`temperature.innerHTML =" " + thies.temperature + "&deg;C";`

**Comment by BerndKohl** [comment]
Thanks you.
But wouldn't that be overwritten when this module gets an update?
I would prefer a configurable solution...

**Comment by amcolash** [comment]
See #773. Once pulled it should be in develop branch. Otherwise you can use the patch until merged.

**Comment by BerndKohl** [comment]
Thanks a lot, that sounds very promising.

**Comment by amcolash** [comment]
Glad to help!
