### ISSUE TITLE
weather not displaying

### ISSUE THREAD

**Issue by dmrowe84** [MichMich/MagicMirror#777]
ive input all my information correctly (as far as i can tell), however i still cannot get the weather to display. 
any advice at all would be helpfull :)

![2017-03-15-203011_1920x1080_scrot](https://cloud.githubusercontent.com/assets/26317586/23978320/5ad30d66-09c1-11e7-947e-c41f5aa73a44.png)
![20170315_204115](https://cloud.githubusercontent.com/assets/26317586/23978324/5f347700-09c1-11e7-8967-16c9fc7723ad.png)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
