### ISSUE TITLE
Weather Forecast - Low Temp Displayed in Wrong units

### ISSUE THREAD

**Issue by dpcarlton** [MichMich/MagicMirror#78]
I am using imperial units in my config.js. The current weather and high forecast shows up in Farenheit, but the low appears to be in Celsius.

![image](https://cloud.githubusercontent.com/assets/17087980/12854753/ac505354-cbf8-11e5-9fce-2741c5935c6e.png)

**Comment by theanimator** [comment]
I'm also using Imperial, but mine appears to be correct even though there is quite a spread between the high and the low. I compared with http://openweathermap.org/city and weather.com

**Comment by dpcarlton** [comment]
Anyway you can post a shot of your weather widget? My temps are not matching up at all.

**Comment by theanimator** [comment]
I'm in Santa Clara CA <img width="1440" alt="magicmirror" src="https://cloud.githubusercontent.com/assets/1187077/12855419/2903cd54-cbf4-11e5-9344-c593abaea62d.png">

**Comment by dpcarlton** [comment]
Yeah, yours looks right. Out of curiosity, are you using lat/long or city name in config. js?

"            q: 'Colorado Springs,US',"

**Comment by theanimator** [comment]
q: 'Santa Clara,US',

**Comment by dpcarlton** [comment]
Could be an issue with my city. I changed to Santa Clara and it came up fine. Odd.

**Comment by axlbundy** [comment]
I'm having the same issues with los angeles weather. I've tried Los Angeles,US and Los Angeles,California both give the same incorrect High/Low Temps. The really strange thing is that the current temperature seems to be spot on

**Comment by MichMich** [comment]
If you use the openweathermap api you could check to see what the api feed sends to your mirror. If it is indeed an issue with the API, I would suggest reporting it to openweathermap.

Please let me know when I can close this issue.

**Comment by dpcarlton** [comment]
Thanks. Is there a way to see the raw api data that I am receiving?

**Comment by MichMich** [comment]
You could use the browsers web inspector, or just surf to the url:

    http://api.openweathermap.org/data//2.5/weather?q=Baarn%2CNetherlands&units=metric&lang=nl&APPID=YOUR_API_KEY_HERE&cnt=5

Make sure to modify the parameters in the link above.

**Comment by dpcarlton** [comment]
Thanks, that url returns the current weather, are you using this for the
forecast?

This url seems to return the correct forecast.

http://api.openweathermap.org/data/2.5/forecast?id=5417598&units=imperial&appid=
<apiID>&cnt=5

**Comment by MichMich** [comment]
you're right. sorry.... posted the wrong link.

**Comment by dpcarlton** [comment]
Ok, so I see something.

In your code, you are using this url:

http://api.openweathermap.org/data/2.5/forecast/daily?id=5417598&units=imperial&appid=
<appid>&cnt=5

{"day":63.41,"min":31.37,"max":70.56,"night":41.77,"eve":62.76,"morn":31.37

This url returns completely different results then this url:

http://api.openweathermap.org/data/2.5/forecast?id=5417598&units=imperial&appid=
<appid>&cnt=5

{"temp":57.13,"temp_min":41.58,"temp_max":57.13,

**Comment by dpcarlton** [comment]
So it appears some odd rounding is happening in the code. 

Here is the displayed data:

![image](https://cloud.githubusercontent.com/assets/17087980/12873381/aedea41e-cd78-11e5-8356-3f8a263c7064.png)

And here is the raw data:

![image](https://cloud.githubusercontent.com/assets/17087980/12873384/bb136d6e-cd78-11e5-8f32-a4bee26f5600.png)

Sun - Min is off by 3 degrees.
Mon - High is off by 2 degrees
Tue - High is off by 2 degrees.
Wed - High is off by 2 degrees.
Thu - Both Match
Fri - Both Match

**Comment by bitte-ein-bit** [comment]
@dpcarlton Sorry to say, but no... this is just rounding to one decimal place. 37.13 becomes 37.1 and 21.49 is rounded to 21.5.
![2016-02-08 21_45_45-bb136d6e-cd78-11e5-8f32-a4bee26f5600 png 895x250](https://cloud.githubusercontent.com/assets/4521676/12898646/1c459b9e-ceae-11e5-807c-5b6f299abed9.png)

**Comment by dpcarlton** [comment]
You are right, sorry. When I looked at it yesterday I could have sworn it was off. No idea how I mis-read it. You can close this issue. I opened one with the api providers.

**Comment by jamesarm97** [comment]
FYI, looks like you were looking at the "current" temps vs the Max temps and that was the reason for the difference.
