### ISSUE TITLE
Google Calendar not working

### ISSUE THREAD

**Issue by bksupersonic10** [MichMich/MagicMirror#79]
Hey guys, 
I'm very, very new to scripting but I've tried looking around the forums for what might be the problem, and while it likely is just my incompetence, I need some help. I'm not sure where the url for my google calendar goes, I've tried it in a few different locations but none of them seem to work. I've been getting a link in ical format but it still does not show up. I've downloaded fresh code and tried it again with no luck. thanks guys!

**Comment by MichMich** [comment]
You should put the url in the config.js file. Somewhere around line 45.

https://github.com/MichMich/MagicMirror/blob/master/js/config.js#L45
