### ISSUE TITLE
Unable to select timezone

### ISSUE THREAD

**Issue by xy86** [MichMich/MagicMirror#797]
Not able to choose timezone. 

Tried:
- timezone: Etc/GMT+01
- timezone: Etc/UTC+02

....for Oslo - Norway.

The clock disappears whenever a timezone-value is added (besides "null" or missing parameter).

Any help appreciated :)

**Comment by MichMich** [comment]
Merged. Closing this issue.

**Comment by roramirez** [comment]
This issue I think need re-open, there a little thing I'm under investigation about mentioned in 
review https://github.com/MichMich/MagicMirror/pull/803#pullrequestreview-30370685

**Comment by MichMich** [comment]
Reopened.

**Comment by MichMich** [comment]
@roramirez Can I close this one?

**Comment by MichMich** [comment]
Closed due to inactivity.

**Comment by sushant96702** [comment]
Hi i have installed magic mirror recently and i wanna know that how can i change timezone i am from india 
please give me step by step instruction
any help would be appreciated

**Comment by sdetweil** [comment]
the clock settings are in the base OS, not in MagicMirror

so, change your system time

**Comment by sushant96702** [comment]
thanks but how do i change time format to 12 hours as on rasp pi i have 12 hr time format but time on magic mirror is still 24 hrs

**Comment by sdetweil** [comment]
@sushant96702  edit the ~/MagicMirror/config/config.js and change the timeFormat to 12 from 24

```
        language: "en",
        timeFormat: 24,                   // < -- this
        units: "metric",
```

**Comment by sushant96702** [comment]
i have already done this

**Comment by sdetweil** [comment]
please post the config.js. note that the config is case sensitive.. timeformat is NOT the same as timeFormat

it should read
```
timeFormat: 12,
```
works for me

**Comment by sushant96702** [comment]
[config.txt](https://github.com/MichMich/MagicMirror/files/4786702/config.txt)




i have turned into txt because git doesnt support .js files

**Comment by sushant96702** [comment]
[config.txt](https://github.com/MichMich/MagicMirror/files/4786702/config.txt)




i have turned into txt because git doesnt support .js files

**Comment by sdetweil** [comment]
@sushant96702  thanks

I put this in for my config.js, by using cp from my Downloads (no edits)
and got this result  (can't post pictures here), working as expected
https://www.dropbox.com/s/3efaky0vf4q5k3x/Screenshot%20at%202020-06-16%2008-03-40.png?dl=0

**Comment by sushant96702** [comment]
but why it aint working on my rasp pi
IDK why it works on yours but not on mine
please help

**Comment by sdetweil** [comment]
tell me more how you have implemented MagicMirror? docker? how install? 

is this the actual config.js being used?  if u take out some quote mark (") does MM fail to load?

**Comment by sushant96702** [comment]
i want to gift  it to my sister
i have installed it using the link which used to be on magic mirror website
yes it is actual config file
Which quotes  "if u take out some quote mark (") does MM fail to load"

**Comment by sdetweil** [comment]
what version is this? do
```
grep version ~/MagicMirror/package.json
```

can u post a link to a  screenshot

**Comment by sushant96702** [comment]
"version": "2.11.0",

**Comment by sdetweil** [comment]
can u post a link to a screenshot of the MM page

**Comment by sdetweil** [comment]
@sushant96702 

can u also try something
edit 
~/MagicMirror/modules/default/clock/clock.js
and change this line 
```
		timeFormat: config.timeFormat,
```
to
```
		timeFormat: 24,
```
then restart MM.. please advise

**Comment by sushant96702** [comment]
https://www.dropbox.com/sh/iyn6yp5z2y447mu/AAC7u46pSnzLFlM-8vFHH13ya?dl=0

**Comment by sdetweil** [comment]
thx.. weird, the weather shows a different base time (19:26).. than clock(19:01)

**Comment by sushant96702** [comment]
Thanks i didnt noticed that BTW do you know why is it happening

**Comment by sdetweil** [comment]
no.. never seen anything like this

what time IS it on the system?

**Comment by sushant96702** [comment]
19.19 on rasp and on left side of MM
7:26 pm on weather wait what how the heck is it in 12 hr format
what is happening with my software

**Comment by sdetweil** [comment]
that time on weather is sunrise or sunset time..  so different.. my image was also different..  
each module does their own thing.. not coordinated with base modules (system clock is everything)

still.. can u change that one line of code I suggested

**Comment by sushant96702** [comment]
yep i did that but nothing changed

**Comment by sdetweil** [comment]
change it to 12 and retest

**Comment by sushant96702** [comment]
yes i changed it to 12 and rebooted it but it was still in 24 hr format

**Comment by sdetweil** [comment]
how is MM started? pm2?  you didn't need to reboot, just pm2 restart ?? name/number
do
```
pm2 status
```

**Comment by sushant96702** [comment]
has this thing ever occured to anyone

**Comment by sushant96702** [comment]
yes i have put it into autorun

**Comment by sdetweil** [comment]
in the 3 years I have been on MM I have never seen it from anyone

so I am wondering if u have 2 MM running.. 1st with some other config and this one starting second and failing cause the port is in use...

**Comment by sushant96702** [comment]
sorry i didnt understood what you just said

**Comment by sdetweil** [comment]
i have seen where there are two instances of MM installed, and both are marked to start at boot. 
both using the same port

the 1st one starts and displays
the 2nd one tries to start , but the port is in use (by the 1st), so it fails

I see this on my dev system when I forget that pm2 starts 1 at boot and I try to start another for testing something

**Comment by sushant96702** [comment]
ID      name                  mode        @       Status       CPU       Memory
0        MagicMirror        Fork          0        Online       0%         2.4mb

**Comment by sdetweil** [comment]
we should take this to the forum or discord better suited to chat format

**Comment by sushant96702** [comment]
Sorry Sir but i dont know how to use forms

**Comment by sushant96702** [comment]
And there is only one MM installed

**Comment by sdetweil** [comment]
>yes i have put it into autorun

what does that mean? 

u posted the pm2 status output

**Comment by sushant96702** [comment]
it asked in terminal that "do you want autorun(y/n)'

**Comment by sushant96702** [comment]
https://www.dropbox.com/sh/iyn6yp5z2y447mu/AAC7u46pSnzLFlM-8vFHH13ya?dl=0

**Comment by sdetweil** [comment]
hm.. i maintain the installer script, and it doesn't have that message
mine has 
"Do you want use pm2 for auto starting of your MagicMirror (y/N)?"

**Comment by sushant96702** [comment]
sorry it said same as yours i forgot

**Comment by sushant96702** [comment]
please help and tell me a solution

**Comment by sdetweil** [comment]
one more thing can u show me the output of
```
ls ~/MagicMirror/config -laF
```

**Comment by sdetweil** [comment]
@sushant96702   waiting for info

**Comment by sushant96702** [comment]
@sdetweil i am soo sorry sir i was not able to end you info can i just send it to you tommo because it is 1:00am
