### ISSUE TITLE
Can't get it to work on win10 device

### ISSUE THREAD

**Issue by JakobA-88** [MichMich/MagicMirror#798]
Hey. I'm a totally newbie, so I've tried to get it to work on my windows 10 laptop.
When i roll the programe in the CMD it shows the black mirror screen, on the monitor. But it says that it can't load the config. How can that be? I'm a totally newbie, and have followed a guide to install it.
I would also like to change the calender and overall language to Danish, if that is possible to? :)
I bought a Asus Zenbook and a Asus touch monitor, to the 'build' so I later on can use the mirror as a jukebox on my bathroom :)

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
