### ISSUE TITLE
[Feature] Digest-Auth for ical URLs

### ISSUE THREAD

**Issue by hahrens** [MichMich/MagicMirror#808]
Currently it's only possible to use Basic-Authentication for ical-URLs. By setting `sendImmediately` to false (as described [in the request documentation](https://github.com/request/request#http-authentication)), the request library will use digest-auth.

(Running on Raspberry PI 3B, Raspbian 8, Node 6.9.4, MagicMirror 2)

**Comment by hahrens** [comment]
I've seen that ist's already supported in the develop branch. Sorry.

**Comment by roramirez** [comment]
Yes, Is added in https://github.com/MichMich/MagicMirror/pull/754
