### ISSUE TITLE
2.1.1 will not run under Windows 10

### ISSUE THREAD

**Issue by cowboysdude** [MichMich/MagicMirror#813]
Upon updating to 2.1.1 it will not start.  

Windows does not recognize the bash or sh command and will error out because it cannot start electron.

see here: https://forum.magicmirror.builders/topic/2191/won-t-start-on-windows-after-upgrade

Doing this makes it work under Windows at the moment.

**Comment by MichMich** [comment]
Windows is not a supported platform. Feel free to send a PR which solves this. Unfortunately the Core team won't focus on supporting it. 

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
