### ISSUE TITLE
Default Modules not working

### ISSUE THREAD

**Issue by xaviruvpadhiyar98** [MichMich/MagicMirror#840]

**Comment by xaviruvpadhiyar98** [comment]
when i start npm start 
then the screen goes black

**Comment by fewieden** [comment]
did you run npm install before?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by 9170895137** [comment]
How do you enable the modules. I see them in the config.js file but they are not being displayed when magic mirror is running
