### ISSUE TITLE
Microphone is not working

### ISSUE THREAD

**Issue by MaengMarco** [MichMich/MagicMirror#841]
I did it(npm install && npm start)
But microphone was not working.
on the other hand, If I access '192.168.0.11:8080' on another computer, microphone is working.
What should I do?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by vandenberg1985** [comment]
I have the same problem.
you can also tray from the LXTerminal
cd Magicmirror
node serveronly (start the server on the background)
*open new LXterminal*
chromium-browser --kiosk http://localhost:8080 (open chrome in fulscreen)
and the microphone works.
