### ISSUE TITLE
Position: fullscreen_below_middle

### ISSUE THREAD

**Issue by howroyd** [MichMich/MagicMirror#843]
Suggestion:

The position identifier "fullscreen_below" is very useful for backgrounds however it is justified left.  It would be useful to be able to do something like, "fullscreen_below_middle"

Keep up the good work,

Many thanks

**Comment by fewieden** [comment]
you could achieve that in custom.css

**Comment by MichMich** [comment]
Indeed. As said, that's what the custom.css is for. Also, a module could leverage it's own css file. 

I'll be closing this issue for now since I think thats the appropriate solution. Let me know if I need to reopen it.
