### ISSUE TITLE
Icloud Calendar isn't loading

### ISSUE THREAD

**Issue by fuzzylogic725** [MichMich/MagicMirror#844]
Raspberry PI 3
Magic Mirror 2.2

I have three calendars modules running on the MM interface. 
The first one is a personal calendar from ical, this works perfectly, the second is a publicly available holiday calendar, and the third is a second personal calendar concerning something different. 

The first two calendars work flawlessly, however, the third when using the same coding as the first two remains as "Loading"

This is the log error i get: 

0|mm       | (node:1055) DeprecationWarning: sys is deprecated. Use util instead.
0|mm       | Error: dates lower than Thu Jan 01 1970 00:00:00 GMT-0500 (EST) are not supported
0|mm       |     at Object.toOrdinal (/home/pi/MagicMirror/node_modules/rrule-alt/lib/rrule.js:105:15)
0|mm       |     at Iterinfo.rebuild (/home/pi/MagicMirror/node_modules/rrule-alt/lib/rrule.js:1409:35)
0|mm       |     at RRule._iter (/home/pi/MagicMirror/node_modules/rrule-alt/lib/rrule.js:978:10)
0|mm       |     at RRule.between (/home/pi/MagicMirror/node_modules/rrule-alt/lib/rrule.js:794:21)
0|mm       |     at /home/pi/MagicMirror/modules/default/calendar/calendarfetcher.js:122:24
0|mm       |     at Request._callback (/home/pi/MagicMirror/modules/default/calendar/vendor/ical.js/node-ical.js:11:5)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:188:22)
0|mm       |     at emitTwo (events.js:106:13)
0|mm       |     at Request.emit (events.js:191:7)
0|mm       |     at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1171:10)

		{		
			module: 'calendar',
			header: 'Personal',
			position: 'top_right',
			config: {
				calendars: [					
					{
				url:'https://p33-calendars.icloud.com/published/2/private'
					},
						],
				},
		},

Just curious what could be causing this?

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
