### ISSUE TITLE
Support PJON

### ISSUE THREAD

**Issue by gioblu** [MichMich/MagicMirror#845]
Ciao @MichMich, how its going? 
Recently PJON has been ported to RPI: https://github.com/gioblu/PJON/wiki/Raspberry-Pi-interfacing
Would be nice to see it used here, because it could open up many new possibilities! 

Here the link to v8 release: https://github.com/gioblu/PJON/releases/tag/8.0

Compliments for this amazing work!

**Comment by MichMich** [comment]
Thanks man! Awesome work. 

I don't se how PJON could be integrated into the MagicMirror core, but of course you could develop a module yourself which leverages PJON! 

Check out the forum if you need any help! http://forum.magicmirror.builders 

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
