### ISSUE TITLE
Current Weather not working/showing

### ISSUE THREAD

**Issue by Steakschen** [MichMich/MagicMirror#849]
Hi,

i installed it on raspi 3.

I Cant see current weather, i synced the git code, but it dosent show up.
Weather Forecast works

`                        module: "currentweather",
                        position: "top_left",
                        colored: "true",
                        config: {
                                location: "Illingen",
                                locationID: "2896538",  //ID from http://www.openweathermap.org/help/city_list.txt
                                appid: "0ded16fae241ce186b274e7c149865b9"
                        }
                },
                {
                        module: "weatherforecast",
                        position: "top_left",
                        header: "Wetter Vorhersage",
                        config: {
                                location: "Illingen",
                                locationID: "2896538",  //ID from http://www.openweathermap.org/help/city_list.txt
                                appid: "9fd73d89a31f8694730d38eb0f9980ec"
                        }
                },
`

**Comment by HawkingJan** [comment]
Just a guess, but is there a reason that you put both modules at "position: "top left" and used different appids (I would recommend to remove them anyway in the post)?
Greetings to Illingen.

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
