### ISSUE TITLE
Newsfeed - Issue with expiration

### ISSUE THREAD

**Issue by mirko3000** [MichMich/MagicMirror#859]
Hello,

I think there is a bug in the newsfeed expiration calculation in newsfeed.js(generateFeed):

if (!(this.config.ignoreOldItems && ((Date.now() - new Date(item.pubdate)) > this.config.ignoreOlderThan))) {

Should be:
if (!(this.config.ignoreOldItems && ((Date.now() - new Date(item.pubdate)) **<** this.config.ignoreOlderThan))) {

Best regards,
Mirko

**Comment by fewieden** [comment]
I did a small test on jsfiddle and it looks good to me https://jsfiddle.net/0g541k8b/

**Comment by mirko3000** [comment]
Yes you are right, the expression was correct. I found the issue: I did not set ignoreOldItems to true.
