### ISSUE TITLE
Missing translation for 'Week' in module 'clock' when showWeek is set to true

### ISSUE THREAD

**Issue by BerndKohl** [MichMich/MagicMirror#860]
**Platform**: Raspberry Pi 3
**Node Version**: 6.10.2
**MagicMirror Version**: 2.1.1
**Description**: Missing translation of "Week" in module 'clock' when showWeek is set to true.
**Steps to Reproduce**: Enable display of calendar week in module 'clock'
**Expected Results**: Display "Woche 16" when language is set to 'de' in config.js
**Actual Results**: "Week 16" is displayed

**Comment by roramirez** [comment]
Send a Pull Request with this change for de language.

**Comment by BerndKohl** [comment]
Would love to, simply don't know how to do this. Is there a short tutorial/introduction available?

**Comment by BerndKohl** [comment]
As I can see this has already been fixed in development branch. Sorry for the hussle.
