### ISSUE TITLE
Clock Module - German "Week" Translation

### ISSUE THREAD

**Issue by Swagielka** [MichMich/MagicMirror#874]
Greetings!
Would you kindly add the german translation for "Week" in the Clock Module?
"Week" = "Woche"

Sincerely,
Kukielka

**Comment by fewieden** [comment]
Merged 3 weeks ago, you have to wait for the next release or use the develop branch.

https://github.com/MichMich/MagicMirror/pull/817

**Comment by roramirez** [comment]
This is  need to  close it. @Swagielka Can you'll close it?
