### ISSUE TITLE
Improve translation flexibility

### ISSUE THREAD

**Issue by Arkkimaagi** [MichMich/MagicMirror#876]
String joining can get us only so far regarding translations. In some cases it would be easier to reorder words with the translation strings.

I'd suggest that we'd add support for something like string literals that are coming in future version of js.

For example calendar could support Finnish way of saying the `RUNNING` a bit better
en.js:
```js
	"RUNNING": "Ends in {timeUntilEnd}",
```
fi.js:
```js
	"RUNNING": "Päättyy {timeUntilEnd} päästä",
```
Notice the `{timeUntilEnd}` variable there? That will be replaced with the variable during translation.

This would be rendered in Finnish as:
```
Päättyy viiden minuutin päästä
```
Where moment.js returns `viiden minuutin` as we have five minutes left.

Here is a screenshot from my mirror (where I have dropped the capitalization with css):
![image](https://cloud.githubusercontent.com/assets/1191667/25406371/1ba1a2d8-2a0f-11e7-8397-6fac496515aa.png)

Of course we'd want to keep the translator backwards compatible, we'd want also this to work just as it does now so that all the current implementations do not break:
```js
	"RUNNING": "Ends in",
```
It should fallback to current approach resulting 
```
Ends in five minutes
```

I have a working sample of this thing with an example for this calendar thing only, but support could be built for all translations in future to combat rigid string joining problems.

**Comment by Arkkimaagi** [comment]
Seems that this has been merged into develop, maybe this issue can be closed? Or do you close these only when merged into master?

**Comment by roramirez** [comment]
Hi @Arkkimaagi you should be close this issue.

**Comment by Arkkimaagi** [comment]
Closing the issue as it was merged.
