### ISSUE TITLE
resume(): documentation <-> behavior mismatch

### ISSUE THREAD

**Issue by markuzSchmidt** [MichMich/MagicMirror#878]
### Description
[Documentation](https://github.com/MichMich/MagicMirror/tree/master/modules) of `resume()` states:

> When a module will be shown after it was previously hidden (using the module.show() method), the resume() method will be called.

Minimal example (see below) shows, that `resume()` actually gets called regardles of the previous hidden status, which doesn't match the expectation implied by "after it was previously hidden".

### Example
```
Module.register("test", {
  defaults: {},
  resume: function() { Log.log("resume() called"); },
  notificationReceived: function(notification, payload, sender) {
    if (notification == "DOM_OBJECTS_CREATED") {
      Log.log("hidden status before call: " + this.hidden);
      this.show();
    }
  }
});
```

### Result
Log shows "hidden status before call: false" followed by "resume() called".

### Suggestion
I suggest to adapt the documentation instead of changing the code to prevent compatibility problems with existing modules.

**Comment by MichMich** [comment]
Please send a PR! Thanks.
