### ISSUE TITLE
bash syntax problem with installer

### ISSUE THREAD

**Issue by z0diak** [MichMich/MagicMirror#884]
Installer in https://github.com/MichMich/MagicMirror/blob/master/installers/raspberry.sh doesn't work correctly on a brand-new RPI with raspbian-jessie. 
Syntax error 
```
bash: line 153: syntax error near unexpected token `then'
bash: line 153: `then'
```

Going to propose PR to fix that.

Just thinking, maybe we should have tests running for installer? Just like: exit code is 0

**Comment by roramirez** [comment]
There are a workaround where you can using the script installer like this.

`bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"`

If you want adding test for installer script ...go ahead.

**Comment by MichMich** [comment]
Fix merged.

**Comment by aramaki87** [comment]
Please also fix at https://magicmirror.builders

**Comment by z0diak** [comment]
@aramaki87 what do you mean?

**Comment by develuxe** [comment]
@z0diak He probably meant the tutorial here -> https://forum.magicmirror.builders/topic/236/complete-setup-tutorial/6

**Comment by z0diak** [comment]
@develuxe Yes, I also thought this way, but since we've changed the code in way to keep execution command the same (not what was suggested by roramirez) there is no need to update tutorial

**Comment by develuxe** [comment]
@z0diak I've found this thread because I had the exact same problem. I followed the linked tutorial. With the posted workaroung I dont get this error. Just fyi

**Comment by joeframbach** [comment]
This is still an issue on a new Jessie installation using the install command on https://magicmirror.builders/

**Comment by roramirez** [comment]
Hey Guys!, few minutes ago the install command onto the [website](https://magicmirror.builders/) are updated. Please you follow this sentence  👌
