### ISSUE TITLE
Error Create Config File

### ISSUE THREAD

**Issue by twosix6** [MichMich/MagicMirror#888]
So, I am getting a warning run my mirror, and it boots to the Create Config page.  I was told to deconstruct my config, which I did.  I figured out I get this error because of my calendar link.  I am using and icloud calendar and cannot figure out the problem to this.  Thanks!  Link to my troubleshooting on the Forum w/ my config file: https://forum.magicmirror.builders/topic/2516/trouble-with-config-file-error-create-config-file/9

**Comment by MichMich** [comment]
Please only submit reproducible issues. For other issues, please use the support forums. Thanks!

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
