### ISSUE TITLE
Google .ics URL not displaying / page formatting

### ISSUE THREAD

**Issue by Phasmius** [MichMich/MagicMirror#89]
This could be because I'm a complete and absolute beginner, but my private .ics Google Calendar URL seems not to display my calendar when placed in its proper spot at line 45. 

Additionally, the formatting for my page seems off. screenshot below. 

What have I done horribly wrong? many thanks in advance for the help.

https://gyazo.com/c983b006ad854eb498de238a58bcb3fc

**Comment by bitte-ein-bit** [comment]
You are missing some files. At least the css is missing / not in the
right directory.

**Comment by MichMich** [comment]
Check you web inspector to see what's going wrong.

**Comment by Phasmius** [comment]
@MichMich Perfect. Found the issues. This can be closed now.
