### ISSUE TITLE
[Suggestion] Move custom.css to /config/

### ISSUE THREAD

**Issue by JanLoebel** [MichMich/MagicMirror#891]
Hi,

what do you think about moving the "_/css/custom.css_" file to "_/config/custom.css_" and only load it if it exists? This would be great to have the possibility to use Docker and only specify the local config- and module-folder.

Any suggestions?

Best regards,
Jan

**Comment by roramirez** [comment]
There not possible to mount css directory into volume of docker?

**Comment by JanLoebel** [comment]
Not really, because in the css directory there is also the _main.css_ which you would have to copy in the mounted local directory.

**Comment by MichMich** [comment]
What could be an option, is to make the main.css path configurable. With the default set to the current location. This way, you can modify it in your config, and it won't be a breaking change.

Feel free to send a PR for this. Make sure to update the CHANGELOG & README accordingly.
