### ISSUE TITLE
Can't install NPM

### ISSUE THREAD

**Issue by Lausbuab1** [MichMich/MagicMirror#903]
When submitting a new issue, please supply the following information:

**Platform**: Raspberry Pi Zero (Debian Jessie)

**Node Version**: v7.10.0 (latest)

**MagicMirror Version**: newest Java version

**Description**: Can't install NPM, always getting the same error

**Steps to Reproduce**: npm install && npm start

**Expected Results**: should be installed.

**Actual Results**: getting error.

Error Log:
pi@raspberrypi:~/MagicMirror $ npm install

> electron-chromedriver@1.6.0 install /home/pi/MagicMirror/node_modules/electron                                                                                                                                                             -chromedriver
> node ./download-chromedriver.js

module.js:472
    throw err;
    ^

Error: Cannot find module './lib/redirect'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:                                                                                                                                                             29:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! Linux 4.9.29+
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install"
npm ERR! node v7.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron-chromedriver@1.6.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-chromedriver@1.6.0 install script 'node ./downlo                                                                                                                                                             ad-chromedriver.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-chromedriver                                                                                                                                                              package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download-chromedriver.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/npm-debug.log

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
