### ISSUE TITLE
I ran the Automatic Installer (Raspberry Pi Only!) and now T'm not sure what to do next

### ISSUE THREAD

**Issue by CatherineMG** [MichMich/MagicMirror#905]
\e[92mWe're ready! Run \e[1m\e[97mDISPLAY=:0 npm start\e[0m\e[92m from the ~/MagicMirror directory to start your MagicMirror.\e[0m"

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
