### ISSUE TITLE
Google Calendar not working

### ISSUE THREAD

**Issue by kyle-ayn** [MichMich/MagicMirror#91]
Everything else is working, except my google calendar. I put in my url in the config file but it's not showing up. I'm using Midori as my browser.
![nano](https://cloud.githubusercontent.com/assets/17487559/13342094/3f85580e-dbf3-11e5-9342-cf557f1c32f6.PNG)

**Comment by bitte-ein-bit** [comment]
You might want to try to comment out the empty second entry. If this
doesn't work, do you see any errors in the development console of chrome
(F12)?

**Comment by kyle-ayn** [comment]
Thanks for the suggestion, but it didn't work.
![nano](https://cloud.githubusercontent.com/assets/17487559/13368011/c92c006e-dc9b-11e5-8f9f-46bc6a9e5631.PNG)

I looked at the console on Google Chrome on my PC, but it looks like nothing is wrong related to the calendar.
![consle](https://cloud.githubusercontent.com/assets/17487559/13368107/7ea8ec72-dc9c-11e5-8309-e8b849c0f211.PNG)

It also doesn't show up in Midori on my Raspberry Pi.
![photo feb 26 3 28 13 pm](https://cloud.githubusercontent.com/assets/17487559/13368279/c35c36ac-dc9d-11e5-94d3-1ef9c1a13b6a.jpg)

**Comment by wcdanh2** [comment]
It looks like it is a group calendar.  Are you the owner?
Group calendars cannot be downloaded using the standard method, you must use the google API with Oauth2.  Currently this is unsupported.

I have a fix that I have been testing and plan to make a pull request in the next few days.

**Comment by kyle-ayn** [comment]
The address is a public calendar for the school I go to. I'll try testing it with my own private calendar.
