### ISSUE TITLE
Stretch module to display border

### ISSUE THREAD

**Issue by micherlinman** [MichMich/MagicMirror#920]
My display is smaller than my mirror. Between the display border and the module border is a lot of unused space on the display. Is there a way to let the modules float to the display border?

**Comment by fewieden** [comment]
you have to put the following lines of code into `~/MagicMirror/css/custom.css`

```
body {
  margin: 0;
  height: 100%;
  width: 100%;
}
```

**Comment by micherlinman** [comment]
Thanks!

**Comment by roramirez** [comment]
Hi @micherlinman, Please close the issue.

Thanks.
