### ISSUE TITLE
The fade/opacity effect on calendar and weather

### ISSUE THREAD

**Issue by tjobo** [MichMich/MagicMirror#93]
I have study the code but cant solve the case. Where is the fading/opacity effect on the calendar and weather coming from? I want to make it all 100% white due to some issues with my monitor.

Thanks alot in advance!

Morten Johnsen
Norway

**Comment by MichMich** [comment]
See: https://github.com/MichMich/MagicMirror/blob/master/js/calendar/calendar.js#L163
Replace: 
    
    var row = $('<tr/>').attr('id', 'event'+i).css('opacity',opacity).addClass('event');

With:

    var row = $('<tr/>').attr('id', 'event'+i).addClass('event');

Cheers, M.

**Comment by tjobo** [comment]
Thank you so much!
