### ISSUE TITLE
Wrong Time On Calendar

### ISSUE THREAD

**Issue by mathias1xxX** [MichMich/MagicMirror#935]
Hi i'm having a problem i installed magic mirror 2 for the first time and everything works except one problem it's 00:01 when i'm writhing this but my mirror's agenda says is 22:01 and i can't find where to change this.

can someone help me ?

Kind Regards.

**Comment by fewieden** [comment]
Did you set the correct timezone on your pi?

**Comment by mathias1xxX** [comment]
the hwtime was off o_O it's fixed thanks :P
