### ISSUE TITLE
analog clock position went wrong after update

### ISSUE THREAD

**Issue by apm1007** [MichMich/MagicMirror#936]
hi, today i made an update to the latest version. i use the clock in top_bar. After the update the analog clock jumped to the left side. Any ideas how to fix this? Dunno where there error comes from.
![grafik](https://user-images.githubusercontent.com/11927080/27950076-3b0ba612-6300-11e7-8935-4ccb24b2193e.png)
![grafik](https://user-images.githubusercontent.com/11927080/27950099-50e20a9e-6300-11e7-940a-f4cee7c1e84a.png)

**Comment by fewieden** [comment]
probably related to #933

**Comment by QNimbus** [comment]
This is addressed in [Issue 993](https://github.com/MichMich/MagicMirror/issues/933).

**Comment by QNimbus** [comment]
You can probably close this issue since [issue #933](https://github.com/MichMich/MagicMirror/issues/933) already addresses this problem.
