### ISSUE TITLE
error with config.js

### ISSUE THREAD

**Issue by abacon118** [MichMich/MagicMirror#942]
I just installed magic mirror and opened index.html and it told me that there was an error with the conifg.js file.  I re-named the file and moved it and still had no luck.  What should i do?

**Comment by fewieden** [comment]
you have to start the server, you can't just open the html file.

**Comment by QNimbus** [comment]
`npm start` should do the trick when run in your MagicMirror folder. Or you can run `node serveronly` and use a browser to open the MagicMirror site.

Let us know if this solved your problem - if it's resolved, please close this issue

**Comment by abacon118** [comment]
When i run npm start from the magic mirror directory i get this.

![mm1](https://user-images.githubusercontent.com/30011386/27996068-f5faf696-64a7-11e7-9291-e1ecc0a9610a.PNG)

**Comment by rejas** [comment]
So have you node installed? What do you get when you run "node -v"-command in that directory?

**Comment by QNimbus** [comment]
Maybe you could try upgrading NodeJS to the latest version?

`$ sudo apt update`
`$ sudo apt install nodejs`

**Comment by roramirez** [comment]
If are you using the manual installation please follow the steps
https://github.com/MichMich/MagicMirror#manual-installation

After clone the repository
```
cd ~/MagicMirror
npm install
npm start
```

If not, you can use the automatic installer script
`bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"`


Good luck!

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Comment by FastGeneration** [comment]
Hy sir please tell me about clone error in installing smart mirror in raspberry
Please tell me solution thank u
