### ISSUE TITLE
installer error

### ISSUE THREAD

**Issue by cfdresearch** [MichMich/MagicMirror#944]
Try to install MagicMirror using installer and got a bash error (below). HW: Raspberry Pi 3B, system details below.

`curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh | bash`

[PM2] Saving current process list...
[PM2] Successfully saved in /home/pi/.pm2/dump.pm2
bash: line 157: syntax error near unexpected token `fi'
bash: line 157: `fi'

pi@mmirror2pi:~ $ uname -a
Linux mmirror2pi 4.9.36-v7+ #1015 SMP Thu Jul 6 16:14:20 BST 2017 armv7l GNU/Linux

pi@mmirror2pi:~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        30G  3.4G   25G  12% /
devtmpfs        458M     0  458M   0% /dev
tmpfs           462M  7.3M  455M   2% /dev/shm
tmpfs           462M  6.4M  456M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           462M     0  462M   0% /sys/fs/cgroup
/dev/mmcblk0p1   42M   21M   21M  51% /boot
tmpfs            93M     0   93M   0% /run/user/1000

**Comment by fewieden** [comment]
This command is deprecated. Use `bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/master/installers/raspberry.sh)"` instead

**Comment by cfdresearch** [comment]
Thanks a lot, now it's fine. I just used this tutorial: [https://forum.magicmirror.builders/topic/236/complete-setup-tutorial/6](url). Issue may be closed.

**Comment by Jopyth** [comment]
I fixed the link in the mentioned tutorial.
