### ISSUE TITLE
npm start ERROR

### ISSUE THREAD

**Issue by CNYoki** [MichMich/MagicMirror#946]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.1.2~prestart: magicmirror@2.1.2
6 silly lifecycle magicmirror@2.1.2~prestart: no script for prestart, continuing
7 info lifecycle magicmirror@2.1.2~start: magicmirror@2.1.2
8 verbose lifecycle magicmirror@2.1.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle magicmirror@2.1.2~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle magicmirror@2.1.2~start: CWD: /home/pi/MagicMirror
11 silly lifecycle magicmirror@2.1.2~start: Args: [ '-c', 'sh run-start.sh' ]
12 info lifecycle magicmirror@2.1.2~start: Failed to exec start script
13 verbose stack Error: magicmirror@2.1.2 start: `sh run-start.sh`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid magicmirror@2.1.2
15 verbose cwd /home/pi/MagicMirror
16 error Linux 4.4.21-v7+
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v6.11.1
19 error npm  v3.10.10
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error magicmirror@2.1.2 start: `sh run-start.sh`
24 error spawn ENOENT
25 error Failed at the magicmirror@2.1.2 start script 'sh run-start.sh'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the magicmirror package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     sh run-start.sh
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs magicmirror
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls magicmirror
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.
