### ISSUE TITLE
INDOOR_HUMIDITY notification

### ISSUE THREAD

**Issue by ryck** [MichMich/MagicMirror#954]
I just implemented the INDOOR_TEMPERATURE notification in one of my modules, and I discover that there is no INDOOR_HUMIDITY notification available. Would that be something interesting to implement or maybe is already too much information on the currentweather module? Temperature and Humidity usually go hand by hand, but, again, maybe that belongs in another module..

I already have a PR ready, but I just wanted to check first if that's something we want.

Cheers,

Rick

**Comment by roramirez** [comment]
I think a good work can be create a feature to implement these things by configuration instead of the into the code.
