### ISSUE TITLE
Error on years with FB birthday calendar

### ISSUE THREAD

**Issue by FurNocte** [MichMich/MagicMirror#97]
I've tried to use my personal FaceBook account to get birthday calendar, and it work. Only dates are too late off one year (as you can see on the three last lines).
![capture du 2016-03-06 18 32 02](https://cloud.githubusercontent.com/assets/13659548/13555839/3e1bde18-e3cb-11e5-8fc9-c55fb9b329dd.png)

**Comment by monsieurpouet** [comment]
Perhaps, you can reduce size of the calendar div no ?

**Comment by SVendittelli** [comment]
I am experiencing the same issue, has anyone found a solution?

@monsieurpouet I'm not sure what you mean by that, can you elaborate?

**Comment by MichMich** [comment]
Please let me know if I can close this issue.

**Comment by delize** [comment]
@FurNocte / @SVendittelli 

I am more interested in to how you got them to appear. 

I can't seem to get webcal:// to work, importing the webcal link into my gmail to use Google's ical link doesn't work, etc.

Could you describe how you did that?

At that point, if I experience the same problem, I will let you know.

**Comment by SVendittelli** [comment]
@delize You can just replace `webcal://` with `http://`. So in the config for calendar urls you might have:

`{
	symbol: 'birthday-cake',
	url: 'http://www.facebook.com/ical/b.php?uid=1234567890&key=ABCDEFGHIJKLM_XY',
},`

I think it is because facebook only gives a start date and duration in the iCal but I'm not sure. Example birthday event:

`BEGIN:VEVENT
DTSTART:20160404
SUMMARY:Some Person's birthday
RRULE:FREQ=YEARLY
DURATION:P1D
UID:b123456789@facebook.com
END:VEVENT`

**Comment by MichMich** [comment]
This should be fixed in V2. (I just finished the calendar module.)

**Comment by SVendittelli** [comment]
I believe the update (46312cb) fixing recurring events broke the Facebook birthdays again, but I can't work out why.

**Comment by MichMich** [comment]
I'll look into it tomorrow. While we are on the subject of Facebook events. Does somebody know how to convert an events page of a Facebook brandpage to an iCal Calendar? For example this page: https://www.facebook.com/DashBerlinOfficial1/events

**Comment by SVendittelli** [comment]
Yes, select one of the events on the page and click going. There should be the option to export the event.
![chrome_2016-04-04_18-46-24](https://cloud.githubusercontent.com/assets/17616742/14257402/93ecf08a-fa95-11e5-8be3-9aa4eb2addd6.png)
Then the ical link should be there!
![chrome_2016-04-04_18-47-45](https://cloud.githubusercontent.com/assets/17616742/14257495/efbd38f2-fa95-11e5-9358-0ea3772a5c4c.png)

**Comment by MichMich** [comment]
Should be fixed again, now. If not, please reopen this issue.

**Comment by MichMich** [comment]
For anyone looking for a nice solution: If you want a compleet feed of all events of a specific fan page, check out https://www.wallflux.com/#other
