### ISSUE TITLE
AM/PM

### ISSUE THREAD

**Issue by Chyase** [MichMich/MagicMirror#98]
Is it possible to get AM/PM on the js?

Thanks,

**Comment by monsieurpouet** [comment]
He is there.
In config.js, you've a parameter to change that. At the top of the file.

**Comment by Chyase** [comment]
```
var config = {
    lang: 'nl',
    time: {
        timeFormat: 12,
        displaySeconds: true,
        digitFade: false,
    },
```


Where at?

**Comment by danynek** [comment]
Time format: 12 or 24

DM

17. 3. 2016 v 13:55, Chyase <notifications@github.com>:

**Comment by Chyase** [comment]
I'm actually looking for it to say if its AM or PM- not 24 hours vs 12 hours-

**Comment by monsieurpouet** [comment]
Yes, I thought about this.
Maybe, I didn't understood the question. You talk about AM/PM and not 12/24.
For me, it was the same things.

**Comment by Chyase** [comment]
Yeah I just want it to show AM when its morning and then PM when its afternoon/night

**Comment by jerome2710** [comment]
You might use the format character `a` to show AM/PM.

Have a look at js/time/time.js near line 74:
`$(this.timeLocation).html(_now.format(this._timeFormat + ':mm[<span class="sec">]ss[</span>] a'));`
Note the added `a` near the end, this will result in AM/PM.

Good luck!

**Comment by Chyase** [comment]
Jerome, that worked. Thanks!
