### ISSUE TITLE
Auto config for client.

### ISSUE THREAD

**Issue by KnottyCord** [MichMich/MagicMirror#994]
I'm not good at coding, but I know just a bit to understand some stuff. But since I made my first mirror a lot of people ask me if I could make them one. But the problem is that the one command installation is not user frendly. Like if you want to connect your mirror to a WiFi you need to go in the files a change the variable, with a keyboard.
If there is someone out there willing to create a full on command installation where you can name you mirror install Module. Move module. Edit wifi passord. etc.... and add like a gear icon at the bottom to acces the setting.

Thank you
Shawn Mercier

**Comment by Terrib1e** [comment]
Sure I'm willing to work with you on that.

**Comment by nhubbard** [comment]
@KnottyCard Feel free! You could also extend the install script with a WiFi setup option.

**Comment by KnottyCord** [comment]
@Terrib1e Sure when can we speek? I have a very basic knownledge on programing. HTML5 And css are what im leaning crurently.

**Comment by MichMich** [comment]
Please continue this discussion on http://forum.magicmirror.builders 
I'm closing this issue for now. If you feel this issue should remain open, please let me know.
